import {NextRequest,NextResponse} from 'next/server';
import {createHmac} from 'node:crypto';
const PLATFORM=process.env.PLATFORM_API_ORIGIN||'http://127.0.0.1:4000';
const SHEETS=process.env.SHEETS_API_ORIGIN||'http://127.0.0.1:4024';
const WEB=process.env.SHEETS_WEB_ORIGIN||'http://localhost:3024';
export const nocache={'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff'};
export function error(message:string,status=400){return NextResponse.json({message},{status,headers:nocache});}
export function mutationAllowed(r:NextRequest){try{return r.headers.get('origin')===new URL(WEB).origin&&r.headers.get('sec-fetch-site')!=='cross-site';}catch{return false;}}
export async function authorized(r:NextRequest):Promise<string|null|undefined>{const cookie=r.headers.get('cookie');if(!cookie)return null;try{const result=await fetch(`${PLATFORM}/v1/bazid/me`,{headers:{cookie,accept:'application/json'},redirect:'manual',cache:'no-store',signal:AbortSignal.timeout(5000)});if(result.status===401||result.status===403)return null;if(!result.ok)return undefined;const body=await result.json();return typeof body?.user?.id==='string'&&body.user.id.length>0&&body.user.id.length<=128?body.user.id:undefined;}catch{return undefined;}}
function assertion(secret:string,sub:string,method:string,path:string){const body=Buffer.from(JSON.stringify({aud:'bazaara-sheets-v1',sub,method,path,exp:Math.floor(Date.now()/1000)+20})).toString('base64url');const sig=createHmac('sha256',secret).update(body).digest('base64url');return `${body}.${sig}`;}
export async function callSheets(r:NextRequest,method:string,path:string,init:{headers?:Record<string,string>,body?:BodyInit}={}){const sub=await authorized(r);if(sub===null)return error('Sign in using BazID.',401);if(sub===undefined)return error('Identity service unavailable.',502);const secret=process.env.SHEETS_INTERNAL_SECRET;if(!secret||secret.length<32)return error('Sheets service is not configured.',503);try{return await fetch(`${SHEETS}${path}`,{method,headers:{...init.headers,'x-sheets-identity':assertion(secret,sub,method,path)},body:init.body,redirect:'manual',cache:'no-store',signal:AbortSignal.timeout(20000)});}catch{return error('Sheets service unavailable.',502);}}
export async function relay(r:NextRequest,method:string,path:string,init:{headers?:Record<string,string>,body?:BodyInit}={}){const result=await callSheets(r,method,path,init);if(result instanceof NextResponse)return result;const raw=await result.text();return new NextResponse(raw,{status:result.status,headers:{...nocache,'Content-Type':'application/json; charset=utf-8'}});}
