'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Brand} from '../../flagship-ui/src/core';
import {APPS,appHref,configuration,type App} from './registry';
type Preferences={version:1;favorites:string[];recent:string[];density:'comfortable'|'compact';contrast:boolean;motion:boolean};
const KEY='bazaara.smart-ui.v2.preferences';
const defaults:Preferences={version:1,favorites:[],recent:[],density:'comfortable',contrast:false,motion:true};
function read():Preferences{
 try{const stored=localStorage.getItem(KEY);const v=JSON.parse(stored||'{}');if(!stored){try{v.favorites=JSON.parse(localStorage.getItem('bazaara.internet.favorites')||'[]');}catch{}}const ids=(x:unknown)=>Array.isArray(x)?[...new Set(x.filter((s):s is string=>typeof s==='string'&&APPS.some(a=>a.slug===s)))].slice(0,60):[];return {...defaults,favorites:ids(v.favorites),recent:ids(v.recent).slice(0,12),density:v.density==='compact'?'compact':'comfortable',contrast:v.contrast===true,motion:v.motion!==false};}catch{return defaults;}
}
function Glyph({app}:{app:App}){
 const paths:Record<string,string>={search:'M21 21l-6-6M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0',bmap:'M12 22s8-8 8-14a8 8 0 0 0-16 0c0 6 8 14 8 14M12 5v6M9 8h6',calendar:'M3 5h18v16H3zM7 2v6M17 2v6M3 10h18M7 14h2M13 14h3',bmail:'M3 5h18v14H3zM3 5l9 8 9-8',bazchat:'M3 4h18v13H9l-6 5zM7 9h10M7 13h6',bazmeet:'M3 6h12v12H3zM15 10l6-4v12l-6-4',contacts:'M15 7a3 3 0 1 1-6 0 3 3 0 0 1 6 0M5 21v-3a7 7 0 0 1 14 0v3',baztune:'M8 18V5l12-2v13M8 5l12-2M8 18a3 3 0 1 1-3-3M20 16a3 3 0 1 1-3-3',notes:'M5 3h14v18H5zM8 8h8M8 12h8M8 16h5',vault:'M5 10h14v11H5zM8 10V6a4 4 0 0 1 8 0v4M12 14v3',bazsend:'M3 7h17l-5-5M20 7l-5 5M21 17H4l5-5M4 17l5 5',bazcut:'M8 8l13 13M8 16L21 3M8 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0M8 19a3 3 0 1 1-6 0 3 3 0 0 1 6 0',photos:'M3 3h18v18H3zM3 17l6-6 5 5 3-3 4 4M16 6h1',news:'M4 3h16v18H4zM7 7h10M7 11h4v4H7zM14 11h3M14 15h3M7 18h10',translate:'M2 5h12M8 2v3M4 5c1 6 5 8 9 10M12 5c-1 5-4 8-10 11M13 22l5-13 5 13M15 18h6',bazcircle:'M8 3L6 21M18 3l-2 18M2 8h20M1 16h20'};
 return <span className={'bs-icon bs-'+app.group.toLowerCase()}>{paths[app.slug]?<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[app.slug]}/></svg>:app.name.slice(0,2)}</span>;
}
export default function BazaaraHub({currentApp,initialScope='All'}:{currentApp:string;initialScope?:string}){
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[scope,setScope]=useState(initialScope),[settings,setSettings]=useState(false),[prefs,setPrefs]=useState(defaults),[urls,setUrls]=useState<Record<string,string>>({}),[online,setOnline]=useState(true),[notice,setNotice]=useState('');
 const dialog=useRef<HTMLDialogElement>(null),search=useRef<HTMLInputElement>(null),ready=useRef(false);
 useEffect(()=>{const p=read();p.recent=[currentApp,...p.recent.filter(s=>s!==currentApp)].filter(s=>APPS.some(a=>a.slug===s)).slice(0,12);setPrefs(p);ready.current=true;try{localStorage.setItem(KEY,JSON.stringify(p));}catch{setNotice('Device preferences could not be saved.');}setUrls(Object.fromEntries(APPS.map(a=>[a.slug,appHref(a,configuration(),window.location)])));setOnline(navigator.onLine);
 const connection=()=>setOnline(navigator.onLine);const storage=(e:StorageEvent)=>{if(e.key===KEY)setPrefs(read());};const key=(e:KeyboardEvent)=>{if(e.altKey&&e.key.toLowerCase()==='i'){e.preventDefault();setScope('Internet');setOpen(v=>!v);return;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'||e.altKey&&e.key.toLowerCase()==='b'){e.preventDefault();setOpen(v=>!v);}};
 window.addEventListener('keydown',key);window.addEventListener('storage',storage);window.addEventListener('online',connection);window.addEventListener('offline',connection);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('storage',storage);window.removeEventListener('online',connection);window.removeEventListener('offline',connection);delete document.documentElement.dataset.bazaaraDensity;delete document.documentElement.dataset.bazaaraContrast;delete document.documentElement.dataset.bazaaraMotion;};},[currentApp]);
 useEffect(()=>{if(!ready.current)return;document.documentElement.dataset.bazaaraDensity=prefs.density;document.documentElement.dataset.bazaaraContrast=String(prefs.contrast);document.documentElement.dataset.bazaaraMotion=prefs.motion?'full':'reduced';},[prefs]);
 useEffect(()=>{const d=dialog.current;if(!open||!d)return;const previous=document.activeElement;d.showModal();search.current?.focus();return()=>{if(d.open)d.close();if(previous instanceof HTMLElement)previous.focus();};},[open]);
 function change(part:Partial<Preferences>){const next={...read(),...part};try{localStorage.setItem(KEY,JSON.stringify(next));setNotice('');}catch{setNotice('Preferences apply now, but could not be saved.');}setPrefs(next);}
 const visible=useMemo(()=>APPS.filter(a=>(scope==='All'||a.group===scope||scope==='Favorites'&&prefs.favorites.includes(a.slug)||scope==='Recent'&&prefs.recent.includes(a.slug))&&`${a.name} ${a.hint} ${a.group}`.toLowerCase().includes(query.trim().toLowerCase())).sort((a,b)=>scope==='Recent'?prefs.recent.indexOf(a.slug)-prefs.recent.indexOf(b.slug):Number(prefs.favorites.includes(b.slug))-Number(prefs.favorites.includes(a.slug))),[query,scope,prefs]);
 const recommended=({search:['bazlens','translate','bmap'],bmail:['contacts','calendar','notes'],bazmeet:['calendar','notes','bazsend'],bazcut:['photos','baztune','bazsend'],news:['search','translate','notes'],translate:['bazlens','search','notes'],bmap:['calendar','contacts','search'],bazchat:['contacts','bazsend','bazcircle']} as Record<string,string[]>)[currentApp]||['notes','tasks','calendar'];
 const here=APPS.find(a=>a.slug===currentApp);
 function item(a:App,compact=false){const url=urls[a.slug];return <article className={'bs-app'+(compact?' bs-app-small':'')} key={a.slug}><Glyph app={a}/><div>{url?<a href={url} data-bs-result aria-current={currentApp===a.slug?'page':undefined} onClick={()=>setOpen(false)}>{a.name}<span aria-hidden="true">↗</span></a>:<span className="bs-unavailable">{a.name}</span>}<small>{url?a.hint:'Add an app URL to enable'}</small></div><button type="button" aria-label={`${prefs.favorites.includes(a.slug)?'Unpin':'Pin'} ${a.name}`} aria-pressed={prefs.favorites.includes(a.slug)} onClick={()=>change({favorites:prefs.favorites.includes(a.slug)?prefs.favorites.filter(s=>s!==a.slug):[...prefs.favorites,a.slug]})}>{prefs.favorites.includes(a.slug)?'★':'☆'}</button></article>;}
 return <div className="bs-root"><button className="bs-launch" aria-label="Open Bazaara command palette" aria-haspopup="dialog" aria-expanded={open} onClick={()=>setOpen(true)}><span aria-hidden="true">⌘</span><span>Apps & commands</span><kbd>Ctrl K</kbd></button>{open&&<dialog ref={dialog} className="bs-dialog" aria-label="Bazaara command palette" onCancel={e=>{e.preventDefault();setOpen(false);}} onClick={e=>{if(e.target===e.currentTarget){const b=e.currentTarget.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)setOpen(false);}}}>
 <header className="bs-head"><Brand name="BAZAARA"/><div><span className={'bs-status'+(online?'':' bs-offline')}>{online?'Online':'Offline'}</span><button type="button" aria-label="Appearance preferences" aria-pressed={settings} onClick={()=>setSettings(v=>!v)}>⚙</button><button type="button" aria-label="Close command palette" onClick={()=>setOpen(false)}>×</button></div></header>
 <div className="bs-lead"><small>YOUR DIGITAL UNIVERSE</small><h2>{settings?'Make it yours.':'Where will you go next?'}</h2><p>{here?`${here.name} · `:''}Independent apps, familiar controls.</p></div>
 {notice&&<p className="bs-notice" role="status">{notice}</p>}
 {settings?<section className="bs-preferences"><h3>Appearance</h3><label>Interface spacing<select value={prefs.density} onChange={e=>change({density:e.target.value==='compact'?'compact':'comfortable'})}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label><input type="checkbox" checked={prefs.contrast} onChange={e=>change({contrast:e.target.checked})}/>Stronger contrast</label><label><input type="checkbox" checked={!prefs.motion} onChange={e=>change({motion:!e.target.checked})}/>Reduce interface motion</label><p>Saved on this browser. Your system’s reduced-motion preference is also respected.</p><button onClick={()=>{change({favorites:[],recent:[currentApp],density:'comfortable',contrast:false,motion:true});}}>Reset launcher preferences</button><button onClick={()=>setSettings(false)}>Back to apps</button></section>:<>
 <label className="bs-search"><span aria-hidden="true">⌕</span><input ref={search} aria-label="Find apps and workflows" type="search" placeholder="Search apps, tools, or a task…" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();dialog.current?.querySelector<HTMLElement>('[data-bs-result]')?.focus();}if(e.key==='Enter'&&visible.length===1&&urls[visible[0].slug])window.location.assign(urls[visible[0].slug]);}}/><kbd>↓</kbd></label>
 <nav className="bs-tabs" aria-label="App groups">{['All','Favorites','Recent','Internet','Workspace','Social','Commerce'].map(s=><button key={s} aria-pressed={s===scope} onClick={()=>setScope(s)}>{s}</button>)}</nav>
 <div className="bs-scroll" onKeyDown={e=>{if(e.key!=='ArrowDown'&&e.key!=='ArrowUp')return;const controls=Array.from(dialog.current?.querySelectorAll<HTMLElement>('[data-bs-result]')||[]);const i=controls.indexOf(document.activeElement as HTMLElement);if(i<0)return;e.preventDefault();controls[(i+(e.key==='ArrowDown'?1:-1)+controls.length)%controls.length]?.focus();}}>
 {!query&&scope==='All'&&<section className="bs-next"><div className="bs-section-title"><h3>Continue your workflow</h3><small>Suggested tools</small></div><div className="bs-grid">{recommended.map(id=>APPS.find(a=>a.slug===id)).filter((a):a is App=>!!a).map(a=>item(a,true))}</div></section>}
 {visible.length?<div className="bs-grid">{visible.map(a=>item(a))}</div>:<div className="bs-empty"><h3>{scope==='Favorites'?'Pin your go-to apps':'No matching apps'}</h3><p>{scope==='Favorites'?'Use the star beside any app to keep it close.':'Try a product name or task such as “write” or “video”.'}</p></div>}
 </div><footer className="bs-foot"><span>{visible.length} apps · preferences on this browser</span><span>↑ ↓ Navigate · Esc Close</span></footer></>}
 </dialog>}</div>;
}
