import { useCallback, useEffect, useState } from "react";
import { Linking, Pressable, Text, TextInput, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import * as SecureStore from "expo-secure-store";
import * as Crypto from "expo-crypto";
import { EmptyState, Screen } from "@bazaara/mobile-ui";
import { foodApi } from "@/lib/api";
import { foodMoney, type FoodOrder } from "@/lib/food";
import { foodStyles as s } from "@/ui/theme";

const PIN_PREFIX="bazaara.food.delivery-pin.";
function formatDuration(seconds:number|null|undefined){if(seconds==null||!Number.isFinite(seconds))return "—";const safe=Math.max(0,Math.floor(seconds));const h=Math.floor(safe/3600),m=Math.floor((safe%3600)/60),sec=safe%60;return h?`${h}h ${m}m`:m?`${m}m ${sec}s`:`${sec}s`;}
export default function FoodOrderDetail(){const{id}=useLocalSearchParams<{id:string}>();const[order,setOrder]=useState<FoodOrder|null>(null);const[pin,setPin]=useState("");const[error,setError]=useState("");const[clock,setClock]=useState(()=>Date.now());const[message,setMessage]=useState("");const[issue,setIssue]=useState("");const[refund,setRefund]=useState("");const[rating,setRating]=useState(5);const[foodRating,setFoodRating]=useState(5);const[deliveryRating,setDeliveryRating]=useState(5);const[review,setReview]=useState("");const[busy,setBusy]=useState("");
 const load=useCallback(async()=>{if(!id)return;try{const body=await foodApi.get<{order:FoodOrder}>(`/v1/food/orders/${encodeURIComponent(id)}`,{cache:"no-store"});setOrder(body.order);setPin(await SecureStore.getItemAsync(`${PIN_PREFIX}${id}`)??"");setError("");if(body.order.deliveryPinVerified)await SecureStore.deleteItemAsync(`${PIN_PREFIX}${id}`)}catch(e){setError(e instanceof Error?e.message:"Could not load order")}},[id]);useEffect(()=>{void load();const timer=setInterval(()=>void load(),5000);const clockTimer=setInterval(()=>setClock(Date.now()),1000);return()=>{clearInterval(timer);clearInterval(clockTimer)}},[load]);
 async function act(key:string,path:string,body?:Record<string,unknown>){if(!id)return;setBusy(key);setError("");try{await foodApi.request(path,{method:"POST",body});await load()}catch(e){setError(e instanceof Error?e.message:"Request failed")}finally{setBusy("")}}
 async function send(){if(!message.trim()||!id)return;setBusy("message");try{await foodApi.post(`/v1/food/orders/${encodeURIComponent(id)}/messages`,{text:message.trim()});setMessage("");await load()}catch(e){setError(e instanceof Error?e.message:"Could not send message")}finally{setBusy("")}}
 async function report(){if(!issue.trim()||!id)return;setBusy("issue");try{await foodApi.post(`/v1/food/orders/${encodeURIComponent(id)}/issues`,{type:"OTHER",details:issue.trim(),requestedRefundMinor:refund?Math.max(0,Math.round(Number(refund)*100)):null});setIssue("");setRefund("");await load()}catch(e){setError(e instanceof Error?e.message:"Could not open support case")}finally{setBusy("")}}
 async function submitReview(){if(!id)return;setBusy("review");try{await foodApi.request(`/v1/food/orders/${encodeURIComponent(id)}/review`,{method:"PUT",body:{rating,foodRating,deliveryRating:order?.fulfillmentType==="DELIVERY"?deliveryRating:null,text:review.trim()||null,photoKeys:[]}});setReview("");await load()}catch(e){setError(e instanceof Error?e.message:"Could not save review")}finally{setBusy("")}}
 async function payNow(){if(!id)return;setBusy("payment");setError("");try{const body=await foodApi.post<{checkoutUrl:string|null}>(`/v1/food/orders/${encodeURIComponent(id)}/payment/initialize`,{}, {idempotencyKey:`food-payment-${Crypto.randomUUID()}`});if(body.checkoutUrl)await Linking.openURL(body.checkoutUrl);await load()}catch(e){setError(e instanceof Error?e.message:"Could not start payment")}finally{setBusy("")}}
 async function checkPayment(){if(!id)return;setBusy("payment-check");setError("");try{await foodApi.post(`/v1/food/orders/${encodeURIComponent(id)}/payment/reconcile`,{});await load()}catch(e){setError(e instanceof Error?e.message:"Could not check payment")}finally{setBusy("")}}
 if(!order)return <Screen tabBarSafe={false}><EmptyState title="Order" message={error||"Loading order…"}/></Screen>;
 const active=!['DELIVERED','CANCELLED'].includes(order.status);const latest=order.tracking.at(-1);const proximity=[...order.tracking].reverse().find(t=>t.status==='COURIER_AT_PICKUP'||t.status==='COURIER_NEAR_PICKUP');const durationEnd=order.deliveredAt?new Date(order.deliveredAt).getTime():order.cancelledAt?new Date(order.cancelledAt).getTime():clock;const durationSeconds=Math.max(0,Math.floor((durationEnd-new Date(order.placedAt).getTime())/1000));
 return <Screen tabBarSafe={false}><View style={s.top}><View><Text style={s.status}>{order.orderNumber}</Text><Text style={s.h1}>{order.status.replaceAll("_"," ")}</Text></View><Pressable onPress={()=>void load()}><Text style={s.status}>REFRESH</Text></Pressable></View>{error?<Text style={s.error}>{error}</Text>:null}<Text style={s.p}>{order.restaurant.name} · {order.fulfillmentType.toLowerCase()} · placed {new Date(order.placedAt).toLocaleString("en-NG")}</Text>
 <View style={[s.card,{marginTop:12,borderColor:order.paymentStatus==="PAID"?"rgba(52,211,153,.38)":"rgba(255,122,0,.38)"}]}><View style={[s.row,{justifyContent:"space-between"}]}><View><Text style={s.status}>{order.paymentStatus==="PAID"?"PAYMENT CONFIRMED":"PAYMENT REQUIRED"}</Text><Text style={s.h2}>{order.paymentMethod==="BAZAARA_PAY"?"Wallet":order.paymentMethod==="PAYSTACK_CARD"?"Card":"Bank transfer"}</Text></View><Text style={order.paymentStatus==="PAID"?s.price:s.error}>{order.paymentStatus}</Text></View><Text style={[s.small,{marginTop:6}]}>{order.paymentStatus==="PAID"?"The restaurant can accept and fulfil this order.":"The restaurant cannot accept this order until payment is confirmed."}</Text>{order.paymentStatus!=="PAID"&&(order.paymentMethod==="PAYSTACK_CARD"||order.paymentMethod==="PAYSTACK_BANK")?<View style={[s.row,{marginTop:10}]}><Pressable style={[s.button,{flex:1}]} disabled={busy==="payment"} onPress={()=>void payNow()}><Text style={s.buttonText}>{busy==="payment"?"Opening…":"Pay now"}</Text></Pressable><Pressable style={[s.secondary,{flex:1}]} disabled={busy==="payment-check"} onPress={()=>void checkPayment()}><Text style={s.secondaryText}>{busy==="payment-check"?"Checking…":"I've paid"}</Text></Pressable></View>:null}</View>
 <View style={[s.card,{marginTop:12,borderColor:"rgba(255,122,0,.28)"}]}><Text style={s.status}>{order.status==="DELIVERED"?"TOTAL DELIVERY TIME":"LIVE ORDER TIME"}</Text><Text style={[s.h1,{marginTop:5}]}>{formatDuration(durationSeconds)}</Text><Text style={s.small}>{order.status==="DELIVERED"?"From order confirmation to delivery":`Estimated ${order.timing.estimatedDeliveryMin}–${order.timing.estimatedDeliveryMax} min`}</Text><View style={[s.row,{marginTop:12,justifyContent:"space-between",gap:8}]}><View style={{flex:1}}><Text style={s.small}>To courier</Text><Text style={s.name}>{formatDuration(order.timing.phases.orderToCourierAssignedSeconds)}</Text></View><View style={{flex:1}}><Text style={s.small}>To pickup</Text><Text style={s.name}>{formatDuration(order.timing.phases.courierAssignedToPickupSeconds)}</Text></View><View style={{flex:1}}><Text style={s.small}>To delivery</Text><Text style={s.name}>{formatDuration(order.timing.phases.pickupToDeliverySeconds)}</Text></View></View></View>
 {proximity&&active?<View style={[s.card,{marginTop:12,borderColor:proximity.status==="COURIER_AT_PICKUP"?"rgba(52,211,153,.45)":"rgba(245,158,11,.45)"}]}><Text style={s.status}>{proximity.status==="COURIER_AT_PICKUP"?"COURIER AT PICKUP":"COURIER NEAR PICKUP"}</Text><Text style={[s.name,{marginTop:6}]}>{proximity.message||"Courier pickup proximity updated."}</Text><Text style={[s.small,{marginTop:4}]}>{new Date(proximity.createdAt).toLocaleTimeString("en-NG")}</Text></View>:null}
 {pin&&!order.deliveryPinVerified&&order.fulfillmentType==="DELIVERY"?<View style={[s.card,{marginTop:14,borderColor:"#FF7A00"}]}><Text style={s.status}>DELIVERY PIN</Text><Text style={[s.h1,{letterSpacing:7,marginTop:4}]}>{pin}</Text><Text style={s.small}>Share this PIN only when your order has arrived. Restaurant staff cannot mark delivery complete before verification.</Text></View>:null}
 <View style={[s.card,{marginTop:12}]}><Text style={s.h2}>Order</Text>{order.items.map(i=><View key={i.id} style={[s.row,{justifyContent:"space-between",marginTop:9}]}><View style={{flex:1}}><Text style={s.name}>{i.quantity} × {i.name}</Text><Text style={s.small}>{i.selectedModifiers.map(m=>m.optionName).join(" · ")}</Text></View><Text style={s.p}>{foodMoney(i.lineTotalMinor)}</Text></View>)}<View style={s.divider}/><Row label="Subtotal" value={foodMoney(order.subtotalMinor)}/><Row label="Delivery" value={foodMoney(order.deliveryFeeMinor)}/><Row label={`Service${order.economics?` ${(order.economics.serviceFeeBps/100).toFixed(1)}%`:""}`} value={foodMoney(order.serviceFeeMinor)}/>{order.tipMinor?<Row label="Tip" value={foodMoney(order.tipMinor)}/>:null}{order.discountMinor?<Row label="Discount" value={`−${foodMoney(order.discountMinor)}`}/>:null}<Row label="Total" value={foodMoney(order.totalMinor)} strong/></View>
 <View style={[s.card,{marginTop:12}]}><Text style={s.h2}>Tracking</Text>{order.tracking.length?order.tracking.map(t=><View key={t.id} style={{marginTop:10}}><Text style={s.name}>{t.status.replaceAll("_"," ")}</Text><Text style={s.p}>{t.message||"Order status updated"}</Text><Text style={s.small}>{new Date(t.createdAt).toLocaleString("en-NG")}{t.latitude!=null&&t.longitude!=null?` · ${t.latitude.toFixed(5)}, ${t.longitude.toFixed(5)}`:""}</Text></View>):<Text style={s.p}>Tracking updates will appear here.</Text>}{latest?.latitude!=null?<Text style={[s.small,{marginTop:10}]}>Courier location is shown only when a real location update has been received.</Text>:null}{order.courier?<View style={[s.row,{justifyContent:"space-between",marginTop:12}]}><Text style={s.p}>GO: {order.courier.displayName}</Text>{order.courier.phone?<Pressable style={s.secondary} onPress={()=>void Linking.openURL(`tel:${order.courier?.phone}`)}><Text style={s.secondaryText}>Call</Text></Pressable>:null}</View>:<Text style={[s.small,{marginTop:10}]}>{order.status==="READY"?"GO is matching an eligible nearby courier.":"Courier assignment starts when the restaurant is ready."}</Text>}</View>
 <View style={[s.card,{marginTop:12}]}><Text style={s.h2}>Order chat</Text>{order.messages.slice(-10).map(m=><View key={m.id} style={{marginTop:8}}><Text style={s.p}>{m.text||"Media message"}</Text><Text style={s.small}>{new Date(m.createdAt).toLocaleTimeString("en-NG")}</Text></View>)}<TextInput style={[s.input,{marginTop:10}]} placeholder="Message the restaurant" placeholderTextColor="#7E8DA6" value={message} onChangeText={setMessage}/><Pressable style={[s.secondary,{marginTop:8}]} disabled={!message.trim()||busy==="message"} onPress={()=>void send()}><Text style={s.secondaryText}>Send message</Text></Pressable></View>
 {active?<View style={[s.row,{marginTop:12}]}>{['PLACED','ACCEPTED'].includes(order.status)?<Pressable style={[s.secondary,{flex:1}]} disabled={busy==="cancel"} onPress={()=>void act("cancel",`/v1/food/orders/${encodeURIComponent(order.id)}/cancel`)}><Text style={s.error}>Cancel order</Text></Pressable>:null}<Pressable style={[s.secondary,{flex:1}]} disabled={busy==="reorder"} onPress={async()=>{setBusy("reorder");try{await foodApi.post(`/v1/food/orders/${encodeURIComponent(order.id)}/reorder`,{});router.push(`/cart/${order.restaurant.slug}`)}catch(e){setError(e instanceof Error?e.message:"Could not reorder")}finally{setBusy("")}}}><Text style={s.secondaryText}>Reorder</Text></Pressable></View>:null}
 <View style={[s.card,{marginTop:12}]}><Text style={s.h2}>Support & refunds</Text>{order.supportIssues.map(i=><View key={i.id} style={{marginTop:9}}><Text style={s.name}>{i.type.replaceAll("_"," ")} · {i.status}</Text><Text style={s.p}>{i.details}</Text>{i.approvedRefundMinor!=null?<Text style={s.price}>Approved: {foodMoney(i.approvedRefundMinor)}</Text>:null}</View>)}<TextInput style={[s.input,{marginTop:10,minHeight:72,textAlignVertical:"top"}]} multiline placeholder="Describe what went wrong" placeholderTextColor="#7E8DA6" value={issue} onChangeText={setIssue}/><TextInput style={[s.input,{marginTop:8}]} keyboardType="numeric" placeholder="Requested refund ₦ (optional)" placeholderTextColor="#7E8DA6" value={refund} onChangeText={setRefund}/><Pressable style={[s.secondary,{marginTop:8}]} disabled={!issue.trim()||busy==="issue"} onPress={()=>void report()}><Text style={s.secondaryText}>{busy==="issue"?"Opening…":"Report order issue"}</Text></Pressable><Pressable style={[s.button,{marginTop:8}]} disabled={busy!==""} onPress={()=>router.push({pathname:"/support",params:{orderId:order.id}} as never)}><Text style={s.buttonText}>Open live support chat</Text></Pressable></View>
 {order.status==="DELIVERED"?<View style={[s.card,{marginTop:12}]}><Text style={s.h2}>Your review</Text>{order.review?<><Text style={s.price}>{"★".repeat(order.review.rating)}{"☆".repeat(5-order.review.rating)}</Text>{order.review.foodRating?<Text style={s.p}>Food {order.review.foodRating}/5{order.review.deliveryRating?` · Delivery ${order.review.deliveryRating}/5`:""}</Text>:null}{order.review.text?<Text style={s.p}>{order.review.text}</Text>:null}{order.review.restaurantReply?<Text style={[s.p,{marginTop:8}]}>Restaurant reply: {order.review.restaurantReply}</Text>:null}</>:<><Text style={[s.small,{marginTop:8}]}>Overall</Text><View style={[s.wrap,{marginTop:6}]}>{[1,2,3,4,5].map(v=><Pressable key={v} style={[s.pill,rating===v&&s.pillActive]} onPress={()=>setRating(v)}><Text style={[s.pillText,rating===v&&s.pillTextActive]}>{v} ★</Text></Pressable>)}</View><Text style={[s.small,{marginTop:10}]}>Food & restaurant</Text><View style={[s.wrap,{marginTop:6}]}>{[1,2,3,4,5].map(v=><Pressable key={v} style={[s.pill,foodRating===v&&s.pillActive]} onPress={()=>setFoodRating(v)}><Text style={[s.pillText,foodRating===v&&s.pillTextActive]}>{v} ★</Text></Pressable>)}</View>{order.fulfillmentType==="DELIVERY"?<><Text style={[s.small,{marginTop:10}]}>Delivery experience</Text><View style={[s.wrap,{marginTop:6}]}>{[1,2,3,4,5].map(v=><Pressable key={v} style={[s.pill,deliveryRating===v&&s.pillActive]} onPress={()=>setDeliveryRating(v)}><Text style={[s.pillText,deliveryRating===v&&s.pillTextActive]}>{v} ★</Text></Pressable>)}</View></>:null}<TextInput style={[s.input,{marginTop:8,minHeight:72,textAlignVertical:"top"}]} multiline placeholder="What was good or could improve?" placeholderTextColor="#7E8DA6" value={review} onChangeText={setReview}/><Pressable style={[s.button,{marginTop:8}]} disabled={busy==="review"} onPress={()=>void submitReview()}><Text style={s.buttonText}>Publish review</Text></Pressable></>}</View>:null}
 </Screen>}
function Row({label,value,strong}:{label:string;value:string;strong?:boolean}){return <View style={[s.row,{justifyContent:"space-between",marginTop:6}]}><Text style={strong?s.name:s.p}>{label}</Text><Text style={strong?s.name:s.p}>{value}</Text></View>}
