import {useCallback,useEffect,useState} from "react";
import {Image,Pressable,Text,View} from "react-native";
import {router,useLocalSearchParams} from "expo-router";
import {EmptyState,Screen} from "@bazaara/mobile-ui";
import {groceryApi,groceryCartRequest} from "@/lib/api";
import {groceryMoney,type ProductDetail} from "@/lib/grocery";
import {groceryStyles as s} from "@/ui/theme";

export default function GroceryProduct(){const{slug}=useLocalSearchParams<{slug:string}>();const[product,setProduct]=useState<ProductDetail|null>(null);const[variantId,setVariantId]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const load=useCallback(async()=>{if(!slug)return;try{const body=await groceryApi.get<{product:ProductDetail}>(`/v1/shopping/products/${encodeURIComponent(slug)}`,{cache:'no-store'});if(body.product.seller?.vertical&&body.product.seller.vertical!=='GROCERY')throw new Error('This item belongs to Marketplace, not Grocery.');setProduct(body.product);setVariantId(body.product.defaultVariantId??body.product.variants[0]?.id??'');setError('')}catch(e){setError(e instanceof Error?e.message:'Could not load Grocery item')}},[slug]);useEffect(()=>{void load()},[load]);async function add(){if(!variantId)return;setBusy(true);try{await groceryCartRequest('/v1/grocery/cart/items',{method:'POST',body:{variantId,quantity:1}});router.push('/cart')}catch(e){setError(e instanceof Error?e.message:'Could not add item')}finally{setBusy(false)}}if(!product)return <Screen tabBarSafe={false}><EmptyState title="Grocery item" message={error||'Loading item…'}/></Screen>;const selected=product.variants.find(v=>v.id===variantId);return <Screen tabBarSafe={false}>{product.media[0]?.url||product.image?.url?<Image source={{uri:product.media[0]?.url??product.image?.url}} style={[s.image,{height:280}]}/>:<View style={[s.image,{height:280}]}/>}<Text style={[s.h1,{marginTop:14}]}>{product.title}</Text>{product.brand?<Text style={s.meta}>{product.brand.name}</Text>:null}<Text style={[s.price,{fontSize:23,marginTop:8}]}>{groceryMoney(selected?.priceMinor??product.priceMinor,product.currency)}</Text><Text style={[s.p,{marginTop:8}]}>{product.description}</Text>{product.variants.length>1?<View style={[s.card,{marginTop:14}]}><Text style={s.h2}>Choose an option</Text><View style={[s.wrap,{marginTop:8}]}>{product.variants.map(v=><Pressable key={v.id} style={[s.pill,variantId===v.id&&s.pillActive]} disabled={v.availableQuantity<1} onPress={()=>setVariantId(v.id)}><Text style={[s.pillText,variantId===v.id&&s.pillTextActive]}>{v.title} · {groceryMoney(v.priceMinor)}</Text></Pressable>)}</View></View>:null}<View style={[s.card,{marginTop:12}]}><Text style={s.h2}>Buying confidence</Text><Text style={s.p}>{product.seller?.verified?'Verified Grocery seller':'Grocery seller'} · {selected?.availableQuantity??product.availableQuantity} available</Text><Text style={s.p}>Fulfilment: {product.fulfillmentModes.join(' · ')||'STANDARD'}</Text></View>{error?<Text style={[s.error,{marginTop:8}]}>{error}</Text>:null}<Pressable style={[s.button,{marginTop:16},(!selected||selected.availableQuantity<1)&&{opacity:.45}]} disabled={busy||!selected||selected.availableQuantity<1} onPress={()=>void add()}><Text style={s.buttonText}>{busy?'Adding…':'Add to Grocery basket'}</Text></Pressable></Screen>}
