"use client";
import { useCallback, useEffect, useState, type FormEvent } from "react";
import { api, errorText } from "@bazaara/social-ui";
import { Access, Frame, State, useReady } from "./Frame";
type Topic={id:string;slug:string;name:string;description:string;_count:{threads:number}};
type Thread={id:string;title:string;body:string;createdAt:string;topic:{name:string};author:{displayName:string|null};_count:{replies:number};voteScore:number;myVote:number};
type Post={id:string;body:string;author:{displayName:string|null};_count:{likes:number;comments:number}};
export default function BicordNext(){
 const session=useReady();const [mode,setMode]=useState<"atlas"|"boards"|"feed">("atlas");const [topics,setTopics]=useState<Topic[]>([]),[topic,setTopic]=useState(""),[threads,setThreads]=useState<Thread[]>([]),[posts,setPosts]=useState<Post[]>([]),[error,setError]=useState(""),[title,setTitle]=useState(""),[body,setBody]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const [ts,ps]=await Promise.all([api.get<{topics:Topic[]}>("/v1/bazforum/topics",{maxRetries:0}),api.get<{posts:Post[]}>("/v1/bazcircle/feed",{query:{limit:16},maxRetries:0})]);setTopics(ts.topics);setPosts(ps.posts)}catch(e){setError(errorText(e))}},[]);
 const loadThreads=useCallback(async(id:string)=>{if(!id)return;try{const r=await api.get<{threads:Thread[]}>("/v1/bazforum/threads",{query:{topicId:id},maxRetries:0});setThreads(r.threads)}catch(e){setError(errorText(e))}},[]);
 useEffect(()=>{if(session.user?.profile)void load()},[session.user?.profile,load]);
 useEffect(()=>{void loadThreads(topic)},[topic,loadThreads]);
 async function create(e:FormEvent){e.preventDefault();if(!topic||!title.trim()||!body.trim()||busy)return;setBusy(true);try{await api.post("/v1/bazforum/threads",{topicId:topic,title:title.trim(),body:body.trim()});setTitle("");setBody("");await loadThreads(topic)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function vote(t:Thread,v:1|-1){try{const x=t.myVote===v?await api.delete<{myVote:number;voteScore:number}>(`/v1/bazforum/threads/${encodeURIComponent(t.id)}/vote`):await api.put<{myVote:number;voteScore:number}>(`/v1/bazforum/threads/${encodeURIComponent(t.id)}/vote`,{value:v});setThreads(rows=>rows.map(y=>y.id===t.id?{...y,...x}:y))}catch(e){setError(errorText(e))}}
 return <Frame app="Bicord" initial="COMMUNITY" mark="Bi" accent="#8a5cff" nav={[{id:"atlas",label:"Atlas",active:mode==="atlas",onClick:()=>setMode("atlas")},{id:"boards",label:"Boards",active:mode==="boards",onClick:()=>setMode("boards")},{id:"feed",label:"Community feed",active:mode==="feed",onClick:()=>setMode("feed")},{id:"current",label:"Current Bicord",onClick:()=>window.location.assign("/")}]}><Access session={session} app="Bicord"/>{session.user?.profile&&<><div className="nx-eyebrow">WELCOME TO THE ATLAS</div><h1>Find your people.<br/>Build your place.</h1><p className="nx-muted">Current discussion topics and the social feed in one standalone product. Real Circle membership, Voice Rooms and granular roles are the next backend milestone.</p>{error&&<div className="nx-alert" role="alert">{error}</div>}<div className="nx-bicordLayout"><aside className="nx-card nx-bicordLeft"><h2>Atlas</h2><p className="nx-muted">Browse current topic-based discussion spaces; full Circle membership is a future service.</p><button className="nx-secondary" onClick={()=>void load()}>Refresh</button><div className="nx-list nx-section">{topics.map(t=><button className={`nx-item ${topic===t.id?"nx-on":""}`} key={t.id} onClick={()=>{setTopic(t.id);setMode("boards")}}><span className="nx-thumb">#</span><span><strong>{t.name}</strong><small>{t._count.threads} discussions</small></span></button>)}{!topics.length&&<State>No Circles yet. Create a community through the current Bicord app.</State>}</div><a href="/" className="nx-secondary nx-bicordLink">Community management ↗</a></aside>
 <section className="nx-card nx-bicordCenter">{mode==="feed"?<><h2>Community feed</h2><p className="nx-muted">The social side of Bicord, without a separate BazCircle app.</p><div className="nx-list">{posts.map(p=><article key={p.id} className="nx-bicordPost"><span className="nx-eyebrow">{p.author.displayName??"Member"}</span><p>{p.body}</p><span className="nx-muted">{p._count.likes} reactions · {p._count.comments} comments</span></article>)}{!posts.length&&<State>Community feed is quiet. Create a post in current Bicord.</State>}</div></>:mode==="atlas"?<div className="nx-bicordAtlas"><span className="nx-bicordOrb">◈</span><h2>Atlas makes discovery intentional.</h2><p>Choose a current discussion space on the left to explore its topics. True Circle membership, Collections, Streams and Voice Rooms require the next community backend milestone.</p><span className="nx-tag">Rooms / Stage / Events: architecture planned</span></div>:<><div className="nx-row"><div><span className="nx-eyebrow">BOARD</span><h2>{topics.find(t=>t.id===topic)?.name??"Choose a Circle"}</h2></div><span className="nx-tag">{threads.length} topics</span></div>{topic&&<form className="nx-bicordCompose" onSubmit={e=>void create(e)}><label htmlFor="nx-topic-title">New discussion</label><input className="nx-input" id="nx-topic-title" placeholder="Discussion title" maxLength={120} value={title} onChange={e=>setTitle(e.target.value)}/><label className="nx-sr" htmlFor="nx-topic-body">Discussion body</label><textarea className="nx-input" id="nx-topic-body" placeholder="Share your thoughts" rows={3} maxLength={5000} value={body} onChange={e=>setBody(e.target.value)}/><button className="nx-primary" disabled={busy||!title.trim()||!body.trim()}>Publish discussion</button></form>}{threads.length?threads.map(t=><article className="nx-bicordPost" key={t.id}><span className="nx-eyebrow">{t.author.displayName??"Member"}</span><h3>{t.title}</h3><p>{t.body}</p><div className="nx-row"><span className="nx-muted">{t._count.replies} replies · score {t.voteScore}</span><div className="nx-row"><button className="nx-secondary" aria-pressed={t.myVote===1} onClick={()=>void vote(t,1)}>↑</button><button className="nx-secondary" aria-pressed={t.myVote===-1} onClick={()=>void vote(t,-1)}>↓</button></div></div></article>):<State>{topic?"No discussions in this Board yet.":"Choose a discussion space to view its topics."}</State>}</>}</section></div></>}</Frame>
}
