import { randomBytes } from "node:crypto";
import { db, Prisma } from "@bazaara/db";
import { postJournal } from "@bazaara/ledger";
import { hashPassword, verifyPassword } from "@bazaara/security";
import type { PayActivityContract, PayBankAccountContract, PayBankContract, PayBeneficiaryContract, PayFeeQuoteContract, PayFixedSavingsContract, PayLoanApplicationContract, PayMoneyRequestContract, PayProfileContract, PayRecipientContract, PayTransferContract, PayWalletContract, PayWithdrawalContract } from "@bazaara/contracts";
import { AppError } from "../errors.js";
import { appendOutboxEvent } from "../outbox.js";
import { env } from "../config.js";
import { createPaystackTransferRecipient, initiatePaystackTransfer, listPaystackBanks, resolvePaystackBankAccount, verifyPaystackTransfer } from "../payments/paystack.js";

function minor(value: bigint) { const n = Number(value); if (!Number.isSafeInteger(n)) throw new Error("Monetary value exceeds transport range"); return n; }
function cleanTag(value: string) { return value.toLowerCase().replace(/[^a-z0-9]/g, "").slice(0, 16) || "bazaara"; }
function requestCode() { return `BZR-${randomBytes(5).toString("hex").toUpperCase()}`; }

export async function ensureUserWallet(userId: string, currency = env.CURRENCY) {
  return db.$transaction(async (tx) => {
    let wallet = await tx.wallet.findUnique({ where: { ownerKey_currency: { ownerKey: `user:${userId}`, currency } } });
    if (!wallet) wallet = await tx.wallet.create({ data: { userId, ownerKey: `user:${userId}`, currency } });
    let account = await tx.ledgerAccount.findFirst({ where: { walletId: wallet.id, currency, kind: "WALLET_LIABILITY" } });
    if (!account) account = await tx.ledgerAccount.create({ data: { walletId: wallet.id, code: `wallet:${wallet.id}:${currency}`, currency, kind: "WALLET_LIABILITY" } });
    return { wallet, account };
  });
}

async function balanceMinor(accountId: string, tx: Prisma.TransactionClient | typeof db = db) {
  const grouped = await tx.ledgerEntry.groupBy({ by: ["direction"], where: { accountId }, _sum: { amountMinor: true } });
  let credit = 0n, debit = 0n; for (const row of grouped) { if (row.direction === "CREDIT") credit = row._sum.amountMinor ?? 0n; else debit = row._sum.amountMinor ?? 0n; }
  return credit - debit;
}

export async function walletContract(userId: string): Promise<PayWalletContract> {
  const { wallet, account } = await ensureUserWallet(userId);
  return { id: wallet.id, ownerKey: wallet.ownerKey, currency: wallet.currency, status: wallet.status, availableMinor: minor(await balanceMinor(account.id)) };
}

export async function ensurePayProfile(userId: string) {
  const existing = await db.payProfile.findUnique({ where: { userId } }); if (existing) return existing;
  const user = await db.user.findUnique({ where: { id: userId }, include: { emails: { where: { isPrimary: true }, take: 1 } } });
  if (!user) throw new AppError("NOT_FOUND", "BazID user not found", 404);
  const base = cleanTag(user.displayName || user.emails[0]?.email.split("@")[0] || "bazaara");
  for (let i=0;i<8;i++) {
    const payTag = `${base}-${randomBytes(2).toString("hex")}`;
    try { return await db.payProfile.create({ data: { userId, payTag } }); } catch (error) { if (i === 7) throw error; }
  }
  throw new Error("Could not allocate Wallet tag");
}

export async function payProfileContract(userId: string): Promise<PayProfileContract> {
  const p = await ensurePayProfile(userId);
  return { userId, payTag: p.payTag, pinSet: Boolean(p.pinHash), dailyTransferLimitMinor: minor(p.dailyTransferLimitMinor), pinLockedUntil: p.pinLockedUntil?.toISOString() ?? null };
}

export async function setPayPin(input: { userId:string; password:string; pin:string }) {
  const credential = await db.passwordCredential.findUnique({ where: { userId: input.userId } });
  if (!credential || !(await verifyPassword(credential.passwordHash, input.password))) throw new AppError("FORBIDDEN", "Your BazID password is incorrect", 403);
  if (!/^\d{6}$/.test(input.pin)) throw new AppError("BAD_REQUEST", "Wallet PIN must be exactly 6 digits", 400);
  const pinHash = await hashPassword(input.pin);
  await ensurePayProfile(input.userId);
  await db.payProfile.update({ where: { userId: input.userId }, data: { pinHash, failedPinAttempts: 0, pinLockedUntil: null } });
  return payProfileContract(input.userId);
}

export async function verifyPayPin(userId: string, pin: string | undefined) {
  const profile = await ensurePayProfile(userId);
  if (!profile.pinHash) throw new AppError("CONFLICT", "Set your 6-digit Wallet PIN before sending money", 409);
  if (profile.pinLockedUntil && profile.pinLockedUntil > new Date()) throw new AppError("FORBIDDEN", "Wallet PIN is temporarily locked. Try again later.", 423);
  if (!pin || !(await verifyPassword(profile.pinHash, pin))) {
    const failed = profile.failedPinAttempts + 1; const lock = failed >= 5 ? new Date(Date.now()+15*60_000) : null;
    await db.payProfile.update({ where: { userId }, data: { failedPinAttempts: lock ? 0 : failed, pinLockedUntil: lock } });
    throw new AppError("FORBIDDEN", lock ? "Too many incorrect PIN attempts. Pay is locked for 15 minutes." : "Incorrect Wallet PIN", lock ? 423 : 403);
  }
  if (profile.failedPinAttempts || profile.pinLockedUntil) await db.payProfile.update({ where: { userId }, data: { failedPinAttempts: 0, pinLockedUntil: null } });
  return profile;
}

function mask(value: string) {
  if (value.includes("@")) {
    const [local = "", domain = ""] = value.split("@", 2);
    return `${local.slice(0, 2)}***@${domain}`;
  }
  if (value.startsWith("+")) return `${value.slice(0, 4)}***${value.slice(-3)}`;
  return null;
}

export async function resolveRecipient(identifier: string, currency = env.CURRENCY): Promise<PayRecipientContract> {
  const raw = identifier.trim(); if (!raw) throw new AppError("BAD_REQUEST", "Recipient is required", 400);
  let userId: string | null = null; let masked: string | null = null;
  if (raw.startsWith("@")) { const profile = await db.payProfile.findUnique({ where: { payTag: raw.slice(1).toLowerCase() } }); userId = profile?.userId ?? null; }
  else {
    const wallet = await db.wallet.findUnique({ where: { id: raw } }); if (wallet?.userId) userId = wallet.userId;
    if (!userId && raw.includes("@")) { const email = await db.userEmail.findFirst({ where: { normalized: raw.toLowerCase(), verifiedAt: { not: null } } }); userId = email?.userId ?? null; masked = mask(raw); }
    if (!userId && raw.startsWith("+")) { const phone = await db.userPhone.findFirst({ where: { e164: raw, verifiedAt: { not: null } } }); userId = phone?.userId ?? null; masked = mask(raw); }
  }
  if (!userId) throw new AppError("NOT_FOUND", "No Wallet user matches that exact Pay tag, email, phone or wallet ID", 404);
  const user = await db.user.findUnique({ where: { id: userId }, select: { displayName: true } });
  const { wallet } = await ensureUserWallet(userId, currency); const profile = await ensurePayProfile(userId);
  return { userId, walletId: wallet.id, displayName: user?.displayName || `@${profile.payTag}`, payTag: profile.payTag, maskedContact: masked };
}

function transferContract(t: any): PayTransferContract { const feeMinor=minor(t.feeMinor??0n); const amountMinor=minor(t.amountMinor); return { id:t.id,reference:t.reference,fromWalletId:t.fromWalletId,toWalletId:t.toWalletId,amountMinor,feeMinor,totalDebitMinor:amountMinor+feeMinor,currency:t.currency,status:t.status,ledgerTransactionId:t.ledgerTransactionId,createdAt:t.createdAt.toISOString(),completedAt:t.completedAt?.toISOString()??null,note:t.note??null }; }
export function quotePayTransferFee(amountMinor:number,currency=env.CURRENCY):PayFeeQuoteContract{const amount=BigInt(Math.max(0,Math.trunc(amountMinor)));const raw=env.PAY_P2P_FEE_BPS<=0?0n:(amount*BigInt(env.PAY_P2P_FEE_BPS)+9999n)/10000n;const min=BigInt(env.PAY_P2P_FEE_MIN_MINOR),max=BigInt(env.PAY_P2P_FEE_MAX_MINOR);const fee=raw===0n?0n:(raw<min?min:raw>max?max:raw);return{amountMinor:minor(amount),feeMinor:minor(fee),totalDebitMinor:minor(amount+fee),currency,bps:env.PAY_P2P_FEE_BPS,minMinor:env.PAY_P2P_FEE_MIN_MINOR,maxMinor:env.PAY_P2P_FEE_MAX_MINOR};}
async function feeRevenueAccount(tx:Prisma.TransactionClient,currency:string){const code=`bazaara:pay:fee-revenue:${currency}`;return await tx.ledgerAccount.findUnique({where:{code}})??await tx.ledgerAccount.create({data:{code,currency,kind:"PLATFORM_FEE_REVENUE"}});}

async function outgoingToday(userId: string) { const start = new Date(); start.setUTCHours(0,0,0,0); const [t,w] = await Promise.all([db.payTransfer.aggregate({ where:{actorUserId:userId,status:"COMPLETED",createdAt:{gte:start}}, _sum:{amountMinor:true} }), db.payWithdrawal.aggregate({ where:{userId,status:{in:["PENDING","PROCESSING","COMPLETED"]},createdAt:{gte:start}}, _sum:{amountMinor:true} })]); return (t._sum.amountMinor??0n)+(w._sum.amountMinor??0n); }

export async function createWalletTransfer(input:{userId:string;toWalletId:string;amountMinor:number;currency:string;note?:string|null;pin?:string;idempotencyKey:string;reference?:string}){
 const profile=await verifyPayPin(input.userId,input.pin);const quote=quotePayTransferFee(input.amountMinor,input.currency);const spent=await outgoingToday(input.userId);if(spent+BigInt(quote.totalDebitMinor)>profile.dailyTransferLimitMinor)throw new AppError("CONFLICT","This transfer would exceed your Wallet daily limit",409);
 const {wallet:source}=await ensureUserWallet(input.userId,input.currency);if(source.id===input.toWalletId)throw new AppError("BAD_REQUEST","You cannot send money to your own wallet",400);const destination=await db.wallet.findUnique({where:{id:input.toWalletId}});if(!destination||destination.currency!==input.currency||destination.status!=="ACTIVE")throw new AppError("NOT_FOUND","Destination wallet not found",404);
 const existing=await db.payTransfer.findFirst({where:{actorUserId:input.userId,idempotencyKey:input.idempotencyKey}});if(existing)return transferContract(existing);const reference=input.reference??`PAY-${Date.now().toString(36).toUpperCase()}-${randomBytes(4).toString("hex").toUpperCase()}`;
 const completed=await db.$transaction(async tx=>{const sourceAccount=await tx.ledgerAccount.findFirst({where:{walletId:source.id,currency:input.currency,kind:"WALLET_LIABILITY"}});if(!sourceAccount)throw new AppError("CONFLICT","Source ledger account is missing",409);const destinationAccount=await tx.ledgerAccount.findFirst({where:{walletId:destination.id,currency:input.currency,kind:"WALLET_LIABILITY"}})??await tx.ledgerAccount.create({data:{walletId:destination.id,code:`wallet:${destination.id}:${input.currency}`,currency:input.currency,kind:"WALLET_LIABILITY"}});const amount=BigInt(input.amountMinor),fee=BigInt(quote.feeMinor),total=amount+fee;const available=await balanceMinor(sourceAccount.id,tx);if(available<total)throw new AppError("CONFLICT","Insufficient wallet balance including transaction fee",409);const pending=await tx.payTransfer.create({data:{reference,actorUserId:input.userId,fromWalletId:source.id,toWalletId:destination.id,amountMinor:amount,feeMinor:fee,currency:input.currency,status:"PENDING",idempotencyKey:input.idempotencyKey,note:input.note?.trim().slice(0,180)||null}});const lines:any[]=[{accountId:sourceAccount.id,direction:"DEBIT",amountMinor:total},{accountId:destinationAccount.id,direction:"CREDIT",amountMinor:amount}];if(fee>0n){const feeAccount=await feeRevenueAccount(tx,input.currency);lines.push({accountId:feeAccount.id,direction:"CREDIT",amountMinor:fee});}const journal=await postJournal(tx,{reference:`pay-transfer:${pending.id}`,kind:"WALLET_TRANSFER",currency:input.currency,description:input.note?.trim()||`Wallet transfer ${reference}`,lines});const row=await tx.payTransfer.update({where:{id:pending.id},data:{status:"COMPLETED",ledgerTransactionId:journal.id,completedAt:new Date()}});await appendOutboxEvent(tx,{aggregateType:"PayTransfer",aggregateId:row.id,eventType:"pay.transfer.completed",payload:{transferId:row.id,fromWalletId:source.id,toWalletId:destination.id,amountMinor:input.amountMinor,feeMinor:quote.feeMinor,totalDebitMinor:quote.totalDebitMinor,currency:input.currency}});return row;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});return transferContract(completed);
}

export async function listTransfers(userId:string){ const wallets=await db.wallet.findMany({where:{userId},select:{id:true}}); const ids=wallets.map(w=>w.id); const rows=await db.payTransfer.findMany({where:{OR:[{fromWalletId:{in:ids}},{toWalletId:{in:ids}}]},orderBy:{createdAt:"desc"},take:100}); return rows.map(transferContract); }

export async function listActivity(userId:string):Promise<PayActivityContract[]>{ const {account}=await ensureUserWallet(userId); const entries=await db.ledgerEntry.findMany({where:{accountId:account.id},include:{transaction:true},orderBy:{createdAt:"desc"},take:100}); return entries.map(e=>({id:e.id,transactionId:e.transactionId,reference:e.transaction.reference,kind:e.transaction.kind,direction:e.direction==="CREDIT"?"IN":"OUT",amountMinor:minor(e.amountMinor),currency:e.transaction.currency,description:e.transaction.description,createdAt:e.createdAt.toISOString()})); }

async function userDisplay(userId:string){ const [user,profile]=await Promise.all([db.user.findUnique({where:{id:userId},select:{displayName:true}}),ensurePayProfile(userId)]); return {displayName:user?.displayName||`@${profile.payTag}`,payTag:profile.payTag}; }

function requestContract(row:any, display:{displayName:string;payTag:string}):PayMoneyRequestContract { return {id:row.id,code:row.code,requesterUserId:row.requesterUserId,requesterWalletId:row.requesterWalletId,requesterDisplayName:display.displayName,requesterPayTag:display.payTag,payerUserId:row.payerUserId,payerWalletId:row.payerWalletId,amountMinor:minor(row.amountMinor),currency:row.currency,note:row.note,status:row.status,createdAt:row.createdAt.toISOString(),expiresAt:row.expiresAt.toISOString(),paidAt:row.paidAt?.toISOString()??null,cancelledAt:row.cancelledAt?.toISOString()??null}; }

export async function createMoneyRequest(input:{userId:string;recipient?:string;amountMinor:number;currency:string;note?:string}){ const {wallet}=await ensureUserWallet(input.userId,input.currency); const profile=await ensurePayProfile(input.userId); let payerUserId:null|string=null,payerWalletId:null|string=null; if(input.recipient?.trim()){const r=await resolveRecipient(input.recipient,input.currency); if(r.userId===input.userId) throw new AppError("BAD_REQUEST","You cannot request money from yourself",400); payerUserId=r.userId;payerWalletId=r.walletId;} const row=await db.payMoneyRequest.create({data:{code:requestCode(),requesterUserId:input.userId,requesterWalletId:wallet.id,payerUserId,payerWalletId,amountMinor:BigInt(input.amountMinor),currency:input.currency,note:input.note?.trim().slice(0,180)||null,expiresAt:new Date(Date.now()+7*24*60*60_000)}}); const d=await userDisplay(input.userId); return requestContract(row,d); }

export async function listMoneyRequests(userId:string){ const rows=await db.payMoneyRequest.findMany({where:{OR:[{requesterUserId:userId},{payerUserId:userId}]},orderBy:{createdAt:"desc"},take:80}); const ids=[...new Set(rows.map(r=>r.requesterUserId))]; const displays=new Map<string,{displayName:string;payTag:string}>(); for(const id of ids) displays.set(id,await userDisplay(id)); return rows.map(r=>requestContract(r,displays.get(r.requesterUserId)!)); }

export async function getMoneyRequestByCode(code:string){ const row=await db.payMoneyRequest.findUnique({where:{code}}); if(!row) throw new AppError("NOT_FOUND","Payment request not found",404); if(row.status==="PENDING"&&row.expiresAt<new Date()) await db.payMoneyRequest.update({where:{id:row.id},data:{status:"EXPIRED"}}); const fresh=await db.payMoneyRequest.findUnique({where:{id:row.id}}); return requestContract(fresh,await userDisplay(row.requesterUserId)); }

export async function payMoneyRequest(input:{userId:string;requestId:string;pin:string;idempotencyKey:string}){ const row=await db.payMoneyRequest.findUnique({where:{id:input.requestId}}); if(!row) throw new AppError("NOT_FOUND","Payment request not found",404); if(row.status!=="PENDING"||row.expiresAt<new Date()) throw new AppError("CONFLICT","This payment request is no longer payable",409); if(row.requesterUserId===input.userId) throw new AppError("BAD_REQUEST","You cannot pay your own request",400); if(row.payerUserId&&row.payerUserId!==input.userId) throw new AppError("FORBIDDEN","This request was created for another payer",403); const transfer=await createWalletTransfer({userId:input.userId,toWalletId:row.requesterWalletId,amountMinor:minor(row.amountMinor),currency:row.currency,note:row.note||`Payment request ${row.code}`,pin:input.pin,idempotencyKey:input.idempotencyKey,reference:`REQ-${row.code}`}); const updated=await db.payMoneyRequest.update({where:{id:row.id},data:{status:"PAID",payerUserId:input.userId,payerWalletId:transfer.fromWalletId,ledgerTransactionId:transfer.ledgerTransactionId,paidAt:new Date()}}); return requestContract(updated,await userDisplay(updated.requesterUserId)); }

export async function cancelMoneyRequest(userId:string,id:string){ const row=await db.payMoneyRequest.findFirst({where:{id,requesterUserId:userId}}); if(!row) throw new AppError("NOT_FOUND","Payment request not found",404); if(row.status!=="PENDING") throw new AppError("CONFLICT","Only pending requests can be cancelled",409); const updated=await db.payMoneyRequest.update({where:{id},data:{status:"CANCELLED",cancelledAt:new Date()}}); return requestContract(updated,await userDisplay(userId)); }

export async function listBeneficiaries(userId:string):Promise<PayBeneficiaryContract[]>{ const rows=await db.payBeneficiary.findMany({where:{userId},orderBy:{createdAt:"desc"}}); const result=[] as PayBeneficiaryContract[]; for(const row of rows){const wallet=await db.wallet.findUnique({where:{id:row.walletId}}); if(!wallet?.userId) continue; const d=await userDisplay(wallet.userId); result.push({id:row.id,walletId:row.walletId,displayName:d.displayName,payTag:d.payTag,label:row.label,createdAt:row.createdAt.toISOString()});} return result; }
export async function saveBeneficiary(input:{userId:string;walletId:string;label?:string}){ const wallet=await db.wallet.findUnique({where:{id:input.walletId}}); if(!wallet?.userId||wallet.userId===input.userId) throw new AppError("BAD_REQUEST","Invalid beneficiary",400); await db.payBeneficiary.upsert({where:{userId_walletId:{userId:input.userId,walletId:input.walletId}},update:{label:input.label?.trim().slice(0,60)||null},create:{userId:input.userId,walletId:input.walletId,label:input.label?.trim().slice(0,60)||null}}); return listBeneficiaries(input.userId); }
export async function removeBeneficiary(userId:string,id:string){ await db.payBeneficiary.deleteMany({where:{id,userId}}); return listBeneficiaries(userId); }

export async function listBanks():Promise<PayBankContract[]>{ if(!env.PAYSTACK_SECRET_KEY) throw new AppError("PROVIDER_UNAVAILABLE","Bank directory requires Paystack configuration",503); return (await listPaystackBanks()).map(b=>({name:b.name,code:b.code,slug:b.slug??null})); }
function bankAccountContract(r:any):PayBankAccountContract{return{id:r.id,provider:r.provider,bankCode:r.bankCode,bankName:r.bankName,accountName:r.accountName,accountNumberLast4:r.accountNumberLast4,status:r.status,createdAt:r.createdAt.toISOString()};}
export async function listBankAccounts(userId:string){return (await db.payBankAccount.findMany({where:{userId,status:"ACTIVE"},orderBy:{createdAt:"desc"}})).map(bankAccountContract);}
export async function addBankAccount(input:{userId:string;bankCode:string;bankName:string;accountNumber:string}){ if(!env.PAYSTACK_SECRET_KEY||!env.PAYSTACK_TRANSFERS_ENABLED) throw new AppError("PROVIDER_UNAVAILABLE","Bank withdrawals are not enabled on this Wallet server",503); if(!/^\d{10}$/.test(input.accountNumber)) throw new AppError("BAD_REQUEST","Enter a valid 10-digit Nigerian account number",400); const resolved=await resolvePaystackBankAccount(input.accountNumber,input.bankCode); const recipient=await createPaystackTransferRecipient({name:resolved.account_name,accountNumber:input.accountNumber,bankCode:input.bankCode,currency:"NGN"}); const row=await db.payBankAccount.create({data:{userId:input.userId,bankCode:input.bankCode,bankName:input.bankName,accountName:resolved.account_name,accountNumberLast4:input.accountNumber.slice(-4),providerRecipientCode:recipient.recipient_code}}); return bankAccountContract(row);}

async function payoutClearing(tx:Prisma.TransactionClient,currency:string){const code=`paystack:funding-clearing:${currency}`;return await tx.ledgerAccount.findUnique({where:{code}})??await tx.ledgerAccount.create({data:{code,currency,kind:"PAYMENT_CLEARING_ASSET"}});}
function withdrawalContract(r:any):PayWithdrawalContract{return{id:r.id,bankAccountId:r.bankAccountId,provider:r.provider,providerReference:r.providerReference,amountMinor:minor(r.amountMinor),currency:r.currency,status:r.status,failureMessage:r.failureMessage,createdAt:r.createdAt.toISOString(),completedAt:r.completedAt?.toISOString()??null,failedAt:r.failedAt?.toISOString()??null};}
async function reverseWithdrawal(id:string,message:string){return db.$transaction(async tx=>{const row=await tx.payWithdrawal.findUnique({where:{id}}); if(!row) throw new AppError("NOT_FOUND","Withdrawal not found",404); if(["FAILED","REVERSED"].includes(row.status)) return row; const walletAccount=await tx.ledgerAccount.findFirst({where:{walletId:row.walletId,currency:row.currency,kind:"WALLET_LIABILITY"}}); if(!walletAccount) throw new AppError("CONFLICT","Wallet account missing",409); const clearing=await payoutClearing(tx,row.currency); await postJournal(tx,{reference:`pay-withdrawal-reversal:${row.id}`,kind:"WALLET_WITHDRAWAL_REVERSAL",currency:row.currency,description:`Reversal for withdrawal ${row.id}`,lines:[{accountId:clearing.id,direction:"DEBIT",amountMinor:row.amountMinor},{accountId:walletAccount.id,direction:"CREDIT",amountMinor:row.amountMinor}]}); return tx.payWithdrawal.update({where:{id:row.id},data:{status:"FAILED",failureMessage:message.slice(0,500),failedAt:new Date()}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function createWithdrawal(input:{userId:string;bankAccountId:string;amountMinor:number;currency:string;pin:string;idempotencyKey:string}){ if(!env.PAYSTACK_SECRET_KEY||!env.PAYSTACK_TRANSFERS_ENABLED) throw new AppError("PROVIDER_UNAVAILABLE","Bank withdrawals are not enabled",503); const profile=await verifyPayPin(input.userId,input.pin); const spent=await outgoingToday(input.userId); if(spent+BigInt(input.amountMinor)>profile.dailyTransferLimitMinor) throw new AppError("CONFLICT","This withdrawal would exceed your daily Pay limit",409); const existing=await db.payWithdrawal.findUnique({where:{userId_idempotencyKey:{userId:input.userId,idempotencyKey:input.idempotencyKey}}}); if(existing) return withdrawalContract(existing); const bank=await db.payBankAccount.findFirst({where:{id:input.bankAccountId,userId:input.userId,status:"ACTIVE"}}); if(!bank) throw new AppError("NOT_FOUND","Bank account not found",404); const {wallet}=await ensureUserWallet(input.userId,input.currency); const pending=await db.$transaction(async tx=>{const walletAccount=await tx.ledgerAccount.findFirst({where:{walletId:wallet.id,currency:input.currency,kind:"WALLET_LIABILITY"}}); if(!walletAccount) throw new AppError("CONFLICT","Wallet account missing",409); const available=await balanceMinor(walletAccount.id,tx); const amount=BigInt(input.amountMinor); if(available<amount) throw new AppError("CONFLICT","Insufficient wallet balance",409); const row=await tx.payWithdrawal.create({data:{userId:input.userId,walletId:wallet.id,bankAccountId:bank.id,amountMinor:amount,currency:input.currency,status:"PROCESSING",idempotencyKey:input.idempotencyKey}}); const clearing=await payoutClearing(tx,input.currency); const journal=await postJournal(tx,{reference:`pay-withdrawal:${row.id}`,kind:"WALLET_WITHDRAWAL",currency:input.currency,description:`Withdrawal to ${bank.bankName} ••••${bank.accountNumberLast4}`,lines:[{accountId:walletAccount.id,direction:"DEBIT",amountMinor:amount},{accountId:clearing.id,direction:"CREDIT",amountMinor:amount}]}); return tx.payWithdrawal.update({where:{id:row.id},data:{ledgerTransactionId:journal.id}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable}); try{const provider=await initiatePaystackTransfer({amountMinor:input.amountMinor,recipientCode:bank.providerRecipientCode,reference:`BZW_${pending.id}`,reason:`Wallet withdrawal`,currency:input.currency}); const updated=await db.payWithdrawal.update({where:{id:pending.id},data:{providerReference:provider.reference,status:provider.status.toLowerCase()==="success"?"COMPLETED":"PENDING",completedAt:provider.status.toLowerCase()==="success"?new Date():null}}); return withdrawalContract(updated);}catch(cause){const reversed=await reverseWithdrawal(pending.id,cause instanceof Error?cause.message:"Withdrawal provider request failed"); return withdrawalContract(reversed);}}
export async function listWithdrawals(userId:string){return (await db.payWithdrawal.findMany({where:{userId},orderBy:{createdAt:"desc"},take:50})).map(withdrawalContract);}
export async function reconcileWithdrawal(userId:string,id:string){const row=await db.payWithdrawal.findFirst({where:{id,userId}});if(!row)throw new AppError("NOT_FOUND","Withdrawal not found",404);if(row.status==="COMPLETED"||row.status==="FAILED")return withdrawalContract(row);if(!row.providerReference)throw new AppError("CONFLICT","Withdrawal provider reference is missing",409);const result=await verifyPaystackTransfer(row.providerReference);const status=result.status.toLowerCase();if(["success","successful"].includes(status)){return withdrawalContract(await db.payWithdrawal.update({where:{id:row.id},data:{status:"COMPLETED",completedAt:new Date(),failureMessage:null}}));}if(["failed","reversed"].includes(status))return withdrawalContract(await reverseWithdrawal(row.id,`Provider reported ${status}`));return withdrawalContract(row);}
export async function processPaystackWithdrawalWebhook(body:{event?:string;data?:{reference?:string;transfer_code?:string;status?:string}}){const event=body.event??"";if(!event.startsWith("transfer."))return{handled:false as const};const ref=body.data?.reference;if(!ref)return{handled:true as const,ignored:true};const row=await db.payWithdrawal.findUnique({where:{providerReference:ref}});if(!row)return{handled:false as const};if(event==="transfer.success"){const done=await db.payWithdrawal.update({where:{id:row.id},data:{status:"COMPLETED",completedAt:new Date(),failureMessage:null}});return{handled:true as const,completed:true,withdrawal:withdrawalContract(done)};}if(event==="transfer.failed"||event==="transfer.reversed"){const failed=await reverseWithdrawal(row.id,event);return{handled:true as const,failed:true,withdrawal:withdrawalContract(failed)};}return{handled:true as const,ignored:true};}


function savingsContract(r:any):PayFixedSavingsContract{return{id:r.id,name:r.name,principalMinor:minor(r.principalMinor),currency:r.currency,status:r.status,lockUntil:r.lockUntil.toISOString(),annualRateBps:r.annualRateBps??null,provider:r.provider??null,pledgedLoanApplicationId:r.pledgedLoanApplicationId??null,createdAt:r.createdAt.toISOString(),releasedAt:r.releasedAt?.toISOString()??null};}
function loanContract(r:any):PayLoanApplicationContract{return{id:r.id,requestedMinor:minor(r.requestedMinor),currency:r.currency,termDays:r.termDays,purpose:r.purpose??null,status:r.status,pledgedSavingsId:r.pledgedSavingsId??null,lenderName:r.lenderName??null,offeredPrincipalMinor:r.offeredPrincipalMinor==null?null:minor(r.offeredPrincipalMinor),interestBps:r.interestBps??null,feeMinor:r.feeMinor==null?null:minor(r.feeMinor),totalRepaymentMinor:r.totalRepaymentMinor==null?null:minor(r.totalRepaymentMinor),repaymentFrequency:r.repaymentFrequency??null,createdAt:r.createdAt.toISOString(),offeredAt:r.offeredAt?.toISOString()??null,acceptedAt:r.acceptedAt?.toISOString()??null,cancelledAt:r.cancelledAt?.toISOString()??null};}
async function testClearingAccount(tx:Prisma.TransactionClient,currency:string){const code=`bazaara:pay:test-clearing:${currency}`;return await tx.ledgerAccount.findUnique({where:{code}})??await tx.ledgerAccount.create({data:{code,currency,kind:"TEST_FUNDING_CLEARING"}});}
export async function seedTestWalletOnce(userId:string,currency=env.CURRENCY){if(env.NODE_ENV==="production"||!env.PAY_TEST_MODE)return null;const reference=`pay-test-seed:v11:${userId}:${currency}`;if(await db.ledgerTransaction.findUnique({where:{reference}}))return walletContract(userId);return db.$transaction(async tx=>{let wallet=await tx.wallet.findUnique({where:{ownerKey_currency:{ownerKey:`user:${userId}`,currency}}});if(!wallet)wallet=await tx.wallet.create({data:{userId,ownerKey:`user:${userId}`,currency}});let account=await tx.ledgerAccount.findFirst({where:{walletId:wallet.id,currency,kind:"WALLET_LIABILITY"}});if(!account)account=await tx.ledgerAccount.create({data:{walletId:wallet.id,code:`wallet:${wallet.id}:${currency}`,currency,kind:"WALLET_LIABILITY"}});const current=await balanceMinor(account.id,tx),target=BigInt(env.PAY_TEST_BALANCE_MINOR);if(current<target){const clearing=await testClearingAccount(tx,currency);await postJournal(tx,{reference,kind:"PAY_TEST_CREDIT",currency,description:"Local test wallet grant for Bazaara ecosystem checkout testing",lines:[{accountId:clearing.id,direction:"DEBIT",amountMinor:target-current},{accountId:account.id,direction:"CREDIT",amountMinor:target-current}]});}return{id:wallet.id,ownerKey:wallet.ownerKey,currency:wallet.currency,status:wallet.status,availableMinor:minor(await balanceMinor(account.id,tx))};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function resetTestWallet(userId:string,currency=env.CURRENCY){if(env.NODE_ENV==="production"||!env.PAY_TEST_MODE)throw new AppError("FORBIDDEN","Test wallet controls are disabled",403);return db.$transaction(async tx=>{let wallet=await tx.wallet.findUnique({where:{ownerKey_currency:{ownerKey:`user:${userId}`,currency}}});if(!wallet)wallet=await tx.wallet.create({data:{userId,ownerKey:`user:${userId}`,currency}});let account=await tx.ledgerAccount.findFirst({where:{walletId:wallet.id,currency,kind:"WALLET_LIABILITY"}});if(!account)account=await tx.ledgerAccount.create({data:{walletId:wallet.id,code:`wallet:${wallet.id}:${currency}`,currency,kind:"WALLET_LIABILITY"}});const current=await balanceMinor(account.id,tx),target=BigInt(env.PAY_TEST_BALANCE_MINOR),delta=target-current;if(delta!==0n){const clearing=await testClearingAccount(tx,currency);await postJournal(tx,{reference:`pay-test-reset:${userId}:${Date.now()}:${randomBytes(3).toString("hex")}`,kind:"PAY_TEST_RESET",currency,description:"Local test wallet reset",lines:delta>0n?[{accountId:clearing.id,direction:"DEBIT",amountMinor:delta},{accountId:account.id,direction:"CREDIT",amountMinor:delta}]:[{accountId:account.id,direction:"DEBIT",amountMinor:-delta},{accountId:clearing.id,direction:"CREDIT",amountMinor:-delta}]});}return{id:wallet.id,ownerKey:wallet.ownerKey,currency:wallet.currency,status:wallet.status,availableMinor:minor(await balanceMinor(account.id,tx))};},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function listFixedSavings(userId:string){const rows=await db.payFixedSavings.findMany({where:{userId},orderBy:{createdAt:"desc"}}),now=new Date(),out:PayFixedSavingsContract[]=[];for(const row of rows){let current=row;if(row.status==="ACTIVE"&&row.lockUntil<=now)current=await db.payFixedSavings.update({where:{id:row.id},data:{status:"MATURED"}});out.push(savingsContract(current));}return out;}
export async function createFixedSavings(input:{userId:string;name:string;amountMinor:number;currency:string;durationDays:number;pin:string}){await verifyPayPin(input.userId,input.pin);if(input.amountMinor<env.PAY_FIXED_SAVINGS_MIN_MINOR)throw new AppError("BAD_REQUEST","Fixed savings amount is below the configured minimum",400);const {wallet}=await ensureUserWallet(input.userId,input.currency);return db.$transaction(async tx=>{const walletAccount=await tx.ledgerAccount.findFirst({where:{walletId:wallet.id,currency:input.currency,kind:"WALLET_LIABILITY"}});if(!walletAccount)throw new AppError("CONFLICT","Wallet ledger account is missing",409);const amount=BigInt(input.amountMinor);if(await balanceMinor(walletAccount.id,tx)<amount)throw new AppError("CONFLICT","Insufficient spendable wallet balance",409);const row=await tx.payFixedSavings.create({data:{userId:input.userId,walletId:wallet.id,name:input.name.trim().slice(0,80)||"Fixed savings",principalMinor:amount,currency:input.currency,status:"ACTIVE",lockUntil:new Date(Date.now()+input.durationDays*86400000)}});const savingsAccount=await tx.ledgerAccount.create({data:{code:`pay:savings:${row.id}:${input.currency}`,currency:input.currency,kind:"FIXED_SAVINGS_LIABILITY"}});const journal=await postJournal(tx,{reference:`pay-savings-fund:${row.id}`,kind:"FIXED_SAVINGS_FUND",currency:input.currency,description:`Fixed savings · ${row.name}`,lines:[{accountId:walletAccount.id,direction:"DEBIT",amountMinor:amount},{accountId:savingsAccount.id,direction:"CREDIT",amountMinor:amount}]});return savingsContract(await tx.payFixedSavings.update({where:{id:row.id},data:{ledgerAccountId:savingsAccount.id,fundingLedgerTransactionId:journal.id}}));},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function releaseFixedSavings(input:{userId:string;savingsId:string;pin:string}){await verifyPayPin(input.userId,input.pin);return db.$transaction(async tx=>{const row=await tx.payFixedSavings.findFirst({where:{id:input.savingsId,userId:input.userId}});if(!row)throw new AppError("NOT_FOUND","Fixed savings plan not found",404);if(row.status==="PLEDGED")throw new AppError("CONFLICT","This savings plan is pledged to a loan application",409);if(row.status==="RELEASED")return savingsContract(row);if(row.lockUntil>new Date())throw new AppError("CONFLICT","This savings plan has not reached maturity",409);if(!row.ledgerAccountId)throw new AppError("CONFLICT","Savings ledger account is missing",409);const walletAccount=await tx.ledgerAccount.findFirst({where:{walletId:row.walletId,currency:row.currency,kind:"WALLET_LIABILITY"}});if(!walletAccount)throw new AppError("CONFLICT","Wallet ledger account is missing",409);const amount=await balanceMinor(row.ledgerAccountId,tx);const journal=await postJournal(tx,{reference:`pay-savings-release:${row.id}`,kind:"FIXED_SAVINGS_RELEASE",currency:row.currency,description:`Fixed savings matured · ${row.name}`,lines:[{accountId:row.ledgerAccountId,direction:"DEBIT",amountMinor:amount},{accountId:walletAccount.id,direction:"CREDIT",amountMinor:amount}]});return savingsContract(await tx.payFixedSavings.update({where:{id:row.id},data:{status:"RELEASED",releaseLedgerTransactionId:journal.id,releasedAt:new Date()}}));},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function listLoanApplications(userId:string){return (await db.payLoanApplication.findMany({where:{userId},orderBy:{createdAt:"desc"},take:50})).map(loanContract);}
export async function createLoanApplication(input:{userId:string;requestedMinor:number;currency:string;termDays:number;purpose?:string;pledgedSavingsId?:string}){return db.$transaction(async tx=>{let pledgedSavingsId:string|null=null;if(input.pledgedSavingsId){const s=await tx.payFixedSavings.findFirst({where:{id:input.pledgedSavingsId,userId:input.userId}});if(!s)throw new AppError("NOT_FOUND","Fixed savings plan not found",404);if(!["ACTIVE","MATURED"].includes(s.status))throw new AppError("CONFLICT","That savings plan cannot be pledged",409);pledgedSavingsId=s.id;}const row=await tx.payLoanApplication.create({data:{userId:input.userId,requestedMinor:BigInt(input.requestedMinor),currency:input.currency,termDays:input.termDays,purpose:input.purpose?.trim().slice(0,180)||null,status:"PENDING_PARTNER",pledgedSavingsId}});if(pledgedSavingsId)await tx.payFixedSavings.update({where:{id:pledgedSavingsId},data:{status:"PLEDGED",pledgedLoanApplicationId:row.id}});return loanContract(row);},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function cancelLoanApplication(userId:string,id:string){return db.$transaction(async tx=>{const row=await tx.payLoanApplication.findFirst({where:{id,userId}});if(!row)throw new AppError("NOT_FOUND","Loan application not found",404);if(!["PENDING_PARTNER","OFFERED"].includes(row.status))throw new AppError("CONFLICT","This loan application can no longer be cancelled",409);if(row.pledgedSavingsId){const s=await tx.payFixedSavings.findFirst({where:{id:row.pledgedSavingsId,userId}});if(s?.pledgedLoanApplicationId===row.id)await tx.payFixedSavings.update({where:{id:s.id},data:{status:s.lockUntil<=new Date()?"MATURED":"ACTIVE",pledgedLoanApplicationId:null}});}return loanContract(await tx.payLoanApplication.update({where:{id:row.id},data:{status:"CANCELLED",cancelledAt:new Date()}}));},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}

export async function payOverview(userId:string){if(env.PAY_TEST_MODE&&env.NODE_ENV!=="production")await seedTestWalletOnce(userId);const [wallet,profile,activity,beneficiaries,requests,banks,withdrawals,savings,loans]=await Promise.all([walletContract(userId),payProfileContract(userId),listActivity(userId),listBeneficiaries(userId),listMoneyRequests(userId),listBankAccounts(userId),listWithdrawals(userId),listFixedSavings(userId),listLoanApplications(userId)]);return{wallet,profile,activity:activity.slice(0,12),beneficiaries:beneficiaries.slice(0,8),requests:requests.slice(0,12),bankAccounts:banks,withdrawals:withdrawals.slice(0,10),savings:savings.slice(0,20),loans:loans.slice(0,20)};}
