export type Title={slug:string;name:string;eyebrow:string;year:number;duration:string;kind:"Film"|"Series"|"Documentary";maturity:string;genres:string[];summary:string;accent:string;artwork:string;episodeCount?:number};
// FICTIONAL EDITORIAL TEST ITEMS ONLY. Not a licensed streaming catalog.
export const titles:Title[]=[
 {slug:"violet-harbor",name:"Violet Harbor",eyebrow:"AN ORIGINAL DEMO WORLD",year:2026,duration:"Concept / 94 min",kind:"Film",maturity:"Unrated demo",genres:["Drama","Mystery"],summary:"As the lights change across a coastal city, a sound archivist begins to discover messages hidden in a vanished station's recordings.",accent:"#bb79ff",artwork:"/art/violet-harbor.svg"},
 {slug:"atlas-beyond",name:"Atlas Beyond",eyebrow:"THE CONSTELLATION COLLECTION",year:2026,duration:"Concept / 6 episodes",kind:"Series",maturity:"Unrated demo",genres:["Science fiction","Adventure"],summary:"A navigator follows a luminous star map that points not to locations, but to forgotten decisions.",accent:"#50d5ff",artwork:"/art/atlas-beyond.svg",episodeCount:6},
 {slug:"earth-after-rain",name:"Earth After Rain",eyebrow:"THE DOCUMENTARY STUDIO",year:2026,duration:"Concept / 51 min",kind:"Documentary",maturity:"Unrated demo",genres:["Nature","Documentary"],summary:"An imagined journey through changing landscapes and the people who care for them.",accent:"#54dfbc",artwork:"/art/earth-after-rain.svg"},
 {slug:"midnight-frequency",name:"Midnight Frequency",eyebrow:"DISCOVER A NEW SIGNAL",year:2026,duration:"Concept / 106 min",kind:"Film",maturity:"Unrated demo",genres:["Thriller","Music"],summary:"A nighttime radio host is drawn into the mysteries of an unknown frequency that carries stories from across the city.",accent:"#e86dbc",artwork:"/art/midnight-frequency.svg"},
 {slug:"the-long-wave",name:"The Long Wave",eyebrow:"CINEMATIC CONSTELLATION",year:2026,duration:"Concept / 4 episodes",kind:"Series",maturity:"Unrated demo",genres:["Adventure","Drama"],summary:"A family of sailors chart their lives against an ever-changing ocean horizon.",accent:"#ffbe82",artwork:"/art/the-long-wave.svg",episodeCount:4},
 {slug:"glass-garden",name:"Glass Garden",eyebrow:"STORIES TO FOLLOW",year:2026,duration:"Concept / 88 min",kind:"Film",maturity:"Unrated demo",genres:["Art","Drama"],summary:"A designer attempts to restore a botanical glasshouse, revealing a story of resilience in its architecture.",accent:"#89a6ff",artwork:"/art/glass-garden.svg"}
];
export const titleBySlug=(slug:string)=>titles.find(t=>t.slug===slug);
