"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { api, errorText } from "@bazaara/social-ui";
import { Access, Frame, State, useReady } from "./Frame";
type Track={id:string;title:string;artistLabel:string;playCount:number;favorited:boolean;media:{url:string};creator:{displayName:string|null}};
type Playlist={id:string;title:string;items:Array<{trackId:string;track:Track}>};
export default function BTuneNext(){
 const session=useReady(),player=useRef<HTMLAudioElement>(null),counted=useRef(new Set<string>());const [mode,setMode]=useState<"home"|"search"|"library">("home");const [tracks,setTracks]=useState<Track[]>([]),[lists,setLists]=useState<Playlist[]>([]),[active,setActive]=useState<string|null>(null),[query,setQuery]=useState(""),[error,setError]=useState(""),[playing,setPlaying]=useState(false);
 const load=useCallback(async()=>{try{const [a,b]=await Promise.all([api.get<{tracks:Track[]}>("/v1/baztune/tracks",{maxRetries:0}),api.get<{playlists:Playlist[]}>("/v1/baztune/playlists",{maxRetries:0})]);setTracks(a.tracks);setLists(b.playlists)}catch(e){setError(errorText(e))}},[]);
 useEffect(()=>{if(session.user?.profile)void load()},[session.user?.profile,load]);
 const current=tracks.find(t=>t.id===active)??null;
 const filtered=useMemo(()=>tracks.filter(t=>(mode!=="library"||t.favorited)&&(!query||`${t.title} ${t.artistLabel}`.toLowerCase().includes(query.toLowerCase()))),[tracks,mode,query]);
 function select(t:Track){setActive(t.id);setPlaying(false)}
 async function markPlay(t:Track){if(counted.current.has(t.id))return;counted.current.add(t.id);try{await api.post(`/v1/baztune/tracks/${encodeURIComponent(t.id)}/play`,{});setTracks(rows=>rows.map(x=>x.id===t.id?{...x,playCount:x.playCount+1}:x))}catch{counted.current.delete(t.id)}}
 useEffect(()=>{if(!active||!player.current)return;const el=player.current;el.load();void el.play().then(()=>setPlaying(true)).catch(()=>setPlaying(false))},[active]);
 async function favorite(t:Track){try{if(t.favorited)await api.delete(`/v1/baztune/tracks/${encodeURIComponent(t.id)}/favorite`);else await api.put(`/v1/baztune/tracks/${encodeURIComponent(t.id)}/favorite`,{});setTracks(xs=>xs.map(x=>x.id===t.id?{...x,favorited:!x.favorited}:x))}catch(e){setError(errorText(e))}}
 return <Frame app="BTune" initial="AUDIO" mark="T" accent="#39cfb2" nav={[{id:"home",label:"Home",active:mode==="home",onClick:()=>setMode("home")},{id:"search",label:"Search",active:mode==="search",onClick:()=>setMode("search")},{id:"library",label:"Library",active:mode==="library",onClick:()=>setMode("library")},{id:"creator",label:"Creator",onClick:()=>window.location.assign("/")}]}><Access session={session} app="BTune"/>{session.user?.profile&&<div className="nx-tuneWrap"><div className="nx-eyebrow">AURA / YOUR SOUND</div><h1>{mode==="library"?"Your saved sound.":mode==="search"?"Find your frequency.":"Stay with the music."}</h1><p className="nx-muted">Independent listening, a clear library, and a player that stays with you.</p>{error&&<div className="nx-alert" role="alert">{error}</div>}
 <section className="nx-tuneAura nx-card"><span className="nx-tuneArt" aria-hidden="true">♫</span><div className="nx-tuneIntro"><span className="nx-eyebrow">NOW PLAYING</span><h2>{current?.title??"Your listening journey"}</h2><p>{current?.artistLabel??"Choose a track from your library"}</p><span className="nx-tag">Artist-led ambience · no autoplay until selected</span></div></section>
 {mode==="search"&&<div className="nx-section"><label htmlFor="nx-track-search">Search your current catalog</label><input id="nx-track-search" className="nx-input" placeholder="Track or artist" value={query} onChange={e=>setQuery(e.target.value)}/></div>}
 <div className="nx-section nx-row"><h2>{mode==="library"?"Saved tracks":mode==="home"?"Continue listening":"Results"}</h2><button className="nx-secondary" onClick={()=>void load()}>Refresh library</button></div><div className="nx-tuneGrid"><section className="nx-card nx-tuneTracks"><div className="nx-list">{filtered.length?filtered.map((t,i)=><div key={t.id} className={`nx-item ${t.id===active?"nx-on":""}`}><span className="nx-tuneNumber">{i+1}</span><button className="nx-tunePlay" onClick={()=>void select(t)} aria-label={`Play ${t.title}`}><span className="nx-thumb">♪</span></button><div className="nx-tuneMeta"><strong>{t.title}</strong><small>{t.artistLabel} · {t.playCount} plays</small></div><button className="nx-secondary" onClick={()=>void favorite(t)} aria-pressed={t.favorited} aria-label={`${t.favorited?"Remove":"Add"} favorite: ${t.title}`}>{t.favorited?"♥":"♡"}</button></div>):<State>{mode==="library"?"You haven't saved any tracks yet.":"No tracks available yet. Publish one through the current Creator screen."}</State>}</div></section>
 <aside className="nx-card"><h2>Collections</h2><p className="nx-muted">Your playlists have a home of their own.</p>{lists.length?lists.map(p=><div className="nx-tuneList" key={p.id}><span className="nx-thumb">≋</span><div><strong>{p.title}</strong><small>{p.items.length} tracks</small></div></div>):<State>No playlists yet. Build one from the current library.</State>}<a className="nx-secondary nx-tuneCreator" href="/">Manage playlists ↗</a></aside></div>
 {current&&<div className="nx-tuneDock" role="region" aria-label="Persistent audio player"><div><strong>{current.title}</strong><small>{current.artistLabel}</small></div><audio key={current.id} ref={player} controls src={current.media.url} onPlay={()=>{setPlaying(true);if(current)void markPlay(current)}} onPause={()=>setPlaying(false)} aria-label={`${current.title} audio player`}/><span className="nx-tag">{playing?"Playing":"Ready"}</span></div>}</div>}</Frame>
}
