"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { BusinessHeader } from "../components/BusinessHeader";
import { businessRequest, useBusinessOrganizations } from "../lib/business";

type Feedback = { id: string; category: string; rating: number | null; subject: string; message: string; status: string; priority: string; resolution: string | null; createdAt: string; updatedAt: string };
export default function FeedbackPage() {
  const business = useBusinessOrganizations(); const [feedback, setFeedback] = useState<Feedback[]>([]); const [form, setForm] = useState({ category: "GENERAL", rating: "5", subject: "", message: "" }); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { if (!business.organizationId) return; try { const r = await businessRequest<{ feedback: Feedback[] }>(`/v1/business/organizations/${business.organizationId}/management/feedback`); setFeedback(r.feedback); setError(""); } catch (e) { setError(e instanceof Error ? e.message : "Could not load feedback"); } }, [business.organizationId]); useEffect(() => { void load(); }, [load]);
  async function submit(e: FormEvent) { e.preventDefault(); if (!business.organizationId) return; setBusy(true); try { await businessRequest(`/v1/business/organizations/${business.organizationId}/management/feedback`, "POST", { category: form.category, rating: form.rating ? Number(form.rating) : undefined, subject: form.subject, message: form.message, sourcePath: window.location.pathname }); setForm({ category: "GENERAL", rating: "5", subject: "", message: "" }); setNotice("Feedback sent to Bazaara Operations."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not submit feedback"); } finally { setBusy(false); } }
  return <div className="business-control-shell"><BusinessHeader organization={business.organization} organizations={business.organizations} organizationId={business.organizationId} setOrganizationId={business.setOrganizationId} active="feedback" /><main className="business-control-main biz-mgmt-main"><section className="business-page-heading business-page-heading-v3"><div><span className="business-kicker">FEEDBACK</span><h1>Send product feedback directly to Operations.</h1><p>Report bugs, billing friction, UX issues or feature requests and track the response state.</p></div></section>{error ? <div className="business-alert">{error}</div> : null}{notice ? <div className="business-notice">{notice}</div> : null}<div className="biz-mgmt-grid two-one"><section className="business-panel"><div className="business-section-heading"><div><span className="business-kicker">HISTORY</span><h2>Your business feedback</h2></div></div><div className="biz-feedback-list">{feedback.map((item) => <article key={item.id}><header><div><span>{item.category}</span><strong>{item.subject}</strong></div><span className={`biz-status ${item.status.toLowerCase()}`}>{item.status}</span></header><p>{item.message}</p><footer><span>{item.rating ? `${"★".repeat(item.rating)}${"☆".repeat(5 - item.rating)}` : "No rating"}</span><small>{new Date(item.createdAt).toLocaleString("en-NG")}</small></footer>{item.resolution ? <div className="biz-resolution"><strong>Operations resolution</strong><span>{item.resolution}</span></div> : null}</article>)}{!feedback.length ? <div className="business-empty-state">No feedback submitted yet.</div> : null}</div></section><aside className="business-panel"><div className="business-section-heading"><div><span className="business-kicker">NEW FEEDBACK</span><h2>Tell us what needs work</h2></div></div><form className="biz-stack-form" onSubmit={submit}><label>Category<select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}><option>GENERAL</option><option>BUG</option><option>FEATURE</option><option>BILLING</option><option>SUPPORT</option><option>UX</option></select></label><label>Rating<select value={form.rating} onChange={(e) => setForm({ ...form, rating: e.target.value })}><option value="5">5 — Excellent</option><option value="4">4 — Good</option><option value="3">3 — Fair</option><option value="2">2 — Poor</option><option value="1">1 — Critical</option></select></label><label>Subject<input required minLength={3} maxLength={160} value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} /></label><label>Details<textarea required minLength={5} maxLength={5000} value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} /></label><button className="business-primary-button" disabled={busy}>{busy ? "Sending…" : "Send feedback"}</button></form></aside></div></main></div>;
}
