import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
import http from 'node:http';
import {URL} from 'node:url';
import {list,get,create,update,remove} from './store.mjs';
const port=Number(process.env.PORT||4037);
function json(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(JSON.stringify(data))}
async function body(req){let s='';for await(const c of req){s+=c;if(s.length>524288)throw Object.assign(new Error('payload too large'),{status:413})}try{return s?JSON.parse(s):{}}catch{throw Object.assign(new Error('invalid JSON'),{status:400})}}
function auth(req){const secret=process.env.PRODUCT_INTERNAL_SECRET||'';if(!secret||req.headers['x-bazaara-internal']!==secret)throw Object.assign(new Error('unauthorized'),{status:401});return String(req.headers['x-bazaara-user']||'local-dev')}
export function createServer(){return http.createServer(async(req,res)=>{try{const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(u.pathname==='/health/live')return json(res,200,{ok:true,service:'bazmeet-api'});if(u.pathname==='/health/ready')return json(res,200,{ok:true,service:'bazmeet-api',storage:'local-file',liveConferencing:false,sfuConfigured:false,turnConfigured:false,features:['meeting-codes','guest-lists','cohosts','waiting-room-policy','host-controls','captions-policy','screen-share-permission-test','recording-consent-policy','transcription-policy','attendance-policy','polls-policy','qna-policy','breakout-room-planning','join-policy','noise-suppression-policy']});const user=auth(req);if(req.method==='GET'&&u.pathname==='/api/v1/items')return json(res,200,{items:await list(user)});if(req.method==='POST'&&u.pathname==='/api/v1/items')return json(res,201,{item:await create(user,await body(req))});const m=u.pathname.match(/^\/api\/v1\/items\/([^/]+)$/);if(m){const id=decodeURIComponent(m[1]);if(req.method==='GET'){const item=await get(user,id);return item?json(res,200,{item}):json(res,404,{error:'not found'})}if(req.method==='PUT')return json(res,200,{item:await update(user,id,await body(req))});if(req.method==='DELETE')return json(res,(await remove(user,id))?200:404,{ok:true})}return json(res,404,{error:'not found'})}catch(e){return json(res,Number(e?.status)||400,{error:e instanceof Error?e.message:'request failed'})}})}
if(import.meta.url===pathToFileURL(resolve(process.argv[1])).href)createServer().listen(port,'127.0.0.1',()=>console.log('[BAZAARA] BazMeet API listening on http://127.0.0.1:'+port));
