import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
function root(){return path.resolve(process.env.DATA_DIR||'.data')}
function safeUser(v){return String(v||'local-dev').replace(/[^a-zA-Z0-9._-]/g,'_').slice(0,96)}
async function read(user){const dir=root();await fs.mkdir(dir,{recursive:true});const file=path.join(dir,safeUser(user)+'.json');try{const rows=JSON.parse(await fs.readFile(file,'utf8'));return Array.isArray(rows)?rows:[]}catch(e){if(e?.code==='ENOENT')return [];throw e}}
async function write(user,items){const dir=root();await fs.mkdir(dir,{recursive:true});const file=path.join(dir,safeUser(user)+'.json');const tmp=file+'.tmp';await fs.writeFile(tmp,JSON.stringify(items,null,2),{encoding:'utf8',mode:0o600});await fs.rename(tmp,file)}
function text(v,max){return typeof v==='string'?v.replace(/\u0000/g,'').slice(0,max):''}
function strings(v,max=100){return Array.isArray(v)?v.filter(x=>typeof x==='string').map(x=>x.trim().slice(0,320)).filter(Boolean).slice(0,max):[]}
function code(v){const raw=text(v,20).toUpperCase().replace(/[^A-Z0-9-]/g,'');if(raw)return raw;const a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let out='';for(let i=0;i<10;i++)out+=a[Math.floor(Math.random()*a.length)];return `${out.slice(0,3)}-${out.slice(3,7)}-${out.slice(7)}`}
function meta(input={},prior={}){const x={...prior,...(input&&typeof input==='object'?input:{})};return{start:text(x.start,64),end:text(x.end,64),guests:strings(x.guests),cohosts:strings(x.cohosts),meetingCode:code(x.meetingCode),waitingRoom:x.waitingRoom!==false,chatEnabled:x.chatEnabled!==false,captionsEnabled:Boolean(x.captionsEnabled),recordingConsent:x.recordingConsent!==false,hostApproval:x.hostApproval!==false,layout:['auto','tiled','spotlight','sidebar'].includes(String(x.layout))?x.layout:'auto',roomStatus:['SCHEDULED','LIVE','ENDED'].includes(String(x.roomStatus))?x.roomStatus:'SCHEDULED',notes:text(x.notes,20000),timezone:text(x.timezone,80),allowScreenShare:x.allowScreenShare!==false,allowReactions:x.allowReactions!==false,allowPolls:x.allowPolls!==false,allowQna:x.allowQna!==false,breakoutCount:Math.min(50,Math.max(0,Number(x.breakoutCount)||0)),transcriptionEnabled:Boolean(x.transcriptionEnabled),attendanceTracking:Boolean(x.attendanceTracking),joinPolicy:['invited','anyone-with-link','organization'].includes(String(x.joinPolicy))?x.joinPolicy:'invited',noiseSuppression:x.noiseSuppression!==false}}
export async function list(user){return (await read(user)).sort((a,b)=>String(b.updatedAt||b.createdAt||'').localeCompare(String(a.updatedAt||a.createdAt||'')))}
export async function get(user,id){return (await read(user)).find(x=>x.id===id)||null}
export async function create(user,input){const items=await read(user);const now=new Date().toISOString();const title=text(input?.title,200).trim();if(!title)throw Object.assign(new Error('title is required'),{status:400});const item={id:crypto.randomUUID(),title,body:text(input?.body,20000),meta:meta(input?.meta),createdAt:now,updatedAt:now};items.push(item);await write(user,items);return item}
export async function update(user,id,input){const items=await read(user);const i=items.findIndex(x=>x.id===id);if(i<0)throw Object.assign(new Error('not found'),{status:404});const prior=items[i];const title=text(input?.title??prior.title,200).trim();if(!title)throw Object.assign(new Error('title is required'),{status:400});const next={...prior,title,body:text(input?.body??prior.body,20000),meta:meta(input?.meta,prior.meta),updatedAt:new Date().toISOString()};items[i]=next;await write(user,items);return next}
export async function remove(user,id){const items=await read(user);const next=items.filter(x=>x.id!==id);if(next.length===items.length)return false;await write(user,next);return true}
