import { pathToFileURL } from 'node:url';
import { resolve } from 'node:path';
import http from 'node:http';
import {URL} from 'node:url';
import {list,get,create,update,remove,preferences,updatePreferences} from './store.mjs';
const port=Number(process.env.PORT||4036);
function json(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(JSON.stringify(data))}
async function body(req){let s='';for await(const c of req){s+=c;if(s.length>524288)throw Object.assign(new Error('payload too large'),{status:413})}try{return s?JSON.parse(s):{}}catch{throw Object.assign(new Error('invalid JSON'),{status:400})}}
function auth(req){const secret=process.env.PRODUCT_INTERNAL_SECRET||'';if(!secret||req.headers['x-bazaara-internal']!==secret)throw Object.assign(new Error('unauthorized'),{status:401});return String(req.headers['x-bazaara-user']||'local-dev')}
function transportConfig(){const raw=String(process.env.BMAIL_TRANSPORT_URL||'').trim();if(!raw)return null;let url;try{url=new URL(raw)}catch{return null}if(url.username||url.password)return null;const local=['localhost','127.0.0.1','::1'].includes(url.hostname);if(url.protocol!=='https:'&&!(local&&url.protocol==='http:'))return null;return{url:url.href,bearer:String(process.env.BMAIL_TRANSPORT_BEARER||'')}}
async function deliver(user,item){const cfg=transportConfig();if(!cfg)throw Object.assign(new Error('Bmail delivery transport is not configured.'),{status:503});const meta=item.meta||{};if(!Array.isArray(meta.to)||meta.to.length===0)throw Object.assign(new Error('Add at least one recipient before sending.'),{status:400});if(meta.confidential&&meta.expiresAt){const expiry=Date.parse(meta.expiresAt);if(Number.isFinite(expiry)&&expiry<=Date.now())throw Object.assign(new Error('This confidential message has already expired.'),{status:400})}const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);let response;try{response=await fetch(cfg.url,{method:'POST',headers:{'content-type':'application/json',...(cfg.bearer?{authorization:`Bearer ${cfg.bearer}`}:{})},body:JSON.stringify({messageId:item.id,threadId:meta.threadId||'',from:meta.from||'',to:meta.to,cc:meta.cc||[],bcc:meta.bcc||[],subject:item.title,body:item.body||'',attachments:meta.attachments||[],labels:meta.labels||[],priority:meta.priority||'normal',confidential:Boolean(meta.confidential),expiresAt:meta.expiresAt||'',allowForward:meta.allowForward!==false,userId:user}),signal:controller.signal})}catch(e){throw Object.assign(new Error(e?.name==='AbortError'?'Delivery transport timed out.':'Delivery transport could not be reached.'),{status:502})}finally{clearTimeout(timer)}if(!response.ok)throw Object.assign(new Error(`Delivery transport rejected the message (${response.status}).`),{status:502});return update(user,item.id,{title:item.title,body:item.body,meta:{...meta,folder:'SENT',sentAt:new Date().toISOString(),scheduledFor:'',snoozedUntil:'',read:true}})}
async function processDue(user){const cfg=transportConfig();const rows=await list(user);for(const item of rows.slice(0,300)){const m=item.meta||{};if(m.folder==='SNOOZED'&&m.snoozedUntil){const wake=Date.parse(m.snoozedUntil);if(Number.isFinite(wake)&&wake<=Date.now()){try{await update(user,item.id,{title:item.title,body:item.body,meta:{...m,folder:'INBOX',snoozedUntil:''}})}catch{}}}if(m.folder!=='SCHEDULED'||!m.scheduledFor||!cfg)continue;const due=Date.parse(m.scheduledFor);if(!Number.isFinite(due)||due>Date.now())continue;try{await deliver(user,item)}catch{/* Keep scheduled state for explicit retry. */}}}
export function createServer(){return http.createServer(async(req,res)=>{try{const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(u.pathname==='/health/live')return json(res,200,{ok:true,service:'bmail-api'});if(u.pathname==='/health/ready'){const cfg=transportConfig();return json(res,200,{ok:true,service:'bmail-api',storage:'local-file',deliveryConfigured:Boolean(cfg),deliveryTransport:cfg?'http-adapter':'disabled',features:['folders','categories','labels','star','read-state','importance','snooze','scheduled-send','undo-send-client','preferences','confidential-metadata','priority','search-operators','transport-adapter']})}const user=auth(req);if(req.method==='GET'&&u.pathname==='/api/v1/items'){await processDue(user);return json(res,200,{items:await list(user)})}if(req.method==='POST'&&u.pathname==='/api/v1/items')return json(res,201,{item:await create(user,await body(req))});if(req.method==='GET'&&u.pathname==='/api/v1/preferences')return json(res,200,{preferences:await preferences(user)});if(req.method==='PUT'&&u.pathname==='/api/v1/preferences')return json(res,200,{preferences:await updatePreferences(user,await body(req))});const send=u.pathname.match(/^\/api\/v1\/items\/([^/]+)\/send$/);if(req.method==='POST'&&send){const id=decodeURIComponent(send[1]);const item=await get(user,id);if(!item)return json(res,404,{error:'not found'});return json(res,200,{item:await deliver(user,item)})}const m=u.pathname.match(/^\/api\/v1\/items\/([^/]+)$/);if(m){const id=decodeURIComponent(m[1]);if(req.method==='GET'){const item=await get(user,id);return item?json(res,200,{item}):json(res,404,{error:'not found'})}if(req.method==='PUT')return json(res,200,{item:await update(user,id,await body(req))});if(req.method==='DELETE')return json(res,(await remove(user,id))?200:404,{ok:true})}return json(res,404,{error:'not found'})}catch(e){return json(res,Number(e?.status)||400,{error:e instanceof Error?e.message:'request failed'})}})}
if(import.meta.url===pathToFileURL(resolve(process.argv[1])).href)createServer().listen(port,'127.0.0.1',()=>console.log('[BAZAARA] Bmail API listening on http://127.0.0.1:'+port));
