export type MailAttachment={id:string;name:string;type:string;size:number};
export type Mail={id:string;kind:'message'|'draft';from:string;to:string;cc:string;bcc:string;subject:string;body:string;date:string;labels:string[];starred:boolean;read:boolean;archived:boolean;trashed:boolean;remind:string;attachments:MailAttachment[];updated:string};
export function validMail(v:unknown):v is Mail{const x=v as Mail;return !!x&&typeof x.id==='string'&&['from','to','cc','bcc','subject','body','date','remind','updated'].every(k=>typeof (x as unknown as Record<string,unknown>)[k]==='string')&&['message','draft'].includes(x.kind)&&['starred','read','archived','trashed'].every(k=>typeof (x as unknown as Record<string,unknown>)[k]==='boolean')&&Array.isArray(x.labels)&&x.labels.every(s=>typeof s==='string')&&Array.isArray(x.attachments)&&x.attachments.every(a=>a&&typeof a.id==='string'&&typeof a.name==='string'&&typeof a.type==='string'&&Number.isFinite(a.size)&&a.size>=0);}
export function freshMail():Mail{const at=new Date().toISOString();return {id:crypto.randomUUID(),kind:'draft',from:'',to:'',cc:'',bcc:'',subject:'',body:'',date:at,labels:[],starred:false,read:true,archived:false,trashed:false,remind:'',attachments:[],updated:at};}
function bytes64(s:string){const binary=atob(s.replace(/\s/g,''));return Uint8Array.from(binary,c=>c.charCodeAt(0));}
function base64(bytes:Uint8Array){let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);}
function decode(bytes:Uint8Array,charset='utf-8'){try{return new TextDecoder(charset).decode(bytes);}catch{throw Error('This message uses an unsupported character encoding: '+charset);}}
function quoted(s:string){const raw=s.replace(/=\r?\n/g,'');const out:number[]=[];for(let i=0;i<raw.length;i++){if(raw[i]==='='&&/^[0-9a-f]{2}$/i.test(raw.slice(i+1,i+3))){out.push(parseInt(raw.slice(i+1,i+3),16));i+=2;}else out.push(raw.charCodeAt(i)&255);}return Uint8Array.from(out);}
function headerDecode(s:string){return s.replace(/=\?([^?]+)\?([bq])\?([^?]*)\?=/gi,(_,charset,encoding,encoded)=>{try{return decode(encoding.toLowerCase()==='b'?bytes64(encoded):quoted(encoded.replace(/_/g,' ')),charset);}catch{return '[Unsupported encoded header]';}});}
function split(raw:string){const at=raw.search(/\r?\n\r?\n/);if(at<0)throw Error('The EML has no header/body separator.');const headers:Record<string,string>={};for(const line of raw.slice(0,at).replace(/\r?\n[ \t]+/g,' ').split(/\r?\n/)){const i=line.indexOf(':');if(i>0)headers[line.slice(0,i).toLowerCase()]=line.slice(i+1).trim();}return {headers,body:raw.slice(at).replace(/^\r?\n\r?\n/,'')};}
function param(header:string,name:string){return new RegExp('(?:^|;)\\s*'+name+'=(?:"([^"]*)"|([^;\\s]*))','i').exec(header)?.slice(1).find(Boolean)||'';}
export function parseEML(raw:string):{mail:Mail;files:{name:string;type:string;bytes:Uint8Array}[]}{
 if(raw.length>15000000)throw Error('EML imports are limited to 15 MB.');
 const root=split(raw),mail=freshMail(),files:{name:string;type:string;bytes:Uint8Array}[]=[];let visited=0;const texts:string[]=[];
 function walk(part:string,depth:number){if(depth>6||++visited>100)throw Error('This MIME message is too deeply nested.');const {headers:h,body}=split(part);const content=h['content-type']||'text/plain';const type=content.split(';')[0].trim().toLowerCase();
  if(type.startsWith('multipart/')){const boundary=param(content,'boundary');if(!boundary||boundary.length>200)throw Error('Invalid MIME boundary.');const lines=body.split(/\r?\n/);let current:string[]|null=null;for(const line of lines){if(line==='--'+boundary||line==='--'+boundary+'--'){if(current?.length)walk(current.join('\r\n'),depth+1);current=line.endsWith('--')?null:[];if(line==='--'+boundary+'--')break;}else current?.push(line);}return;}
  const encoding=(h['content-transfer-encoding']||'7bit').toLowerCase();const bytes=encoding==='base64'?bytes64(body):encoding==='quoted-printable'?quoted(body):Uint8Array.from(body,c=>c.charCodeAt(0)&255);
  const name=headerDecode(param(h['content-disposition']||'','filename')||param(content,'name'));
  if(name||/^attachment/i.test(h['content-disposition']||'')){if(files.length>=20||bytes.length>10000000)throw Error('Attachment import exceeds supported bounds.');files.push({name:name||'attachment',type,bytes});return;}
  if(type==='text/plain')texts.push(decode(bytes,param(content,'charset')||'utf-8'));
 }
 walk(raw,0);if(!texts.length)throw Error('Import requires a plain-text MIME part. HTML-only, encrypted and proprietary messages are not rendered.');
 mail.kind='message';for(const k of ['from','to','cc','bcc','subject'] as const)mail[k]=headerDecode(root.headers[k]||'');mail.body=texts.join('\n\n');if(mail.body.length>200000)throw Error('The message body exceeds the 200,000-character import limit.');const d=new Date(root.headers.date||'');mail.date=Number.isFinite(+d)?d.toISOString():mail.date;mail.read=false;return {mail,files};
}
function clean(s:string){if(/[\r\n]/.test(s))throw Error('Mail headers cannot contain line breaks.');return s;}
function encoded(s:string){return '=?UTF-8?B?'+base64(new TextEncoder().encode(clean(s)))+'?=';}
function wrapped(s:string){return s.match(/.{1,76}/g)?.join('\r\n')||'';}
export async function exportEML(mail:Mail,getBlob:(id:string)=>Promise<Blob>):Promise<string>{
 const boundary='Bazaara_'+crypto.randomUUID().replace(/-/g,'');const lines=['MIME-Version: 1.0','X-Unsent: '+(mail.kind==='draft'?'1':'0'),'Date: '+new Date(mail.date).toUTCString(),'From: '+clean(mail.from),'To: '+clean(mail.to),'Cc: '+clean(mail.cc),'Bcc: '+clean(mail.bcc),'Subject: '+encoded(mail.subject),'Content-Type: multipart/mixed; boundary="'+boundary+'"','','--'+boundary,'Content-Type: text/plain; charset=utf-8','Content-Transfer-Encoding: base64','',wrapped(base64(new TextEncoder().encode(mail.body)))];
 for(const a of mail.attachments){const blob=await getBlob(a.id);const name=a.name.replace(/["\r\n\\]/g,'_');const type=/^[a-z0-9!#$&^_.+-]+\/[a-z0-9!#$&^_.+-]+$/i.test(a.type)?a.type:'application/octet-stream';lines.push('--'+boundary,'Content-Type: '+type,'Content-Disposition: attachment; filename="'+name+'"','Content-Transfer-Encoding: base64','',wrapped(base64(new Uint8Array(await blob.arrayBuffer()))));}
 lines.push('--'+boundary+'--','');return lines.join('\r\n');
}
export function mailMatches(mail:Mail,query:string){const tokens=query.match(/(?:[^\s"]+|"[^"]*")+/g)||[];return tokens.every(raw=>{const negative=raw.startsWith('-');const t=(negative?raw.slice(1):raw).replace(/"/g,'');const i=t.indexOf(':');const key=i<0?'':t.slice(0,i).toLowerCase(),value=(i<0?t:t.slice(i+1)).toLowerCase();let yes=false;
 if(['from','to','subject','label'].includes(key))yes=(key==='label'?mail.labels.join(' '):mail[key as 'from'|'to'|'subject']).toLowerCase().includes(value);
 else if(key==='is')yes=value==='unread'?!mail.read:value==='read'?mail.read:value==='starred'?mail.starred:value==='draft'?mail.kind==='draft':false;
 else if(key==='has')yes=value==='attachment'&&mail.attachments.length>0;
 else if(key==='after'||key==='before'){const at=Date.parse(value);yes=Number.isFinite(at)&&(key==='after'?Date.parse(mail.date)>=at:Date.parse(mail.date)<at);}
 else yes=[mail.subject,mail.body,mail.from,mail.to,mail.labels.join(' ')].join(' ').toLowerCase().includes(t.toLowerCase());return negative?!yes:yes;});}
export function attachmentDB(){return new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('bazaara.mail.v2.attachments',1);r.onupgradeneeded=()=>r.result.createObjectStore('blobs');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(Error('Attachment storage is unavailable.'));});}
export async function attachmentStore(id:string,blob?:Blob):Promise<Blob>{const db=await attachmentDB();return new Promise((resolve,reject)=>{const tx=db.transaction('blobs',blob?'readwrite':'readonly'),store=tx.objectStore('blobs');const request=blob?store.put(blob,id):store.get(id);let result:unknown;request.onsuccess=()=>result=request.result;tx.oncomplete=()=>{db.close();if(blob)resolve(blob);else if(result instanceof Blob)resolve(result);else reject(Error('This attachment is missing from device storage.'));};tx.onerror=()=>{db.close();reject(Error('Could not store/read this attachment.'));};tx.onabort=()=>{db.close();reject(Error('Attachment transaction was aborted.'));};});}
export async function removeAttachment(id:string){const db=await attachmentDB();return new Promise<void>((resolve,reject)=>{const tx=db.transaction('blobs','readwrite');tx.objectStore('blobs').delete(id);tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>{db.close();reject(Error('Could not delete attachment.'));};});}
const checksum=async(bytes:Uint8Array)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes as BufferSource)),v=>v.toString(16).padStart(2,'0')).join('');
export async function mailBackup(messages:Mail[]){const ids=[...new Set(messages.flatMap(m=>m.attachments.map(a=>a.id)))],files:{id:string;data:string;type:string;sha256:string}[]=[];let total=0;for(const id of ids){const blob=await attachmentStore(id);total+=blob.size;if(total>25000000)throw Error('Export supports up to 25 MB of attachments at once. Export selected messages in smaller batches.');const bytes=new Uint8Array(await blob.arrayBuffer());files.push({id,data:base64(bytes),type:blob.type,sha256:await checksum(bytes)});}return {version:2,product:'Bazaara Bmail',messages,files};}
export async function restoreMailBackup(file:File):Promise<Mail[]>{
 if(file.size>40000000)throw Error('Mail backups must be under 40 MB.');const value=JSON.parse(await file.text());if(value?.version!==2||value.product!=='Bazaara Bmail'||!Array.isArray(value.messages)||value.messages.length>10000||!value.messages.every(validMail)||!Array.isArray(value.files)||value.files.length>1000)throw Error('Invalid Bmail backup.');
 const decoded: {id:string;blob:Blob}[]=[];let total=0;const ids=new Set<string>();for(const f of value.files){if(!f||typeof f.id!=='string'||typeof f.data!=='string'||typeof f.type!=='string'||typeof f.sha256!=='string'||ids.has(f.id))throw Error('Invalid backup attachment.');ids.add(f.id);const bytes=bytes64(f.data);total+=bytes.length;if(total>25000000||await checksum(bytes)!==f.sha256)throw Error('An attachment exceeds the restore limit or failed its checksum.');decoded.push({id:f.id,blob:new Blob([bytes as BlobPart],{type:f.type})});}
 for(const m of value.messages as Mail[])for(const a of m.attachments){const f=decoded.find(f=>f.id===a.id);if(!f||f.blob.size!==a.size)throw Error('Backup attachment metadata does not match.');}
 const mapped=new Map(decoded.map(f=>[f.id,crypto.randomUUID()]));for(const f of decoded)await attachmentStore(mapped.get(f.id)!,f.blob);
 return (value.messages as Mail[]).map(m=>({...m,id:crypto.randomUUID(),attachments:m.attachments.map(a=>({...a,id:mapped.get(a.id)!}))}));
}
