'use client';
import {useMemo,useState} from 'react';
import {Dialog,Empty,Field,ImportButton,Notice,Shell,ToolRow,download,now,readJson,uid,useCollection} from './core';
type Check={id:string;text:string;done:boolean};
type Note={id:string;title:string;text:string;labels:string[];color:string;pinned:boolean;archived:boolean;trashed:boolean;reminder:string;checks:Check[];updated:string};
const isNote=(v:unknown):v is Note=>{const x=v as Note;return !!x&&typeof x.id==='string'&&typeof x.title==='string'&&typeof x.text==='string'&&Array.isArray(x.labels)&&x.labels.every(s=>typeof s==='string')&&Array.isArray(x.checks)&&x.checks.every(c=>c&&typeof c.id==='string'&&typeof c.text==='string'&&typeof c.done==='boolean')&&typeof x.updated==='string'&&typeof x.reminder==='string'&&['violet','cyan','rose'].includes(x.color)&&['pinned','archived','trashed'].every(k=>typeof (x as unknown as Record<string,unknown>)[k]==='boolean');};
const fresh=():Note=>({id:uid(),title:'',text:'',labels:[],color:'violet',pinned:false,archived:false,trashed:false,reminder:'',checks:[],updated:now()});
export default function Notes(){
  const store=useCollection<Note>('notes',isNote);const [query,setQuery]=useState(''),[section,setSection]=useState('Notes'),[label,setLabel]=useState(''),[edit,setEdit]=useState<Note|null>(null),[notice,setNotice]=useState('');
  const labels=[...new Set(store.items.flatMap(n=>n.labels))].sort();
  const shown=useMemo(()=>store.items.filter(n=>section==='Trash'?n.trashed:section==='Archive'?n.archived&&!n.trashed:section==='Reminders'?!!n.reminder&&!n.trashed:!n.archived&&!n.trashed).filter(n=>(n.title+' '+n.text+' '+n.labels.join(' ')).toLowerCase().includes(query.toLowerCase())&&(!label||n.labels.includes(label))).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||b.updated.localeCompare(a.updated)),[store.items,section,query,label]);
  const put=(n:Note)=>store.put({...n,updated:now()});
  const save=()=>{if(!edit||(!edit.title.trim()&&!edit.text.trim()&&!edit.checks.length))return;if(put({...edit,title:edit.title.trim()||'Untitled note'})){setEdit(null);setNotice('Note saved on this device.');}};
  return <Shell name="Notes" description="Capture ideas, pin important notes, and keep checklists organized." error={store.error} notice={notice} actions={<><a className="bf-button" href="/connected">Connected records</a><button onClick={()=>setEdit(fresh())} disabled={!store.ready}>＋ New note</button><ImportButton label="Import Markdown" accept=".md,.markdown,.txt" onFile={async f=>{if(f.size>60000)throw Error('Notes imported from text must be under 60 KB.');const raw=(await f.text()).replace(/^\uFEFF/,'').replace(/\r/g,''),lines=raw.split('\n');const heading=/^#\s+(.+)$/.exec(lines[0]||'');if(heading)lines.shift();const checks:Check[]=[],body:string[]=[];for(const line of lines){const match=/^\s*[-*]\s+\[([ xX])\]\s+(.+)$/.exec(line);if(match)checks.push({id:uid(),done:match[1].toLowerCase()==='x',text:match[2]});else body.push(line);}const note={...fresh(),title:(heading?.[1]||f.name.replace(/\.[^.]+$/,'')).slice(0,180),text:body.join('\n').trim(),checks};if(store.put(note))setNotice('Markdown note imported on this device.');}}/><button onClick={()=>download('bazaara-notes.json',JSON.stringify({format:'bazaara.notes.v1',notes:store.items},null,2))}>Export backup</button><ImportButton onFile={async f=>{const d=await readJson(f,(v):v is {format:string;notes:Note[]}=>{const x=v as {format:string;notes:Note[]};return x?.format==='bazaara.notes.v1'&&Array.isArray(x.notes)&&x.notes.every(isNote);});if(store.mutate(rows=>[...d.notes,...rows.filter(r=>!d.notes.some(n=>n.id===r.id))]))setNotice('Backup imported.');}}/></>}>
    <div className="bf-split"><aside className="bf-side">{['Notes','Reminders','Archive','Trash'].map(s=><button key={s} aria-pressed={s===section} onClick={()=>setSection(s)}>{s}</button>)}<Field label="Label"><select value={label} onChange={e=>setLabel(e.target.value)}><option value="">All labels</option>{labels.map(s=><option key={s}>{s}</option>)}</select></Field></aside><div><ToolRow><input aria-label="Search notes" placeholder="Search titles, notes and labels" value={query} onChange={e=>setQuery(e.target.value)}/><span>{shown.length} notes</span></ToolRow><div className="bf-grid" style={{marginTop:16}}>{shown.map(n=><article className="bf-card" key={n.id} style={{borderTopColor:n.color==='cyan'?'#70cfff':n.color==='rose'?'#db95c9':'#b995ff',borderTopWidth:3}}><div className="bf-row"><h2>{n.title}</h2>{n.pinned&&<span className="bf-tag">Pinned</span>}</div><p className="bf-note-body">{n.text}</p>{!!n.checks.length&&<ul className="bf-checklist">{n.checks.map(c=><li key={c.id}><input type="checkbox" checked={c.done} aria-label={c.text} onChange={()=>put({...n,checks:n.checks.map(x=>x.id===c.id?{...x,done:!x.done}:x)})}/><span style={{textDecoration:c.done?'line-through':undefined}}>{c.text}</span></li>)}</ul>}<div className="bf-tags">{n.labels.map(l=><span className="bf-tag" key={l}>{l}</span>)}</div>{n.reminder&&<small>Reminder {new Date(n.reminder).toLocaleString()}{new Date(n.reminder)<new Date()?' · Due':''}</small>}<small>Edited {new Date(n.updated).toLocaleString()}</small><footer><button onClick={()=>setEdit(n)}>Edit</button>{!n.trashed?<><button aria-pressed={n.pinned} onClick={()=>put({...n,pinned:!n.pinned})}>{n.pinned?'Unpin':'Pin'}</button><button onClick={()=>put({...n,archived:!n.archived})}>{n.archived?'Unarchive':'Archive'}</button><button onClick={()=>put({...n,trashed:true})}>Trash</button></>:<><button onClick={()=>put({...n,trashed:false})}>Restore</button><button className="danger" onClick={()=>{if(confirm('Permanently delete this note?'))store.remove(n.id);}}>Delete permanently</button></>}<button onClick={()=>download(n.title+'.md',n.title+'\n\n'+n.text+'\n\n'+n.checks.map(c=>`- [${c.done?'x':' '}] ${c.text}`).join('\n'),'text/markdown')}>Download</button></footer></article>)}</div>{!shown.length&&<Empty title={store.ready?'No notes in this view':'Loading notes'}>Create a note or change your search and filters.</Empty>}</div></div>
    {edit&&<Dialog title="Edit note" close={()=>setEdit(null)}><form onSubmit={e=>{e.preventDefault();save();}}><Field label="Title"><input autoFocus value={edit.title} maxLength={180} onChange={e=>setEdit({...edit,title:e.target.value})}/></Field><Field label="Note"><textarea value={edit.text} maxLength={50000} onChange={e=>setEdit({...edit,text:e.target.value})}/></Field><Field label="Labels, separated by commas"><input key={edit.id} defaultValue={edit.labels.join(', ')} onBlur={e=>setEdit({...edit,labels:[...new Set(e.target.value.split(',').map(s=>s.trim()).filter(Boolean))].slice(0,15)})}/></Field><div className="bf-row"><Field label="Accent"><select value={edit.color} onChange={e=>setEdit({...edit,color:e.target.value})}><option value="violet">Violet</option><option value="cyan">Cyan</option><option value="rose">Rose</option></select></Field><Field label="Reminder on this device"><input type="datetime-local" value={edit.reminder} onChange={e=>setEdit({...edit,reminder:e.target.value})}/></Field></div><ul className="bf-checklist">{edit.checks.map(c=><li key={c.id}><input type="checkbox" aria-label="Completed" checked={c.done} onChange={()=>setEdit({...edit,checks:edit.checks.map(x=>x.id===c.id?{...x,done:!x.done}:x)})}/><input aria-label="Checklist item" value={c.text} onChange={e=>setEdit({...edit,checks:edit.checks.map(x=>x.id===c.id?{...x,text:e.target.value}:x)})}/><button type="button" aria-label="Remove checklist item" onClick={()=>setEdit({...edit,checks:edit.checks.filter(x=>x.id!==c.id)})}>✕</button></li>)}</ul><button type="button" onClick={()=>setEdit({...edit,checks:[...edit.checks,{id:uid(),text:'',done:false}]})}>Add checklist item</button><Notice error>{store.error}</Notice><div className="bf-actions"><button type="button" onClick={()=>setEdit(null)}>Cancel</button><button className="primary" type="submit">Save note</button></div></form></Dialog>}
  </Shell>;
}
