'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,Empty,Field,ImportButton,Notice,Shell,ToolRow,download,errorText,uid} from './core';
type Photo={id:string;name:string;type:string;size:number;created:string;hash:string;albums:string[];favorite:boolean;trashed:boolean;blob:Blob};
type BackupPhoto=Omit<Photo,'blob'> & {data:string};
function openDb(){return new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('bazaara.photos.device.v1',1);request.onupgradeneeded=()=>request.result.createObjectStore('photos',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(Error('Device photo storage is unavailable.'));});}
async function records(){const db=await openDb();try{return await new Promise<Photo[]>((resolve,reject)=>{const request=db.transaction('photos','readonly').objectStore('photos').getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(Error('Unable to read device photos.'));});}finally{db.close();}}
async function write(rows:Photo[],remove:string[]=[]){const db=await openDb();try{await new Promise<void>((resolve,reject)=>{const transaction=db.transaction('photos','readwrite'),store=transaction.objectStore('photos');rows.forEach(p=>store.put(p));remove.forEach(id=>store.delete(id));transaction.oncomplete=()=>resolve();transaction.onerror=()=>reject(Error('Photo storage failed. Device storage may be full.'));transaction.onabort=()=>reject(Error('Photo storage was interrupted.'));});}finally{db.close();}}
const blobData=(blob:Blob)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(Error('Unable to read image.'));reader.readAsDataURL(blob);});
const hash=async(blob:Blob)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await blob.arrayBuffer()))).map(n=>n.toString(16).padStart(2,'0')).join('');
const validBackup=(v:unknown):v is {format:string;photos:BackupPhoto[]}=>{const x=v as {format:string;photos:BackupPhoto[]};return !!x&&x.format==='bazaara.photos.v1'&&Array.isArray(x.photos)&&x.photos.length<=2000&&x.photos.every(p=>p&&['id','name','type','created','hash','data'].every(k=>typeof (p as unknown as Record<string,unknown>)[k]==='string')&&Array.isArray(p.albums)&&p.albums.every(s=>typeof s==='string')&&typeof p.favorite==='boolean'&&typeof p.trashed==='boolean'&&/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(p.data)&&p.data.length<=42000000)&&new Set(x.photos.map(p=>p.id)).size===x.photos.length;};
export default function Photos(){
 const [items,setItems]=useState<Photo[]>([]),[urls,setUrls]=useState<Record<string,string>>({}),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[album,setAlbum]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[open,setOpen]=useState<string|null>(null),[rotation,setRotation]=useState(0),[brightness,setBrightness]=useState(100),[contrast,setContrast]=useState(100),[saturation,setSaturation]=useState(100),[crop,setCrop]=useState({left:0,top:0,width:100,height:100}),[albumDraft,setAlbumDraft]=useState('');
 const file=useRef<HTMLInputElement>(null),mounted=useRef(true),writing=useRef(false);const active=items.find(x=>x.id===open),shown=items.filter(p=>p.trashed===(filter==='trash')&&(filter!=='favorites'||p.favorite)&&(!album||p.albums.includes(album))&&(p.name+' '+p.albums.join(' ')).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.created.localeCompare(a.created));
 const refresh=async()=>{const values=await records();if(mounted.current)setItems(values);};
 useEffect(()=>{mounted.current=true;void refresh().catch(e=>setError(errorText(e)));return()=>{mounted.current=false;};},[]);
 useEffect(()=>{const next:Record<string,string>={};for(const p of items)next[p.id]=URL.createObjectURL(p.blob);setUrls(next);return()=>Object.values(next).forEach(u=>URL.revokeObjectURL(u));},[items]);
 useEffect(()=>{setAlbumDraft(items.find(x=>x.id===open)?.albums.join(', ')||'');setRotation(0);setBrightness(100);setContrast(100);setSaturation(100);setCrop({left:0,top:0,width:100,height:100});},[open]);
 async function operation(fn:()=>Promise<void>){if(writing.current)return;writing.current=true;setBusy(true);setError('');try{await fn();await refresh();}catch(e){setError(errorText(e));}finally{writing.current=false;setBusy(false);}}
 async function importFiles(files:File[]){await operation(async()=>{const current=await records(),known=new Set(current.map(p=>p.hash)),next:Photo[]=[];let skipped=0;for(const f of files){if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>30*1024*1024||!f.size)throw Error('Import PNG, JPEG, or WebP images under 30 MB each.');const digest=await hash(f);if(known.has(digest)){skipped++;continue;}known.add(digest);next.push({id:uid(),name:f.name,type:f.type,size:f.size,created:new Date(f.lastModified||Date.now()).toISOString(),hash:digest,albums:album?[album]:[],favorite:false,trashed:false,blob:f});}if([...current,...next].reduce((n,p)=>n+p.blob.size,0)>500*1024*1024)throw Error('This device gallery has a 500 MB limit. Export originals before removing older photos.');await write(next);setNotice(`${next.length} images imported${skipped?`; ${skipped} exact duplicates skipped`:''}.`);});}
 const patch=(p:Photo,changes:Partial<Photo>)=>void operation(async()=>{const current=(await records()).find(x=>x.id===p.id);if(!current)throw Error('This image was removed.');await write([{...current,...changes}]);});
 async function edited(){if(!active||!urls[active.id])throw Error('Select an image.');const image=new Image();image.src=urls[active.id];await image.decode();const sx=image.naturalWidth*crop.left/100,sy=image.naturalHeight*crop.top/100,sw=image.naturalWidth*Math.min(crop.width,100-crop.left)/100,sh=image.naturalHeight*Math.min(crop.height,100-crop.top)/100;if(sw<1||sh<1)throw Error('Crop must include part of the image.');const canvas=document.createElement('canvas'),turn=rotation%180!==0;canvas.width=Math.round(turn?sh:sw);canvas.height=Math.round(turn?sw:sh);const context=canvas.getContext('2d');if(!context)throw Error('Image editing is unavailable.');context.translate(canvas.width/2,canvas.height/2);context.rotate(rotation*Math.PI/180);context.filter=`brightness(${brightness}%) contrast(${contrast}%) saturate(${saturation}%)`;context.drawImage(image,sx,sy,sw,sh,-sw/2,-sh/2,sw,sh);return new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('Image export failed.')),'image/png'));}
 return <Shell name="Photos" description="Organize your own photos into albums, find duplicates, and crop or adjust images on your device." error={error} notice={notice} actions={<><a className="bf-button" href="/connected">Connected records</a><button disabled={busy} onClick={()=>file.current?.click()}>{busy?'Working…':'Import photos'}</button><input ref={file} type="file" hidden multiple accept="image/png,image/jpeg,image/webp" onChange={e=>{const files=Array.from(e.currentTarget.files||[]);e.currentTarget.value='';void importFiles(files);}}/><button disabled={busy} onClick={()=>void operation(async()=>{const values=await records();if(values.reduce((n,p)=>n+p.blob.size,0)>70*1024*1024)throw Error('Gallery backup limit is 70 MB. Download original images individually for larger galleries.');const photos:BackupPhoto[]=[];for(const {blob,...metadata} of values)photos.push({...metadata,data:await blobData(blob)});download('bazaara-photos.json',JSON.stringify({format:'bazaara.photos.v1',photos}));setNotice('Gallery backup exported with originals and metadata.');})}>Export gallery backup</button><ImportButton onFile={async f=>{if(f.size>100*1024*1024)throw Error('Gallery backups must be under 100 MB.');const v:unknown=JSON.parse(await f.text());if(!validBackup(v))throw Error('Invalid gallery backup.');let failure:unknown;await operation(async()=>{try{const current=await records(),photos:Photo[]=[];for(const {data,...metadata} of v.photos){const blob=await (await fetch(data)).blob();if(await hash(blob)!==metadata.hash)throw Error('An image in the backup failed its checksum.');photos.push({...metadata,size:blob.size,blob});}const merged=[...photos,...current.filter(x=>!photos.some(y=>y.id===x.id))];if(merged.reduce((n,p)=>n+p.blob.size,0)>500*1024*1024)throw Error('Import exceeds the device gallery limit.');await write(photos);setNotice('Gallery backup restored.');}catch(err){failure=err;throw err;}});if(failure)throw failure;}}/></>}>
 <ToolRow><input aria-label="Find photos" placeholder="Find photos or albums" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Photo filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All photos</option><option value="favorites">Favorites</option><option value="trash">Trash</option></select><select aria-label="Album" value={album} onChange={e=>setAlbum(e.target.value)}><option value="">All albums</option>{[...new Set(items.flatMap(p=>p.albums))].sort().map(s=><option key={s}>{s}</option>)}</select><span>{shown.length} photos · {(items.reduce((n,p)=>n+p.size,0)/1024/1024).toFixed(1)} MB</span></ToolRow>
 <div className="bf-gallery" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void importFiles(Array.from(e.dataTransfer.files));}}>{shown.map(p=><article key={p.id} className="bf-card"><button className="bf-photo-open" aria-label={'Open '+p.name} onClick={()=>setOpen(p.id)}><img loading="lazy" src={urls[p.id]} alt={p.name}/></button><h3>{p.name}</h3><div className="bf-actions"><button disabled={busy} aria-pressed={p.favorite} onClick={()=>patch(p,{favorite:!p.favorite})}>{p.favorite?'★ Favorite':'☆ Favorite'}</button><button disabled={busy} onClick={()=>patch(p,{trashed:!p.trashed})}>{p.trashed?'Restore':'Move to trash'}</button>{p.trashed&&<button disabled={busy} className="danger" onClick={()=>{if(window.confirm('Permanently remove this device photo?'))void operation(()=>write([],[p.id]));}}>Delete permanently</button>}</div></article>)}</div>{!shown.length&&<Empty title="No photos in this view">Import images or drop them into the gallery. Cloud backup and shared albums require a connected photo service.</Empty>}
 {active&&<Dialog title={active.name} close={()=>setOpen(null)}><img src={urls[active.id]} alt={active.name} style={{width:'100%',maxHeight:'50vh',objectFit:'contain',filter:`brightness(${brightness}%) contrast(${contrast}%) saturate(${saturation}%)`,transform:`rotate(${rotation}deg)`}}/><ToolRow><button onClick={()=>setOpen(shown[Math.max(0,shown.findIndex(p=>p.id===active.id)-1)]?.id||active.id)}>Previous</button><button onClick={()=>setOpen(shown[Math.min(shown.length-1,shown.findIndex(p=>p.id===active.id)+1)]?.id||active.id)}>Next</button><button onClick={()=>download(active.name,active.blob)}>Download original</button><button onClick={()=>setRotation((rotation+90)%360)}>Rotate 90°</button></ToolRow><Field label="Albums, comma separated"><input value={albumDraft} maxLength={500} onChange={e=>setAlbumDraft(e.target.value)}/><button disabled={busy} onClick={()=>patch(active,{albums:[...new Set(albumDraft.split(',').map(s=>s.trim()).filter(Boolean))].slice(0,15)})}>Save albums</button></Field><div className="bf-grid">{[['Brightness',brightness,setBrightness],['Contrast',contrast,setContrast],['Saturation',saturation,setSaturation]].map(([label,value,setter])=><Field key={String(label)} label={String(label)}><input type="range" min={0} max={200} value={value as number} onChange={e=>(setter as (value:number)=>void)(Number(e.target.value))}/></Field>)}</div><p>Crop percentages are applied when exporting or saving a copy.</p><div className="bf-grid">{(['left','top','width','height'] as const).map(k=><Field key={k} label={'Crop '+k+' (%)'}><input type="number" min={k==='width'||k==='height'?1:0} max={100} value={crop[k]} onChange={e=>setCrop({...crop,[k]:Math.max(k==='width'||k==='height'?1:0,Math.min(100,Number(e.target.value)))})}/></Field>)}</div><div className="bf-actions"><button disabled={busy} onClick={()=>void operation(async()=>download(active.name.replace(/\.[^.]+$/,'')+'-edited.png',await edited()))}>Export edited PNG</button><button disabled={busy} onClick={()=>void operation(async()=>{const blob=await edited();await write([{...active,id:uid(),name:active.name.replace(/\.[^.]+$/,'')+'-edited.png',type:'image/png',size:blob.size,hash:await hash(blob),created:new Date().toISOString(),blob}]);setNotice('Edited copy saved. Your original is preserved.');})}>Save edited copy</button></div><Notice error>{error}</Notice></Dialog>}
 </Shell>;
}
