'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,Empty,Field,ImportButton,Notice,Shell,ToolRow,copyText,download,errorText,now,readJson,safeLink,uid} from './core';
import {derive,generatePassword,newSalt,seal,unseal,validEnvelope,type Envelope,type VaultItem} from './vault-crypto';
const STORAGE='bazaara.vault.encrypted.v1';
export default function Vault(){
 const [envelope,setEnvelope]=useState<Envelope|null>(null),[ready,setReady]=useState(false),[items,setItems]=useState<VaultItem[]|null>(null),[master,setMaster]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[edit,setEdit]=useState<VaultItem|null>(null),[reveal,setReveal]=useState(false),[backup,setBackup]=useState<Envelope|null>(null),[backupPassword,setBackupPassword]=useState('');
 const key=useRef<CryptoKey|null>(null),epoch=useRef(0),writing=useRef(false),importing=useRef(false),stored=useRef<string|null>(null),idle=useRef<ReturnType<typeof setTimeout>|null>(null),envelopeRef=useRef<Envelope|null>(null);envelopeRef.current=envelope;
 const lock=()=>{epoch.current++;key.current=null;setItems(null);setEdit(null);setMaster('');setConfirm('');setReveal(false);setBackup(null);setBackupPassword('');};
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE);stored.current=raw;if(raw){const v:unknown=JSON.parse(raw);if(!validEnvelope(v))throw Error('Stored vault is invalid. Your existing data has been preserved.');setEnvelope(v);}if(!crypto.subtle)throw Error('Vault requires HTTPS or localhost and Web Crypto support.');}catch(e){setError(errorText(e));}setReady(true);const changed=(e:StorageEvent)=>{if(e.key===STORAGE){lock();try{const value=e.newValue?JSON.parse(e.newValue):null;if(value&&!validEnvelope(value))throw Error('Vault changed to an invalid record.');stored.current=e.newValue;setEnvelope(value);setNotice('Vault changed in another tab. Unlock the latest version.');}catch(err){setError(errorText(err));}}};window.addEventListener('storage',changed);return()=>{window.removeEventListener('storage',changed);epoch.current++;key.current=null;if(idle.current)clearTimeout(idle.current);};},[]);
 useEffect(()=>{if(!items)return;const reset=()=>{if(idle.current)clearTimeout(idle.current);idle.current=setTimeout(()=>{lock();setNotice('Vault locked after five minutes of inactivity.');},300000);},hidden=()=>{if(document.hidden)lock();};reset();window.addEventListener('pointerdown',reset);window.addEventListener('keydown',reset);document.addEventListener('visibilitychange',hidden);return()=>{if(idle.current)clearTimeout(idle.current);window.removeEventListener('pointerdown',reset);window.removeEventListener('keydown',reset);document.removeEventListener('visibilitychange',hidden);};},[items!==null]);
 async function unlock(){if(writing.current)return;writing.current=true;setBusy(true);setError('');const generation=epoch.current;try{let current=envelope;if(!current){if(master.length<12||master!==confirm)throw Error('Use a master password of at least 12 characters and enter the same confirmation.');if(stored.current!==null)throw Error('Existing vault data must be repaired or restored before creating a vault.');const salt=newSalt(),k=await derive(master,salt);current=await seal([],k,salt);if(generation!==epoch.current)return;if(localStorage.getItem(STORAGE)!==stored.current)throw Error('The vault changed in another tab. Reload it before proceeding.');const raw=JSON.stringify(current);localStorage.setItem(STORAGE,raw);stored.current=raw;key.current=k;setEnvelope(current);setItems([]);}else{const k=await derive(master,current.salt,current.iterations),records=await unseal(current,k);if(generation!==epoch.current)return;key.current=k;setItems(records);}setMaster('');setConfirm('');setNotice('Unlocked on this device. Keep an encrypted backup and remember your master password.');}catch(e){setError(errorText(e));}finally{writing.current=false;setBusy(false);}}
 async function save(next:VaultItem[]){const current=envelopeRef.current,k=key.current;if(!current||!k||writing.current)return false;writing.current=true;setBusy(true);const generation=epoch.current;try{const encrypted=await seal(next,k,current.salt,current.iterations);if(generation!==epoch.current)return false;if(localStorage.getItem(STORAGE)!==stored.current)throw Error('Vault changed in another tab. Lock and reopen it before saving.');const raw=JSON.stringify(encrypted);localStorage.setItem(STORAGE,raw);stored.current=raw;setEnvelope(encrypted);setItems(next);setError('');return true;}catch(e){setError(errorText(e));return false;}finally{writing.current=false;setBusy(false);}}
 return <Shell name="Vault" description="Keep an encrypted device vault, generate passwords, and export encrypted backups." storage={false} error={error} notice={notice} actions={<><a className="bf-button" href="/connected">Connected records</a>{envelope&&<button onClick={()=>download('bazaara-vault.encrypted.json',JSON.stringify(envelope,null,2))}>Export encrypted backup</button>}{items&&<><button disabled={busy} onClick={()=>{setReveal(false);setEdit({id:uid(),title:'',username:'',password:generatePassword(),url:'',notes:'',updated:now()});}}>＋ New login</button><button onClick={lock}>Lock vault</button></>}</>}>
 {!items?<section className="bf-panel" style={{maxWidth:560,margin:'auto'}}><h2>{envelope?'Unlock your vault':'Create a device vault'}</h2><form onSubmit={e=>{e.preventDefault();void unlock();}}><Field label="Master password"><input required type="password" autoComplete="off" value={master} minLength={envelope?undefined:12} onChange={e=>setMaster(e.target.value)}/></Field>{!envelope&&<Field label="Confirm master password"><input required type="password" autoComplete="off" value={confirm} onChange={e=>setConfirm(e.target.value)}/></Field>}<button className="primary" disabled={!ready||busy}>{busy?'Opening…':envelope?'Unlock':'Create encrypted vault'}</button></form><p>Records are encrypted before being stored. Your master password is never saved. Losing it means losing access; keep an encrypted backup. This device vault has no cloud recovery or browser autofill.</p><ImportButton label="Restore encrypted backup" onFile={async file=>{const value=await readJson(file,validEnvelope);setBackup(value);setBackupPassword('');}}/></section>:<><ToolRow><input aria-label="Find logins" placeholder="Find logins" value={query} onChange={e=>setQuery(e.target.value)}/><ImportButton label="Merge encrypted backup" onFile={async f=>{setBackup(await readJson(f,validEnvelope));setBackupPassword('');}}/></ToolRow><div className="bf-grid">{items.filter(x=>(x.title+' '+x.username+' '+x.url).toLowerCase().includes(query.toLowerCase())).map(x=><article className="bf-card" key={x.id}><h2>{x.title}</h2><p>{x.username}</p>{safeLink(x.url)&&<a href={safeLink(x.url)} target="_blank" rel="noopener noreferrer">Open website</a>}<div className="bf-actions"><button disabled={busy} onClick={()=>{setEdit(x);setReveal(false);}}>Edit</button><button onClick={()=>void copyText(x.password).then(()=>setNotice('Password copied. Clear your clipboard when finished.')).catch(e=>setError(errorText(e)))}>Copy password</button></div></article>)}</div>{!items.length&&<Empty title="Your vault is empty">Add a login or merge an encrypted backup.</Empty>}</>}
 {edit&&items&&<Dialog title="Login" close={()=>setEdit(null)}><form onSubmit={e=>{e.preventDefault();void save([{...edit,title:edit.title.trim(),updated:now()},...items.filter(x=>x.id!==edit.id)]).then(ok=>{if(ok)setEdit(null);});}}><Field label="Title"><input required autoFocus maxLength={200} value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})}/></Field><Field label="Username / email"><input value={edit.username} maxLength={1000} autoComplete="off" onChange={e=>setEdit({...edit,username:e.target.value})}/></Field><Field label="Password"><input type={reveal?'text':'password'} value={edit.password} maxLength={2000} autoComplete="off" onChange={e=>setEdit({...edit,password:e.target.value})}/></Field><ToolRow><button type="button" aria-pressed={reveal} onClick={()=>setReveal(!reveal)}>{reveal?'Hide':'Show'}</button><button type="button" onClick={()=>setEdit({...edit,password:generatePassword()})}>Generate 24-character password</button></ToolRow><Field label="Website"><input type="url" value={edit.url} maxLength={2000} onChange={e=>setEdit({...edit,url:e.target.value})}/></Field><Field label="Notes"><textarea value={edit.notes} maxLength={15000} onChange={e=>setEdit({...edit,notes:e.target.value})}/></Field><Notice error>{error}</Notice><div className="bf-actions"><button type="button" className="danger" disabled={busy} onClick={()=>{if(confirmDelete())void save(items.filter(x=>x.id!==edit.id)).then(ok=>{if(ok)setEdit(null);});}}>Delete</button><button className="primary" disabled={busy}>Save encrypted</button></div></form></Dialog>}
 {backup&&<Dialog title="Import encrypted vault" close={()=>{setBackup(null);setBackupPassword('');}}><form onSubmit={e=>{e.preventDefault();if(writing.current||importing.current)return;importing.current=true;setBusy(true);const generation=epoch.current;void (async()=>{try{const k=await derive(backupPassword,backup.salt,backup.iterations),imported=await unseal(backup,k);if(generation!==epoch.current)return;if(items){if(await save([...imported,...items.filter(x=>!imported.some(y=>y.id===x.id))])){setBackup(null);setBackupPassword('');setNotice('Encrypted backup merged.');}}else{if(stored.current&&!window.confirm('Replace the current encrypted vault with this backup?'))return;if(localStorage.getItem(STORAGE)!==stored.current)throw Error('Vault changed in another tab. Reload before importing.');const raw=JSON.stringify(backup);localStorage.setItem(STORAGE,raw);stored.current=raw;setEnvelope(backup);key.current=k;setItems(imported);setBackup(null);setBackupPassword('');setError('');}}catch(err){setError(errorText(err));}finally{importing.current=false;setBusy(false);}})();}}><Field label="Backup master password"><input required autoFocus type="password" value={backupPassword} autoComplete="off" onChange={e=>setBackupPassword(e.target.value)}/></Field><Notice error>{error}</Notice><button disabled={busy} className="primary">Decrypt and {items?'merge':'restore'}</button></form></Dialog>}
 </Shell>;
}
function confirmDelete(){return window.confirm('Delete this login from your device vault?');}
