export type VaultItem={id:string;title:string;username:string;password:string;url:string;notes:string;updated:string};
export type Envelope={format:'bazaara.vault.aesgcm.v1';iterations:number;salt:string;iv:string;ciphertext:string};
const base64=(value:ArrayBuffer|Uint8Array)=>{const bytes=new Uint8Array(value instanceof ArrayBuffer?value:value.buffer.slice(value.byteOffset,value.byteOffset+value.byteLength));let out='';for(const byte of bytes)out+=String.fromCharCode(byte);return btoa(out);};
const unbase64=(value:string)=>{const text=atob(value),out=new Uint8Array(text.length);for(let i=0;i<text.length;i++)out[i]=text.charCodeAt(i);return out;};
export function validEnvelope(v:unknown):v is Envelope{const x=v as Envelope;try{return !!x&&x.format==='bazaara.vault.aesgcm.v1'&&Number.isInteger(x.iterations)&&x.iterations>=600000&&x.iterations<=1200000&&['salt','iv','ciphertext'].every(k=>typeof (x as unknown as Record<string,unknown>)[k]==='string')&&unbase64(x.salt).length===16&&unbase64(x.iv).length===12&&unbase64(x.ciphertext).length>=16&&x.ciphertext.length<3000000;}catch{return false;}}
export function validItems(v:unknown):v is VaultItem[]{return Array.isArray(v)&&v.length<=1000&&v.every(x=>x&&['id','title','username','password','url','notes','updated'].every(k=>typeof x[k]==='string')&&x.title.length<=200&&x.password.length<=2000&&x.notes.length<=15000)&&new Set(v.map(x=>x.id)).size===v.length;}
export async function derive(password:string,salt:string,iterations=600000){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt:unbase64(salt),iterations},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
export function newSalt(){return base64(crypto.getRandomValues(new Uint8Array(16)));}
export async function seal(items:VaultItem[],key:CryptoKey,salt:string,iterations=600000):Promise<Envelope>{if(!validItems(items))throw Error('Invalid vault records.');const iv=crypto.getRandomValues(new Uint8Array(12));const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode('bazaara.vault.aesgcm.v1')},key,new TextEncoder().encode(JSON.stringify(items)));return {format:'bazaara.vault.aesgcm.v1',iterations,salt,iv:base64(iv),ciphertext:base64(ciphertext)};}
export async function unseal(envelope:Envelope,key:CryptoKey){let bytes:ArrayBuffer;try{bytes=await crypto.subtle.decrypt({name:'AES-GCM',iv:unbase64(envelope.iv),additionalData:new TextEncoder().encode('bazaara.vault.aesgcm.v1')},key,unbase64(envelope.ciphertext));}catch{throw Error('The password is incorrect or this vault backup has been changed.');}const items:unknown=JSON.parse(new TextDecoder().decode(bytes));if(!validItems(items))throw Error('Invalid vault contents.');return items;}
export function generatePassword(length=24){const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%&*-_';let result='';const cutoff=256-256%alphabet.length;while(result.length<length){const bytes=crypto.getRandomValues(new Uint8Array(length));for(const n of bytes)if(n<cutoff&&result.length<length)result+=alphabet[n%alphabet.length];}return result;}
