'use client';
import {useEffect,useRef,useState} from 'react';
import {Dialog,Empty,Field,ImportButton,Notice,Shell,ToolRow,download,errorText,now,readJson,uid,useCollection,useHistory} from './core';
import {clipDuration,dimensions,exportSrt,filterFor,importSrt,projectDuration,renderVideo,transformAt,type Caption,type MediaAsset,type VideoClip,type VideoProject} from './video-engine';
const fresh=():VideoProject=>({id:uid(),name:'Untitled edit',assets:[],clips:[],captions:[],aspect:'16:9',resolution:1080,fps:30,fit:'contain',background:'#070913',captionSize:36,musicId:'',musicVolume:.5,chroma:false,chromaColor:'#00ff00',chromaTolerance:90,updated:now()});
const valid=(v:unknown):v is VideoProject=>{const p=v as VideoProject;return !!p&&typeof p.id==='string'&&typeof p.name==='string'&&typeof p.updated==='string'&&Array.isArray(p.assets)&&p.assets.every(a=>a&&typeof a.id==='string'&&typeof a.name==='string'&&Number.isFinite(a.duration)&&a.duration>0&&['video','audio'].includes(a.kind))&&Array.isArray(p.clips)&&p.clips.every(c=>c&&typeof c.id==='string'&&typeof c.assetId==='string'&&Number.isFinite(c.in)&&Number.isFinite(c.out)&&c.in>=0&&c.out>c.in&&Number.isFinite(c.speed)&&c.speed>=.25&&c.speed<=4&&['brightness','contrast','saturation','hue','blur','scale','x','y','rotation','opacity','volume','fadeIn','fadeOut'].every(k=>Number.isFinite((c as unknown as Record<string,number>)[k]))&&['none','circle'].includes(c.mask)&&typeof c.mirror==='boolean'&&c.volume>=0&&c.volume<=2&&c.scale>0&&c.scale<=10&&c.opacity>=0&&c.opacity<=1&&c.fadeIn>=0&&c.fadeOut>=0&&Array.isArray(c.keyframes)&&c.keyframes.every(k=>k&&['time','scale','x','y','rotation','opacity'].every(n=>Number.isFinite((k as unknown as Record<string,number>)[n]))&&k.time>=0&&k.scale>0&&k.opacity>=0&&k.opacity<=1))&&Array.isArray(p.captions)&&p.captions.every(c=>c&&typeof c.id==='string'&&typeof c.text==='string'&&Number.isFinite(c.start)&&Number.isFinite(c.end)&&c.start>=0&&c.end>c.start)&&['16:9','9:16','1:1'].includes(p.aspect)&&[720,1080,2160].includes(p.resolution)&&[24,30,60].includes(p.fps)&&/^#[a-f0-9]{6}$/i.test(p.background)&&/^#[a-f0-9]{6}$/i.test(p.chromaColor)&&Number.isFinite(p.captionSize)&&p.captionSize>=12&&p.captionSize<=100&&Number.isFinite(p.musicVolume)&&p.musicVolume>=0&&p.musicVolume<=2&&Number.isFinite(p.chromaTolerance)&&p.chromaTolerance>=0&&p.chromaTolerance<=441&&typeof p.chroma==='boolean'&&typeof p.musicId==='string'&&['contain','cover'].includes(p.fit)&&p.assets.length<=100&&new Set(p.assets.map(a=>a.id)).size===p.assets.length&&p.clips.length<=100&&p.captions.length<=1000&&p.clips.every(c=>c.keyframes.length<=1000&&p.assets.some(a=>a.id===c.assetId&&a.kind==='video'&&c.out<=a.duration+.03))&&(!p.musicId||p.assets.some(a=>a.id===p.musicId&&a.kind==='audio'));};
const newClip=(a:MediaAsset):VideoClip=>({id:uid(),assetId:a.id,in:0,out:a.duration,speed:1,volume:1,brightness:100,contrast:100,saturation:100,hue:0,blur:0,scale:1,x:0,y:0,rotation:0,opacity:1,mirror:false,fadeIn:0,fadeOut:0,mask:'none',keyframes:[]});
export default function Video(){
 const store=useCollection<VideoProject>('bazcut-v2',valid),hist=useHistory<VideoProject>(fresh());const p=hist.value;
 const [urls,setUrls]=useState<Record<string,string>>({}),[selected,setSelected]=useState(''),[time,setTime]=useState(0),[rendering,setRendering]=useState(false),[importing,setImporting]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[caption,setCaption]=useState<Caption|null>(null);
 const busy=rendering||importing;
 const video=useRef<HTMLVideoElement>(null),allUrls=useRef(new Set<string>()),controller=useRef<AbortController|null>(null),attaching=useRef(false),pendingSeek=useRef<number|null>(null);const selectedClip=p.clips.find(c=>c.id===selected)||p.clips[0];const total=projectDuration(p),offset=selectedClip?p.clips.slice(0,p.clips.findIndex(c=>c.id===selectedClip.id)).reduce((n,c)=>n+clipDuration(c),0):0;
 useEffect(()=>()=>{controller.current?.abort();allUrls.current.forEach(u=>URL.revokeObjectURL(u));},[]);
 useEffect(()=>{if(video.current&&selectedClip){video.current.playbackRate=selectedClip.speed;if(video.current.readyState>=1){video.current.currentTime=pendingSeek.current??selectedClip.in;pendingSeek.current=null;}}},[selectedClip?.speed,selectedClip?.id]);
 const change=(patch:Partial<VideoProject>)=>hist.change({...p,...patch,updated:now()});const patchClip=(patch:Partial<VideoClip>)=>{if(selectedClip)change({clips:p.clips.map(c=>c.id===selectedClip.id?{...c,...patch}:c)});};
 async function attach(file:File){
  if(attaching.current)return;
  if(!/^(video|audio)\//.test(file.type)||file.size===0||file.size>500*1024*1024)throw Error('Select a non-empty video/audio source under 500 MB.');
  attaching.current=true;setImporting(true);setError('');
  const objectUrl=URL.createObjectURL(file),el=document.createElement(file.type.startsWith('video/')?'video':'audio');el.preload='metadata';el.src=objectUrl;
  try{await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Source metadata timed out.')),15000);el.onloadedmetadata=()=>{clearTimeout(timer);resolve();};el.onerror=()=>{clearTimeout(timer);reject(Error('The browser cannot read this source file.'));};});
   if(el.duration===Infinity){await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Could not determine this recording’s duration.')),15000);const done=()=>{clearTimeout(timer);el.removeEventListener('seeked',done);resolve();};el.addEventListener('seeked',done,{once:true});el.currentTime=1e10;});}
   if(!Number.isFinite(el.duration)||el.duration<=0)throw Error('This source has no readable duration.');const original=p.assets.find(a=>a.name===file.name&&a.kind===(file.type.startsWith('video/')?'video':'audio'));
   if(!original&&(p.assets.length>=100||file.type.startsWith('video/')&&p.clips.length>=100))throw Error('A project supports up to 100 sources and 100 clips.');
   if(original&&p.clips.some(c=>c.assetId===original.id&&c.out>el.duration+.03))throw Error('This replacement source is shorter than an existing trim range.');
   const a:MediaAsset={id:original?.id||uid(),name:file.name,duration:el.duration,width:el instanceof HTMLVideoElement?el.videoWidth:0,height:el instanceof HTMLVideoElement?el.videoHeight:0,kind:file.type.startsWith('video/')?'video':'audio'};allUrls.current.add(objectUrl);setUrls(old=>({...old,[a.id]:objectUrl}));const assets=[a,...p.assets.filter(x=>x.id!==a.id)];const c=a.kind==='video'&&!original?newClip(a):null;change({assets,clips:c?[...p.clips,c]:p.clips,musicId:a.kind==='audio'&&!p.musicId?a.id:p.musicId});if(c)setSelected(c.id);setNotice(original?'Source reattached.':'Source imported.');
  }catch(e){URL.revokeObjectURL(objectUrl);throw e;}finally{el.pause();el.removeAttribute('src');el.load();attaching.current=false;setImporting(false);}
 }
 const exportMovie=async()=>{if(controller.current||attaching.current)return;setRendering(true);setError('');setNotice('Rendering locally. Keep this tab active until the export finishes.');controller.current=new AbortController();try{const blob=await renderVideo(p,urls,controller.current.signal,setProgress);download(p.name+'.webm',blob);setNotice('WebM exported with source audio, captions and your edit effects.');}catch(e){setError(errorText(e));setNotice('');}finally{setRendering(false);controller.current=null;}};
 const split=()=>{if(!selectedClip)return;const local=Math.max(.05,Math.min(clipDuration(selectedClip)-.05,time-offset)),at=selectedClip.in+local*selectedClip.speed;if(at<=selectedClip.in||at>=selectedClip.out)return;const i=p.clips.findIndex(c=>c.id===selectedClip.id),clips=[...p.clips];clips.splice(i,1,{...selectedClip,out:at,keyframes:[]},{...selectedClip,id:uid(),in:at,keyframes:[]});change({clips});};
 const reorder=(by:number)=>{if(!selectedClip)return;const i=p.clips.findIndex(c=>c.id===selectedClip.id),j=i+by;if(j<0||j>=p.clips.length)return;const clips=[...p.clips];[clips[i],clips[j]]=[clips[j],clips[i]];change({clips});};
 const t=selectedClip?transformAt(selectedClip,Math.max(0,time-offset)):null;
 return <Shell name="BazCut" description="Edit your own media with a multi-clip timeline, source audio, keyframes, masks, captions, and real browser video export." error={error||store.error} notice={notice} actions={<><a className="bf-button" href="/connected">Connected projects</a><button disabled={busy} onClick={()=>{hist.replace(fresh());setSelected('');setTime(0);}}>New project</button><button disabled={busy} onClick={()=>{if(store.put(p))setNotice('Project plan saved. Source files remain separate; reattach them after reopening.');}}>Save project</button><button onClick={()=>download(p.name+'.bazproject.json',JSON.stringify(p,null,2))}>Export project</button><ImportButton onFile={async f=>{const v=await readJson(f,valid);hist.replace(v);setSelected(v.clips[0]?.id||'');setNotice('Project loaded. Reattach source files with the same names.');}}/></>}>
 <ToolRow><input aria-label="Project title" value={p.name} maxLength={160} disabled={busy} onChange={e=>change({name:e.target.value})}/><button onClick={hist.undo} disabled={busy||!hist.canUndo}>Undo</button><button onClick={hist.redo} disabled={busy||!hist.canRedo}>Redo</button><Field label="Import source"><input type="file" accept="video/*,audio/*" disabled={busy} onChange={e=>{const f=e.currentTarget.files?.[0];e.currentTarget.value='';if(f)void attach(f).catch(err=>setError(errorText(err)));}}/></Field><select aria-label="Saved project" value="" disabled={busy} onChange={e=>{const x=store.items.find(x=>x.id===e.target.value);if(x){hist.replace(x);setSelected(x.clips[0]?.id||'');setNotice('Reattach this project’s source files to preview and render.');}}}><option value="">Open saved project</option>{store.items.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></ToolRow>
 <div className="bf-editor-layout"><section className="bf-panel"><h2>Preview</h2>{selectedClip&&urls[selectedClip.assetId]?<div style={{position:'relative',overflow:'hidden',background:p.background,borderRadius:14,aspectRatio:p.aspect.replace(':','/')}}><video className="bf-media" ref={video} src={urls[selectedClip.assetId]} controls playsInline style={{height:'100%',filter:filterFor(selectedClip),opacity:t?.opacity,objectFit:p.fit,transform:`translate(${t?.x||0}%,${t?.y||0}%) rotate(${t?.rotation||0}deg) scale(${selectedClip.mirror?-(t?.scale||1):t?.scale||1},${t?.scale||1})`,clipPath:selectedClip.mask==='circle'?'circle(45%)':undefined}} onLoadedMetadata={e=>{e.currentTarget.currentTime=pendingSeek.current??selectedClip.in;pendingSeek.current=null;e.currentTarget.playbackRate=selectedClip.speed;}} onTimeUpdate={e=>{const v=e.currentTarget;const position=offset+(v.currentTime-selectedClip.in)/selectedClip.speed;setTime(Math.max(0,position));if(v.currentTime>=selectedClip.out){v.pause();if(Math.abs(v.currentTime-selectedClip.out)>.02)v.currentTime=selectedClip.out;}}}/>{p.captions.filter(c=>time>=c.start&&time<c.end).map(c=><div key={c.id} style={{position:'absolute',bottom:'5%',left:'5%',right:'5%',textAlign:'center',whiteSpace:'pre-wrap',fontWeight:800,fontSize:p.captionSize,color:'white',textShadow:'0 2px 5px black',pointerEvents:'none'}}>{c.text}</div>)}</div>:<Empty title={p.clips.length?'Reattach your source files':'Import a video to begin'}>Project backups save your edit plan; original media files stay separate.</Empty>}
 <div className="bf-row"><strong>{time.toFixed(2)}s / {total.toFixed(2)}s</strong><span className="bf-tag">{dimensions(p).width} × {dimensions(p).height} · {p.fps}fps</span></div><input type="range" min={0} max={Math.max(.01,total)} step={.05} aria-label="Timeline playhead" value={Math.min(time,total)} onChange={e=>{const value=Number(e.target.value);setTime(value);let n=0;const c=p.clips.find(c=>{const match=value>=n&&value<=n+clipDuration(c);if(!match)n+=clipDuration(c);return match;});if(c){pendingSeek.current=c.in+(value-n)*c.speed;setSelected(c.id);if(c.id===selectedClip?.id&&video.current){video.current.currentTime=pendingSeek.current;pendingSeek.current=null;}}}}/>
 <h2>Timeline</h2><div className="bf-content">{p.clips.map((c,i)=><article className="bf-card" key={c.id}><div className="bf-row"><button aria-pressed={selectedClip?.id===c.id} onClick={()=>{setSelected(c.id);setTime(p.clips.slice(0,i).reduce((n,x)=>n+clipDuration(x),0));}}>{i+1}. {p.assets.find(a=>a.id===c.assetId)?.name||'Source'} · {clipDuration(c).toFixed(2)}s</button><span className="bf-tag">{c.speed}×</span></div></article>)}</div><div className="bf-actions"><button disabled={!selectedClip||busy||p.clips.length>=100} onClick={split}>Split at playhead</button><button disabled={!selectedClip||busy} onClick={()=>reorder(-1)}>Move earlier</button><button disabled={!selectedClip||busy} onClick={()=>reorder(1)}>Move later</button><button disabled={!selectedClip||busy||p.clips.length>=100} onClick={()=>{if(selectedClip)change({clips:[...p.clips,{...selectedClip,id:uid()}]});}}>Duplicate clip</button><button className="danger" disabled={!selectedClip||busy} onClick={()=>{if(selectedClip)change({clips:p.clips.filter(c=>c.id!==selectedClip.id)});}}>Remove clip</button></div>
 </section><aside className="bf-panel"><h2>Clip inspector</h2>{selectedClip&&<><div className="bf-grid"><Field label="Trim in (seconds)"><input type="number" min={0} max={selectedClip.out-.01} step={.05} value={selectedClip.in} disabled={busy} onChange={e=>patchClip({in:Number(e.target.value)})}/></Field><Field label="Trim out (seconds)"><input type="number" min={selectedClip.in+.01} max={p.assets.find(a=>a.id===selectedClip.assetId)?.duration} step={.05} value={selectedClip.out} disabled={busy} onChange={e=>patchClip({out:Number(e.target.value)})}/></Field></div><Field label="Speed"><select value={selectedClip.speed} disabled={busy} onChange={e=>patchClip({speed:Number(e.target.value)})}>{[.25,.5,.75,1,1.5,2,4].map(n=><option key={n} value={n}>{n}×</option>)}</select></Field>{([['volume','Source volume',0,1,.05],['brightness','Brightness',0,200,1],['contrast','Contrast',0,200,1],['saturation','Saturation',0,200,1],['hue','Hue',-180,180,1],['blur','Blur',0,20,.5],['scale','Scale',.1,3,.05],['x','Horizontal position',-100,100,1],['y','Vertical position',-100,100,1],['rotation','Rotation',-180,180,1],['opacity','Opacity',0,1,.05],['fadeIn','Fade in, seconds',0,3,.1],['fadeOut','Fade out, seconds',0,3,.1]] as const).map(([k,label,min,max,step])=><Field key={k} label={label+' · '+selectedClip[k]}><input type="range" min={min} max={max} step={step} value={selectedClip[k]} disabled={busy} onChange={e=>patchClip({[k]:Number(e.target.value)})}/></Field>)}<label className="bf-field check"><input type="checkbox" checked={selectedClip.mirror} disabled={busy} onChange={e=>patchClip({mirror:e.target.checked})}/>Mirror horizontally</label><Field label="Mask"><select value={selectedClip.mask} disabled={busy} onChange={e=>patchClip({mask:e.target.value as VideoClip['mask']})}><option value="none">No mask</option><option value="circle">Circle</option></select></Field><button disabled={busy} onClick={()=>patchClip({keyframes:[...selectedClip.keyframes.filter(k=>Math.abs(k.time-(time-offset))>.02),{time:Math.max(0,time-offset),scale:selectedClip.scale,x:selectedClip.x,y:selectedClip.y,rotation:selectedClip.rotation,opacity:selectedClip.opacity}]})}>Add transform keyframe at playhead</button><div className="bf-content">{selectedClip.keyframes.map((k,i)=><div key={i} className="bf-row"><small>{k.time.toFixed(2)}s · scale {k.scale}</small><button aria-label="Remove keyframe" disabled={busy} onClick={()=>patchClip({keyframes:selectedClip.keyframes.filter((_,n)=>n!==i)})}>✕</button></div>)}</div></>}
 <h2>Canvas & audio</h2><Field label="Aspect ratio"><select value={p.aspect} disabled={busy} onChange={e=>change({aspect:e.target.value as VideoProject['aspect']})}><option>16:9</option><option>9:16</option><option>1:1</option></select></Field><Field label="Source fit"><select value={p.fit} disabled={busy} onChange={e=>change({fit:e.target.value as VideoProject['fit']})}><option value="contain">Fit with background</option><option value="cover">Fill / crop</option></select></Field><Field label="Background"><input type="color" value={p.background} disabled={busy} onChange={e=>change({background:e.target.value})}/></Field><Field label="Music track"><select value={p.musicId} disabled={busy} onChange={e=>change({musicId:e.target.value})}><option value="">No music</option>{p.assets.filter(a=>a.kind==='audio').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></Field>{p.musicId&&<Field label="Music volume"><input type="range" min={0} max={1} step={.05} value={p.musicVolume} disabled={busy} onChange={e=>change({musicVolume:Number(e.target.value)})}/></Field>}<label className="bf-field check"><input type="checkbox" checked={p.chroma} disabled={busy} onChange={e=>change({chroma:e.target.checked})}/>Chroma-key replacement during export</label>{p.chroma&&<><Field label="Key color"><input type="color" value={p.chromaColor} disabled={busy} onChange={e=>change({chromaColor:e.target.value})}/></Field><Field label="Key tolerance"><input type="range" min={1} max={250} value={p.chromaTolerance} disabled={busy} onChange={e=>change({chromaTolerance:Number(e.target.value)})}/></Field><small>Chroma-key replacement is applied to exported frames; the live HTML preview shows the original colors.</small></>}
 </aside></div>
 <section className="bf-panel"><h2>Captions</h2><ToolRow><button disabled={busy||total<=0||p.captions.length>=1000} onClick={()=>setCaption({id:uid(),start:Math.max(0,Math.min(time,total-.01)),end:Math.min(total,time+3),text:''})}>Add caption</button><ImportButton label="Import SRT / VTT" accept=".srt,.vtt" onFile={async f=>{if(f.size>500000)throw Error('Caption files must be under 500 KB.');const captions=importSrt(await f.text());if(captions.some(c=>c.end>total))throw Error('Caption timestamps extend beyond the timeline.');change({captions});}}/><button onClick={()=>download(p.name+'.srt',exportSrt(p.captions),'text/plain')}>Export SRT</button><Field label="Caption size"><input type="number" min={12} max={100} value={p.captionSize} disabled={busy} onChange={e=>change({captionSize:Number(e.target.value)})}/></Field></ToolRow>{p.captions.map(c=><div key={c.id} className="bf-row"><span>{c.start.toFixed(2)}–{c.end.toFixed(2)}s · {c.text}</span><button disabled={busy} onClick={()=>setCaption(c)}>Edit</button><button disabled={busy} onClick={()=>change({captions:p.captions.filter(x=>x.id!==c.id)})}>Remove</button></div>)}</section>
 <ToolRow><Field label="Export resolution"><select value={p.resolution} disabled={busy} onChange={e=>change({resolution:Number(e.target.value) as VideoProject['resolution']})}><option value={720}>720p</option><option value={1080}>1080p</option><option value={2160}>2160p / 4K dimensions</option></select></Field><Field label="Frame rate"><select value={p.fps} disabled={busy} onChange={e=>change({fps:Number(e.target.value) as VideoProject['fps']})}><option>24</option><option>30</option><option>60</option></select></Field><button className="primary" onClick={()=>void exportMovie()} disabled={busy||!p.clips.length||total<=0||total>180}>{rendering?`Rendering ${progress}%`:importing?'Importing source…':'Export WebM with audio'}</button>{rendering&&<button onClick={()=>controller.current?.abort()}>Cancel export</button>}<small>Browser render limit: 3 minutes. Higher dimensions do not restore detail absent from the source.</small></ToolRow>{rendering&&<progress value={progress} max={100}/>}
 {caption&&<Dialog title="Caption timing" close={()=>setCaption(null)}><form onSubmit={e=>{e.preventDefault();if(caption.start<0||caption.end<=caption.start||caption.end>total){setError('Caption timing must be within the project timeline.');return;}change({captions:[...p.captions.filter(c=>c.id!==caption.id),caption].sort((a,b)=>a.start-b.start)});setCaption(null);}}><Field label="Text"><textarea required autoFocus value={caption.text} maxLength={1000} onChange={e=>setCaption({...caption,text:e.target.value})}/></Field><Field label="Start"><input type="number" min={0} step="any" value={caption.start} onChange={e=>setCaption({...caption,start:Number(e.target.value)})}/></Field><Field label="End"><input type="number" min={0} max={total} step="any" value={caption.end} onChange={e=>setCaption({...caption,end:Number(e.target.value)})}/></Field><button className="primary">Save caption</button></form></Dialog>}
 </Shell>;
}
