"use client";
import {useCallback,useEffect,useMemo,useRef,useState,type FormEvent,type CSSProperties} from "react";
import {API_BASE,api,errorText,signInUrl,uploadMedia,useSocialSession} from "@bazaara/social-ui";
type User={id:string;displayName:string|null;handle?:string;socialProfile?:{handle:string}|null};
type Conversation={id:string;participants:User[];unread:number;updatedAt:string;latestMessage:{body:string|null;createdAt:string}|null};
type Message={id:string;senderUserId:string;body:string|null;createdAt:string;deletedAt:string|null;replyToMessageId?:string|null;replyTo?:{body:string|null;senderUserId:string}|null;attachment?:{url:string;name:string}|null};
const url=(c:string)=>`/v1/bazchat/conversations/${encodeURIComponent(c)}`;
export default function Feature(){const session=useSocialSession();const [conversations,setConversations]=useState<Conversation[]>([]),[active,setActive]=useState(""),[messages,setMessages]=useState<Message[]>([]),[cursor,setCursor]=useState<string|null>(null),[hasMore,setHasMore]=useState(false),[find,setFind]=useState(""),[members,setMembers]=useState<User[]>([]),[draft,setDraft]=useState(""),[localFilter,setLocalFilter]=useState(""),[reply,setReply]=useState<Message|null>(null),[file,setFile]=useState<File|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
const messagesRef=useRef<Message[]>([]);useEffect(()=>{messagesRef.current=messages},[messages]);
const loadList=useCallback(async()=>{try{const x=await api.get<{conversations:Conversation[]}>("/v1/bazchat/conversations",{maxRetries:0});setConversations(x.conversations)}catch(e){setError(errorText(e))}},[]);
const loadMessages=useCallback(async(c:string,after?:string)=>{if(!c)return;try{const q=after?{limit:50,after}:{limit:50};const x=await api.get<{messages:Message[];nextCursor:string|null;hasMore:boolean}>(`${url(c)}/messages`,{query:q,maxRetries:0});setMessages(p=>after?[...p,...x.messages.filter(m=>!p.some(y=>y.id===m.id))]:x.messages);setCursor(x.nextCursor);setHasMore(x.hasMore);if(x.messages.length)void api.post(`${url(c)}/read`,{}).catch(()=>undefined)}catch(e){setError(errorText(e))}},[]);
useEffect(()=>{if(!session.user)return;void loadList();const t=window.setInterval(()=>void loadList(),16000);return()=>window.clearInterval(t)},[session.user,loadList]);
useEffect(()=>{setMessages([]);setCursor(null);setReply(null);if(active)void loadMessages(active)},[active,loadMessages]);
useEffect(()=>{if(!session.user)return;let alive=true;const ev=new EventSource(`${API_BASE}/v1/bazchat/events`,{withCredentials:true});ev.addEventListener("changed",(e:MessageEvent)=>{if(!alive)return;try{const event=JSON.parse(String(e.data)) as {conversationId:string};void loadList();if(event.conversationId===active){void loadMessages(active,messagesRef.current.at(-1)?.id)}}catch{}});return()=>{alive=false;ev.close()}},[session.user,active,loadList,loadMessages]);
useEffect(()=>{if(!active)return;const t=window.setInterval(()=>void loadMessages(active,messagesRef.current.at(-1)?.id),12000);return()=>window.clearInterval(t)},[active,loadMessages]);
async function lookup(){if(find.trim().length<2)return;setError("");try{const r=await api.get<{users:User[]}>("/v1/social/users",{query:{q:find.trim()},maxRetries:0});setMembers(r.users)}catch(e){setError(errorText(e))}}
async function connect(id:string){setBusy(true);try{const r=await api.post<{conversationId:string}>("/v1/bazchat/conversations",{recipientUserId:id});await loadList();setActive(r.conversationId);setMembers([]);setFind("")}catch(e){setError(errorText(e))}finally{setBusy(false)}}
async function send(e:FormEvent){e.preventDefault();if(!active||(!draft.trim()&&!file)||busy)return;setBusy(true);setError("");try{let assetId:string|undefined;let attachmentName:string|undefined;if(file){if(file.size>25*1024*1024)throw Error("Attachments must be at most 25 MB.");const a=await uploadMedia(file,"PRIVATE");assetId=a.id;attachmentName=file.name}await api.post(`${url(active)}/messages`,{body:draft.trim(),clientNonce:crypto.randomUUID(),...(assetId?{assetId,attachmentName}:{}),...(reply?{replyToMessageId:reply.id}:{})});setDraft("");setFile(null);setReply(null);await loadMessages(active,messages[messages.length-1]?.id);await loadList()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
async function remove(m:Message){if(!active||!confirm("Remove this message from the conversation?"))return;try{await api.delete(`${url(active)}/messages/${encodeURIComponent(m.id)}`);setMessages(p=>p.map(x=>x.id===m.id?{...x,deletedAt:new Date().toISOString(),body:null,attachment:null}:x))}catch(e){setError(errorText(e))}}
function exportLoaded(){const b=new Blob([messages.map(m=>`${m.createdAt} ${m.senderUserId===session.user?.id?"You":"Contact"}: ${m.deletedAt?"[deleted]":m.body??"[attachment]"}`).join("\n")],{type:"text/plain"});const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download="bchat-loaded-history.txt";a.click();window.setTimeout(()=>URL.revokeObjectURL(u),1500)}
const current=conversations.find(x=>x.id===active);const peer=current?.participants.find(p=>p.id!==session.user?.id);const visible=useMemo(()=>messages.filter(m=>(m.body??"").toLowerCase().includes(localFilter.toLowerCase())),[messages,localFilter]);
return <main className="bz3" style={{"--accent":"#8a5cff"} as CSSProperties}><header><div className="bzbrand"><span className="bzmark">B</span><div><strong>BChat</strong><small>BAZAARA • PRIVATE CONVERSATIONS</small></div></div><span className="chip">Authenticated messaging API • E2EE not enabled</span></header><div className="deck"><span className="eyebrow">Communication</span><h1>Your conversations</h1><p>Server-backed direct messages, message replies, attachments and live event updates. Private chats are not yet end-to-end encrypted.</p></div><div className="v3caps" aria-label="BChat capabilities"><span className="live">Direct messages</span><span className="live">Replies & files</span><span className="live">Realtime updates</span><span className="planned">Channels & groups · service expansion</span><span className="planned">Huddles & calls · WebRTC service</span><span className="planned">Workflows & bots · automation service</span><span className="planned">E2EE · cryptographic service</span></div>
{session.loading?<p role="status">Checking your BazID session…</p>:session.unauthenticated?<a href={signInUrl()}>Sign in to BChat</a>:session.error?<div className="status" role="alert">{session.error}</div>:<><div className="body cols"><section className="panel"><h2>Inbox</h2><label>Find a member<input value={find} onChange={e=>setFind(e.target.value)} minLength={2} placeholder="Search a public handle"/></label><button onClick={()=>void lookup()} disabled={find.trim().length<2||busy}>Find people</button>{members.length>0&&<div className="list">{members.map(p=><button key={p.id} onClick={()=>void connect(p.id)} disabled={busy} className="item"><strong>{p.displayName??p.handle??"Member"}</strong><span className="sub">@{p.handle??"member"} • New conversation</span></button>)}</div>}<div className="divider"/><div className="list">{conversations.map(c=>{const p=c.participants.find(x=>x.id!==session.user?.id);return <button key={c.id} onClick={()=>setActive(c.id)} className={`item ${active===c.id?"selected":""}`}><strong>{p?.displayName??p?.socialProfile?.handle??p?.handle??"Member"}</strong><span className="sub nowrap">{c.latestMessage?.body??"Attachment or new conversation"}</span>{c.unread>0&&<span className="chip">{c.unread} unread</span>}</button>})}{!conversations.length&&<p>No conversations yet. Search for discoverable members to begin.</p>}</div></section>
<section className="panel"><div className="row"><div className="grow"><h2>{(peer?.displayName??peer?.socialProfile?.handle)??(active?"Conversation":"Select a chat")}</h2>{(peer?.socialProfile?.handle||peer?.handle)&&<span className="sub">@{peer.socialProfile?.handle??peer.handle}</span>}</div>{active&&<button onClick={exportLoaded}>Export loaded messages</button>}</div>{active?<><div className="well scroll scrollNo" style={{minHeight:360,maxHeight:"55dvh"}} aria-label="Conversation history">{visible.map(m=><article className="callout" key={m.id} style={{marginLeft:m.senderUserId===session.user?.id?"12%":0,marginRight:m.senderUserId!==session.user?.id?"12%":0}}><div className="row"><strong>{m.senderUserId===session.user?.id?"You":peer?.displayName??"Member"}</strong><small className="sub">{new Date(m.createdAt).toLocaleString()}</small></div>{m.replyTo&&<div className="chip">Reply to: {(m.replyTo.body??"Attachment").slice(0,100)}</div>}<div className="contentBody">{m.deletedAt?"[Message deleted]":m.body}</div>{!m.deletedAt&&m.attachment&&<a href={m.attachment.url} target="_blank" rel="noopener noreferrer">Attachment: {m.attachment.name}</a>}{!m.deletedAt&&<div className="actions"><button onClick={()=>setReply(m)}>Reply</button>{m.senderUserId===session.user?.id&&<button onClick={()=>void remove(m)}>Delete</button>}</div>}</article>)}{!visible.length&&<p>No messages in this view.</p>}</div><div className="row">{hasMore&&<button onClick={()=>void loadMessages(active,cursor??undefined)}>Load next 50</button>}<button onClick={()=>void loadMessages(active,messages[messages.length-1]?.id)}>Refresh newer</button></div><form onSubmit={e=>void send(e)}>{reply&&<div className="chip">Replying to {(reply.body??"Attachment").slice(0,70)} <button type="button" onClick={()=>setReply(null)}>Cancel</button></div>}<label>Message<textarea rows={2} value={draft} maxLength={4000} onChange={e=>setDraft(e.target.value)}/></label><label>Attachment (optional, up to 25 MB)<input type="file" onChange={e=>setFile(e.currentTarget.files?.[0]??null)}/></label><button className="primary" disabled={busy||(!draft.trim()&&!file)}>{busy?"Sending…":"Send"}</button></form></>:<p>Select a conversation on the left or search for a member to start messaging.</p>}</section>
<aside className="panel sticky"><h2>Find in this conversation</h2><label>Filter loaded messages<input value={localFilter} onChange={e=>setLocalFilter(e.target.value)} placeholder="Search"/></label><div className="callout"><strong>Security state</strong><p>This release uses the existing authenticated messaging API. Do not send sensitive information under an assumption of end-to-end encryption.</p></div><p className="sub">Messages load in pages of 50. Search filters the messages already loaded in this browser.</p></aside></div>{error&&<div role="alert" className="status danger">{error} <button onClick={()=>setError("")}>Dismiss</button></div>}</>}</main>
}
