import {useState} from "react";
import {Pressable,Text,TextInput,View} from "react-native";
import {router} from "expo-router";
import {Screen} from "@bazaara/mobile-ui";
import {groceryApi,groceryCartRequest} from "@/lib/api";
import {groceryMoney,type ProductSummary} from "@/lib/grocery";
import {groceryStyles as s} from "@/ui/theme";

type Plan={title:string;people:number;disclaimer:string;ingredients:Array<{label:string;quantity:number;note:string|null;products:ProductSummary[]}>};
export default function GroceryPlanner(){const[prompt,setPrompt]=useState('Jollof rice for 4 people');const[plan,setPlan]=useState<Plan|null>(null);const[error,setError]=useState('');const[busy,setBusy]=useState(false);async function make(){setBusy(true);setError('');try{setPlan(await groceryApi.post<Plan>('/v1/grocery/planner',{prompt:prompt.trim()}))}catch(e){setError(e instanceof Error?e.message:'Could not build a plan')}finally{setBusy(false)}}async function add(product:ProductSummary,qty:number){if(!product.defaultVariantId)return;try{await groceryCartRequest('/v1/grocery/cart/items',{method:'POST',body:{variantId:product.defaultVariantId,quantity:Math.min(99,Math.max(1,qty))}})}catch(e){setError(e instanceof Error?e.message:'Could not add planned item')}}return <Screen tabBarSafe={false}><Text style={s.h1}>Smart grocery planner</Text><Text style={s.p}>Describe the meal or household need. Suggestions stay editable and never auto-buy anything.</Text><TextInput style={[s.input,{marginTop:14,minHeight:78,textAlignVertical:'top'}]} multiline value={prompt} onChangeText={setPrompt} placeholder="e.g. breakfast for a family of 5 for 3 days" placeholderTextColor="#777D77"/><Pressable style={[s.button,{marginTop:10}]} disabled={busy||prompt.trim().length<2} onPress={()=>void make()}><Text style={s.buttonText}>{busy?'Planning…':'Build plan'}</Text></Pressable>{error?<Text style={[s.error,{marginTop:8}]}>{error}</Text>:null}{plan?<><Text style={[s.h2,{marginTop:18}]}>{plan.title}</Text><Text style={s.small}>{plan.disclaimer}</Text>{plan.ingredients.map((i,idx)=><View key={`${i.label}-${idx}`} style={[s.card,{marginTop:10}]}><Text style={s.name}>{i.quantity} × {i.label}</Text>{i.note?<Text style={s.small}>{i.note}</Text>:null}{i.products[0]?<><Text style={[s.p,{marginTop:6}]}>Suggested: {i.products[0].title} · {groceryMoney(i.products[0].priceMinor)}</Text><Pressable style={[s.secondary,{marginTop:7}]} onPress={()=>void add(i.products[0],i.quantity)}><Text style={s.secondaryText}>Add suggestion</Text></Pressable></>:<Text style={s.small}>No matching Grocery item is currently available.</Text>}</View>)}<Pressable style={[s.button,{marginTop:14}]} onPress={()=>router.push('/cart')}><Text style={s.buttonText}>Review basket</Text></Pressable></>:null}</Screen>}
