import {useCallback,useEffect,useMemo,useState} from "react";
import {Pressable,Text,TextInput,View} from "react-native";
import {Screen} from "@bazaara/mobile-ui";
import {groceryApi} from "@/lib/api";
import {groceryStyles as s} from "@/ui/theme";

type Message={id:string;kind:string;body:string;createdAt:string};
type SupportCase={id:string;category:string;subject:string;description:string;status:string;priority:string;messages:Message[]};
const CATEGORIES=["ORDER","DELIVERY","PAYMENT","RETURN","PRODUCT","ACCOUNT","OTHER"] as const;
export default function GrocerySupport(){
 const[cases,setCases]=useState<SupportCase[]>([]);const[selected,setSelected]=useState("");const[lastSync,setLastSync]=useState<Date|null>(null);const[category,setCategory]=useState<(typeof CATEGORIES)[number]>("ORDER");const[subject,setSubject]=useState("");const[description,setDescription]=useState("");const[reply,setReply]=useState("");const[busy,setBusy]=useState("");const[error,setError]=useState("");
 const current=useMemo(()=>cases.find(item=>item.id===selected),[cases,selected]);
 const load=useCallback(async()=>{try{const body=await groceryApi.get<{cases:SupportCase[]}>("/v1/support/cases",{cache:"no-store"});setCases(body.cases);setLastSync(new Date());setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load support cases")}},[]);useEffect(()=>{void load();const timer=setInterval(()=>void load(),7000);return()=>clearInterval(timer)},[load]);
 async function create(){if(!subject.trim()||!description.trim())return;setBusy("create");try{const body=await groceryApi.post<{case:SupportCase}>("/v1/support/cases",{category,subject:subject.trim(),description:description.trim()});setCases(v=>[body.case,...v]);setSelected(body.case.id);setSubject("");setDescription("");setError("")}catch(e){setError(e instanceof Error?e.message:"Could not create support case")}finally{setBusy("")}}
 async function send(){if(!current||!reply.trim())return;setBusy("reply");try{const body=await groceryApi.post<{case:SupportCase}>(`/v1/support/cases/${encodeURIComponent(current.id)}/messages`,{body:reply.trim()});setCases(v=>v.map(item=>item.id===body.case.id?body.case:item));setReply("");setError("")}catch(e){setError(e instanceof Error?e.message:"Could not send message")}finally{setBusy("")}}
 async function escalate(){if(!current)return;setBusy("escalate");try{const body=await groceryApi.post<{case:SupportCase}>(`/v1/support/cases/${encodeURIComponent(current.id)}/escalate`,{reason:"Customer requested additional review in Grocery"});setCases(v=>v.map(item=>item.id===body.case.id?body.case:item));setError("")}catch(e){setError(e instanceof Error?e.message:"Could not escalate support case")}finally{setBusy("")}}
 return <Screen><Text style={s.h1}>Help & live support</Text><Text style={s.p}>For a specific Grocery order, use the order page first so picking and refund context stays attached to that order.</Text>{lastSync?<Text style={[s.small,{marginTop:6}]}>● LIVE SYNC · {lastSync.toLocaleTimeString("en-NG")}</Text>:null}{error?<Text style={[s.error,{marginTop:10}]}>{error}</Text>:null}{current?<><Pressable style={{marginTop:12}} onPress={()=>setSelected("")}><Text style={s.price}>‹ All support cases</Text></Pressable><View style={[s.card,{marginTop:10}]}><View style={s.row}><Text style={[s.name,{flex:1}]}>{current.subject}</Text><Text style={s.status}>{current.status.replace(/_/g," ")}</Text></View><Text style={s.small}>{current.category} · {current.priority}</Text>{current.messages.map(message=><View key={message.id} style={[s.card,{marginTop:8}]}><Text style={s.small}>{message.kind} · {new Date(message.createdAt).toLocaleString("en-NG")}</Text><Text style={s.p}>{message.body}</Text></View>)}{current.status!=="CLOSED"?<><TextInput style={[s.input,{marginTop:10,minHeight:72,textAlignVertical:"top"}]} multiline value={reply} onChangeText={setReply} placeholder="Write a reply" placeholderTextColor="#777D77"/><Pressable style={[s.button,{marginTop:8}]} disabled={busy==="reply"} onPress={()=>void send()}><Text style={s.buttonText}>{busy==="reply"?"Sending…":"Send reply"}</Text></Pressable><Pressable style={[s.secondary,{marginTop:8}]} disabled={busy==="escalate"} onPress={()=>void escalate()}><Text style={s.secondaryText}>{busy==="escalate"?"Escalating…":"Request additional review"}</Text></Pressable></>:null}</View></>:<><View style={[s.card,{marginTop:14}]}><Text style={s.h2}>Start a support case</Text><View style={[s.wrap,{marginTop:8}]}>{CATEGORIES.map(item=><Pressable key={item} style={[s.pill,category===item&&s.pillActive]} onPress={()=>setCategory(item)}><Text style={[s.pillText,category===item&&s.pillTextActive]}>{item}</Text></Pressable>)}</View><TextInput style={[s.input,{marginTop:10}]} value={subject} onChangeText={setSubject} placeholder="Subject" placeholderTextColor="#777D77"/><TextInput style={[s.input,{marginTop:8,minHeight:88,textAlignVertical:"top"}]} multiline value={description} onChangeText={setDescription} placeholder="Describe what happened" placeholderTextColor="#777D77"/><Pressable style={[s.button,{marginTop:10}]} disabled={busy==="create"} onPress={()=>void create()}><Text style={s.buttonText}>{busy==="create"?"Creating…":"Create case & start live chat"}</Text></Pressable></View><Text style={[s.h2,{marginTop:18}]}>Your cases</Text>{cases.length===0?<Text style={s.p}>No support cases yet.</Text>:cases.map(item=><Pressable key={item.id} style={s.card} onPress={()=>setSelected(item.id)}><View style={s.row}><View style={{flex:1}}><Text style={s.name}>{item.subject}</Text><Text style={s.small}>{item.category} · {item.status.replace(/_/g," ")}</Text></View><Text style={s.price}>›</Text></View></Pressable>)}</>}</Screen>
}
