import Link from 'next/link';
import type { Metadata } from 'next';
export const metadata:Metadata={title:'How this Search build handles data | BAZAARA',description:'Technical data-handling information for BAZAARA Search V8.6.',robots:{index:false,follow:false}};
export default function SearchDataPage(){return <main style={{minHeight:'100dvh',padding:'clamp(24px,5vw,68px)',background:'radial-gradient(circle at 95% 0, #24164f, transparent 40%),linear-gradient(145deg,#0b1020,#111c31)',color:'#e8f0ff',fontFamily:'system-ui,sans-serif'}}>
 <article style={{maxWidth:810,margin:'0 auto',lineHeight:1.65}}><Link href="/" style={{color:'#8be9ff',textDecoration:'none'}}>← BAZAARA Search</Link><p style={{letterSpacing:'.13em',fontSize:11,marginTop:44,color:'#c5a9ff',fontWeight:750}}>TRANSPARENT PRODUCT DOCUMENTATION</p><h1 style={{fontSize:'clamp(30px,5vw,52px)',letterSpacing:'-.05em',lineHeight:1.1}}>How Search V8.6 handles your data</h1><p style={{fontSize:17,color:'#c0cbe1'}}>This explains the features in the supplied Search build. It is not a replacement for approved legal terms, a deployment-specific privacy policy or a provider privacy notice.</p>
 <h2>Submitting a search</h2><p>When you choose Search, your query and supported search options pass through the Search web application’s same-origin route to its configured Search API and external search provider. Provider terms, deployment logs and retention depend on how the system is configured.</p>
 <h2>Browser-saved history</h2><p>Local search history is off by default. If you enable it, this browser stores at most 80 recent unique terms. The browser can display, export and clear that history. Disabling history stops future saving but does not silently erase existing entries. Clearing local history does not remove requests or records held by servers, providers or BazID.</p>
 <h2>Visual search and local files</h2><p>BazLens images are transmitted only when you explicitly request image analysis. The V8.6 text attachment tool reads TXT, Markdown, CSV and JSON files locally; only the excerpt you choose to insert is sent when you submit your search. Uploaded PDF or DOCX indexing is not provided by this release.</p>
 <h2>Voice input and AI</h2><p>Voice recognition depends on browser support and permission. The browser’s speech recognition implementation may use third-party infrastructure. Spoken excerpts use the browser’s speech synthesis. AI-generated image creation is not represented as available without a connected service; an optional AI Studio link is a separate product handoff.</p>
 <h2>Region preferences</h2><p>Where a trusted deployment supplies a country code, Search can use it as an approximate network country. Otherwise it may fall back to the browser locale. Network region can be inaccurate and is not precise geolocation.</p>
 <h2>Account and legal documents</h2><p>BazID manages supported BAZAARA account features separately. This release does not claim to synchronize local Search history with BazID or implement account-wide provider data deletion. Publish deployment-approved privacy and terms documents through your legal and product teams before a public launch.</p>
 <p style={{paddingTop:24,borderTop:'1px solid #46526c',fontSize:12,color:'#9daccc'}}>Product implementation note · BAZAARA Search V8.6 · not a legal policy.</p></article></main>}
