import type { FastifyInstance } from "fastify";
import { z } from "zod";
import { audit } from "../audit.js";
import { requireAuth } from "../auth.js";
import { requirePermission } from "../authorization.js";
import { adjustInventory, bulkImportProducts, businessShoppingContext, createManagedProduct, createManagedVariant, createMerchantPromotion, listManagedProducts, listMerchantPromotions, merchantOrganization, setStoreFulfillment, updateManagedProduct, updateManagedVariant, updateMerchantPromotion } from "./catalog-management.js";

const money = z.coerce.number().int().min(0).max(Number.MAX_SAFE_INTEGER);
const variantSchema = z.object({ sku: z.string().trim().min(1).max(80), title: z.string().trim().min(1).max(160), attributes: z.unknown().optional(), priceMinor: money, compareAtPriceMinor: money.nullish(), currency: z.string().trim().regex(/^[A-Z]{3}$/).optional(), active: z.boolean().optional() });
const mediaSchema = z.object({ type: z.enum(["IMAGE", "VIDEO"]).default("IMAGE"), url: z.string().url().refine((url) => url.startsWith("https://"), "Media must use HTTPS"), alt: z.string().trim().min(1).max(180), sortOrder: z.coerce.number().int().min(0).max(1000).optional() });
const productSchema = z.object({ slug: z.string().trim().max(100).optional(), title: z.string().trim().min(2).max(200), shortDescription: z.string().trim().max(400).nullish(), description: z.string().trim().min(2).max(10000), categoryId: z.string().min(1), brandId: z.string().min(1).nullish(), currency: z.string().trim().regex(/^[A-Z]{3}$/).default("NGN"), priceMinor: money, compareAtPriceMinor: money.nullish(), status: z.enum(["DRAFT", "ACTIVE", "ARCHIVED"]).default("DRAFT"), featured: z.boolean().default(false), variants: z.array(variantSchema).min(1).max(100), media: z.array(mediaSchema).max(30).optional() });
const productUpdateSchema = productSchema.partial({ variants: true }).extend({ title: productSchema.shape.title, description: productSchema.shape.description, categoryId: productSchema.shape.categoryId, priceMinor: productSchema.shape.priceMinor });
const inventorySchema = z.object({ storeId: z.string().min(1), delta: z.coerce.number().int().min(-1_000_000).max(1_000_000).refine((n) => n !== 0, "Adjustment cannot be zero"), reason: z.enum(["RECEIPT", "SALE_CORRECTION", "RETURN", "DAMAGE", "COUNT", "TRANSFER", "OTHER"]), note: z.string().trim().max(500).optional() });
const fulfillmentSchema = z.object({ modes: z.array(z.enum(["STANDARD", "PICKUP", "SAME_DAY", "NEXT_DAY"])).min(1).max(4) });
const promotionSchema = z.object({ code: z.string().trim().min(2).max(40).optional(), name: z.string().trim().min(2).max(160), description: z.string().trim().max(1000).optional(), type: z.enum(["PERCENTAGE", "FIXED_AMOUNT", "FREE_DELIVERY"]), scope: z.enum(["PLATFORM", "CATEGORY", "PRODUCT", "SELLER"]).default("SELLER"), status: z.enum(["DRAFT", "ACTIVE", "PAUSED", "EXPIRED"]).default("DRAFT"), activation: z.enum(["CODE", "AUTOMATIC"]).default("CODE"), priority: z.coerce.number().int().min(1).max(10000).default(100), percentOff: z.coerce.number().int().min(1).max(100).nullish(), amountOffMinor: money.nullish(), maxDiscountMinor: money.nullish(), minimumSubtotalMinor: money.default(0), budgetMinor: money.nullish(), usageLimit: z.coerce.number().int().min(1).nullish(), perUserLimit: z.coerce.number().int().min(1).max(100).default(1), firstOrderOnly: z.boolean().default(false), customerSegments: z.array(z.enum(["FIRST_ORDER", "RETURNING", "GUEST", "VERIFIED", "CONTACT_VERIFIED", "IDENTITY_VERIFIED", "FINANCIAL_VERIFIED", "BUSINESS_VERIFIED"])).default([]), eligibleCountries: z.array(z.string().trim().min(2).max(3)).default([]), eligibleRegions: z.array(z.string().trim().min(2).max(100)).default([]), excludedProductIds: z.array(z.string()).default([]), excludedCategoryIds: z.array(z.string()).default([]), excludedMerchantIds: z.array(z.string()).default([]), allowStacking: z.boolean().default(false), stackGroup: z.string().trim().max(80).nullish(), fraudRules: z.object({ minAccountAgeDays: z.coerce.number().int().min(0).max(3650).optional(), maxAttemptsPerHour: z.coerce.number().int().min(1).max(1000).optional(), requireVerified: z.boolean().optional() }).optional(), categoryId: z.string().nullish(), productId: z.string().nullish(), startsAt: z.coerce.date(), endsAt: z.coerce.date() });

async function authorize(request: Parameters<typeof requirePermission>[0], userId: string, merchantId: string, permission: "catalog.manage" | "inventory.manage" | "promotion.manage") { const context = await merchantOrganization(userId, merchantId); await requirePermission(request, permission, { organizationId: context.organizationId }); return context; }

export async function shoppingCatalogRoutes(app: FastifyInstance) {
  app.get("/v1/business/shopping/catalog/context", async (request) => { const auth = await requireAuth(request); return businessShoppingContext(auth.userId); });
  app.get("/v1/business/shopping/merchants/:merchantId/products", async (request) => { const auth = await requireAuth(request); const { merchantId } = request.params as { merchantId: string }; await authorize(request, auth.userId, merchantId, "catalog.manage"); const query = z.object({ q: z.string().trim().max(120).optional() }).parse(request.query); return listManagedProducts(auth.userId, merchantId, query.q); });
  app.post("/v1/business/shopping/merchants/:merchantId/products", async (request, reply) => { const auth = await requireAuth(request); const { merchantId } = request.params as { merchantId: string }; const context = await authorize(request, auth.userId, merchantId, "catalog.manage"); const result = await createManagedProduct(auth.userId, merchantId, productSchema.parse(request.body)); await audit({ actorUserId: auth.userId, action: "shopping.catalog.product.created", resourceType: "Product", resourceId: result.product.id, requestId: request.id, ipAddress: request.ip, metadata: { organizationId: context.organizationId } }); return reply.code(201).send(result); });
  app.put("/v1/business/shopping/merchants/:merchantId/products/:productId", async (request) => { const auth = await requireAuth(request); const { merchantId, productId } = request.params as { merchantId: string; productId: string }; const context = await authorize(request, auth.userId, merchantId, "catalog.manage"); const result = await updateManagedProduct(auth.userId, merchantId, productId, productUpdateSchema.parse(request.body)); await audit({ actorUserId: auth.userId, action: "shopping.catalog.product.updated", resourceType: "Product", resourceId: productId, requestId: request.id, ipAddress: request.ip, metadata: { organizationId: context.organizationId } }); return result; });
  app.post("/v1/business/shopping/merchants/:merchantId/products/:productId/variants", async (request, reply) => { const auth = await requireAuth(request); const { merchantId, productId } = request.params as { merchantId: string; productId: string }; await authorize(request, auth.userId, merchantId, "catalog.manage"); const result = await createManagedVariant(auth.userId, merchantId, productId, variantSchema.parse(request.body)); await audit({ actorUserId: auth.userId, action: "shopping.catalog.variant.created", resourceType: "ProductVariant", resourceId: result.variant.id, requestId: request.id, ipAddress: request.ip }); return reply.code(201).send(result); });
  app.put("/v1/business/shopping/merchants/:merchantId/products/:productId/variants/:variantId", async (request) => { const auth = await requireAuth(request); const { merchantId, productId, variantId } = request.params as { merchantId: string; productId: string; variantId: string }; await authorize(request, auth.userId, merchantId, "catalog.manage"); const result = await updateManagedVariant(auth.userId, merchantId, productId, variantId, variantSchema.parse(request.body)); await audit({ actorUserId: auth.userId, action: "shopping.catalog.variant.updated", resourceType: "ProductVariant", resourceId: variantId, requestId: request.id, ipAddress: request.ip }); return result; });
  app.post("/v1/business/shopping/merchants/:merchantId/variants/:variantId/inventory-adjustments", async (request, reply) => { const auth = await requireAuth(request); const { merchantId, variantId } = request.params as { merchantId: string; variantId: string }; await authorize(request, auth.userId, merchantId, "inventory.manage"); const input = inventorySchema.parse(request.body); const result = await adjustInventory(auth.userId, merchantId, variantId, input.storeId, input.delta, input.reason, input.note); await audit({ actorUserId: auth.userId, action: "shopping.inventory.adjusted", resourceType: "InventoryItem", resourceId: result.inventory.id, requestId: request.id, ipAddress: request.ip, metadata: { delta: input.delta, reason: input.reason, storeId: input.storeId } }); return reply.code(201).send(result); });
  app.patch("/v1/business/shopping/merchants/:merchantId/stores/:storeId/fulfillment", async (request) => { const auth = await requireAuth(request); const { merchantId, storeId } = request.params as { merchantId: string; storeId: string }; await authorize(request, auth.userId, merchantId, "inventory.manage"); const result = await setStoreFulfillment(auth.userId, merchantId, storeId, fulfillmentSchema.parse(request.body).modes); await audit({ actorUserId: auth.userId, action: "shopping.store.fulfillment.updated", resourceType: "Store", resourceId: storeId, requestId: request.id, ipAddress: request.ip }); return result; });
  app.post("/v1/business/shopping/merchants/:merchantId/products/bulk-import", async (request, reply) => { const auth = await requireAuth(request); const { merchantId } = request.params as { merchantId: string }; await authorize(request, auth.userId, merchantId, "catalog.manage"); const input = z.object({ products: z.array(productSchema).min(1).max(100) }).parse(request.body); const result = await bulkImportProducts(auth.userId, merchantId, input.products); await audit({ actorUserId: auth.userId, action: "shopping.catalog.bulk-imported", resourceType: "Merchant", resourceId: merchantId, requestId: request.id, ipAddress: request.ip, metadata: { imported: result.imported } }); return reply.code(201).send(result); });
  app.post("/v1/business/shopping/catalog/validate", async (request) => { const body = request.body as unknown; const single = productSchema.safeParse(body); if (single.success) return { valid: true, product: single.data }; const batch = z.object({ products: z.array(productSchema).min(1).max(100) }).safeParse(body); if (batch.success) return { valid: true, count: batch.data.products.length }; return { valid: false, issues: single.error.issues.map((issue) => ({ path: issue.path.join("."), message: issue.message })) }; });
  app.get("/v1/business/shopping/merchants/:merchantId/promotions", async (request) => { const auth = await requireAuth(request); const { merchantId } = request.params as { merchantId: string }; await authorize(request, auth.userId, merchantId, "promotion.manage"); return listMerchantPromotions(auth.userId, merchantId); });
  app.post("/v1/business/shopping/merchants/:merchantId/promotions", async (request, reply) => { const auth = await requireAuth(request); const { merchantId } = request.params as { merchantId: string }; await authorize(request, auth.userId, merchantId, "promotion.manage"); const result = await createMerchantPromotion(auth.userId, merchantId, promotionSchema.parse(request.body)); await audit({ actorUserId: auth.userId, action: "shopping.promotion.created", resourceType: "Promotion", resourceId: result.promotion.id, requestId: request.id, ipAddress: request.ip }); return reply.code(201).send(result); });
  app.put("/v1/business/shopping/merchants/:merchantId/promotions/:promotionId", async (request) => { const auth = await requireAuth(request); const { merchantId, promotionId } = request.params as { merchantId: string; promotionId: string }; await authorize(request, auth.userId, merchantId, "promotion.manage"); const result = await updateMerchantPromotion(auth.userId, merchantId, promotionId, promotionSchema.parse(request.body)); await audit({ actorUserId: auth.userId, action: "shopping.promotion.updated", resourceType: "Promotion", resourceId: promotionId, requestId: request.id, ipAddress: request.ip }); return result; });
}
