import {StyleSheet} from "react-native";
import {colors,verticalColors} from "@bazaara/mobile-ui";
export const foodTone=verticalColors.food;
export const foodStyles=StyleSheet.create({
  top:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:10,marginBottom:10},brand:{color:colors.text,fontSize:18,fontWeight:"900",letterSpacing:-.5},brandAccent:{color:foodTone.secondary},h1:{color:colors.text,fontSize:28,lineHeight:32,fontWeight:"900",letterSpacing:-.9},h2:{color:colors.text,fontSize:19,fontWeight:"900",letterSpacing:-.35},p:{color:colors.muted,fontSize:12,lineHeight:18},small:{color:colors.muted2,fontSize:10,lineHeight:14},status:{color:foodTone.secondary,fontSize:10,fontWeight:"900",letterSpacing:.5},
  search:{minHeight:46,borderRadius:16,borderWidth:1,borderColor:colors.borderStrong,backgroundColor:colors.surface,color:colors.text,paddingHorizontal:14,fontSize:13},row:{flexDirection:"row",gap:9,alignItems:"center"},wrap:{flexDirection:"row",gap:8,flexWrap:"wrap"},
  card:{borderWidth:1,borderColor:colors.border,borderRadius:18,backgroundColor:colors.surface,padding:13,gap:6},restaurant:{borderWidth:1,borderColor:colors.border,borderRadius:18,backgroundColor:colors.surface,overflow:"hidden",marginBottom:10,flexDirection:"row",minHeight:106},image:{width:108,height:"100%",minHeight:106,backgroundColor:colors.card},restaurantBody:{flex:1,padding:12,gap:5,justifyContent:"center"},name:{color:colors.text,fontSize:15,fontWeight:"900"},meta:{color:colors.muted,fontSize:10,lineHeight:14},price:{color:foodTone.secondary,fontWeight:"900",fontSize:12},
  button:{minHeight:46,borderRadius:14,backgroundColor:foodTone.primary,alignItems:"center",justifyContent:"center",paddingHorizontal:16},buttonText:{color:"#fff",fontWeight:"900"},secondary:{minHeight:42,borderRadius:13,borderWidth:1,borderColor:colors.borderStrong,backgroundColor:colors.card,alignItems:"center",justifyContent:"center",paddingHorizontal:14},secondaryText:{color:colors.text,fontWeight:"800"},error:{color:"#FCA5A5",lineHeight:19},label:{color:colors.muted,fontSize:10,fontWeight:"800"},input:{minHeight:44,borderRadius:12,borderWidth:1,borderColor:colors.borderStrong,backgroundColor:colors.card,color:colors.text,paddingHorizontal:12},divider:{height:1,backgroundColor:colors.border,marginVertical:7},
  pill:{borderRadius:999,borderWidth:1,borderColor:colors.borderStrong,backgroundColor:colors.surface,paddingHorizontal:11,paddingVertical:7},pillActive:{borderColor:foodTone.secondary,backgroundColor:"rgba(255,122,0,.12)"},pillText:{color:colors.muted,fontSize:10,fontWeight:"800"},pillTextActive:{color:foodTone.secondary},empty:{padding:22,alignItems:"center",gap:8},
  locationChip:{borderWidth:1,borderColor:"rgba(255,122,0,.28)",backgroundColor:"rgba(255,122,0,.085)",borderRadius:18,paddingHorizontal:13,paddingVertical:10,maxWidth:205,minWidth:152},locationLabel:{color:foodTone.secondary,fontSize:8,fontWeight:"900",letterSpacing:.9},locationValue:{color:colors.text,fontSize:12,fontWeight:"900",marginTop:2},locationHint:{color:colors.muted2,fontSize:8,marginTop:2},
  luxeIntro:{borderWidth:1,borderColor:"rgba(255,122,0,.22)",borderRadius:22,backgroundColor:"rgba(255,122,0,.065)",padding:16,marginTop:2},heroEyebrow:{color:foodTone.secondary,fontSize:9,fontWeight:"900",letterSpacing:1.2},heroTitle:{color:colors.text,fontSize:26,lineHeight:29,fontWeight:"900",letterSpacing:-.9,marginTop:5},heroCopy:{color:colors.muted,fontSize:11,lineHeight:16,marginTop:6},
  quickRail:{gap:8,paddingTop:11,paddingBottom:1},quickCard:{width:116,minHeight:68,borderWidth:1,borderColor:colors.border,borderRadius:16,backgroundColor:colors.surface,padding:11,justifyContent:"flex-end"},quickTitle:{color:colors.text,fontSize:12,fontWeight:"900"},quickHint:{color:colors.muted2,fontSize:9,marginTop:2},
  categoryCard:{width:94,minHeight:82,borderWidth:1,borderColor:colors.border,borderRadius:18,backgroundColor:colors.surface,padding:11,justifyContent:"space-between"},categoryGlyph:{color:foodTone.secondary,fontSize:22,fontWeight:"900"},categoryTitle:{color:colors.text,fontSize:11,fontWeight:"900"},categoryHint:{color:colors.muted2,fontSize:8},
  demandCard:{width:250,borderWidth:1,borderColor:colors.border,borderRadius:18,backgroundColor:colors.surface,padding:13},demandRank:{color:foodTone.secondary,fontSize:11,fontWeight:"900"},
  menuRow:{minHeight:68,borderBottomWidth:1,borderBottomColor:colors.border,flexDirection:"row",alignItems:"center",gap:12,paddingVertical:10},menuIcon:{width:38,height:38,borderRadius:12,backgroundColor:colors.card,alignItems:"center",justifyContent:"center"},menuIconText:{color:foodTone.secondary,fontWeight:"900",fontSize:16},menuTitle:{color:colors.text,fontSize:14,fontWeight:"800"},menuCopy:{color:colors.muted2,fontSize:9,marginTop:3},menuChevron:{color:colors.muted,fontSize:24},
  primeCard:{borderRadius:22,borderWidth:1,borderColor:"rgba(255,122,0,.35)",backgroundColor:"rgba(255,122,0,.08)",padding:17,gap:8},primeTitle:{color:colors.text,fontSize:22,fontWeight:"900",letterSpacing:-.6},primeBadge:{alignSelf:"flex-start",borderRadius:999,backgroundColor:foodTone.secondary,paddingHorizontal:9,paddingVertical:5},primeBadgeText:{color:"#0A0D12",fontSize:9,fontWeight:"900"},

  paymentCard:{borderWidth:1,borderColor:colors.border,borderRadius:16,backgroundColor:colors.surface,padding:13,marginTop:9,flexDirection:"row",alignItems:"center",gap:11},paymentCardActive:{borderColor:foodTone.secondary,backgroundColor:"rgba(255,122,0,.09)"},paymentCardDisabled:{opacity:.45},paymentIcon:{width:38,height:38,borderRadius:12,backgroundColor:"rgba(255,122,0,.12)",alignItems:"center",justifyContent:"center"},paymentIconText:{color:foodTone.secondary,fontSize:12,fontWeight:"900"},paymentCheck:{color:foodTone.secondary,fontWeight:"900",fontSize:16},
  locationMapPreview:{height:238,borderRadius:28,overflow:"hidden",borderWidth:1,borderColor:"rgba(255,122,0,.24)",backgroundColor:"#111820",position:"relative",marginBottom:12},settingsToggleRow:{minHeight:66,borderBottomWidth:1,borderBottomColor:colors.border,flexDirection:"row",alignItems:"center",gap:12,paddingVertical:10},locationMapGrid:{position:"absolute",left:0,right:0,top:0,bottom:0,opacity:.55,backgroundColor:"#111820",borderWidth:18,borderColor:"rgba(255,255,255,.015)"},locationMapPin:{position:"absolute",left:"44%",top:"34%",width:74,height:74,borderRadius:37,backgroundColor:foodTone.secondary,alignItems:"center",justifyContent:"center",borderWidth:8,borderColor:"rgba(255,122,0,.18)"},locationMapPinText:{color:"#0A0D12",fontSize:34,fontWeight:"900"},locationMapTitle:{position:"absolute",alignSelf:"center",top:20,left:78,right:78,backgroundColor:"rgba(7,10,14,.88)",borderRadius:999,paddingHorizontal:15,paddingVertical:9},locationMapTitleText:{color:"#fff",fontSize:12,fontWeight:"900",textAlign:"center"},locationMapBrand:{position:"absolute",left:14,bottom:14},locationMapBrandMain:{color:"#fff",fontSize:14,fontWeight:"900",letterSpacing:.4},locationMapBrandSub:{color:foodTone.secondary,fontSize:7,fontWeight:"900",letterSpacing:1.2,marginTop:1},locationClose:{position:"absolute",right:14,top:14,width:40,height:40,borderRadius:20,backgroundColor:"rgba(255,255,255,.92)",alignItems:"center",justifyContent:"center"},locationCloseText:{color:"#111",fontSize:26,lineHeight:28},locationSheetBody:{paddingBottom:34},locationSheetEyebrow:{color:foodTone.secondary,fontSize:9,fontWeight:"900",letterSpacing:1.2},locationSheetTitle:{color:colors.text,fontSize:29,lineHeight:32,fontWeight:"900",letterSpacing:-1,marginTop:6},locationSheetCopy:{color:colors.muted,fontSize:11,lineHeight:16,marginTop:6},locationCurrentRow:{marginTop:18,minHeight:72,borderRadius:18,borderWidth:1,borderColor:"rgba(255,122,0,.24)",backgroundColor:"rgba(255,122,0,.065)",padding:13,flexDirection:"row",alignItems:"center",gap:11},locationSavedHead:{marginTop:22,marginBottom:5,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},locationSavedTitle:{color:colors.text,fontSize:14,fontWeight:"900"},locationSavedCount:{color:colors.muted2,fontSize:9},locationSavedRow:{minHeight:72,borderBottomWidth:1,borderBottomColor:colors.border,flexDirection:"row",alignItems:"center",gap:11,paddingVertical:12},locationRowIcon:{color:foodTone.secondary,fontSize:22,width:34,textAlign:"center",fontWeight:"900"},locationRowTitle:{color:colors.text,fontSize:13,fontWeight:"900"},locationRowCopy:{color:colors.muted,fontSize:9,lineHeight:13,marginTop:3},locationRowAction:{color:foodTone.secondary,fontSize:11,fontWeight:"900"},
});
