import { useCallback, useEffect, useMemo, useState } from "react";
import { Linking, Pressable, Switch, Text, TextInput, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import * as Crypto from "expo-crypto";
import * as SecureStore from "expo-secure-store";
import * as Location from "expo-location";
import { EmptyState, Screen } from "@bazaara/mobile-ui";
import { foodCartRequest } from "@/lib/api";
import { clearGuestCartToken } from "@/lib/guest-cart";
import { isSignedIn, signInWithBazId } from "@/lib/auth";
import { foodMoney, type FoodCart, type FoodOrder } from "@/lib/food";
import { foodStyles as s } from "@/ui/theme";

type FoodPaymentMethod="BAZAARA_PAY"|"PAYSTACK_CARD"|"PAYSTACK_BANK";
type FoodPaymentCapabilities={currency:string;walletBalanceMinor:number;walletPinSet:boolean;walletPinLockedUntil:string|null;methods:Array<{key:FoodPaymentMethod;label:string;available:boolean;reason:string|null}>};
const PIN_PREFIX = "bazaara.food.delivery-pin.";
const WALLET_WEB_BASE_URL = process.env.EXPO_PUBLIC_WALLET_WEB_BASE_URL ?? "http://10.0.2.2:3010";
export default function FoodCheckout() {
  const { slug } = useLocalSearchParams<{ slug: string }>();
  const [cart,setCart]=useState<FoodCart|null>(null); const [signed,setSigned]=useState<boolean|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [paymentCapabilities,setPaymentCapabilities]=useState<FoodPaymentCapabilities|null>(null); const [paymentMethod,setPaymentMethod]=useState<FoodPaymentMethod>("BAZAARA_PAY"); const [walletPin,setWalletPin]=useState("");
  const [fullName,setFullName]=useState(""); const [phone,setPhone]=useState(""); const [region,setRegion]=useState("Lagos"); const [city,setCity]=useState("Lagos"); const [street,setStreet]=useState(""); const [landmark,setLandmark]=useState(""); const [deliveryPoint,setDeliveryPoint]=useState<{latitude:number;longitude:number}|null>(null); const [locationBusy,setLocationBusy]=useState(false);
  const [tip,setTip]=useState("0"); const [promo,setPromo]=useState(""); const [note,setNote]=useState(""); const [gift,setGift]=useState(false); const [recipientName,setRecipientName]=useState(""); const [recipientPhone,setRecipientPhone]=useState(""); const [giftMessage,setGiftMessage]=useState(""); const [schedule,setSchedule]=useState<"ASAP"|"60"|"120">("ASAP");
  const load=useCallback(async()=>{if(!slug)return;try{const [body,auth]=await Promise.all([foodCartRequest<{cart:FoodCart}>(`/v1/food/restaurants/${encodeURIComponent(slug)}/cart`,{method:"GET",cache:"no-store"}),isSignedIn()]);setCart(body.cart);setSigned(auth);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load checkout")}},[slug]);useEffect(()=>{void load()},[load]);
  useEffect(()=>{if(signed!==true||!cart)return;void foodCartRequest<FoodPaymentCapabilities>("/v1/food/payment-capabilities",{method:"GET",cache:"no-store"}).then(cap=>{setPaymentCapabilities(cap);const usable=(m:{key:FoodPaymentMethod;available:boolean})=>m.available&&(m.key!=="BAZAARA_PAY"||cap.walletBalanceMinor>=cart.totalMinor);const current=cap.methods.find(m=>m.key===paymentMethod);if(!current||!usable(current)){const next=cap.methods.find(usable);if(next)setPaymentMethod(next.key)}}).catch(e=>setError(e instanceof Error?e.message:"Could not load payment methods"))},[signed,cart?.totalMinor]);
  const scheduledFor=useMemo(()=>schedule==="ASAP"?null:new Date(Date.now()+Number(schedule)*60_000).toISOString(),[schedule]);
  async function signIn(){setBusy(true);try{const result=await signInWithBazId(`/checkout/${slug}`);if(result.ok){setSigned(true);await load()}}catch(e){setError(e instanceof Error?e.message:"BazID sign-in failed")}finally{setBusy(false)}}
  async function captureDeliveryPoint(){setLocationBusy(true);setError("");try{const permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=="granted")throw new Error("Location permission is required to add a delivery pin.");const current=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.High});setDeliveryPoint({latitude:current.coords.latitude,longitude:current.coords.longitude});}catch(e){setError(e instanceof Error?e.message:"Could not capture delivery pin")}finally{setLocationBusy(false)}}
  async function place(){if(!slug||!cart)return;if(cart.fulfillmentType==="DELIVERY"&&(!fullName.trim()||!phone.trim()||!region.trim()||!city.trim()||!street.trim())){setError("Name, phone, state, city and street are required for delivery.");return}if(gift&&(!recipientName.trim()||!recipientPhone.trim())){setError("Recipient name and phone are required for a gift order.");return}setBusy(true);setError("");try{
    const bodyPrefs:{cart:FoodCart}=await foodCartRequest(`/v1/food/restaurants/${encodeURIComponent(slug)}/cart/preferences`,{method:"PATCH",body:{deliveryAddress:cart.fulfillmentType==="DELIVERY"?{fullName:fullName.trim(),phone:phone.trim(),country:"NG",region:region.trim(),city:city.trim(),street:street.trim(),landmark:landmark.trim()||undefined,latitude:deliveryPoint?.latitude,longitude:deliveryPoint?.longitude}:null,scheduledFor,tipMinor:Math.max(0,Math.round((Number(tip)||0)*100)),promoCode:promo.trim()||null,note:note.trim()||null,isGift:gift,recipientName:gift?recipientName.trim():null,recipientPhone:gift?recipientPhone.trim():null,giftMessage:gift?(giftMessage.trim()||null):null}});setCart(bodyPrefs.cart);
    const body=await foodCartRequest<{order:FoodOrder&{deliveryPin?:string|null}}>(`/v1/food/restaurants/${encodeURIComponent(slug)}/orders`,{method:"POST",body:{paymentMethod,walletPin:paymentMethod==="BAZAARA_PAY"?walletPin:undefined},headers:{"idempotency-key":`food-${Crypto.randomUUID()}`}});setWalletPin("");
    if(body.order.deliveryPin)await SecureStore.setItemAsync(`${PIN_PREFIX}${body.order.id}`,body.order.deliveryPin);
    await clearGuestCartToken();
    if(paymentMethod==="PAYSTACK_CARD"||paymentMethod==="PAYSTACK_BANK"){
      try{
        const payment=await foodCartRequest<{checkoutUrl:string|null;alreadyPaid:boolean;paymentStatus:string}>(`/v1/food/orders/${encodeURIComponent(body.order.id)}/payment/initialize`,{method:"POST",body:{},headers:{"idempotency-key":`food-payment-${Crypto.randomUUID()}`}});
        if(payment.checkoutUrl)await Linking.openURL(payment.checkoutUrl);
      }catch(paymentError){
        setError(paymentError instanceof Error?paymentError.message:"Could not open secure payment");
      }
    }
    router.replace({pathname:"/order/[id]",params:{id:body.order.id}});
  }catch(e){setError(e instanceof Error?e.message:"Could not place order")}finally{if(paymentMethod==="BAZAARA_PAY")setWalletPin("");setBusy(false)}}
  if(!cart||signed===null)return <Screen tabBarSafe={false}><EmptyState title="Checkout" message={error||"Preparing your order…"}/></Screen>;
  if(!cart.items.length)return <Screen tabBarSafe={false}><EmptyState title="Your basket is empty" message="Add dishes before checkout."/></Screen>;
  if(!signed)return <Screen tabBarSafe={false}><Text style={s.h1}>Sign in to checkout</Text><Text style={s.p}>Your restaurant basket stays on this device. BazID is required only when you place the order.</Text>{error?<Text style={s.error}>{error}</Text>:null}<Pressable style={[s.button,{marginTop:18}]} disabled={busy} onPress={()=>void signIn()}><Text style={s.buttonText}>{busy?"Connecting…":"Continue with BazID"}</Text></Pressable></Screen>;
  return <Screen tabBarSafe={false}><Text style={s.h1}>Checkout</Text><Text style={s.p}>{cart.restaurant.name} · {cart.fulfillmentType.toLowerCase()}</Text>{error?<Text style={[s.error,{marginTop:10}]}>{error}</Text>:null}
    {cart.fulfillmentType==="DELIVERY"?<View style={[s.card,{marginTop:16}]}><Text style={s.h2}>Delivery address</Text><Field label="Full name" value={fullName} onChange={setFullName}/><Field label="Phone" value={phone} onChange={setPhone} keyboard="phone-pad"/><Field label="State / FCT" value={region} onChange={setRegion}/><Field label="City / town" value={city} onChange={setCity}/><Field label="Street address" value={street} onChange={setStreet}/><Field label="Landmark (optional)" value={landmark} onChange={setLandmark}/><Pressable style={[s.secondary,{marginTop:12}]} disabled={locationBusy} onPress={()=>void captureDeliveryPoint()}><Text style={s.secondaryText}>{locationBusy?"Capturing delivery pin…":deliveryPoint?"Update delivery pin":"Use my current delivery pin"}</Text></Pressable><Text style={[s.small,{marginTop:8}]}>{deliveryPoint?"Delivery pin captured for smarter GO routing and handoff.":"Add a location pin so the courier can navigate to the exact handoff point."}</Text></View>:<View style={[s.card,{marginTop:16}]}><Text style={s.h2}>Pickup</Text><Text style={s.p}>Collect directly from the restaurant. No delivery fee is charged.</Text></View>}
    {cart.restaurant.scheduledEnabled?<View style={[s.card,{marginTop:12}]}><Text style={s.h2}>When?</Text><View style={[s.wrap,{marginTop:10}]}>{(["ASAP","60","120"] as const).map(v=><Pressable key={v} style={[s.pill,schedule===v&&s.pillActive]} onPress={()=>setSchedule(v)}><Text style={[s.pillText,schedule===v&&s.pillTextActive]}>{v==="ASAP"?"ASAP":v==="60"?"In 1 hour":"In 2 hours"}</Text></Pressable>)}</View></View>:null}
    <View style={[s.card,{marginTop:12}]}><Text style={s.h2}>Extras</Text><Field label="Tip (₦)" value={tip} onChange={(v)=>setTip(v.replace(/[^0-9.]/g,""))} keyboard="numeric"/><Field label="Promotion code" value={promo} onChange={setPromo} autoCap/><Field label="Order note" value={note} onChange={setNote} multiline/><View style={[s.row,{justifyContent:"space-between",marginTop:8}]}><Text style={s.p}>Send as a gift</Text><Switch value={gift} onValueChange={setGift}/></View>{gift?<><Field label="Recipient name" value={recipientName} onChange={setRecipientName}/><Field label="Recipient phone" value={recipientPhone} onChange={setRecipientPhone} keyboard="phone-pad"/><Field label="Gift message" value={giftMessage} onChange={setGiftMessage} multiline/></>:null}</View>
    <View style={[s.card,{marginTop:12}]}><Text style={s.h2}>Payment</Text><Text style={[s.small,{marginTop:4}]}>No cash on delivery. Choose Wallet, card or bank transfer.</Text>{paymentCapabilities?.methods.map(method=>{const enoughWallet=method.key!=="BAZAARA_PAY"||paymentCapabilities.walletBalanceMinor>=cart.totalMinor;const available=method.available&&enoughWallet;const copy=method.key==="BAZAARA_PAY"?`Balance ${foodMoney(paymentCapabilities.walletBalanceMinor,paymentCapabilities.currency)}`:method.key==="PAYSTACK_CARD"?"Visa, Mastercard and supported cards":"Secure bank / transfer checkout";return <Pressable key={method.key} disabled={!available||busy} style={[s.paymentCard,paymentMethod===method.key&&s.paymentCardActive,!available&&s.paymentCardDisabled]} onPress={()=>setPaymentMethod(method.key)}><View style={s.paymentIcon}><Text style={s.paymentIconText}>{method.key==="BAZAARA_PAY"?"W":method.key==="PAYSTACK_CARD"?"CARD":"BANK"}</Text></View><View style={{flex:1}}><Text style={s.name}>{method.label}</Text><Text style={s.small}>{available?copy:method.key==="BAZAARA_PAY"?"Insufficient Wallet balance":method.reason||"Unavailable"}</Text></View><Text style={s.paymentCheck}>{paymentMethod===method.key?"✓":""}</Text></Pressable>})??<Text style={[s.p,{marginTop:8}]}>Loading payment methods…</Text>}{paymentMethod==="BAZAARA_PAY"?<View style={{marginTop:12}}><Text style={s.status}>WALLET SECURITY</Text>{paymentCapabilities?.walletPinSet?<><TextInput style={[s.input,{marginTop:8,letterSpacing:8,textAlign:"center"}]} secureTextEntry keyboardType="number-pad" maxLength={6} placeholder="6-digit Wallet PIN" placeholderTextColor="#7E8DA6" value={walletPin} onChangeText={value=>setWalletPin(value.replace(/\D/g,"").slice(0,6))}/><Text style={[s.small,{marginTop:7}]}>Your PIN is verified by Wallet before the order is confirmed. It is never stored in Food checkout.</Text></>:<><Text style={[s.small,{marginTop:7}]}>Set a 6-digit Wallet PIN before using your balance for orders.</Text><Pressable style={[s.secondary,{marginTop:8}]} onPress={()=>void Linking.openURL(WALLET_WEB_BASE_URL)}><Text style={s.secondaryText}>Open Wallet</Text></Pressable></>}</View>:null}</View>
    <View style={[s.card,{marginTop:12}]}><View style={[s.row,{justifyContent:"space-between"}]}><Text style={s.p}>Subtotal</Text><Text style={s.p}>{foodMoney(cart.subtotalMinor)}</Text></View><View style={[s.row,{justifyContent:"space-between"}]}><Text style={s.p}>Current total</Text><Text style={s.h2}>{foodMoney(cart.totalMinor)}</Text></View><Text style={[s.small,{marginTop:8}]}>Payment must be confirmed before the restaurant can accept the order.</Text><Pressable style={[s.button,{marginTop:14}]} disabled={busy||!paymentCapabilities||(paymentMethod==="BAZAARA_PAY"&&(paymentCapabilities.walletBalanceMinor<cart.totalMinor||!paymentCapabilities.walletPinSet||!/^[0-9]{6}$/.test(walletPin)))||!(paymentCapabilities.methods.find(m=>m.key===paymentMethod)?.available)} onPress={()=>void place()}><Text style={s.buttonText}>{busy?"Securing order…":paymentMethod==="BAZAARA_PAY"?"Confirm with PIN & pay":"Continue to secure payment"}</Text></Pressable></View>
  </Screen>;
}
function Field({label,value,onChange,keyboard,multiline,autoCap}:{label:string;value:string;onChange:(v:string)=>void;keyboard?:"phone-pad"|"numeric";multiline?:boolean;autoCap?:boolean}){return <View style={{marginTop:10}}><Text style={s.label}>{label}</Text><TextInput style={[s.input,multiline&&{minHeight:80,textAlignVertical:"top"}]} value={value} onChangeText={onChange} keyboardType={keyboard} multiline={multiline} autoCapitalize={autoCap?"characters":"sentences"}/></View>}
