import Link from "next/link";
import { FoodHeader } from "../../components/food-header";
import { API_BASE, money } from "../../lib/food-api";

export const dynamic = "force-dynamic";

type Deal = { id:string; code:string|null; title:string; description:string|null; discountType:string; value:number; minSubtotalMinor:number; maxDiscountMinor:number|null; fundingSource:"MERCHANT"|"BAZAARA"|"SHARED"; merchantFundingBps:number; endsAt:string; restaurant:{slug:string;name:string;heroImageUrl:string|null;cuisineTags:string[]} };
async function loadDeals(){try{const r=await fetch(`${API_BASE}/v1/food/deals`,{cache:"no-store"});return r.ok?(await r.json() as {deals:Deal[]}):{deals:[]};}catch{return{deals:[]}}}
export default async function DealsPage(){const{deals}=await loadDeals();return <div className="food-shell"><FoodHeader/><main className="food-page"><div className="checkout-title"><span>LIVE OFFERS</span><h1>Food deals</h1><p>Live promotions with transparent minimums, funding and expiry dates.</p></div>{deals.length?<div className="food-deals-grid">{deals.map(d=><article className="food-deal-card" key={d.id}>{d.restaurant.heroImageUrl?<img src={d.restaurant.heroImageUrl} alt=""/>:null}<div><span>{d.discountType==="PERCENT"?`${d.value}% off`:`${money(d.value)} off`}</span><h2>{d.title}</h2><p>{d.description||d.restaurant.name}</p>{d.code?<code>{d.code}</code>:null}<small>{d.fundingSource==="BAZAARA"?"Funded by Bazaara":d.fundingSource==="SHARED"?"Shared promotion":"Funded by restaurant"} · {d.minSubtotalMinor?`Minimum ${money(d.minSubtotalMinor)} · `:""}Ends {new Date(d.endsAt).toLocaleString()}</small><Link className="food-primary" href={`/restaurants/${d.restaurant.slug}`}>Order from {d.restaurant.name}</Link></div></article>)}</div>:<div className="food-empty"><h2>No live deals right now</h2><p>Restaurants can publish time-bound offers without inflating normal menu pricing.</p><Link className="food-primary" href="/">Browse restaurants</Link></div>}</main></div>}
