-- Drive + Pharmacy completion. Additive migration preserving existing data.

ALTER TABLE "DrivePricingQuote"
  ADD COLUMN "subtotalMinor" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN "fuelAdjustmentMinor" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN "demandAdjustmentMinor" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN "tollsMinor" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN "feesMinor" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN "discountsMinor" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN "fuelPricePerLitreMinor" BIGINT,
  ADD COLUMN "fuelReferencePricePerLitreMinor" BIGINT,
  ADD COLUMN "platformFeeBps" INTEGER NOT NULL DEFAULT 1500,
  ADD COLUMN "platformFeeMinor" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN "driverEarningsMinor" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN "pricingRuleVersion" TEXT NOT NULL DEFAULT 'drive-v2.0',
  ADD COLUMN "pricingSnapshot" JSONB,
  ADD COLUMN "confirmedAt" TIMESTAMP(3);
UPDATE "DrivePricingQuote" SET "subtotalMinor"="totalMinor", "platformFeeMinor"=ROUND(("totalMinor"::numeric*1500)/10000)::bigint, "driverEarningsMinor"="totalMinor"-ROUND(("totalMinor"::numeric*1500)/10000)::bigint WHERE "subtotalMinor"=0;
ALTER TABLE "DrivePricingQuote" ALTER COLUMN "subtotalMinor" DROP DEFAULT;
ALTER TABLE "DrivePricingQuote" ALTER COLUMN "platformFeeMinor" DROP DEFAULT;
ALTER TABLE "DrivePricingQuote" ALTER COLUMN "driverEarningsMinor" DROP DEFAULT;
CREATE INDEX "DrivePricingQuote_rideClass_createdAt_idx" ON "DrivePricingQuote"("rideClass","createdAt");

ALTER TABLE "DriveRide"
  ADD COLUMN "scheduledFor" TIMESTAMP(3), ADD COLUMN "pickupNotes" TEXT,
  ADD COLUMN "paymentMode" TEXT NOT NULL DEFAULT 'WALLET', ADD COLUMN "fareFundingStatus" TEXT NOT NULL DEFAULT 'UNFUNDED',
  ADD COLUMN "fundedAmountMinor" BIGINT NOT NULL DEFAULT 0, ADD COLUMN "platformFeeBps" INTEGER NOT NULL DEFAULT 1500,
  ADD COLUMN "platformChargeMinor" BIGINT NOT NULL DEFAULT 0, ADD COLUMN "driverEarningsMinor" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN "platformChargeSecuredAt" TIMESTAMP(3), ADD COLUMN "settledAt" TIMESTAMP(3),
  ADD COLUMN "searchRadiusMeters" INTEGER NOT NULL DEFAULT 2000, ADD COLUMN "matchingAttempt" INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN "callUnlockedAt" TIMESTAMP(3), ADD COLUMN "actualDropoffLatitude" DOUBLE PRECISION,
  ADD COLUMN "actualDropoffLongitude" DOUBLE PRECISION, ADD COLUMN "actualDropoffDistanceMeters" INTEGER,
  ADD COLUMN "dropoffOverrideReason" TEXT;
UPDATE "DriveRide" r SET "platformFeeBps"=q."platformFeeBps", "platformChargeMinor"=q."platformFeeMinor", "driverEarningsMinor"=q."driverEarningsMinor" FROM "DrivePricingQuote" q WHERE q."id"=r."quoteId";
CREATE INDEX "DriveRide_status_scheduledFor_createdAt_idx" ON "DriveRide"("status","scheduledFor","createdAt");

CREATE TABLE "DriveDriverProfile" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"approvalStatus" TEXT NOT NULL DEFAULT 'PENDING',"availability" TEXT NOT NULL DEFAULT 'OFFLINE',"serviceClasses" TEXT[] NOT NULL DEFAULT ARRAY['GO']::TEXT[],"maxPickupDistanceMeters" INTEGER NOT NULL DEFAULT 5000,"maxPickupEtaSeconds" INTEGER NOT NULL DEFAULT 600,"currentLatitude" DOUBLE PRECISION,"currentLongitude" DOUBLE PRECISION,"locationAccuracyMeters" DOUBLE PRECISION,"lastLocationAt" TIMESTAMP(3),"destinationMode" JSONB,"preferredAreas" JSONB,"ratingAverage" DECIMAL(3,2),"ratingCount" INTEGER NOT NULL DEFAULT 0,"walletBalanceMinor" BIGINT NOT NULL DEFAULT 0,"platformDebtMinor" BIGINT NOT NULL DEFAULT 0,"approvedAt" TIMESTAMP(3),"suspendedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "DriveDriverProfile_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "DriveDriverProfile_userId_key" ON "DriveDriverProfile"("userId"); CREATE INDEX "DriveDriverProfile_approvalStatus_availability_lastLocationAt_idx" ON "DriveDriverProfile"("approvalStatus","availability","lastLocationAt");
CREATE TABLE "DriveVehicle" ("id" TEXT NOT NULL,"driverProfileId" TEXT NOT NULL,"rideClass" TEXT NOT NULL,"make" TEXT NOT NULL,"model" TEXT NOT NULL,"color" TEXT NOT NULL,"plateNumber" TEXT NOT NULL,"capacity" INTEGER NOT NULL DEFAULT 4,"status" TEXT NOT NULL DEFAULT 'PENDING',"inspectionDueAt" TIMESTAMP(3),"insuranceDueAt" TIMESTAMP(3),"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "DriveVehicle_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "DriveVehicle_plateNumber_key" ON "DriveVehicle"("plateNumber"); CREATE INDEX "DriveVehicle_driverProfileId_status_active_idx" ON "DriveVehicle"("driverProfileId","status","active"); CREATE INDEX "DriveVehicle_rideClass_status_active_idx" ON "DriveVehicle"("rideClass","status","active"); ALTER TABLE "DriveVehicle" ADD CONSTRAINT "DriveVehicle_driverProfileId_fkey" FOREIGN KEY("driverProfileId") REFERENCES "DriveDriverProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "DriveDriverDocument" ("id" TEXT NOT NULL,"driverProfileId" TEXT NOT NULL,"type" TEXT NOT NULL,"assetId" TEXT,"documentNumber" TEXT,"status" TEXT NOT NULL DEFAULT 'PENDING',"expiresAt" TIMESTAMP(3),"metadata" JSONB,"reviewedByUserId" TEXT,"reviewedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "DriveDriverDocument_pkey" PRIMARY KEY("id"));
CREATE INDEX "DriveDriverDocument_driverProfileId_status_type_idx" ON "DriveDriverDocument"("driverProfileId","status","type"); CREATE INDEX "DriveDriverDocument_expiresAt_status_idx" ON "DriveDriverDocument"("expiresAt","status"); ALTER TABLE "DriveDriverDocument" ADD CONSTRAINT "DriveDriverDocument_driverProfileId_fkey" FOREIGN KEY("driverProfileId") REFERENCES "DriveDriverProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "DriveDispatchOffer" ("id" TEXT NOT NULL,"rideId" TEXT NOT NULL,"driverUserId" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'OFFERED',"pickupDistanceMeters" INTEGER NOT NULL,"pickupEtaSeconds" INTEGER NOT NULL,"searchRadiusMeters" INTEGER NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"respondedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "DriveDispatchOffer_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "DriveDispatchOffer_rideId_driverUserId_key" ON "DriveDispatchOffer"("rideId","driverUserId"); CREATE INDEX "DriveDispatchOffer_driverUserId_status_expiresAt_idx" ON "DriveDispatchOffer"("driverUserId","status","expiresAt"); CREATE INDEX "DriveDispatchOffer_rideId_status_createdAt_idx" ON "DriveDispatchOffer"("rideId","status","createdAt"); ALTER TABLE "DriveDispatchOffer" ADD CONSTRAINT "DriveDispatchOffer_rideId_fkey" FOREIGN KEY("rideId") REFERENCES "DriveRide"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "DriveFareHold" ("id" TEXT NOT NULL,"rideId" TEXT NOT NULL,"riderUserId" TEXT NOT NULL,"amountMinor" BIGINT NOT NULL,"currency" TEXT NOT NULL,"sourceType" TEXT NOT NULL DEFAULT 'WALLET',"status" TEXT NOT NULL DEFAULT 'HELD',"reservationReference" TEXT NOT NULL,"settlement" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"releasedAt" TIMESTAMP(3),CONSTRAINT "DriveFareHold_pkey" PRIMARY KEY("id"));
CREATE UNIQUE INDEX "DriveFareHold_rideId_key" ON "DriveFareHold"("rideId"); CREATE UNIQUE INDEX "DriveFareHold_reservationReference_key" ON "DriveFareHold"("reservationReference"); CREATE INDEX "DriveFareHold_riderUserId_status_createdAt_idx" ON "DriveFareHold"("riderUserId","status","createdAt"); ALTER TABLE "DriveFareHold" ADD CONSTRAINT "DriveFareHold_rideId_fkey" FOREIGN KEY("rideId") REFERENCES "DriveRide"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "DriveDriverLedgerEntry" ("id" TEXT NOT NULL,"driverUserId" TEXT NOT NULL,"rideId" TEXT,"type" TEXT NOT NULL,"amountMinor" BIGINT NOT NULL,"balanceAfterMinor" BIGINT NOT NULL,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "DriveDriverLedgerEntry_pkey" PRIMARY KEY("id")); CREATE INDEX "DriveDriverLedgerEntry_driverUserId_createdAt_idx" ON "DriveDriverLedgerEntry"("driverUserId","createdAt"); CREATE INDEX "DriveDriverLedgerEntry_rideId_createdAt_idx" ON "DriveDriverLedgerEntry"("rideId","createdAt");
CREATE TABLE "DriveDriverPenalty" ("id" TEXT NOT NULL,"rideId" TEXT NOT NULL,"driverUserId" TEXT NOT NULL,"type" TEXT NOT NULL,"rateBps" INTEGER NOT NULL,"baseAmountMinor" BIGINT NOT NULL,"amountMinor" BIGINT NOT NULL,"status" TEXT NOT NULL DEFAULT 'APPLIED',"reason" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "DriveDriverPenalty_pkey" PRIMARY KEY("id")); CREATE INDEX "DriveDriverPenalty_driverUserId_createdAt_idx" ON "DriveDriverPenalty"("driverUserId","createdAt"); CREATE INDEX "DriveDriverPenalty_rideId_type_idx" ON "DriveDriverPenalty"("rideId","type"); ALTER TABLE "DriveDriverPenalty" ADD CONSTRAINT "DriveDriverPenalty_rideId_fkey" FOREIGN KEY("rideId") REFERENCES "DriveRide"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "DriveFuelPrice" ("id" TEXT NOT NULL,"region" TEXT NOT NULL,"fuelType" TEXT NOT NULL DEFAULT 'PMS',"priceMinorPerLitre" BIGINT NOT NULL,"referencePriceMinorPerLitre" BIGINT NOT NULL,"indexBps" INTEGER NOT NULL,"source" TEXT NOT NULL,"status" TEXT NOT NULL DEFAULT 'ACTIVE',"effectiveFrom" TIMESTAMP(3) NOT NULL,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "DriveFuelPrice_pkey" PRIMARY KEY("id")); CREATE INDEX "DriveFuelPrice_region_fuelType_status_effectiveFrom_idx" ON "DriveFuelPrice"("region","fuelType","status","effectiveFrom");

ALTER TABLE "PharmacyProduct" ADD COLUMN "genericName" TEXT, ADD COLUMN "brand" TEXT, ADD COLUMN "activeIngredient" TEXT, ADD COLUMN "strength" TEXT, ADD COLUMN "dosageForm" TEXT, ADD COLUMN "barcode" TEXT, ADD COLUMN "imageUrl" TEXT;
CREATE INDEX "PharmacyProduct_barcode_idx" ON "PharmacyProduct"("barcode"); CREATE INDEX "PharmacyProduct_genericName_active_idx" ON "PharmacyProduct"("genericName","active");
ALTER TABLE "PharmacyPrescription" ADD COLUMN "reviewNotes" TEXT;
CREATE TABLE "PharmacyMerchantProfile" ("id" TEXT NOT NULL,"merchantId" TEXT NOT NULL,"regulator" TEXT NOT NULL DEFAULT 'PCN',"licenceNumber" TEXT,"verificationStatus" TEXT NOT NULL DEFAULT 'PENDING',"pharmacistInChargeUserId" TEXT,"deliveryEnabled" BOOLEAN NOT NULL DEFAULT true,"pickupEnabled" BOOLEAN NOT NULL DEFAULT true,"consultationEnabled" BOOLEAN NOT NULL DEFAULT false,"verifiedAt" TIMESTAMP(3),"suspendedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "PharmacyMerchantProfile_pkey" PRIMARY KEY("id")); CREATE UNIQUE INDEX "PharmacyMerchantProfile_merchantId_key" ON "PharmacyMerchantProfile"("merchantId"); CREATE INDEX "PharmacyMerchantProfile_verificationStatus_updatedAt_idx" ON "PharmacyMerchantProfile"("verificationStatus","updatedAt");
CREATE TABLE "PharmacyPharmacistProfile" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"merchantId" TEXT NOT NULL,"regulator" TEXT NOT NULL DEFAULT 'PCN',"licenceNumber" TEXT NOT NULL,"verificationStatus" TEXT NOT NULL DEFAULT 'PENDING',"expiresAt" TIMESTAMP(3),"verifiedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "PharmacyPharmacistProfile_pkey" PRIMARY KEY("id")); CREATE UNIQUE INDEX "PharmacyPharmacistProfile_userId_key" ON "PharmacyPharmacistProfile"("userId"); CREATE INDEX "PharmacyPharmacistProfile_merchantId_verificationStatus_idx" ON "PharmacyPharmacistProfile"("merchantId","verificationStatus"); CREATE INDEX "PharmacyPharmacistProfile_expiresAt_verificationStatus_idx" ON "PharmacyPharmacistProfile"("expiresAt","verificationStatus");
CREATE TABLE "PharmacyInventoryBatch" ("id" TEXT NOT NULL,"productId" TEXT NOT NULL,"batchNumber" TEXT NOT NULL,"lotNumber" TEXT,"quantityOnHand" INTEGER NOT NULL,"reservedQuantity" INTEGER NOT NULL DEFAULT 0,"expiresAt" TIMESTAMP(3),"receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"supplierName" TEXT,"costMinor" BIGINT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "PharmacyInventoryBatch_pkey" PRIMARY KEY("id")); CREATE UNIQUE INDEX "PharmacyInventoryBatch_productId_batchNumber_key" ON "PharmacyInventoryBatch"("productId","batchNumber"); CREATE INDEX "PharmacyInventoryBatch_productId_expiresAt_idx" ON "PharmacyInventoryBatch"("productId","expiresAt"); CREATE INDEX "PharmacyInventoryBatch_expiresAt_quantityOnHand_idx" ON "PharmacyInventoryBatch"("expiresAt","quantityOnHand"); ALTER TABLE "PharmacyInventoryBatch" ADD CONSTRAINT "PharmacyInventoryBatch_productId_fkey" FOREIGN KEY("productId") REFERENCES "PharmacyProduct"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "PharmacyPrescriptionEvent" ("id" TEXT NOT NULL,"prescriptionId" TEXT NOT NULL,"type" TEXT NOT NULL,"actorUserId" TEXT,"payload" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PharmacyPrescriptionEvent_pkey" PRIMARY KEY("id")); CREATE INDEX "PharmacyPrescriptionEvent_prescriptionId_createdAt_idx" ON "PharmacyPrescriptionEvent"("prescriptionId","createdAt"); CREATE INDEX "PharmacyPrescriptionEvent_type_createdAt_idx" ON "PharmacyPrescriptionEvent"("type","createdAt"); ALTER TABLE "PharmacyPrescriptionEvent" ADD CONSTRAINT "PharmacyPrescriptionEvent_prescriptionId_fkey" FOREIGN KEY("prescriptionId") REFERENCES "PharmacyPrescription"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "PharmacyOrder" ("id" TEXT NOT NULL,"orderNumber" TEXT NOT NULL,"userId" TEXT NOT NULL,"merchantId" TEXT NOT NULL,"prescriptionId" TEXT,"status" TEXT NOT NULL DEFAULT 'PLACED',"fulfillmentType" TEXT NOT NULL DEFAULT 'DELIVERY',"deliveryAddress" JSONB,"subtotalMinor" BIGINT NOT NULL,"deliveryFeeMinor" BIGINT NOT NULL DEFAULT 0,"serviceFeeMinor" BIGINT NOT NULL DEFAULT 0,"discountMinor" BIGINT NOT NULL DEFAULT 0,"totalMinor" BIGINT NOT NULL,"currency" TEXT NOT NULL DEFAULT 'NGN',"paymentStatus" TEXT NOT NULL DEFAULT 'PENDING',"priceConfirmedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"deliveryBookingId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "PharmacyOrder_pkey" PRIMARY KEY("id")); CREATE UNIQUE INDEX "PharmacyOrder_orderNumber_key" ON "PharmacyOrder"("orderNumber"); CREATE INDEX "PharmacyOrder_userId_createdAt_idx" ON "PharmacyOrder"("userId","createdAt"); CREATE INDEX "PharmacyOrder_merchantId_status_createdAt_idx" ON "PharmacyOrder"("merchantId","status","createdAt"); CREATE INDEX "PharmacyOrder_prescriptionId_idx" ON "PharmacyOrder"("prescriptionId"); ALTER TABLE "PharmacyOrder" ADD CONSTRAINT "PharmacyOrder_prescriptionId_fkey" FOREIGN KEY("prescriptionId") REFERENCES "PharmacyPrescription"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE TABLE "PharmacyOrderItem" ("id" TEXT NOT NULL,"orderId" TEXT NOT NULL,"productId" TEXT NOT NULL,"nameSnapshot" TEXT NOT NULL,"quantity" INTEGER NOT NULL,"unitPriceMinor" BIGINT NOT NULL,"lineTotalMinor" BIGINT NOT NULL,"requiresPrescription" BOOLEAN NOT NULL,"substitutionForItemId" TEXT,"status" TEXT NOT NULL DEFAULT 'RESERVED',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PharmacyOrderItem_pkey" PRIMARY KEY("id")); CREATE INDEX "PharmacyOrderItem_orderId_status_idx" ON "PharmacyOrderItem"("orderId","status"); CREATE INDEX "PharmacyOrderItem_productId_createdAt_idx" ON "PharmacyOrderItem"("productId","createdAt"); ALTER TABLE "PharmacyOrderItem" ADD CONSTRAINT "PharmacyOrderItem_orderId_fkey" FOREIGN KEY("orderId") REFERENCES "PharmacyOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "PharmacyOrderItem" ADD CONSTRAINT "PharmacyOrderItem_productId_fkey" FOREIGN KEY("productId") REFERENCES "PharmacyProduct"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
CREATE TABLE "PharmacySubstitutionProposal" ("id" TEXT NOT NULL,"orderId" TEXT NOT NULL,"originalItemId" TEXT NOT NULL,"proposedProductId" TEXT NOT NULL,"pharmacistUserId" TEXT NOT NULL,"reason" TEXT NOT NULL,"priceDeltaMinor" BIGINT NOT NULL,"status" TEXT NOT NULL DEFAULT 'PENDING',"customerDecisionAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PharmacySubstitutionProposal_pkey" PRIMARY KEY("id")); CREATE INDEX "PharmacySubstitutionProposal_orderId_status_createdAt_idx" ON "PharmacySubstitutionProposal"("orderId","status","createdAt"); ALTER TABLE "PharmacySubstitutionProposal" ADD CONSTRAINT "PharmacySubstitutionProposal_orderId_fkey" FOREIGN KEY("orderId") REFERENCES "PharmacyOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "PharmacyRefillPlan" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"productId" TEXT,"prescriptionId" TEXT,"cadenceDays" INTEGER NOT NULL,"quantity" INTEGER NOT NULL DEFAULT 1,"status" TEXT NOT NULL DEFAULT 'ACTIVE',"nextRunAt" TIMESTAMP(3) NOT NULL,"reminderDays" INTEGER NOT NULL DEFAULT 3,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "PharmacyRefillPlan_pkey" PRIMARY KEY("id")); CREATE INDEX "PharmacyRefillPlan_userId_status_nextRunAt_idx" ON "PharmacyRefillPlan"("userId","status","nextRunAt"); CREATE INDEX "PharmacyRefillPlan_nextRunAt_status_idx" ON "PharmacyRefillPlan"("nextRunAt","status"); ALTER TABLE "PharmacyRefillPlan" ADD CONSTRAINT "PharmacyRefillPlan_productId_fkey" FOREIGN KEY("productId") REFERENCES "PharmacyProduct"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "PharmacyRefillPlan" ADD CONSTRAINT "PharmacyRefillPlan_prescriptionId_fkey" FOREIGN KEY("prescriptionId") REFERENCES "PharmacyPrescription"("id") ON DELETE SET NULL ON UPDATE CASCADE;
