import {useCallback,useEffect,useMemo,useState} from "react";
import {Image,Pressable,ScrollView,Text,TextInput,View} from "react-native";
import {router,useFocusEffect} from "expo-router";import * as SecureStore from "expo-secure-store";
import {Screen,SectionTitle,EmptyState} from "@bazaara/mobile-ui";import {foodApi} from "@/lib/api";import {foodStyles as s} from "@/ui/theme";
type Restaurant={id:string;slug:string;name:string;description:string;heroImageUrl:string|null;cuisineTags:string[];rating:number;ratingCount?:number;etaMinutes:{min:number;max:number};deliveryFeeMinor:number;isOpen:boolean;distanceMeters?:number|null};type Home={cuisines:Array<{name:string;count:number}>;restaurants:Restaurant[];featuredItems:Array<{id:string;name:string;priceMinor:number;restaurant:Restaurant}>};
type Loc={latitude:number;longitude:number;label:string};const KEY="bazaara.food.mobile.location";
export default function Home(){const[data,setData]=useState<Home|null>(null);const[error,setError]=useState("");const[q,setQ]=useState("");const[loc,setLoc]=useState<Loc|null>(null);
 const load=useCallback(async(next:Loc|null)=>{try{const qs=next?`?latitude=${next.latitude}&longitude=${next.longitude}`:"";setData(await foodApi.get<Home>(`/v1/food/home${qs}`,{cache:"no-store"}));setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load Food")}},[]);
 const refreshLocation=useCallback(async()=>{const saved=await SecureStore.getItemAsync(KEY);if(saved){try{const parsed=JSON.parse(saved) as Loc;setLoc(parsed);await load(parsed);return}catch{}}setLoc(null);await load(null)},[load]);
 useEffect(()=>{void refreshLocation()},[]);
 useFocusEffect(useCallback(()=>{void refreshLocation()},[refreshLocation]));
 const demand=useMemo(()=>[...(data?.restaurants??[])].sort((a,b)=>(b.ratingCount??0)-(a.ratingCount??0)||b.rating-a.rating).slice(0,6),[data]);
 return <Screen><View style={s.top}><View><Text style={s.brand}>BAZAARA<Text style={s.brandAccent}>.FOOD</Text></Text><Text style={s.small}>Good food, closer to you.</Text></View><Pressable style={s.locationChip} onPress={()=>router.push("/location")}><Text style={s.locationLabel}>DELIVER TO</Text><Text numberOfLines={1} style={s.locationValue}>{loc?.label||"Set location"}</Text><Text numberOfLines={1} style={s.locationHint}>{loc?"Tap to change":"Choose your delivery point"}</Text></Pressable></View>
 <View style={s.luxeIntro}><Text style={s.heroEyebrow}>NEARBY · FAST · PERSONAL</Text><Text style={s.heroTitle}>{loc?"What are you craving?":"Find your next favourite meal."}</Text><Text style={s.heroCopy}>{loc?"Restaurants are ranked around your selected delivery point.":"Use your location for smarter nearby discovery."}</Text></View>
 <TextInput style={[s.search,{marginTop:11}]} value={q} onChangeText={setQ} placeholder="Search food, restaurants or cuisines" placeholderTextColor="#7E8DA6" returnKeyType="search" onSubmitEditing={()=>router.push({pathname:"/(tabs)/search",params:{q}})}/>
 <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.quickRail}><Quick label="Open now" hint="Ready to order" onPress={()=>router.push("/(tabs)/search")}/><Quick label="Delivery" hint="To your door" onPress={()=>router.push("/(tabs)/search")}/><Quick label="Pickup" hint="Collect yourself" onPress={()=>router.push("/(tabs)/search")}/><Quick label="Deals" hint="Current offers" onPress={()=>router.push("/deals")}/></ScrollView>
 {data?.cuisines.length?<><SectionTitle eyebrow="Explore" title="Categories"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.quickRail}>{data.cuisines.slice(0,12).map((c,i)=><Pressable key={c.name} style={s.categoryCard} onPress={()=>router.push({pathname:"/(tabs)/search",params:{q:c.name}})}><Text style={s.categoryGlyph}>{["◎","◒","◇","△","✦","◉"][i%6]}</Text><View><Text style={s.categoryTitle}>{c.name}</Text><Text style={s.categoryHint}>{c.count} nearby</Text></View></Pressable>)}</ScrollView></>:null}
 {demand.length?<><SectionTitle eyebrow="Trending" title="Most in demand"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.quickRail}>{demand.map((r,i)=><Pressable key={r.id} style={s.demandCard} onPress={()=>router.push(`/restaurant/${r.slug}`)}><Text style={s.demandRank}>#{i+1}</Text><Text style={[s.name,{marginTop:5}]}>{r.name}</Text><Text style={s.meta}>★ {r.rating.toFixed(1)} · {r.etaMinutes.min}–{r.etaMinutes.max} min</Text></Pressable>)}</ScrollView></>:null}
 <SectionTitle eyebrow={loc?"Nearest first":"Discover"} title="Restaurants near you"/>{!data&&!error?<Text style={s.p}>Loading restaurants…</Text>:null}{error?<EmptyState title="Food is temporarily unavailable" message={error}/>:null}{data?.restaurants.map(r=><RestaurantRow key={r.id} restaurant={r}/>)}</Screen>}
function Quick({label,hint,onPress}:{label:string;hint:string;onPress:()=>void}){return <Pressable style={s.quickCard} onPress={onPress}><Text style={s.quickTitle}>{label}</Text><Text style={s.quickHint}>{hint}</Text></Pressable>}
function RestaurantRow({restaurant:r}:{restaurant:Restaurant}){const distance=r.distanceMeters==null?null:r.distanceMeters<1000?`${Math.round(r.distanceMeters/100)*100} m`:`${(r.distanceMeters/1000).toFixed(1)} km`;return <Pressable style={s.restaurant} onPress={()=>router.push(`/restaurant/${r.slug}`)}>{r.heroImageUrl?<Image source={{uri:r.heroImageUrl}} style={s.image}/>:<View style={s.image}/>}<View style={s.restaurantBody}><View style={[s.row,{justifyContent:"space-between"}]}><Text numberOfLines={1} style={[s.name,{flex:1}]}>{r.name}</Text><Text style={s.price}>★ {r.rating.toFixed(1)}</Text></View><Text numberOfLines={1} style={s.meta}>{r.cuisineTags.join(" · ")}</Text><Text style={s.meta}>{r.etaMinutes.min}–{r.etaMinutes.max} min · {r.deliveryFeeMinor?`₦${Math.round(r.deliveryFeeMinor/100).toLocaleString()} delivery`:"Free delivery"}{distance?` · ${distance}`:""}</Text></View></Pressable>}
