"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { api, errorText } from "@bazaara/social-ui";
import { Access, Frame, State, useReady } from "./Frame";
type Clip={id:string;caption:string;createdAt:string;liked:boolean;viewCount:number;creator:{displayName:string|null;socialProfile?:{handle:string}|null};media:{url:string};_count:{likes:number;comments:number}};
export default function ZimZamNext(){
 const session=useReady();const [mode,setMode]=useState<"pulse"|"latest"|"explore">("pulse");const [clips,setClips]=useState<Clip[]>([]),[error,setError]=useState(""),[query,setQuery]=useState("");const seen=useRef(new Set<string>());
 const load=useCallback(async()=>{try{const r=await api.get<{clips:Clip[]}>("/v1/bazclips/feed",{query:{limit:24},maxRetries:0});setClips(r.clips)}catch(e){setError(errorText(e))}},[]);
 useEffect(()=>{if(session.user?.profile)void load()},[session.user?.profile,load]);
 const feed=useMemo(()=>{const rows=mode==="latest"?[...clips].sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)):clips;return query?rows.filter(c=>(c.caption+" "+(c.creator.displayName??"")).toLowerCase().includes(query.toLowerCase())):rows},[clips,mode,query]);
 async function like(c:Clip){try{if(c.liked)await api.delete(`/v1/bazclips/clips/${encodeURIComponent(c.id)}/like`);else await api.put(`/v1/bazclips/clips/${encodeURIComponent(c.id)}/like`,{});setClips(rows=>rows.map(x=>x.id===c.id?{...x,liked:!x.liked,_count:{...x._count,likes:x._count.likes+(x.liked?-1:1)}}:x))}catch(e){setError(errorText(e))}}
 async function view(c:Clip){if(seen.current.has(c.id))return;seen.current.add(c.id);try{const x=await api.post<{viewCount:number}>(`/v1/bazclips/clips/${encodeURIComponent(c.id)}/view`,{});setClips(rows=>rows.map(y=>y.id===c.id?{...y,viewCount:x.viewCount}:y))}catch{seen.current.delete(c.id)}}
 return <Frame app="ZimZam" initial="CREATOR CULTURE" mark="Z" accent="#e44dd2" nav={[{id:"pulse",label:"Pulse",active:mode==="pulse",onClick:()=>setMode("pulse")},{id:"latest",label:"Latest",active:mode==="latest",onClick:()=>setMode("latest")},{id:"explore",label:"Explore",active:mode==="explore",onClick:()=>setMode("explore")},{id:"create",label:"Create",onClick:()=>window.location.assign("/")}]}><Access session={session} app="ZimZam"/> {session.user?.profile&&<><div className="nx-eyebrow">YOUR PULSE</div><div className="nx-row nx-zimHead"><div><h1>Watch your way.</h1><p className="nx-muted">Short-form first, with discovery you can control.</p></div><a className="nx-primary" href="/">+ Create</a></div>{error&&<div className="nx-alert" role="alert">{error}</div>}
 {mode==="explore"&&<div className="nx-card nx-zimSearch"><label htmlFor="nx-zim-find">Search the current feed</label><input className="nx-input" id="nx-zim-find" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Creator, caption, topic…"/></div>}
 <div className="nx-tabs" role="tablist" aria-label="Feed mode"><button role="tab" aria-selected={mode==="pulse"} onClick={()=>setMode("pulse")}>For You</button><button role="tab" aria-selected={mode==="latest"} onClick={()=>setMode("latest")}>Latest</button><button role="tab" aria-selected={mode==="explore"} onClick={()=>setMode("explore")}>Explore</button><button className="nx-secondary" onClick={()=>void load()}>Refresh</button></div><div className="nx-zimViewport">{feed.length?feed.map((c,i)=><article key={c.id} className="nx-zimCell" aria-label={`Video ${i+1} by ${c.creator.displayName??"Creator"}`}><div className="nx-zimVideo"><video controls playsInline preload={i===0?"metadata":"none"} src={c.media.url} onPlay={()=>void view(c)}/><div className="nx-zimOverlay"><div><span className="nx-tag">PULSE / {i+1} OF {feed.length}</span><h2>{c.creator.displayName??"Creator"}</h2><p>{c.caption||"New creation"}</p></div></div></div><div className="nx-zimActions"><button aria-pressed={c.liked} onClick={()=>void like(c)} aria-label={c.liked?"Remove like":"Like clip"}>{c.liked?"♥":"♡"}<small>{c._count.likes}</small></button><a href="/" aria-label="Open comments in current ZimZam">☰<small>{c._count.comments}</small></a><span className="nx-zimCount">{c.viewCount} views</span></div></article>):<State>No videos match yet. Use the current Create page to publish the first clip.</State>}</div></>}</Frame>
}
