"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createApiClient } from "@bazaara/api-client";
import { BusinessHeaderStandalone } from "../components/BusinessHeaderStandalone";
import { uploadBusinessFile } from "../lib/business";

function apiBase(){const origin=typeof window!=="undefined"?window.location.origin:"http://localhost:3001";return `${origin}/api/bazaara-platform`;}
function api(){return createApiClient({baseUrl:apiBase(),credentials:"include"});}
type Context={merchants:Array<{id:string;name:string;slug:string;verification:null|{verificationStatus:string;licenceNumber:string|null}}>};
type Product={id:string;name:string;genericName:string|null;brand:string|null;category:string;priceMinor:number;stockOnHand:number;requiresPrescription:boolean;active:boolean;imageUrl:string|null;batches:Array<{id:string;batchNumber:string;quantityOnHand:number;reservedQuantity:number;expiresAt:string|null}>};
type Rx={id:string;status:string;submittedAt:string;reviewedAt:string|null};
type Order={id:string;orderNumber:string;status:string;paymentStatus:string;fulfillmentType:string;totalMinor:number;currency:string;items:Array<{id:string;name:string;quantity:number;status:string;requiresPrescription:boolean}>;substitutions:Array<{id:string;reason:string;status:string;priceDeltaMinor:number}>};
function money(n:number,c="NGN"){return new Intl.NumberFormat("en-NG",{style:"currency",currency:c,maximumFractionDigits:0}).format(n/100)}

export default function PharmacyBusiness(){
 const[ctx,setCtx]=useState<Context>({merchants:[]});const[merchantId,setMerchantId]=useState("");const[products,setProducts]=useState<Product[]>([]);const[prescriptions,setPrescriptions]=useState<Rx[]>([]);const[orders,setOrders]=useState<Order[]>([]);const[error,setError]=useState("");const[notice,setNotice]=useState("");const[busy,setBusy]=useState("");
 const[productForm,setProductForm]=useState({sku:"",slug:"",name:"",genericName:"",brand:"",activeIngredient:"",strength:"",dosageForm:"",barcode:"",imageUrl:"",description:"",category:"OTC & Wellness",priceMinor:"",requiresPrescription:false});const[imageBusy,setImageBusy]=useState(false);
 const load=useCallback(async()=>{try{const c=await api().get<Context>("/v1/business/pharmacy/context");setCtx(c);const mid=merchantId||c.merchants[0]?.id||"";if(mid&&!merchantId)setMerchantId(mid);if(mid){const[p,r,o]=await Promise.all([api().get<{products:Product[]}>(`/v1/pharmacy/merchant/products?merchantId=${encodeURIComponent(mid)}`),api().get<{prescriptions:Rx[]}>(`/v1/pharmacy/merchant/prescriptions?merchantId=${encodeURIComponent(mid)}`),api().get<{orders:Order[]}>(`/v1/pharmacy/merchant/orders?merchantId=${encodeURIComponent(mid)}`)]);setProducts(p.products);setPrescriptions(r.prescriptions);setOrders(o.orders)}setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load Pharmacy Business")}},[merchantId]);
 useEffect(()=>{void load()},[load]);
 const openOrders=useMemo(()=>orders.filter(o=>!["DELIVERED","CANCELLED"].includes(o.status)),[orders]);
 const activeMerchant=ctx.merchants.find(m=>m.id===merchantId)??ctx.merchants[0];
 const expiring=useMemo(()=>products.flatMap(p=>p.batches).filter(b=>b.expiresAt&&Date.parse(b.expiresAt)<Date.now()+90*86400000).length,[products]);
 async function run(key:string,fn:()=>Promise<unknown>,msg:string){setBusy(key);setError("");try{await fn();setNotice(msg);await load()}catch(e){setError(e instanceof Error?e.message:"Operation failed")}finally{setBusy("")}}
 async function addProduct(e:FormEvent){e.preventDefault();await run("product",()=>api().post("/v1/pharmacy/merchant/products",{merchantId,...productForm,priceMinor:Math.round(Number(productForm.priceMinor)*100),genericName:productForm.genericName||undefined,brand:productForm.brand||undefined,activeIngredient:productForm.activeIngredient||undefined,strength:productForm.strength||undefined,dosageForm:productForm.dosageForm||undefined,barcode:productForm.barcode||undefined,imageUrl:productForm.imageUrl||undefined}),"Pharmacy product created")}
 async function uploadProductImage(file:File){setImageBusy(true);setError("");try{const upload=await uploadBusinessFile(file,"PUBLIC");setProductForm(current=>({...current,imageUrl:upload.publicUrl??""}));setNotice("Product photo uploaded.")}catch(e){setError(e instanceof Error?e.message:"Could not upload product photo")}finally{setImageBusy(false)}}
 async function addBatch(productId:string){const batch=prompt("Batch / lot number");const qty=Number(prompt("Quantity received")||0);const expiry=prompt("Expiry YYYY-MM-DD (optional)");if(!batch||qty<1)return;await run(`batch:${productId}`,()=>api().post("/v1/pharmacy/merchant/inventory/batches",{productId,batchNumber:batch,quantityOnHand:qty,expiresAt:expiry?`${expiry}T23:59:59.000Z`:undefined}),"Inventory batch added")}
 async function review(id:string,decision:"APPROVE"|"REJECT"|"REQUEST_INFORMATION"){await run(`rx:${id}`,()=>api().post(`/v1/pharmacy/merchant/prescriptions/${id}/review`,{decision,notes:decision==="APPROVE"?"Approved by verified pharmacist":"Pharmacist review decision"}),`Prescription ${decision.toLowerCase()}`)}
 async function advance(o:Order){const next:Record<string,string>={PLACED:"CONFIRMED",CONFIRMED:"DISPENSING",DISPENSING:"READY",READY:o.fulfillmentType==="DELIVERY"?"OUT_FOR_DELIVERY":"DELIVERED",OUT_FOR_DELIVERY:"DELIVERED"};if(!next[o.status])return;await run(`order:${o.id}`,()=>api().patch(`/v1/pharmacy/merchant/orders/${o.id}/status`,{status:next[o.status]}),`Order moved to ${next[o.status]}`)}
 return <div className="business-control-shell"><BusinessHeaderStandalone active="pharmacy"/><main className="business-control-main">
  <section className="business-page-heading business-page-heading-v3"><div><span className="business-kicker">PHARMACY</span><h1>Dispense safely. Track every batch.</h1><p>Catalogue, prescription review, FEFO inventory and paid-order dispensing stay inside one regulated workspace.</p></div><div className={`business-compliance-badge ${activeMerchant?.verification?.verificationStatus==="VERIFIED"?"verified":"pending"}`}><span>PHARMACY STATUS</span><strong>{activeMerchant?.verification?.verificationStatus??"SETUP"}</strong><small>{activeMerchant?.verification?.licenceNumber?`Licence ${activeMerchant.verification.licenceNumber}`:"Verification required for regulated fulfillment"}</small></div></section>
  {error?<div className="business-alert">{error}<small>If you own/admin this organization, Business access should authorize merchant management. Pharmacist-only actions still require a verified pharmacist profile.</small></div>:null}{notice?<div className="business-notice">{notice}</div>:null}
  <section className="business-control-kpis business-control-kpis-v3"><article><span>PUBLISHED PRODUCTS</span><strong>{products.filter(p=>p.active).length}</strong><small>{products.length} catalogue items</small></article><article><span>RX QUEUE</span><strong>{prescriptions.filter(r=>["SUBMITTED","IN_REVIEW","MORE_INFORMATION_REQUIRED"].includes(r.status)).length}</strong><small>awaiting pharmacist action</small></article><article><span>OPEN ORDERS</span><strong>{openOrders.length}</strong><small>dispensing and fulfillment</small></article><article><span>EXPIRY ALERTS</span><strong>{expiring}</strong><small>within the next 90 days</small></article></section>
  <div className="business-pharmacy-grid"><section className="business-panel"><div className="business-section-heading"><div><span className="business-kicker">PRESCRIPTIONS</span><h2>Review queue</h2></div><span className="business-soft-pill">Verified pharmacist only</span></div>{prescriptions.length?prescriptions.map(r=><article className="business-pharmacy-row" key={r.id}><div><strong>{r.id.slice(0,12)}</strong><small>{r.status} · {new Date(r.submittedAt).toLocaleString("en-NG")}</small></div>{["SUBMITTED","IN_REVIEW","MORE_INFORMATION_REQUIRED"].includes(r.status)?<div className="business-inline-actions"><button disabled={busy===`rx:${r.id}`} onClick={()=>void review(r.id,"APPROVE")}>{busy===`rx:${r.id}`?"Saving…":"Approve"}</button><button disabled={busy===`rx:${r.id}`} onClick={()=>void review(r.id,"REQUEST_INFORMATION")}>{busy===`rx:${r.id}`?"Saving…":"Need info"}</button><button disabled={busy===`rx:${r.id}`} onClick={()=>void review(r.id,"REJECT")}>{busy===`rx:${r.id}`?"Saving…":"Reject"}</button></div>:<span className="business-soft-pill">{r.status}</span>}</article>):<div className="business-empty-state">No prescriptions in queue.</div>}</section>
  <section className="business-panel"><div className="business-section-heading"><div><span className="business-kicker">ORDERS</span><h2>Dispensing queue</h2></div><span className="business-soft-pill">{openOrders.length} open</span></div>{openOrders.length?openOrders.map(o=><article className="business-pharmacy-row" key={o.id}><div><strong>{o.orderNumber}</strong><small>{o.status} · {o.paymentStatus} · {money(o.totalMinor,o.currency)}</small></div><button className="business-primary-button compact" disabled={busy===`order:${o.id}`||o.paymentStatus!=="PAID"} onClick={()=>void advance(o)}>{o.paymentStatus!=="PAID"?"Awaiting payment":"Advance"}</button></article>):<div className="business-empty-state">No pharmacy orders require action.</div>}</section></div>
  <div className="business-pharmacy-grid"><section className="business-panel"><div className="business-section-heading"><div><span className="business-kicker">CATALOGUE</span><h2>Products & batches</h2></div><a className="business-text-link" href="/pharmacy/products">Full catalogue</a></div>{products.slice(0,6).map(p=><article className="business-pharmacy-product" key={p.id}>{p.imageUrl?<img className="business-pharmacy-thumb" src={p.imageUrl} alt={p.name}/>:null}<div><span className="business-soft-pill">{p.requiresPrescription?"RX":"OTC"}</span><strong>{p.name}</strong><small>{p.genericName??p.brand??p.category} · {money(p.priceMinor)}</small></div><div><strong>{p.stockOnHand}</strong><small>units</small><button disabled={busy===`batch:${p.id}`} onClick={()=>void addBatch(p.id)}>{busy===`batch:${p.id}`?"Adding…":"+ Batch"}</button></div></article>)}</section>
  <section className="business-panel"><span className="business-kicker">QUICK ADD</span><h2>Add pharmacy product</h2><form className="business-form business-pharmacy-form" onSubmit={addProduct}><label>SKU<input required value={productForm.sku} onChange={e=>setProductForm({...productForm,sku:e.target.value})}/></label><label>Slug<input required value={productForm.slug} onChange={e=>setProductForm({...productForm,slug:e.target.value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")})}/></label><label className="wide">Name<input required value={productForm.name} onChange={e=>setProductForm({...productForm,name:e.target.value})}/></label><label>Generic name<input value={productForm.genericName} onChange={e=>setProductForm({...productForm,genericName:e.target.value})}/></label><label>Brand<input value={productForm.brand} onChange={e=>setProductForm({...productForm,brand:e.target.value})}/></label><label>Category<input required value={productForm.category} onChange={e=>setProductForm({...productForm,category:e.target.value})}/></label><label>Price (NGN)<input required inputMode="decimal" value={productForm.priceMinor} onChange={e=>setProductForm({...productForm,priceMinor:e.target.value})}/></label><label className="wide">Description<textarea required value={productForm.description} onChange={e=>setProductForm({...productForm,description:e.target.value})}/></label><label className="wide business-file-label">Product photo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={imageBusy} onChange={e=>{const file=e.target.files?.[0];if(file)void uploadProductImage(file)}}/><small>{imageBusy?"Uploading…":productForm.imageUrl?"Photo ready":"JPG, PNG or WebP"}</small></label><label className="business-check-label"><input type="checkbox" checked={productForm.requiresPrescription} onChange={e=>setProductForm({...productForm,requiresPrescription:e.target.checked})}/>Prescription required</label><button className="business-primary-button" disabled={busy==="product"}>Create product</button></form></section></div>
 </main></div>
}
