import {useCallback,useEffect,useState} from "react";
import {Pressable,Text,TextInput,View} from "react-native";
import {EmptyState,Screen} from "@bazaara/mobile-ui";
import {ApiError,groceryApi} from "@/lib/api";
import {signInWithBazId} from "@/lib/auth";
import {groceryPalette,groceryStyles as s} from "@/ui/theme";

type Item={id:string;label:string;quantity:number;checked:boolean};type Collaborator={id:string;userId:string;role:"VIEWER"|"EDITOR";displayName:string|null;email:string|null};type List={id:string;name:string;accessRole:"OWNER"|"EDITOR"|"VIEWER";canEdit:boolean;canManage:boolean;items:Item[];collaborators:Collaborator[]};
export default function GroceryLists(){
 const[lists,setLists]=useState<List[]>([]);const[needAuth,setNeedAuth]=useState(false);const[error,setError]=useState("");const[name,setName]=useState("");const[draft,setDraft]=useState<Record<string,string>>({});const[quantity,setQuantity]=useState<Record<string,number>>({});const[collab,setCollab]=useState<Record<string,string>>({});const[busy,setBusy]=useState("");
 const load=useCallback(async()=>{try{const body=await groceryApi.get<{lists:List[]}>("/v1/grocery/lists",{cache:"no-store"});setLists(body.lists);setNeedAuth(false);setError("")}catch(cause){if(cause instanceof ApiError&&cause.status===401)setNeedAuth(true);else setError(cause instanceof Error?cause.message:"Could not load lists")}},[]);useEffect(()=>{void load()},[load]);
 async function create(){if(!name.trim())return;setBusy("new");try{await groceryApi.post("/v1/grocery/lists",{name:name.trim()});setName("");await load()}finally{setBusy("")}}
 async function add(list:List){const label=draft[list.id]?.trim();if(!label)return;setBusy(`add:${list.id}`);try{await groceryApi.post(`/v1/grocery/lists/${list.id}/items`,{label,quantity:Math.max(1,Math.min(99,quantity[list.id]??1))});setDraft(current=>({...current,[list.id]:""}));setQuantity(current=>({...current,[list.id]:1}));await load()}finally{setBusy("")}}
 async function patch(list:List,item:Item,data:{quantity?:number;checked?:boolean}){setBusy(item.id);try{await groceryApi.patch(`/v1/grocery/lists/${list.id}/items/${item.id}`,data);await load()}finally{setBusy("")}}
 async function invite(list:List){const email=collab[list.id]?.trim();if(!email)return;setBusy(`invite:${list.id}`);try{await groceryApi.post(`/v1/grocery/lists/${list.id}/collaborators`,{email,role:"EDITOR"});setCollab(current=>({...current,[list.id]:""}));await load()}catch(cause){setError(cause instanceof Error?cause.message:"Could not share list")}finally{setBusy("")}}
 if(needAuth)return <Screen><Text style={s.h1}>My Grocery Lists</Text><Text style={s.p}>Sign in with BazID to keep quantity-aware lists synced.</Text><Pressable style={[s.button,{marginTop:14}]} onPress={async()=>{const result=await signInWithBazId("/(tabs)/lists");if(result.ok)await load()}}><Text style={s.buttonText}>Continue with BazID</Text></Pressable></Screen>;
 return <Screen><Text style={{color:groceryPalette.success,fontSize:7,fontWeight:"900",letterSpacing:.7}}>MY GROCERY SYSTEM</Text><Text style={s.h1}>Lists</Text><Text style={[s.p,{marginTop:4}]}>Set quantities, tick items off and reuse your regular shop.</Text>{error?<Text style={[s.error,{marginTop:8}]}>{error}</Text>:null}
  <View style={[s.card,{marginTop:12}]}><TextInput style={s.input} value={name} onChangeText={setName} placeholder="New list name" placeholderTextColor={groceryPalette.muted2}/><Pressable style={[s.button,{marginTop:8}]} disabled={!name.trim()||busy==="new"} onPress={()=>void create()}><Text style={s.buttonText}>{busy==="new"?"Creating…":"Create list"}</Text></Pressable></View>
  {!lists.length?<EmptyState title="No lists yet" message="Create one for weekly staples or a shared household shop."/>:null}
  {lists.map(list=><View key={list.id} style={[s.card,{marginTop:9}]}><Text style={s.h2}>{list.name}</Text><Text style={s.small}>{list.items.length} items · {list.items.reduce((sum,item)=>sum+item.quantity,0)} total units</Text>
    {list.items.map(item=><View key={item.id} style={{marginTop:7,minHeight:48,padding:7,flexDirection:"row",alignItems:"center",gap:7,borderRadius:10,backgroundColor:groceryPalette.surface2}}><Pressable style={{width:30,height:30,alignItems:"center",justifyContent:"center",borderRadius:8,backgroundColor:item.checked?"rgba(47,143,98,.18)":groceryPalette.surface3}} disabled={!list.canEdit||busy===item.id} onPress={()=>void patch(list,item,{checked:!item.checked})}><Text style={{color:groceryPalette.success,fontWeight:"900"}}>{item.checked?"✓":""}</Text></Pressable><Text numberOfLines={1} style={[s.name,{flex:1,fontSize:11,textDecorationLine:item.checked?"line-through":"none"}]}>{item.label}</Text><View style={s.row}><Pressable style={s.secondary} disabled={!list.canEdit||item.quantity<=1||busy===item.id} onPress={()=>void patch(list,item,{quantity:item.quantity-1})}><Text style={s.secondaryText}>−</Text></Pressable><Text style={[s.name,{width:22,textAlign:"center"}]}>{item.quantity}</Text><Pressable style={s.secondary} disabled={!list.canEdit||item.quantity>=99||busy===item.id} onPress={()=>void patch(list,item,{quantity:item.quantity+1})}><Text style={s.secondaryText}>+</Text></Pressable></View></View>)}
    {list.canEdit?<View style={{marginTop:9}}><TextInput style={s.input} value={draft[list.id]??""} onChangeText={value=>setDraft(current=>({...current,[list.id]:value}))} placeholder="Add an item" placeholderTextColor={groceryPalette.muted2}/><View style={[s.row,{marginTop:7}]}><Pressable style={s.secondary} disabled={(quantity[list.id]??1)<=1} onPress={()=>setQuantity(current=>({...current,[list.id]:Math.max(1,(current[list.id]??1)-1)}))}><Text style={s.secondaryText}>−</Text></Pressable><Text style={[s.name,{minWidth:24,textAlign:"center"}]}>{quantity[list.id]??1}</Text><Pressable style={s.secondary} disabled={(quantity[list.id]??1)>=99} onPress={()=>setQuantity(current=>({...current,[list.id]:Math.min(99,(current[list.id]??1)+1)}))}><Text style={s.secondaryText}>+</Text></Pressable><Pressable style={[s.button,{flex:1}]} disabled={!draft[list.id]?.trim()||busy===`add:${list.id}`} onPress={()=>void add(list)}><Text style={s.buttonText}>Add item</Text></Pressable></View></View>:null}
    {list.canManage?<><View style={s.divider}/><Text style={s.label}>HOUSEHOLD COLLABORATORS</Text><View style={[s.row,{marginTop:7}]}><TextInput style={[s.input,{flex:1}]} autoCapitalize="none" keyboardType="email-address" value={collab[list.id]??""} onChangeText={value=>setCollab(current=>({...current,[list.id]:value}))} placeholder="Verified BazID email" placeholderTextColor={groceryPalette.muted2}/><Pressable style={s.secondary} disabled={!collab[list.id]?.trim()||busy===`invite:${list.id}`} onPress={()=>void invite(list)}><Text style={s.secondaryText}>Invite</Text></Pressable></View>{list.collaborators.map(person=><Text key={person.id} style={[s.small,{marginTop:6}]}>{person.displayName||person.email||"BazID member"} · {person.role}</Text>)}</>:null}
  </View>)}
 </Screen>
}
