import {useCallback,useEffect,useState} from "react";
import {Pressable,Text,View} from "react-native";
import {router} from "expo-router";
import {EmptyState,Screen} from "@bazaara/mobile-ui";
import {ApiError,groceryApi} from "@/lib/api";
import {signInWithBazId} from "@/lib/auth";
import {groceryMoney,type GroceryOrder} from "@/lib/grocery";
import {groceryStyles as s} from "@/ui/theme";

export default function GroceryOrders(){const[orders,setOrders]=useState<GroceryOrder[]>([]);const[needAuth,setNeedAuth]=useState(false);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const load=useCallback(async()=>{setLoading(true);try{const body=await groceryApi.get<{orders:GroceryOrder[]}>('/v1/grocery/orders',{cache:'no-store'});setOrders(body.orders);setNeedAuth(false);setError('')}catch(e){if(e instanceof ApiError&&e.status===401)setNeedAuth(true);else setError(e instanceof Error?e.message:'Could not load Grocery orders')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);if(needAuth)return <Screen><Text style={s.h1}>Your Grocery orders</Text><Text style={s.p}>Sign in with BazID to track picking, replacements, delivery and support.</Text><Pressable style={[s.button,{marginTop:16}]} onPress={async()=>{const r=await signInWithBazId('/(tabs)/orders');if(r.ok)await load()}}><Text style={s.buttonText}>Continue with BazID</Text></Pressable></Screen>;return <Screen><View style={s.top}><View><Text style={s.h1}>Orders</Text><Text style={s.p}>Grocery-only order history</Text></View><Pressable onPress={()=>void load()}><Text style={s.status}>REFRESH</Text></Pressable></View>{error?<Text style={s.error}>{error}</Text>:null}{loading&&!orders.length?<Text style={s.p}>Loading orders…</Text>:null}{!loading&&!orders.length?<EmptyState title="No Grocery orders yet" message="Your placed Grocery orders will appear here." action={<Pressable style={s.button} onPress={()=>router.push('/(tabs)')}><Text style={s.buttonText}>Shop groceries</Text></Pressable>}/>:orders.map(o=><Pressable key={o.id} style={[s.card,{marginBottom:10}]} onPress={()=>router.push({pathname:'/order/[id]',params:{id:o.id}})}><View style={[s.row,{justifyContent:'space-between'}]}><View style={{flex:1}}><Text style={s.name}>{o.orderNumber}</Text><Text style={s.meta}>{new Date(o.placedAt).toLocaleString('en-NG')} · {o.deliveryMode.replaceAll('_',' ')}</Text></View><Text style={s.status}>{o.status.replaceAll('_',' ')}</Text></View><View style={[s.row,{justifyContent:'space-between',marginTop:8}]}><Text style={s.p}>{o.sellerOrders.length} store{o.sellerOrders.length===1?'':'s'}</Text><Text style={s.price}>{groceryMoney(o.totalMinor,o.currency)}</Text></View></Pressable>)}</Screen>}
