'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {csv,download,parseCsv} from '../../../packages/flagship-ui/src/core';
import {columnName,displayValue} from '../lib/formulas.mjs';

type Sheet={id:string;name:string;cells:Record<string,string>};
type WorkbookBody={sheets:Sheet[];activeSheetId:string};
type BookSummary={id:string;title:string;revision:number;createdAt:string;updatedAt:string;sheetCount:number;cellCount:number;formulaCount:number};
type Book=BookSummary&{workbook:WorkbookBody};
type SaveState='saved'|'saving'|'dirty'|'error';
const ROWS=50,COLS=18;
const blankBook=():WorkbookBody=>({sheets:[{id:'sheet-1',name:'Sheet 1',cells:{}}],activeSheetId:'sheet-1'});
const templates={
  blank:{title:'Untitled spreadsheet',workbook:blankBook()},
  budget:{title:'Monthly budget',workbook:{sheets:[{id:'sheet-1',name:'Budget',cells:{A1:'Category',B1:'Planned',C1:'Actual',D1:'Variance',A2:'Housing',A3:'Food',A4:'Transport',A5:'Utilities',A6:'Other',A8:'Total',B8:'=SUM(B2:B6)',C8:'=SUM(C2:C6)',D2:'=B2-C2',D3:'=B3-C3',D4:'=B4-C4',D5:'=B5-C5',D6:'=B6-C6',D8:'=SUM(D2:D6)'}}],activeSheetId:'sheet-1'}},
  inventory:{title:'Inventory tracker',workbook:{sheets:[{id:'sheet-1',name:'Inventory',cells:{A1:'Item',B1:'SKU',C1:'Quantity',D1:'Unit cost',E1:'Value',E2:'=C2*D2',E3:'=C3*D3',E4:'=C4*D4',E5:'=C5*D5',A7:'Total value',E7:'=SUM(E2:E5)'}}],activeSheetId:'sheet-1'}}
};
async function json(res:Response){try{return await res.json();}catch{return {message:'Unexpected server response.'}}}
function clone<T>(v:T):T{return JSON.parse(JSON.stringify(v));}
function csvCell(v:string){return /[",\n]/.test(v)?`"${v.replace(/"/g,'""')}"`:v;}
export default function SheetsApp(){
  const [books,setBooks]=useState<BookSummary[]>([]),[active,setActive]=useState<Book|null>(null),[title,setTitle]=useState(''),[workbook,setWorkbook]=useState<WorkbookBody>(blankBook()),[authorized,setAuthorized]=useState(true),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[saveState,setSaveState]=useState<SaveState>('saved'),[query,setQuery]=useState(''),[showTemplates,setShowTemplates]=useState(false),[selected,setSelected]=useState('A1');
  const [rowQuery,setRowQuery]=useState(''),[filterColumn,setFilterColumn]=useState('A'),[highlight,setHighlight]=useState('none'),[chart,setChart]=useState(false),[chartLabel,setChartLabel]=useState('A'),[chartValue,setChartValue]=useState('B');
  const undoStack=useRef<WorkbookBody[]>([]),redoStack=useRef<WorkbookBody[]>([]),[historyTick,setHistoryTick]=useState(0),saveInFlight=useRef<Promise<boolean>|null>(null),lastSaved=useRef({id:'',title:'',serialized:''});
  const saveTimer=useRef<ReturnType<typeof setTimeout>|null>(null),latest=useRef<{id:string;title:string;workbook:WorkbookBody;revision:number}>({id:'',title:'',workbook:blankBook(),revision:0});
  const sheet=workbook.sheets.find(s=>s.id===workbook.activeSheetId)||workbook.sheets[0];
  const raw=sheet?.cells[selected]??'';
  const refresh=useCallback(async()=>{try{const r=await fetch('/api/sheets',{cache:'no-store'}),body=await json(r);if(r.status===401){setAuthorized(false);setBooks([]);setMessage('Sign in with BazID to use Sheets.');return;}if(!r.ok)throw new Error(body.message||'Unable to load Sheets.');setAuthorized(true);setBooks(body.workbooks||[]);setMessage('');}catch(e){setMessage(e instanceof Error?e.message:'Unable to connect to Sheets.');}finally{setLoading(false)}},[]);
  useEffect(()=>{void refresh();return()=>{if(saveTimer.current)clearTimeout(saveTimer.current)}},[refresh]);
  async function saveNow():Promise<boolean>{
    if(saveTimer.current){clearTimeout(saveTimer.current);saveTimer.current=null;}
    while(saveInFlight.current){if(!await saveInFlight.current)return false;}
    const payload={...latest.current,workbook:clone(latest.current.workbook)},serialized=JSON.stringify(payload.workbook);
    if(!payload.id)return true;
    if(lastSaved.current.id===payload.id&&lastSaved.current.title===payload.title&&lastSaved.current.serialized===serialized){setSaveState('saved');return true;}
    setSaveState('saving');
    const operation=(async()=>{try{
      const r=await fetch('/api/sheets/'+payload.id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:payload.title,workbook:payload.workbook,expectedRevision:payload.revision})}),body=await json(r);
      if(r.status===409)throw Error('This workbook changed in another session. Export your current CSV, then reopen it before saving again.');
      if(!r.ok)throw Error(body.message||'Unable to save workbook.');
      lastSaved.current={id:payload.id,title:body.title,serialized};
      if(latest.current.id===payload.id){latest.current.revision=body.revision;const newer=latest.current.title!==payload.title||JSON.stringify(latest.current.workbook)!==serialized;setActive(a=>a?.id===payload.id?{...a,...body,workbook:latest.current.workbook}:a);setSaveState(newer?'dirty':'saved');}
      setBooks(list=>list.map(b=>b.id===body.id?body:b).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)));return true;
    }catch(e){setSaveState('error');setMessage(e instanceof Error?e.message:'Autosave failed.');return false;}})();
    saveInFlight.current=operation;let ok=false;try{ok=await operation;}finally{if(saveInFlight.current===operation)saveInFlight.current=null;}
    if(ok&&latest.current.id===payload.id&&(latest.current.title!==lastSaved.current.title||JSON.stringify(latest.current.workbook)!==lastSaved.current.serialized))return saveNow();
    return ok;
  }
  function dirty(nextTitle=title,nextBook=workbook){if(!active)return;latest.current={id:active.id,title:nextTitle,workbook:nextBook,revision:latest.current.revision};setSaveState('dirty');if(saveTimer.current)clearTimeout(saveTimer.current);saveTimer.current=setTimeout(()=>void saveNow(),800);}
  const open=useCallback(async(id:string)=>{if(saveState!=='saved'&&!await saveNow())return;try{setLoading(true);const r=await fetch(`/api/sheets/${id}`,{cache:'no-store'}),body=await json(r);if(!r.ok)throw new Error(body.message||'Unable to open workbook.');const book=body as Book;setActive(book);setTitle(book.title);setWorkbook(book.workbook);setSelected('A1');latest.current={id:book.id,title:book.title,workbook:book.workbook,revision:book.revision};lastSaved.current={id:book.id,title:book.title,serialized:JSON.stringify(book.workbook)};undoStack.current=[];redoStack.current=[];setHistoryTick(t=>t+1);setSaveState('saved');setMessage('');history.replaceState(null,'',`?sheet=${book.id}`);}catch(e){setMessage(e instanceof Error?e.message:'Unable to open workbook.');}finally{setLoading(false)}},[saveState]);
  useEffect(()=>{if(!authorized||loading||active)return;const id=new URLSearchParams(location.search).get('sheet');if(id&&/^[a-f0-9]{32}$/.test(id))void open(id);},[authorized,loading,active,open]);
  async function create(template:keyof typeof templates='blank'){if(!await saveNow())return;try{const value=templates[template],r=await fetch('/api/sheets',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)}),body=await json(r);if(!r.ok)throw new Error(body.message||'Unable to create workbook.');setShowTemplates(false);await refresh();await open(body.id);}catch(e){setMessage(e instanceof Error?e.message:'Unable to create workbook.');}}
  function changeTitle(v:string){setTitle(v);dirty(v,workbook);}
  useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(latest.current.id&&(latest.current.title!==lastSaved.current.title||JSON.stringify(latest.current.workbook)!==lastSaved.current.serialized)){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[]);
  function commit(next:WorkbookBody){undoStack.current=[...undoStack.current.slice(-99),clone(latest.current.workbook)];redoStack.current=[];setHistoryTick(t=>t+1);setWorkbook(next);dirty(title,next);}
  function undo(){const next=undoStack.current.pop();if(!next)return;redoStack.current.push(clone(workbook));setHistoryTick(t=>t+1);setWorkbook(next);dirty(title,next);}
  function redo(){const next=redoStack.current.pop();if(!next)return;undoStack.current.push(clone(workbook));setHistoryTick(t=>t+1);setWorkbook(next);dirty(title,next);}
  function pasteMatrix(matrix:string[][],at=selected){if(!sheet||!matrix.length)return;const match=at.match(/^([A-Z]+)(\d+)$/)!;const col=cols.indexOf(match[1]),row=Number(match[2])-1;if(col<0||row<0||matrix.length+row>ROWS||matrix.some(r=>r.length+col>COLS)){setMessage('Import or paste exceeds the visible 50-row, 18-column grid. No cells were changed.');return;}const next=clone(workbook),target=next.sheets.find(s=>s.id===sheet.id)!;matrix.forEach((values,r)=>values.forEach((value,c)=>{const ref=columnName(c+col)+(r+row+1);if(value)target.cells[ref]=value;else delete target.cells[ref];}));commit(next);setMessage('Data imported. Formula cells use the supported safe interpreter.');}
  async function importCsv(file:File){try{if(file.size>1000000)throw Error('CSV imports must be under 1 MB.');pasteMatrix(parseCsv(await file.text()),'A1');}catch(e){setMessage(e instanceof Error?e.message:'CSV import failed.');}}
  function sortRows(descending=false){if(!sheet)return;if(Object.keys(sheet.cells).some(ref=>{const m=ref.match(/^([A-Z]+)(\d+)$/);return !m||Number(m[2])>ROWS||!cols.includes(m[1]);})){setMessage('This sheet has cells beyond the visible grid. Sorting was cancelled to preserve them.');return;}const used=Object.keys(sheet.cells).filter(ref=>Number(ref.match(/\d+$/)?.[0])>1);if(used.some(ref=>sheet.cells[ref].startsWith('='))){setMessage('Sorting is available for value-only tables. Export calculated values as CSV and import them into a new sheet to sort without changing formula references.');return;}const values=rows.slice(1).map(r=>cols.map(c=>sheet.cells[c+r]||'')).filter(r=>r.some(Boolean));const index=cols.indexOf(filterColumn);values.sort((a,b)=>{const x=a[index],y=b[index],numeric=x.trim()!==''&&y.trim()!==''&&Number.isFinite(Number(x))&&Number.isFinite(Number(y));return (numeric?Number(x)-Number(y):x.localeCompare(y,undefined,{numeric:true}))*(descending?-1:1);});const next=clone(workbook),target=next.sheets.find(s=>s.id===sheet.id)!;used.forEach(ref=>delete target.cells[ref]);values.forEach((row,r)=>row.forEach((value,c)=>{if(value)target.cells[cols[c]+(r+2)]=value;}));commit(next);}
  function setCell(ref:string,value:string){if(!sheet)return;const next=clone(workbook),target=next.sheets.find(s=>s.id===next.activeSheetId)||next.sheets[0];if(value==='')delete target.cells[ref];else target.cells[ref]=value;commit(next);}
  function setFormula(v:string){setCell(selected,v);}
  function switchSheet(id:string){const next={...workbook,activeSheetId:id};setWorkbook(next);dirty(title,next);setSelected('A1');}
  function addSheet(){if(workbook.sheets.length>=10){setMessage('This alpha supports up to 10 sheets per workbook.');return;}const ids=new Set(workbook.sheets.map(s=>s.id));let n=workbook.sheets.length+1,id=`sheet-${n}`;while(ids.has(id)){n++;id=`sheet-${n}`;}const next={sheets:[...workbook.sheets,{id,name:`Sheet ${n}`,cells:{}}],activeSheetId:id};commit(next);setSelected('A1');}
  function renameSheet(){if(!sheet)return;const name=prompt('Rename sheet',sheet.name)?.trim();if(!name)return;if(workbook.sheets.some(s=>s.id!==sheet.id&&s.name.toLowerCase()===name.toLowerCase())){setMessage('Sheet names must be unique.');return;}const next=clone(workbook);const target=next.sheets.find(s=>s.id===sheet.id)!;target.name=name.slice(0,50);commit(next);}
  function deleteSheet(){if(!sheet||workbook.sheets.length===1)return; if(!confirm(`Delete sheet “${sheet.name}”?`))return;const sheets=workbook.sheets.filter(s=>s.id!==sheet.id),next={sheets,activeSheetId:sheets[0].id};commit(next);setSelected('A1');}
  async function remove(){if(!active||!confirm(`Delete “${title||'Untitled spreadsheet'}” permanently?`))return;if(saveTimer.current){clearTimeout(saveTimer.current);saveTimer.current=null;}while(saveInFlight.current)await saveInFlight.current;try{const r=await fetch(`/api/sheets/${active.id}`,{method:'DELETE'}),body=await json(r);if(!r.ok)throw new Error(body.message||'Unable to delete workbook.');setActive(null);setTitle('');setWorkbook(blankBook());latest.current={id:'',title:'',workbook:blankBook(),revision:0};lastSaved.current={id:'',title:'',serialized:''};history.replaceState(null,'',location.pathname);await refresh();}catch(e){setMessage(e instanceof Error?e.message:'Unable to delete workbook.');}}
  function exportCsv(){if(!sheet)return;let maxRow=1,maxCol=0;for(const ref of Object.keys(sheet.cells)){const m=ref.match(/^([A-Z]+)(\d+)$/);if(!m)continue;maxRow=Math.max(maxRow,Number(m[2]));let idx=0;for(const c of m[1])idx=idx*26+c.charCodeAt(0)-64;maxCol=Math.max(maxCol,idx-1);}if(maxRow*(maxCol+1)>10000){setMessage('CSV export exceeds the 10,000-cell limit.');return;}const values=[];for(let r=1;r<=maxRow;r++){const row=[];for(let c=0;c<=maxCol;c++){const value=displayValue(sheet.cells,columnName(c)+r);row.push(value!==''&&Number.isFinite(Number(value))?Number(value):value);}values.push(row);}download((title||'spreadsheet')+'-'+sheet.name+'.csv',csv(values),'text/csv;charset=utf-8');}

  const filtered=books.filter(b=>b.title.toLowerCase().includes(query.trim().toLowerCase()));
  const status=saveState==='saved'?'Saved':saveState==='saving'?'Saving…':saveState==='dirty'?'Unsaved changes':'Save problem';
  const cols=useMemo(()=>Array.from({length:COLS},(_,i)=>columnName(i)),[]),rows=useMemo(()=>Array.from({length:ROWS},(_,i)=>i+1),[]);
  return <div className="shell">
    <aside className="rail"><a className="brand" href="http://localhost:3021"><span className="mark">▥</span><span>BAZAARA <b>Sheets</b><small>ECOSYSTEM 03</small></span></a><button className="new" onClick={()=>setShowTemplates(v=>!v)} disabled={!authorized}>＋ New spreadsheet</button>
      {showTemplates&&<div className="template-menu"><button onClick={()=>void create('blank')}><b>Blank workbook</b><span>Start with an empty grid</span></button><button onClick={()=>void create('budget')}><b>Monthly budget</b><span>Plan, actual and variance formulas</span></button><button onClick={()=>void create('inventory')}><b>Inventory tracker</b><span>Quantity, cost and value formulas</span></button></div>}
      <label className="book-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find spreadsheets"/></label>
      <div className="book-list">{loading&&!books.length?<div className="rail-empty">Loading…</div>:filtered.map(b=><button className={active?.id===b.id?'book-item active':'book-item'} key={b.id} onClick={()=>void open(b.id)}><span className="book-icon">▥</span><span><b>{b.title}</b><small>{b.sheetCount} sheet{b.sheetCount===1?'':'s'} · {b.cellCount} cells</small></span></button>)}{!loading&&authorized&&!filtered.length&&<div className="rail-empty">{query?'No matches':'Create your first spreadsheet.'}</div>}</div>
      <div className="rail-links"><a href="http://localhost:3022">Box ↗</a><a href="http://localhost:3023">Docs ↗</a><a href="http://localhost:3021">Workspace ↗</a></div>
    </aside>
    <main className="main"><header className="topbar"><div className="mobile-brand">BAZAARA Sheets</div><div className="top-actions"><span className={`save ${saveState}`}>{status}</span><span className="alpha">LOCAL ALPHA</span><a href="http://localhost:3004/account">BazID ↗</a></div></header>
      {message&&<div className="alert"><span>{message}</span><button onClick={()=>setMessage('')}>×</button></div>}
      {!active?<section className="welcome"><span className="eyebrow">PRODUCTIVITY · ECOSYSTEM 3</span><h1>Data that stays connected.</h1><p>Create structured spreadsheets with autosave, safe formulas and Box-backed storage under your BazID identity.</p><div className="welcome-actions"><button onClick={()=>void create('blank')} disabled={!authorized}>Create blank spreadsheet</button><button onClick={()=>setShowTemplates(true)} disabled={!authorized}>Choose a template</button></div><div className="feature-row"><div><span>01</span><b>Safe formulas</b><p>Arithmetic and core aggregate functions without JavaScript eval.</p></div><div><span>02</span><b>Autosave</b><p>Optimistic revision protection prevents stale sessions overwriting newer work.</p></div><div><span>03</span><b>Box-backed</b><p>Workbook bodies are stored as private .bsheet objects through Bazaara Box.</p></div></div></section>:
      <section className="workspace"><div className="book-header"><input aria-label="Workbook title" value={title} maxLength={100} onChange={e=>changeTitle(e.target.value)}/><div><button onClick={undo} disabled={!undoStack.current.length}>Undo</button><button onClick={redo} disabled={!redoStack.current.length}>Redo</button><button onClick={()=>void saveNow()}>Save now</button><label className="bf-button">Import CSV<input type="file" accept=".csv,text/csv" hidden onChange={e=>{const f=e.currentTarget.files?.[0];e.currentTarget.value='';if(f)void importCsv(f);}}/></label><button onClick={exportCsv}>Export CSV</button><button className="danger" onClick={()=>void remove()}>Delete</button></div></div>
        <div className="bf-root" style={{minHeight:0,padding:12,borderRadius:10}}><div className="bf-toolbar"><select aria-label="Filter or sort column" value={filterColumn} onChange={e=>setFilterColumn(e.target.value)}>{cols.map(c=><option key={c}>{c}</option>)}</select><input aria-label="Filter rows" value={rowQuery} placeholder="Filter rows in this column" onChange={e=>setRowQuery(e.target.value)}/><button onClick={()=>sortRows(false)}>Sort ascending</button><button onClick={()=>sortRows(true)}>Sort descending</button><select aria-label="Conditional highlight" value={highlight} onChange={e=>setHighlight(e.target.value)}><option value="none">No conditional colors</option><option value="negative">Highlight negative numbers</option><option value="positive">Highlight positive numbers</option></select><button aria-pressed={chart} onClick={()=>setChart(!chart)}>Bar chart</button></div>{chart&&<><div className="bf-toolbar"><label>Labels <select aria-label="Chart labels" value={chartLabel} onChange={e=>setChartLabel(e.target.value)}>{cols.map(c=><option key={c}>{c}</option>)}</select></label><label>Values <select aria-label="Chart values" value={chartValue} onChange={e=>setChartValue(e.target.value)}>{cols.map(c=><option key={c}>{c}</option>)}</select></label><span>First 12 numeric data rows</span></div><SheetChart cells={sheet?.cells||{}} labels={chartLabel} values={chartValue}/></>}</div>
        <div className="formula-bar"><div className="cell-name">{selected}</div><span>fx</span><input value={raw} onChange={e=>setFormula(e.target.value)} placeholder="Enter a value or formula, e.g. =SUM(A1:A5)"/></div>
        <div className="grid-wrap"><div className="sheet-grid" style={{gridTemplateColumns:`52px repeat(${COLS}, minmax(92px, 1fr))`}}><div className="corner"/>{cols.map(c=><div className="col-head" key={c}>{c}</div>)}{rows.filter(r=>r===1||!rowQuery||String(displayValue(sheet?.cells||{},filterColumn+r)).toLowerCase().includes(rowQuery.toLowerCase())).map(r=><div key={`row-${r}`} className="row-fragment" style={{display:'contents'}}><div className="row-head">{r}</div>{cols.map(c=>{const ref=`${c}${r}`,cellRaw=sheet?.cells[ref]??'',display=displayValue(sheet?.cells||{},ref),isSelected=selected===ref;return <input key={ref} aria-label={`Cell ${ref}`} className={`cell ${isSelected?'selected':''} ${cellRaw.startsWith('=')?'formula':''}`} value={isSelected?cellRaw:String(display)} style={highlight!=='none'&&display!==''&&Number.isFinite(Number(display))&&((highlight==='negative'&&Number(display)<0)||(highlight==='positive'&&Number(display)>0))?{background:highlight==='negative'?'#4b233c':'#153f45',color:'#fff'}:undefined} onPaste={e=>{const text=e.clipboardData.getData('text/plain');if(text.includes('\t')||text.includes('\n')){e.preventDefault();pasteMatrix(text.replace(/\r/g,'').replace(/\n$/,'').split('\n').map(r=>r.split('\t')),ref);}}} onFocus={()=>setSelected(ref)} onChange={e=>{setSelected(ref);setCell(ref,e.target.value)}}/>})}</div>)}</div></div>
        <div className="sheet-tabs"><div className="tabs-scroll">{workbook.sheets.map(s=><button key={s.id} className={s.id===workbook.activeSheetId?'active':''} onClick={()=>switchSheet(s.id)}>{s.name}</button>)}</div><button onClick={addSheet} title="Add sheet">＋</button><button onClick={renameSheet} title="Rename current sheet">✎</button><button onClick={deleteSheet} disabled={workbook.sheets.length===1} title="Delete current sheet">−</button></div>
        <div className="statusbar"><span>{active.cellCount} populated cells · {active.formulaCount} formulas</span><span>Functions: SUM · AVERAGE · MIN · MAX · COUNT · COUNTA · IF · IFERROR · ROUND · ABS · AND · OR · NOT · CONCAT · LEN · LOWER · UPPER · TRIM</span></div></section>}
    </main>
  </div>;
}

function SheetChart({cells,labels,values}:{cells:Record<string,string>;labels:string;values:string}){
 const points=Array.from({length:49},(_,i)=>i+2).map(r=>({label:String(displayValue(cells,labels+r)),raw:displayValue(cells,values+r)})).filter(p=>p.raw!==''&&Number.isFinite(Number(p.raw))).slice(0,12).map(p=>({...p,value:Number(p.raw)}));if(!points.length)return <p>No numeric values for this chart.</p>;
 const min=Math.min(0,...points.map(p=>p.value)),max=Math.max(0,...points.map(p=>p.value)),range=max-min||1,y=(v:number)=>180-(v-min)/range*150,zero=y(0),width=540/points.length;
 return <svg viewBox="0 0 600 250" role="img" aria-label={'Bar chart: '+points.map(p=>p.label+' '+p.value).join(', ')} style={{width:'100%',maxWidth:700}}><line x1="40" x2="590" y1={zero} y2={zero} stroke="#8793ac"/>{points.map((p,i)=><g key={i}><rect x={45+i*width} y={Math.min(zero,y(p.value))} width={Math.max(5,width-8)} height={Math.max(1,Math.abs(zero-y(p.value)))} fill={p.value<0?'#e39bcc':'#98b0ff'}/><text x={45+i*width} y={210} fill="#eef2ff" fontSize="10">{p.label.slice(0,9)||i+1}</text><text x={45+i*width} y={235} fill="#b9c7df" fontSize="10">{p.value}</text></g>)}</svg>;
}
