import {useCallback,useEffect,useState} from "react";
import {Pressable,Text,TextInput,View} from "react-native";
import {router,useLocalSearchParams} from "expo-router";
import {EmptyState,Screen} from "@bazaara/mobile-ui";
import {groceryApi} from "@/lib/api";
import {signInWithBazId} from "@/lib/auth";
import {groceryMoney} from "@/lib/grocery";
import {groceryStyles as s} from "@/ui/theme";

type Group={id:string;shareToken:string;status:string;spendingLimitMinor:number|null;expiresAt:string;itemCount?:number;members:Array<{id:string;displayName:string;role:string;status:string;paymentAllocationMinor:number|null}>;settlementNote?:string};
export default function GroceryGroupJoin(){const{token}=useLocalSearchParams<{token:string}>();const[group,setGroup]=useState<Group|null>(null);const[name,setName]=useState('');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[joined,setJoined]=useState(false);const load=useCallback(async()=>{if(!token)return;try{const b=await groceryApi.get<{group:Group}>(`/v1/grocery/group-carts/${encodeURIComponent(token)}`,{cache:'no-store'});setGroup(b.group);setError('')}catch(e){setError(e instanceof Error?e.message:'This group basket is unavailable')}},[token]);useEffect(()=>{void load()},[load]);async function join(){if(!token||!name.trim())return;setBusy(true);setError('');try{const signed=await signInWithBazId(`/group/${token}`);if(!signed.ok)return;const g=await groceryApi.post<Group>(`/v1/grocery/group-carts/join/${encodeURIComponent(token)}`,{displayName:name.trim()});setGroup(g);setJoined(true)}catch(e){setError(e instanceof Error?e.message:'Could not join group basket')}finally{setBusy(false)}}if(!group)return <Screen tabBarSafe={false}><EmptyState title="Group Grocery basket" message={error||'Loading invitation…'}/></Screen>;return <Screen tabBarSafe={false}><Text style={s.status}>HOUSEHOLD SHOPPING</Text><Text style={s.h1}>Join the shared basket</Text><Text style={s.p}>Your existing Grocery basket is merged into the host basket where stock allows. Everyone then shops against the same live cart.</Text>{error?<Text style={[s.error,{marginTop:8}]}>{error}</Text>:null}<View style={[s.card,{marginTop:14}]}><View style={[s.row,{justifyContent:'space-between'}]}><Text style={s.p}>Items</Text><Text style={s.name}>{group.itemCount??'—'}</Text></View><View style={[s.row,{justifyContent:'space-between',marginTop:7}]}><Text style={s.p}>Members</Text><Text style={s.name}>{group.members.length}</Text></View>{group.spendingLimitMinor!=null?<View style={[s.row,{justifyContent:'space-between',marginTop:7}]}><Text style={s.p}>Spending limit</Text><Text style={s.name}>{groceryMoney(group.spendingLimitMinor)}</Text></View>:null}<Text style={[s.small,{marginTop:8}]}>Expires {new Date(group.expiresAt).toLocaleString('en-NG')}</Text></View>{joined?<><Text style={[s.success,{marginTop:14}]}>Joined. Grocery cart actions now use the shared basket.</Text><Pressable style={[s.button,{marginTop:12}]} onPress={()=>router.replace('/cart')}><Text style={s.buttonText}>Open shared basket</Text></Pressable></>:<><Text style={[s.label,{marginTop:14}]}>Your display name</Text><TextInput style={s.input} value={name} onChangeText={setName} placeholder="Your name" placeholderTextColor="#777D77"/><Pressable style={[s.button,{marginTop:10}]} disabled={busy||!name.trim()} onPress={()=>void join()}><Text style={s.buttonText}>{busy?'Joining…':'Continue with BazID & join'}</Text></Pressable></>}<Text style={[s.small,{marginTop:12}]}>{group.settlementNote??'Split allocations coordinate who owes what; external multi-party payment is not simulated.'}</Text></Screen>}
