"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { createApiClient } from "@bazaara/api-client";
import styles from "./support.module.css";
const API=(process.env.NEXT_PUBLIC_API_BASE_URL??"http://localhost:4000").replace(/\/$/,""); const api=createApiClient({baseUrl:API,credentials:"include"});
type Message={id:string;kind:string;body:string;createdAt:string;author?:{displayName:string|null}|null};type Case={id:string;category:string;subject:string;description:string;status:string;priority:string;orderId:string|null;lastActivityAt:string;messages:Message[]};
const categories=["ORDER","DELIVERY","PAYMENT","RETURN","PRODUCT","ACCOUNT","OTHER"] as const;
export default function SupportPage(){
 const[requested,setRequested]=useState<string|undefined>(),[cases,setCases]=useState<Case[]>([]),[selected,setSelected]=useState<string|undefined>(),[error,setError]=useState(""),[busy,setBusy]=useState("");const[category,setCategory]=useState<(typeof categories)[number]>("ORDER"),[subject,setSubject]=useState(""),[description,setDescription]=useState(""),[reply,setReply]=useState("");
 useEffect(()=>{const value=new URLSearchParams(window.location.search).get("case")??undefined;setRequested(value);if(value)setSelected(value);},[]);
 const current=useMemo(()=>cases.find(item=>item.id===selected),[cases,selected]);const load=useCallback(async()=>{try{const body=await api.get<{cases:Case[]}>("/v1/support/cases",{cache:"no-store"});setCases(body.cases);if(requested&&body.cases.some(item=>item.id===requested))setSelected(requested);}catch(cause){setError(cause instanceof Error?cause.message:"Could not load support cases");}},[requested]);useEffect(()=>{void load();},[load]);
 async function create(e:FormEvent){e.preventDefault();setBusy("create");setError("");try{const body=await api.post<{case:Case}>("/v1/support/cases",{category,subject:subject.trim(),description:description.trim()});setCases(v=>[body.case,...v]);setSelected(body.case.id);setSubject("");setDescription("");}catch(cause){setError(cause instanceof Error?cause.message:"Could not create support case");}finally{setBusy("");}}
 async function send(e:FormEvent){e.preventDefault();if(!current||!reply.trim())return;setBusy("reply");try{const body=await api.post<{case:Case}>(`/v1/support/cases/${encodeURIComponent(current.id)}/messages`,{body:reply.trim()});setCases(v=>v.map(item=>item.id===body.case.id?body.case:item));setReply("");}catch(cause){setError(cause instanceof Error?cause.message:"Could not send reply");}finally{setBusy("");}}
 async function escalate(){if(!current)return;setBusy("escalate");try{const body=await api.post<{case:Case}>(`/v1/support/cases/${encodeURIComponent(current.id)}/escalate`,{reason:"Customer requested additional review from Shopping support"});setCases(v=>v.map(item=>item.id===body.case.id?body.case:item));}catch(cause){setError(cause instanceof Error?cause.message:"Could not escalate case");}finally{setBusy("");}}
 return <main className={styles.page}><div className={styles.wrap}><header className={styles.header}><div><p>SHOPPING</p><h1>Help & support</h1><span>Contextual assistance for orders, deliveries, payments and returns.</span></div><Link href="/account">Account</Link></header>{error?<div className={styles.error}>{error}<button onClick={()=>setError("")}>×</button></div>:null}{current?<section className={styles.detail}><button className={styles.back} onClick={()=>setSelected(undefined)}>‹ All support cases</button><div className={styles.caseHead}><div><span>{current.category}</span><h2>{current.subject}</h2><p>{current.status.replaceAll("_"," ")} · {current.priority}</p></div>{current.orderId?<Link href={`/orders/${encodeURIComponent(current.orderId)}`}>View order</Link>:null}</div><div className={styles.messages}>{current.messages.map(message=><article key={message.id} className={`${styles.message} ${message.kind==="CUSTOMER"?styles.customer:""}`}><div><strong>{message.kind==="CUSTOMER"?"You":message.author?.displayName??"Bazaara Support"}</strong><time>{new Date(message.createdAt).toLocaleString("en-NG")}</time></div><p>{message.body}</p></article>)}</div>{current.status!=="CLOSED"?<form onSubmit={send} className={styles.reply}><label>Reply<textarea value={reply} onChange={e=>setReply(e.target.value)} required maxLength={4000}/></label><div><button disabled={busy==="reply"}>{busy==="reply"?"Sending…":"Send reply"}</button><button type="button" className={styles.secondary} disabled={busy==="escalate"} onClick={()=>void escalate()}>Escalate</button></div></form>:null}</section>:<div className={styles.grid}><section className={styles.panel}><h2>Start a support case</h2><form onSubmit={create}><label>Issue category<select value={category} onChange={e=>setCategory(e.target.value as typeof category)}>{categories.map(item=><option key={item}>{item}</option>)}</select></label><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)} minLength={3} maxLength={160} required/></label><label>What happened?<textarea value={description} onChange={e=>setDescription(e.target.value)} minLength={3} maxLength={4000} required/></label><button disabled={busy==="create"}>{busy==="create"?"Creating…":"Create case"}</button></form></section><section><div className={styles.listHead}><h2>Your cases</h2><button onClick={()=>void load()}>Refresh</button></div><div className={styles.list}>{cases.length===0?<div className={styles.empty}>No support cases yet.</div>:cases.map(item=><button key={item.id} onClick={()=>setSelected(item.id)} className={styles.caseRow}><span>{item.category}</span><strong>{item.subject}</strong><small>{item.status.replaceAll("_"," ")} · {new Date(item.lastActivityAt).toLocaleDateString("en-NG")}</small></button>)}</div></section></div>}</div></main>;
}
