'use client';
import {useEffect,useRef,useState,type ChangeEvent,type FormEvent} from 'react';
import StandaloneFrame from './StandaloneFrame';
import InternetWorkspace from './InternetWorkspace';
import {translationChunks,translationRequest} from '../../../packages/smart-ui/src/translation';
import {Dialog,Field,ToolRow,download,useCollection} from '../../../packages/flagship-ui/src/core';
import {LANGUAGES} from './languageCatalog';

type Entry={id:string;original:string;translation:string;from:string;to:string;at:string;folder?:string};
type Selector='source'|'target'|null;
type LiveMode='Listening'|'Conversation'|'Text only';
const historyKey='bazaara-translate-recent-v8';
function validEntry(v:unknown):v is Entry{const e=v as Entry;return !!e&&['id','original','translation','from','to','at'].every(k=>typeof (e as unknown as Record<string,unknown>)[k]==='string')&&(e.folder===undefined||typeof e.folder==='string');}
function label(code:string){return LANGUAGES.find(item=>item[0]===code)?.[1]||code;}
function appUrl(slug:string,port:number){if(typeof window==='undefined')return '#';try{const urls=JSON.parse(process.env.NEXT_PUBLIC_BAZAARA_APP_URLS||'{}') as Record<string,string>;if(typeof urls[slug]==='string'&&/^https:\/\//.test(urls[slug]))return urls[slug];}catch{}const h=window.location.hostname;return ['localhost','127.0.0.1','::1'].includes(h)?`${window.location.protocol}//${h.includes(':')?`[${h}]`:h}:${port}/`:'#';}

type Rec={start():void;stop():void;abort?():void;lang:string;continuous?:boolean;interimResults?:boolean;onresult:((e:{results:ArrayLike<ArrayLike<{transcript:string;confidence?:number}>&{isFinal?:boolean}>;resultIndex?:number})=>void)|null;onerror:(()=>void)|null;onend:(()=>void)|null};
function recognition():Rec|null{const w=window as typeof window&{SpeechRecognition?:new()=>Rec;webkitSpeechRecognition?:new()=>Rec};const C=w.SpeechRecognition||w.webkitSpeechRecognition;return C?new C():null;}

export default function TranslateExperience(){
 const [tab,setTab]=useState('Text'),[source,setSource]=useState('auto'),[target,setTarget]=useState('es'),[selector,setSelector]=useState<Selector>(null),[filter,setFilter]=useState(''),[favorites,setFavorites]=useState<string[]>(['en','es']),[text,setText]=useState(''),[output,setOutput]=useState(''),[provider,setProvider]=useState(false),[working,setWorking]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[history,setHistory]=useState<Entry[]>([]),[site,setSite]=useState(''),[liveMode,setLiveMode]=useState<LiveMode>('Listening'),[listening,setListening]=useState(false),[liveText,setLiveText]=useState(''),[inputLang,setInputLang]=useState<'source'|'target'>('source'),[lens,setLens]=useState('#'),[transcribing,setTranscribing]=useState(false),[transcript,setTranscript]=useState(''),[interim,setInterim]=useState(''),[large,setLarge]=useState(false);
 const phrases=useCollection<Entry>('translate-phrases-v2',validEntry);const [phraseQuery,setPhraseQuery]=useState(''),[phraseFolder,setPhraseFolder]=useState(''),[phrase,setPhrase]=useState<Entry|null>(null),[doc,setDoc]=useState<{name:string;text:string;translation:string}|null>(null),[progress,setProgress]=useState(''),[compareTargets,setCompareTargets]=useState<string[]>(['en','fr','es']),[compared,setCompared]=useState<{language:string;text:string}[]>([]);const job=useRef<AbortController|null>(null);
 const fileRef=useRef<HTMLInputElement>(null);const recognizer=useRef<Rec|null>(null);const transcriber=useRef<Rec|null>(null);
 useEffect(()=>{setLens(appUrl('bazlens',3041));try{const h=JSON.parse(localStorage.getItem(historyKey)||'[]') as Entry[];if(Array.isArray(h))setHistory(h.filter(validEntry).slice(0,50));const f=JSON.parse(localStorage.getItem('bazaara-translate-favorites-v8')||'[]') as string[];if(Array.isArray(f)&&f.length)setFavorites(f.filter(x=>typeof x==='string').slice(0,20));}catch{}void fetch('/api/translate',{cache:'no-store'}).then(r=>r.json()).then((v:{configured?:boolean})=>setProvider(v.configured===true)).catch(()=>setProvider(false));return()=>{job.current?.abort();recognizer.current?.abort?.();recognizer.current?.stop();transcriber.current?.stop();window.speechSynthesis?.cancel();};},[]);
 function swap(){if(source==='auto'){setNotice('Choose a source language to swap.');return;}setSource(target);setTarget(source);setText(output);setOutput(text);}
 function copy(value:string){if(!navigator.clipboard){setNotice('Select and copy text manually.');return;}void navigator.clipboard.writeText(value).then(()=>setNotice('Copied')).catch(()=>setNotice('Clipboard is unavailable.'));}
 function speak(value:string,lang:string){if(!value.trim())return;if(!('speechSynthesis'in window)){setNotice('Speech playback is unavailable in this browser.');return;}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(value.slice(0,5000));u.lang=lang==='auto'?'en':lang;window.speechSynthesis.speak(u);}
 useEffect(()=>{job.current?.abort();setWorking(false);},[text,source,target,tab]);
 async function translateText(original:string,from:string,to:string,saveHistory=true){if(!provider){setError('Connect your translation provider to translate.');return;}if(!original.trim())return;job.current?.abort();const controller=new AbortController();job.current=controller;setWorking(true);setError('');try{const translated=await translationRequest(original,from,to,controller.signal);if(controller.signal.aborted)return;setOutput(translated);if(saveHistory){const item:Entry={id:crypto.randomUUID(),original,translation:translated,from,to,at:new Date().toISOString()};setHistory(old=>{const next=[item,...old].slice(0,50);try{localStorage.setItem(historyKey,JSON.stringify(next));}catch{setNotice('Translation completed, but history could not be saved.');}return next;});}if(tab==='Live'&&liveMode==='Conversation')speak(translated,to);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Translation is unavailable.');}finally{if(job.current===controller)setWorking(false);}}
 async function translateDocument(){if(!doc||!provider)return;job.current?.abort();const controller=new AbortController();job.current=controller;setWorking(true);setError('');setDoc({...doc,translation:''});try{const chunks=translationChunks(doc.text),translated:string[]=[];for(let i=0;i<chunks.length;i++){setProgress(`Translating part ${i+1} of ${chunks.length}`);translated.push(chunks[i].trim()?await translationRequest(chunks[i],source,target,controller.signal):chunks[i]);if(controller.signal.aborted)return;}setDoc({...doc,translation:translated.join('\n')});setNotice('Every document part was translated. Review formatting before exporting.');}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Document translation failed.');}finally{if(job.current===controller){setWorking(false);setProgress('');}}}
 async function compare(){if(!text.trim()||!provider)return;job.current?.abort();const controller=new AbortController();job.current=controller;setWorking(true);setError('');setCompared([]);try{const result:{language:string;text:string}[]=[];for(const language of compareTargets){result.push({language,text:await translationRequest(text,source,language,controller.signal)});if(controller.signal.aborted)return;}setCompared(result);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Comparison failed.');}finally{if(job.current===controller)setWorking(false);}}
 function bookmark(entry?:Entry){const item=entry||{id:crypto.randomUUID(),original:text,translation:output,from:source,to:target,at:new Date().toISOString(),folder:'General'};setPhrase({...item,folder:item.folder||'General'});}
 async function save(){if(!text.trim()&&!transcript.trim())return;const original=(tab==='Transcribe'?transcript:text).trim();setWorking(true);try{const body='BZ_INTERNET_1|'+JSON.stringify({v:2,source,target,original,translated:output,mode:tab,notes:''});if(body.length>9000)throw Error('Entry too large. Save shorter text.');const response=await fetch('/api/items',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({title:original.slice(0,90),body})});if(!response.ok)throw Error('Could not save translation.');setNotice('Saved to your translation library.');}catch(e){setError(e instanceof Error?e.message:'Save failed.');}finally{setWorking(false);}}
 async function imported(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(!/\.(txt|md|csv)$/i.test(file.name)){setError('Choose a TXT, MD or CSV document.');return;}if(file.size>500000){setError('Choose a document smaller than 500 KB.');return;}const txt=await file.text();if(txt.length>50000){setError('This document exceeds the 50,000-character translation limit. Split it before importing.');return;}if(!txt.trim()){setError('This document is empty.');return;}setDoc({name:file.name,text:txt,translation:''});setNotice(`Loaded all ${txt.length.toLocaleString()} characters from ${file.name}.`);}
 function voice(lang:'source'|'target'='source'){if(listening){recognizer.current?.stop();setListening(false);return;}const r=recognition();if(!r){setError('Voice recognition is not available in this browser.');return;}r.lang=(lang==='source'?source:target)==='auto'?(navigator.language||'en-US'):(lang==='source'?source:target);setInputLang(lang);r.onresult=e=>{const spoken=e.results[0]?.[0]?.transcript||'';if(!spoken.trim())return;setLiveText(spoken);if(tab==='Live')void translateText(spoken,lang==='source'?source:target,lang==='source'?target:source);else{setText(spoken);setOutput('');setTab('Text');}};r.onerror=()=>{setListening(false);setError('Microphone recognition failed. Check microphone permissions.');};r.onend=()=>setListening(false);recognizer.current=r;try{r.start();setListening(true);}catch{setError('Could not start speech recognition.');}}
 function toggleTranscribe(){if(transcribing){transcriber.current?.stop();setTranscribing(false);return;}const r=recognition();if(!r){setError('Live transcription is unavailable in this browser.');return;}r.lang=source==='auto'?(navigator.language||'en-US'):source;r.continuous=true;r.interimResults=true;r.onresult=e=>{let finals='';let temp='';for(let i=e.resultIndex||0;i<e.results.length;i++){const row=e.results[i];const phrase=row?.[0]?.transcript||'';if((row as {isFinal?:boolean}).isFinal)finals+=phrase+' ';else temp+=phrase;}if(finals)setTranscript(value=>(value+' '+finals).replace(/\s+/g,' ').trim().slice(0,8000));setInterim(temp.slice(0,1200));};r.onerror=()=>{setTranscribing(false);setError('Transcription stopped. Check microphone permission or language support.');};r.onend=()=>setTranscribing(false);transcriber.current=r;try{r.start();setTranscribing(true);setError('');}catch{setError('Could not start transcription.');}}
 const langs=LANGUAGES.filter(([code])=>selector==='source'||code!=='auto').filter(([,name])=>name.toLowerCase().includes(filter.toLowerCase())).sort((a,b)=>Number(favorites.includes(b[0]))-Number(favorites.includes(a[0])));
 function toggleFavorite(code:string){setFavorites(old=>{const next=old.includes(code)?old.filter(x=>x!==code):[...old,code].slice(0,20);try{localStorage.setItem('bazaara-translate-favorites-v8',JSON.stringify(next));}catch{}return next;});}
 const tabs=['Text','Live','Transcribe','Camera','Documents','Websites','History','Phrasebook','Compare','Saved'];
 return <StandaloneFrame product="Translate" tagline="" tabs={tabs} active={tab} onTab={next=>{setTab(next);setError('');}} actions={<button className="ig5-top-icon" type="button" aria-label="Favorite languages" onClick={()=>{setFilter('');setSelector('target');}}>☆</button>}>
  {notice&&<div className="gt5-notice bz8-notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss">×</button></div>}
  {error&&<div className="gt5-error bz8-error" role="alert">{error}</div>}

  {selector&&<div className="gt5-language-modal bz8-modal bz83-language-modal" role="dialog" aria-modal="true" aria-label={`Translate ${selector==='source'?'from':'to'} language`}>
    <header><button className="gt5-back" onClick={()=>setSelector(null)} aria-label="Close language picker">←</button><div><small>LANGUAGE</small><strong>Translate {selector==='source'?'from':'to'}</strong></div><button onClick={()=>setSelector(null)} aria-label="Close">×</button></header>
    <div className="gt5-filter"><span>⌕</span><input autoFocus placeholder="Search languages" value={filter} onChange={e=>setFilter(e.target.value)}/></div>
    <div className="gt5-language-list">{langs.map(([code,name])=><div key={code} className="gt5-language-row"><button className="gt5-lang-select" onClick={()=>{if(selector==='source')setSource(code);else setTarget(code);setSelector(null);setFilter('');setOutput('');}}>{name}{(selector==='source'?source:target)===code&&<span>✓</span>}</button><button className="gt5-lang-star" onClick={()=>toggleFavorite(code)} aria-label={`${favorites.includes(code)?'Unfavorite':'Favorite'} ${name}`}>{favorites.includes(code)?'★':'☆'}</button></div>)}</div>
    <p className="gt5-language-note">Text, speech, live translation and camera translation may support different language sets.</p>
  </div>}

  {tab==='Text'&&<div className="bz83-translate-home">
    <section className="bz83-translate-canvas">
      <div className="bz83-translate-title-row"><div><small>BAZAARA TRANSLATE</small><h1>Translate text</h1></div><button className="bz83-paste" onClick={()=>{if(navigator.clipboard)void navigator.clipboard.readText().then(v=>{setText(v.slice(0,5000));setOutput('');}).catch(()=>setNotice('Clipboard access denied.'));}}>▣ <span>Paste</span></button></div>
      <div className="bz83-translate-editor">
        <div className="bz83-translate-input"><textarea aria-label="Text to translate" value={text} maxLength={5000} onChange={e=>{setText(e.target.value);setOutput('');setError('');}} placeholder="Enter text"/><div className="bz83-editor-tools"><span>{text.length}/5,000</span><button disabled={!text} onClick={()=>speak(text,source)} aria-label="Listen to source">◖))</button><button disabled={!text} onClick={()=>{setText('');setOutput('');}} aria-label="Clear">×</button></div></div>
        <div className={`bz83-translate-output ${output?'has-output':''} ${large?'bs-large-translation':''}`} dir={['ar','he','fa','ur'].includes(target)?'rtl':'auto'} aria-live="polite">{output?<><div className="bz83-output-head"><span>{label(target)}</span><button onClick={()=>setLarge(value=>!value)}>{large?'Exit large text':'⛶'}</button></div><p>{output}</p><div className="bz83-output-actions"><button onClick={()=>speak(output,target)}>◖)) Listen</button><button onClick={()=>copy(output)}>▣ Copy</button><button onClick={()=>void save()} disabled={working}>Save to library</button><button onClick={()=>bookmark()}>☆ Phrasebook</button></div></>:<div className="bz83-output-empty"><span>✨</span><p>Your translation appears here</p></div>}</div>
      </div>
    </section>

    <div className="bz83-language-switcher"><button onClick={()=>{setFilter('');setSelector('source');}}><small>FROM</small><strong>{label(source)}</strong></button><button className="bz83-swap" aria-label="Swap languages" onClick={swap}>⇄</button><button onClick={()=>{setFilter('');setSelector('target');}}><small>TO</small><strong>{label(target)}</strong></button></div>

    <div className="bz83-translate-primary-actions">
      <button onClick={()=>setTab('Live')}><span>◉</span><strong>Live translate</strong><small>Listen or converse</small></button>
      <button className={`bz83-main-mic ${listening?'is-live':''}`} onClick={()=>voice()} aria-pressed={listening}><span>{listening?'■':'🎙'}</span><strong>{listening?'Listening…':'Voice'}</strong></button>
      <button onClick={()=>setTab('Camera')}><span>▣</span><strong>Camera</strong><small>Translate what you see</small></button>
    </div>

    <button className="bz83-translate-go" onClick={()=>void translateText(text,source,target)} disabled={!text.trim()||working||!provider}>{working?'Translating…':provider?'Translate':'Connect translation provider'}</button>
    <p className="bz83-capability-note">Translation is provider-backed. Voice recognition, live speech and camera input are separate capabilities and are never simulated.</p>
  </div>}

  {tab==='Live'&&<div className="bz83-live-page">
    <div className="bz83-live-head"><button onClick={()=>setTab('Text')} aria-label="Back">←</button><div><small>LIVE TRANSLATE</small><h1>Understand speech in real time</h1></div></div>
    <div className="bz83-live-language"><button onClick={()=>setSelector('source')}><small>Their language</small><strong>{label(source)}</strong></button><button onClick={swap} aria-label="Swap">⇄</button><button onClick={()=>setSelector('target')}><small>Your language</small><strong>{label(target)}</strong></button></div>
    <div className="bz83-live-visual" aria-hidden="true"><div className="bz83-live-orb"><span>◖))</span></div><div><strong>{listening?'Listening now':'Ready when you are'}</strong><small>{liveMode==='Listening'?'Hear translated speech':liveMode==='Conversation'?'Take turns speaking':'Read translations without playback'}</small></div></div>
    <div className="bz83-live-modes">{(['Listening','Conversation','Text only'] as LiveMode[]).map(mode=><button key={mode} aria-pressed={liveMode===mode} onClick={()=>setLiveMode(mode)}><span>{mode==='Listening'?'◖))':mode==='Conversation'?'⇄':'≡'}</span><div><strong>{mode}</strong><small>{mode==='Listening'?'Listen to translated audio':mode==='Conversation'?'Translations play aloud':'Read translations silently'}</small></div>{liveMode===mode&&<b>✓</b>}</button>)}</div>
    {liveText&&<div className="bz83-live-transcript"><small>HEARD</small><strong>{liveText}</strong>{output&&<p>{output}</p>}</div>}
    <div className="bz83-live-footer"><button className="bz83-live-start" disabled={!provider} onClick={()=>voice('source')}>{listening?'■ Stop':'🎙 Start'}</button>{liveMode==='Conversation'&&<button className="bz83-live-secondary" disabled={!provider} onClick={()=>voice('target')}>Speak {label(target)}</button>}</div>
  </div>}

  {tab==='Transcribe'&&<div className="bz83-feature-page"><div className="bz83-feature-intro"><small>TRANSCRIBE</small><h1>Long-form speech, translated</h1><p>Capture continuous speech, review the transcript, then translate through your connected provider.</p></div><div className="bz83-transcribe-card"><div className="bz83-transcribe-state"><span className={transcribing?'live':''}/><strong>{transcribing?'Listening continuously':'Microphone paused'}</strong></div><div className="bz83-transcript" aria-live="polite">{transcript||interim?<>{transcript&&<span>{transcript}</span>}{interim&&<em>{interim}</em>}</>:<p>Your transcript will appear here.</p>}</div><div className="bz83-inline-actions"><button className="bz83-primary" onClick={toggleTranscribe}>{transcribing?'■ Stop':'🎙 Start transcribing'}</button><button disabled={!transcript.trim()||working||!provider} onClick={()=>void translateText(transcript,source,target)}>Translate transcript</button><button disabled={!transcript} onClick={()=>{setTranscript('');setInterim('');setOutput('');}}>Clear</button></div>{output&&<div className="bz83-transcript-result"><span>{label(target)}</span><p>{output}</p><div><button onClick={()=>speak(output,target)}>Listen</button><button onClick={()=>copy(output)}>Copy</button><button onClick={()=>void save()}>Save</button></div></div>}</div></div>}

  {tab==='Camera'&&<div className="bz83-feature-page"><div className="bz83-feature-icon">◎</div><div className="bz83-feature-intro"><small>CAMERA</small><h1>Translate what you see</h1><p>BazLens handles camera, uploaded images, OCR and region selection, then hands recognized text into translation workflows.</p></div><a className="bz83-primary-link" href={lens!=='#'?lens:'#'} aria-disabled={lens==='#'}>Open BazLens <span>↗</span></a></div>}
  {tab==='Documents'&&<div className="bz83-feature-page"><div className="bz83-feature-intro"><small>DOCUMENTS</small><h1>Every part, translated.</h1><p>Import up to 50,000 characters of TXT, CSV or Markdown. Your connected provider translates each bounded part; the export includes the complete result.</p></div><input ref={fileRef} type="file" accept=".txt,.md,.csv" hidden onChange={e=>void imported(e)}/><button className="bz83-primary" disabled={working} onClick={()=>fileRef.current?.click()}>Choose document</button>{doc&&<section className="bs-translation-document"><h2>{doc.name}</h2><p>{doc.text.length.toLocaleString()} characters · {label(source)} → {label(target)}</p><div className="bs-translation-columns"><pre>{doc.text}</pre><pre dir="auto">{doc.translation||progress||'The full translation appears here.'}</pre></div><div className="bz83-inline-actions"><button className="bz83-primary" disabled={!provider||working} onClick={()=>void translateDocument()}>Translate all parts</button>{working&&<button onClick={()=>{job.current?.abort();setWorking(false);setProgress('Cancelled');}}>Cancel</button>}<button disabled={!doc.translation} onClick={()=>download(doc.name.replace(/\.(txt|md|csv)$/i,'')+'-'+target+'.txt',doc.translation,'text/plain')}>Export translation</button></div></section>}</div>}
  {tab==='Compare'&&<div className="bz83-feature-page"><div className="bz83-feature-intro"><small>COMPARE LANGUAGES</small><h1>One thought. Three languages.</h1><p>Enter your source in the Text tab, then choose up to three languages.</p></div><div className="bs-compare-select">{compareTargets.map((code,i)=><select key={i} aria-label={'Comparison language '+(i+1)} value={code} disabled={working} onChange={e=>setCompareTargets(compareTargets.map((c,n)=>n===i?e.target.value:c))}>{LANGUAGES.filter(([c])=>c!=='auto').map(([c,n])=><option key={c} value={c}>{n}</option>)}</select>)}</div><button className="bz83-primary" disabled={!text.trim()||!provider||working} onClick={()=>void compare()}>{working?'Translating…':'Compare translations'}</button><div className="bs-compare-results">{compared.map((v,i)=><article key={i}><small>{label(v.language)}</small><p dir="auto">{v.text}</p><button onClick={()=>copy(v.text)}>Copy</button><button onClick={()=>speak(v.text,v.language)}>Listen</button><button onClick={()=>bookmark({id:crypto.randomUUID(),original:text,translation:v.text,from:source,to:v.language,at:new Date().toISOString()})}>Save phrase</button></article>)}</div></div>}
  {tab==='Phrasebook'&&<div className="bz83-feature-page"><div className="bz83-feature-intro"><small>ON THIS DEVICE</small><h1>Your words, ready to use.</h1></div><ToolRow><input aria-label="Search phrasebook" placeholder="Find a phrase…" value={phraseQuery} onChange={e=>setPhraseQuery(e.target.value)}/><select aria-label="Phrasebook folder" value={phraseFolder} onChange={e=>setPhraseFolder(e.target.value)}><option value="">All folders</option>{[...new Set(phrases.items.map(p=>p.folder||'General'))].sort().map(f=><option key={f}>{f}</option>)}</select><button onClick={()=>download('bazaara-phrasebook.json',JSON.stringify(phrases.items,null,2))}>Export phrasebook</button></ToolRow><div className="bs-phrase-list">{phrases.items.filter(p=>(!phraseFolder||(p.folder||'General')===phraseFolder)&&(p.original+' '+p.translation).toLowerCase().includes(phraseQuery.toLowerCase())).map(p=><article key={p.id}><small>{p.folder||'General'} · {label(p.from)} → {label(p.to)}</small><strong>{p.original}</strong><p dir="auto">{p.translation}</p><div><button onClick={()=>{setSource(p.from);setTarget(p.to);setText(p.original);setOutput(p.translation);setTab('Text');}}>Use phrase</button><button onClick={()=>bookmark(p)}>Edit folder</button><button onClick={()=>phrases.remove(p.id)}>Remove</button></div></article>)}{!phrases.items.length&&<p>Save a translated phrase to start your phrasebook.</p>}</div></div>}
  {phrase&&<Dialog title="Save to phrasebook" close={()=>setPhrase(null)}><Field label="Folder"><input autoFocus maxLength={100} value={phrase.folder||''} onChange={e=>setPhrase({...phrase,folder:e.target.value})}/></Field><p>{phrase.original}</p><p dir="auto">{phrase.translation}</p><button onClick={()=>{if(phrases.put({...phrase,folder:phrase.folder?.trim()||'General'})){setPhrase(null);setNotice('Phrase saved on this device.');}}}>Save phrase</button>{phrases.error&&<p role="alert">{phrases.error}</p>}</Dialog>}
  {tab==='Websites'&&<div className="bz83-feature-page"><div className="bz83-feature-icon">⌕</div><div className="bz83-feature-intro"><small>WEBSITES</small><h1>Website translation</h1><p>Open the source site safely. Full-page proxy translation activates only when a webpage-translation integration is connected.</p></div><form className="bz83-site-form" onSubmit={(e:FormEvent)=>{e.preventDefault();try{const u=new URL(site);if(!['https:','http:'].includes(u.protocol)||u.username||u.password)throw Error();window.open(u.href,'_blank','noopener,noreferrer');}catch{setError('Enter a valid URL.');}}}><input type="url" placeholder="https://example.com" value={site} onChange={e=>setSite(e.target.value)} required/><button>Open ↗</button></form></div>}
  {tab==='History'&&<div className="bz83-feature-page"><div className="bz83-history-head"><div><small>ON THIS DEVICE</small><h1>Translation history</h1></div><button onClick={()=>download('bazaara-translation-history.json',JSON.stringify(history,null,2))}>Export history</button><button onClick={()=>{setHistory([]);try{localStorage.removeItem(historyKey);}catch{}}}>Clear</button></div><div className="bz83-history-list">{history.length?history.map(entry=><button key={entry.id} onClick={()=>{setSource(entry.from);setTarget(entry.to);setText(entry.original);setOutput(entry.translation);setTab('Text');}}><strong>{entry.original.slice(0,180)}</strong><span>{entry.translation.slice(0,180)}</span><small>{label(entry.from)} → {label(entry.to)} · {new Date(entry.at).toLocaleString()}</small></button>):<p>No translations yet.</p>}</div></div>}
  {tab==='Saved'&&<div className="bz83-feature-page"><div className="bz83-feature-intro"><small>LIBRARY</small><h1>Saved translations</h1></div><InternetWorkspace kind="translate"/></div>}
 </StandaloneFrame>;
}
