
'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
type Item={id:string;title:string;body:string;createdAt:string};
const PRODUCT="BCloud"; const ITEM="Resource";
export default function ProductApp(){
 const [items,setItems]=useState<Item[]>([]);const [title,setTitle]=useState('');const [body,setBody]=useState('');const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 async function load(){setLoading(true);try{const r=await fetch('/api/items',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');setItems(d.items||[]);setError('')}catch(e){setError(e instanceof Error?e.message:'Request failed')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const latest=useMemo(()=>items.slice(0,6),[items]);
 async function create(e:FormEvent){e.preventDefault();if(!title.trim())return;const r=await fetch('/api/items',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:title.trim(),body:body.trim()})});const d=await r.json();if(!r.ok){setError(d.error||'Create failed');return}setTitle('');setBody('');await load()}
 async function remove(id:string){await fetch('/api/items/'+encodeURIComponent(id),{method:'DELETE'});await load()}
 return <div className="shell"><aside className="side"><div className="brand"><span className="mark"/>BAZAARA</div><p>Developer cloud resources and infrastructure control.</p><div className="nav"><span>Overview</span><span>Resources</span><span>Settings</span></div></aside><main className="main"><div className="top"><div><div className="eyebrow">Platform & Infrastructure</div><h1>BCloud</h1><p className="lead">Developer cloud resources and infrastructure control.</p></div><div className="badge">BazID connected · Alpha</div></div><section className="hero"><div className="panel"><h2>Create resource</h2><form className="create" onSubmit={create}><input value={title} onChange={e=>setTitle(e.target.value)} placeholder={ITEM+' title'} maxLength={120}/><textarea value={body} onChange={e=>setBody(e.target.value)} placeholder="Add context, details or notes" maxLength={4000}/><button className="primary">Add {ITEM}</button></form>{error&&<p className="status">{error}</p>}</div><div className="panel"><div className="eyebrow">System status</div><div className="stats"><div className="stat"><strong>{items.length}</strong><span className="status">Saved resources</span></div><div className="stat"><strong>3043</strong><span className="status">Local web port</span></div></div><p className="status" style={{marginTop:16,lineHeight:1.55}}>Local alpha with persistent per-user records and BAZAARA Spectrum styling.</p></div></section><section className="panel" style={{marginTop:18}}><div className="top"><div><div className="eyebrow">Recent</div><h2 style={{margin:'6px 0 0'}}>Your resources</h2></div><button className="badge" onClick={load}>Refresh</button></div><div className="list">{loading?<div className="empty">Loading…</div>:latest.length===0?<div className="empty">No resources yet.</div>:latest.map(item=><div className="row" key={item.id}><div style={{display:'flex',gap:12}}><span className="dot"/><div><h3>{item.title}</h3><p>{item.body||'No additional details'}</p><p className="status">{new Date(item.createdAt).toLocaleString()}</p></div></div><button className="danger" onClick={()=>remove(item.id)}>Delete</button></div>)}</div></section></main></div>
}
