"use client";
import {useCallback,useEffect,useState,type FormEvent} from "react";
import {api,errorText,uploadMedia} from "@bazaara/social-ui";
import {Dock,Failure,Notice} from "./Dock";
type Track={id:string;title:string;artistLabel:string};
type Playlist={id:string;title:string;items:Array<{trackId:string;track:Track}>};
export default function Tools(){return <Dock app="BTune">{()=> <Panel/>}</Dock>}
function Panel(){
 const [tracks,setTracks]=useState<Track[]>([]),[lists,setLists]=useState<Playlist[]>([]),[selected,setSelected]=useState(""),[track,setTrack]=useState(""),[title,setTitle]=useState(""),[description,setDescription]=useState(""),[file,setFile]=useState<File|null>(null),[artist,setArtist]=useState(""),[uploadTitle,setUploadTitle]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState<"playlists"|"upload">("playlists");
 const load=useCallback(async()=>{try{const [a,b]=await Promise.all([api.get<{tracks:Track[]}>("/v1/baztune/tracks",{maxRetries:0}),api.get<{playlists:Playlist[]}>("/v1/baztune/playlists",{maxRetries:0})]);setTracks(a.tracks);setLists(b.playlists)}catch(e){setError(errorText(e))}},[]);
 useEffect(()=>{void load()},[load]);
 async function makeList(e:FormEvent){e.preventDefault();if(!title.trim()||busy)return;setBusy(true);try{const x=await api.post<{playlist:Playlist}>("/v1/baztune/playlists",{title:title.trim(),description:description.trim(),visibility:"PRIVATE"});setTitle("");setDescription("");setSelected(x.playlist.id);setNotice("Private playlist created.");await load()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function add(){if(!selected||!track||busy)return;setBusy(true);try{await api.put(`/v1/baztune/playlists/${encodeURIComponent(selected)}/tracks/${encodeURIComponent(track)}`,{});await load();setNotice("Track added to playlist.")}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function remove(id:string){if(!selected||busy)return;setBusy(true);try{await api.delete(`/v1/baztune/playlists/${encodeURIComponent(selected)}/tracks/${encodeURIComponent(id)}`);await load();setNotice("Track removed.")}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function publish(e:FormEvent){e.preventDefault();if(!file||!file.type.startsWith("audio/")||!uploadTitle.trim()||busy)return;setBusy(true);setNotice("Uploading your audio. Keep this page open.");try{const asset=await uploadMedia(file,"PRIVATE");await api.post("/v1/baztune/tracks",{assetId:asset.id,title:uploadTitle.trim(),artistLabel:artist.trim(),visibility:"PRIVATE"});setFile(null);setUploadTitle("");setArtist("");setTab("playlists");await load();setNotice("Private audio uploaded to your catalog.")}catch(e){setError(errorText(e));setNotice("")}finally{setBusy(false)}}
 const current=lists.find(l=>l.id===selected);
 return <><span className="tag">REAL PLAYLIST / MEDIA API</span><h2>Your listening library</h2><p>Create private playlists, organize tracks and upload audio you own. Licensed streaming, spatial audio and commercial music discovery are separate release requirements.</p><div className="actions"><button className={tab==="playlists"?"primary":""} onClick={()=>setTab("playlists")}>Playlists</button><button className={tab==="upload"?"primary":""} onClick={()=>setTab("upload")}>Upload own audio</button><button onClick={()=>void load()}>Refresh</button></div><Failure message={error} clear={()=>setError("")}/><Notice message={notice}/>
 {tab==="upload"?<form className="card" onSubmit={e=>void publish(e)}><h3>Add your own recording</h3><label>Audio file (100 MB maximum)<input type="file" accept="audio/*" disabled={busy} onChange={e=>{const next=e.target.files?.[0]??null;if(next&&next.size>100*1024*1024){setError("Audio limit: 100 MB.");return}setFile(next)}}/></label><label>Title<input value={uploadTitle} maxLength={160} onChange={e=>setUploadTitle(e.target.value)}/></label><label>Artist / creator<input value={artist} maxLength={120} onChange={e=>setArtist(e.target.value)}/></label><button className="primary" disabled={!file||!uploadTitle.trim()||busy}>Upload private recording</button></form>:<><form className="card" onSubmit={e=>void makeList(e)}><h3>Create playlist</h3><label>Name<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={120} placeholder="My listening session" /></label><label>Description<textarea rows={2} maxLength={300} value={description} onChange={e=>setDescription(e.target.value)}/></label><button disabled={busy||!title.trim()} className="primary">Create private playlist</button></form><label>Manage playlist<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select a playlist</option>{lists.map(l=><option key={l.id} value={l.id}>{l.title} ({l.items.length})</option>)}</select></label>{current?<div className="card"><h3>{current.title}</h3><label>Add track<select value={track} onChange={e=>setTrack(e.target.value)}><option value="">Choose a track</option>{tracks.map(t=><option key={t.id} value={t.id}>{t.title} · {t.artistLabel}</option>)}</select></label><button onClick={()=>void add()} disabled={busy||!track}>Add track</button><div className="list">{current.items.map(row=><div className="row card" key={row.trackId}><span>{row.track?.title??"Unavailable track"}</span><button type="button" onClick={()=>void remove(row.trackId)} disabled={busy}>Remove</button></div>)}{!current.items.length&&<p>This playlist is empty.</p>}</div></div>:<p>Select a playlist to manage its track list.</p>}</>}
 </>
}
