"use client";

import { BusinessHeaderStandalone } from "../components/BusinessHeaderStandalone";

import { type FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { createApiClient } from "@bazaara/api-client";

const API = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:4000";

type Shipment = { id:string; status:string; carrier:string|null; service:string|null; trackingIdentifier:string|null; labelUrl:string|null; estimatedDeliveryAt:string|null; items:Array<{orderItemId:string;quantity:number}>; events:Array<{id:string;status:string;description:string|null;occurredAt:string}> };
type ReturnCase = { id:string; status:string; reason:string; requestedRefundMinor:number|null; approvedRefundMinor:number|null; requestedAt:string; returnCarrier?:string|null; returnService?:string|null; returnTrackingId?:string|null; items:Array<{id:string;orderItemId:string;quantity:number;inspectedQuantity?:number|null;inspectionOutcome?:string|null;conditionNotes?:string|null;restockApproved?:boolean|null;refundableAmountMinor?:number|null}>; evidence?:Array<{id:string;type:string;url:string;note?:string|null}>; disputes:Array<{id:string;status:string;reason:string}> };
type SellerOrder = { id:string;orderId:string;orderNumber:string;status:string;paymentStatus:string;currency:string;totalMinor:number;placedAt:string;seller:{id:string;name:string;organizationId:string};store:{id:string;name:string};assignedToUserId:string|null;sla:{dueAt:string|null;overdue:boolean;remainingMinutes:number|null};items:Array<{id:string;productTitle:string;variantTitle:string;sku:string;quantity:number;lineTotalMinor:number}>;shipments:Shipment[];cancellationRequests:Array<{id:string;status:string;reason:string}>;returns:ReturnCase[] };
type Member = { userId:string;displayName:string|null;email:string|null;title:string|null };
type Merchant = { id:string;name:string };
type Performance = { open:number;overdue:number;shippedOnTime:number;delivered:number };

type Queue = "OPEN"|"NEW"|"PICKING"|"PACKING"|"READY"|"EXCEPTIONS"|"COMPLETE";
const nextStatus:Record<string,string|undefined>={PLACED:"CONFIRMED",CONFIRMED:"PICKING",PROCESSING:"PACKED",PICKING:"PACKED",PACKED:"READY_TO_SHIP"};

const api=createApiClient({baseUrl:API,credentials:"include"});
type CallInit={method?:"GET"|"POST"|"PUT"|"PATCH"|"DELETE";body?:unknown;headers?:HeadersInit};
async function request<T>(path:string,init:CallInit={}):Promise<T>{
  let body=init.body;
  if(typeof body==="string"){try{body=JSON.parse(body)}catch{}}
  return api.request<T>(path,{method:init.method,body,headers:init.headers});
}
function money(value:number,currency="NGN"){return new Intl.NumberFormat("en-NG",{style:"currency",currency,maximumFractionDigits:0}).format(value/100)}
function label(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/^./,c=>c.toUpperCase())}
function inQueue(order:SellerOrder,queue:Queue){
  if(queue==="OPEN")return !["DELIVERED","CANCELLED","RETURNED","REFUNDED"].includes(order.status);
  if(queue==="NEW")return ["PLACED","CONFIRMED"].includes(order.status);
  if(queue==="PICKING")return ["PICKING","PROCESSING"].includes(order.status);
  if(queue==="PACKING")return order.status==="PACKED";
  if(queue==="READY")return order.status==="READY_TO_SHIP";
  if(queue==="EXCEPTIONS")return order.sla.overdue||order.status==="CANCELLATION_REQUESTED"||order.returns.some(r=>["REQUESTED","UNDER_REVIEW","REFUND_PENDING","DISPUTED"].includes(r.status));
  return ["DELIVERED","CANCELLED","RETURNED","REFUNDED"].includes(order.status);
}

export default function FulfillmentPage(){
  const [orders,setOrders]=useState<SellerOrder[]>([]);const[performance,setPerformance]=useState<Performance>({open:0,overdue:0,shippedOnTime:0,delivered:0});
  const [merchants,setMerchants]=useState<Merchant[]>([]);const[merchantId,setMerchantId]=useState("");const[members,setMembers]=useState<Member[]>([]);const[queue,setQueue]=useState<Queue>("OPEN");
  const[error,setError]=useState("");const[notice,setNotice]=useState("");const[busy,setBusy]=useState("");
  const[carrier,setCarrier]=useState<Record<string,string>>({});const[service,setService]=useState<Record<string,string>>({});const[tracking,setTracking]=useState<Record<string,string>>({});const[labelUrl,setLabelUrl]=useState<Record<string,string>>({});const[eta,setEta]=useState<Record<string,string>>({});

  const load=useCallback(async()=>{try{
    const [context,fulfillment]=await Promise.all([
      request<{merchants:Array<{id:string;name:string}>}>("/v1/business/shopping/catalog/context"),
      request<{orders:SellerOrder[];performance:Performance}>(`/v1/business/shopping/fulfillment${merchantId?`?merchantId=${encodeURIComponent(merchantId)}`:""}`),
    ]);
    setMerchants(context.merchants);setOrders(fulfillment.orders);setPerformance(fulfillment.performance);setError("");
    if(!merchantId&&context.merchants.length)setMerchantId(context.merchants[0]?.id??"");
  }catch(e){setError(e instanceof Error?e.message:"Could not load fulfillment workspace")}},[merchantId]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{if(!merchantId){setMembers([]);return}void request<{members:Member[]}>(`/v1/business/shopping/merchants/${merchantId}/members`).then(r=>setMembers(r.members)).catch(e=>setError(e instanceof Error?e.message:"Could not load team"))},[merchantId]);

  const visible=useMemo(()=>orders.filter(order=>(!merchantId||order.seller.id===merchantId)&&inQueue(order,queue)),[orders,merchantId,queue]);
  async function advance(order:SellerOrder){const status=nextStatus[order.status];if(!status)return;setBusy(order.id);try{await request(`/v1/business/shopping/fulfillment/${order.id}/status`,{method:"PATCH",body:JSON.stringify({status})});setNotice(`${order.orderNumber} moved to ${label(status)}.`);await load()}catch(e){setError(e instanceof Error?e.message:"Could not update fulfillment")}finally{setBusy("")}}
  async function assign(order:SellerOrder,assigneeUserId:string){setBusy(`assign-${order.id}`);try{await request(`/v1/business/shopping/fulfillment/${order.id}/assignment`,{method:"PATCH",body:JSON.stringify({assigneeUserId:assigneeUserId||null})});await load()}catch(e){setError(e instanceof Error?e.message:"Could not assign order")}finally{setBusy("")}}
  async function createShipment(order:SellerOrder){setBusy(`ship-${order.id}`);try{const existing=new Map<string,number>();for(const shipment of order.shipments)if(shipment.status!=="CANCELLED")for(const item of shipment.items)existing.set(item.orderItemId,(existing.get(item.orderItemId)??0)+item.quantity);const items=order.items.map(item=>({orderItemId:item.id,quantity:Math.max(0,item.quantity-(existing.get(item.id)??0))})).filter(item=>item.quantity>0);if(!items.length)throw new Error("All ordered quantities are already allocated to shipments.");const etaValue=(eta[order.id]??"").trim();await request(`/v1/business/shopping/fulfillment/${order.id}/shipments`,{method:"POST",body:JSON.stringify({carrier:(carrier[order.id]??"").trim()||undefined,service:(service[order.id]??"").trim()||undefined,trackingIdentifier:(tracking[order.id]??"").trim()||undefined,labelUrl:(labelUrl[order.id]??"").trim()||undefined,estimatedDeliveryAt:etaValue?new Date(etaValue).toISOString():undefined,items})});setNotice(`Shipment created for ${order.orderNumber}.`);await load()}catch(e){setError(e instanceof Error?e.message:"Could not create shipment")}finally{setBusy("")}}
  async function ship(shipment:Shipment){setBusy(shipment.id);try{if(["DRAFT","LABEL_CREATED"].includes(shipment.status))await request(`/v1/business/shopping/shipments/${shipment.id}/status`,{method:"PATCH",body:JSON.stringify({status:"PACKED"})});const refreshed=await request<{shipment:Shipment}>(`/v1/business/shopping/shipments/${shipment.id}/status`,{method:"PATCH",body:JSON.stringify({status:["DRAFT","LABEL_CREATED"].includes(shipment.status)?"READY_TO_SHIP":shipment.status==="PACKED"?"READY_TO_SHIP":"SHIPPED"})});if(refreshed.shipment.status==="READY_TO_SHIP")await request(`/v1/business/shopping/shipments/${shipment.id}/status`,{method:"PATCH",body:JSON.stringify({status:"SHIPPED"})});setNotice("Shipment marked shipped; later delivery states require Operations or a trusted courier integration.");await load()}catch(e){setError(e instanceof Error?e.message:"Could not update shipment")}finally{setBusy("")}}
  async function cancelRequest(order:SellerOrder){const reason=window.prompt("Reason for cancellation request");if(!reason)return;setBusy(`cancel-${order.id}`);try{await request(`/v1/business/shopping/fulfillment/${order.id}/cancellation-requests`,{method:"POST",body:JSON.stringify({reason})});setNotice("Cancellation request sent to Operations.");await load()}catch(e){setError(e instanceof Error?e.message:"Could not request cancellation")}finally{setBusy("")}}
  async function reviewReturn(returnCase:ReturnCase,decision:"APPROVE"|"REJECT"){setBusy(returnCase.id);try{await request(`/v1/business/shopping/returns/${returnCase.id}/review`,{method:"POST",body:JSON.stringify({decision,approvedRefundMinor:decision==="APPROVE"?returnCase.requestedRefundMinor??0:undefined})});setNotice(`Return ${decision==="APPROVE"?"approved":"rejected"}.`);await load()}catch(e){setError(e instanceof Error?e.message:"Could not review return")}finally{setBusy("")}}
  async function transitionReturn(returnCase:ReturnCase,status:string){setBusy(`return-${returnCase.id}`);try{await request(`/v1/business/shopping/returns/${returnCase.id}/status`,{method:"PATCH",body:JSON.stringify({status})});setNotice(`Return moved to ${label(status)}.`);await load()}catch(e){setError(e instanceof Error?e.message:"Could not update return")}finally{setBusy("")}}
  async function inspectReturn(event:FormEvent<HTMLFormElement>,returnCase:ReturnCase){event.preventDefault();const form=new FormData(event.currentTarget);const approvedNgn=Number(form.get("approvedRefundNgn")??0);if(!Number.isFinite(approvedNgn)||approvedNgn<0){setError("Approved refund must be a valid amount.");return}const items=returnCase.items.map(item=>{const inspectedQuantity=Number(form.get(`qty:${item.id}`)??item.quantity);const refundableNgn=Number(form.get(`refund:${item.id}`)??0);return{returnItemId:item.id,inspectedQuantity,outcome:String(form.get(`outcome:${item.id}`)??"ACCEPTED"),conditionNotes:String(form.get(`notes:${item.id}`)??"")||undefined,restockApproved:form.get(`restock:${item.id}`)==="on",refundableAmountMinor:Number.isFinite(refundableNgn)?Math.max(0,Math.round(refundableNgn*100)):undefined}});setBusy(`inspect-${returnCase.id}`);try{await request(`/v1/business/shopping/returns/${returnCase.id}/inspect`,{method:"POST",body:JSON.stringify({approvedRefundMinor:Math.round(approvedNgn*100),items})});setNotice("Return inspection completed and moved to refund review.");await load()}catch(e){setError(e instanceof Error?e.message:"Could not complete return inspection")}finally{setBusy("")}}

  return <div className="business-control-shell"><BusinessHeaderStandalone active="fulfillment"/><main className="business-control-main">
    <section className="business-page-heading business-page-heading-v3"><div><span className="business-kicker">FULFILLMENT</span><h1>Move every order without losing the SLA.</h1><p>Assignment, picking, packing, shipment creation, returns and cancellation requests in one execution queue.</p></div><label className="business-merchant-filter"><span>Merchant</span><select value={merchantId} onChange={e=>setMerchantId(e.target.value)}><option value="">All merchants</option>{merchants.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label></section>
    {error?<div className="business-alert">{error}<button onClick={()=>setError("")}>×</button></div>:null}{notice?<div className="business-notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>:null}
    <section className="business-control-kpis business-control-kpis-v3"><article><span>OPEN</span><strong>{performance.open}</strong><small>orders requiring work</small></article><article><span>SLA BREACHES</span><strong>{performance.overdue}</strong><small>past fulfillment deadline</small></article><article><span>SHIPPED ON TIME</span><strong>{performance.shippedOnTime}</strong><small>within current SLA</small></article><article><span>DELIVERED</span><strong>{performance.delivered}</strong><small>completed seller orders</small></article></section>
    <section className="business-panel business-fulfillment-board"><div className="business-queue-tabs">{(["OPEN","NEW","PICKING","PACKING","READY","EXCEPTIONS","COMPLETE"] as Queue[]).map(q=><button key={q} className={queue===q?"active":""} onClick={()=>setQueue(q)}>{label(q)}<span>{orders.filter(o=>(!merchantId||o.seller.id===merchantId)&&inQueue(o,q)).length}</span></button>)}</div>
    {visible.length===0?<div className="business-empty-state business-empty-state-large"><strong>Nothing needs attention here.</strong><span>Orders will appear as they enter this stage.</span></div>:<div className="business-fulfillment-list">{visible.map(order=><article className={`business-order-card ${order.sla.overdue?"overdue":""}`} key={order.id}><div className="business-order-card-head"><div><span className="business-soft-pill">{label(order.status)}</span><h2>{order.orderNumber}</h2><p>{order.seller.name} · {order.store.name}</p></div><div className="business-order-value"><strong>{money(order.totalMinor,order.currency)}</strong><small>{order.paymentStatus}</small></div></div>
      <div className="business-order-progress"><span className="done">Confirmed</span><span className={["PICKING","PROCESSING","PACKED","READY_TO_SHIP","SHIPPED","OUT_FOR_DELIVERY","DELIVERED"].includes(order.status)?"done":""}>Picking</span><span className={["PACKED","READY_TO_SHIP","SHIPPED","OUT_FOR_DELIVERY","DELIVERED"].includes(order.status)?"done":""}>Packed</span><span className={["READY_TO_SHIP","SHIPPED","OUT_FOR_DELIVERY","DELIVERED"].includes(order.status)?"done":""}>Ready</span><span className={["SHIPPED","OUT_FOR_DELIVERY","DELIVERED"].includes(order.status)?"done":""}>Shipped</span></div>
      <div className="business-order-meta"><label>Assigned to<select value={order.assignedToUserId??""} disabled={busy===`assign-${order.id}`} onChange={e=>void assign(order,e.target.value)}><option value="">Unassigned</option>{members.map(member=><option key={member.userId} value={member.userId}>{member.displayName||member.email||member.userId}</option>)}</select></label><div><span>SLA</span><strong className={order.sla.overdue?"danger":""}>{order.sla.overdue?"Overdue":order.sla.remainingMinutes==null?"Complete":`${Math.max(0,Math.round(order.sla.remainingMinutes/60))}h left`}</strong></div><div><span>Placed</span><strong>{new Date(order.placedAt).toLocaleString("en-NG")}</strong></div></div>
      <details className="business-order-details"><summary>Order items & shipping</summary><div className="business-fulfillment-items">{order.items.map(item=><div key={item.id}><strong>{item.productTitle}</strong><span>{item.variantTitle} · {item.sku} · ×{item.quantity}</span></div>)}</div><div className="business-shipment-grid"><div className="business-shipment-create"><h3>Create shipment</h3><input placeholder="Carrier" value={carrier[order.id]??""} onChange={e=>setCarrier(v=>({...v,[order.id]:e.target.value}))}/><input placeholder="Service" value={service[order.id]??""} onChange={e=>setService(v=>({...v,[order.id]:e.target.value}))}/><input placeholder="Tracking identifier" value={tracking[order.id]??""} onChange={e=>setTracking(v=>({...v,[order.id]:e.target.value}))}/><input placeholder="Label URL (optional)" value={labelUrl[order.id]??""} onChange={e=>setLabelUrl(v=>({...v,[order.id]:e.target.value}))}/><label>Estimated delivery<input type="datetime-local" value={eta[order.id]??""} onChange={e=>setEta(v=>({...v,[order.id]:e.target.value}))}/></label><button className="business-secondary-button" disabled={busy===`ship-${order.id}`} onClick={()=>void createShipment(order)}>Create shipment</button></div><div><h3>Shipments</h3>{order.shipments.length===0?<p className="business-muted">No shipments yet.</p>:order.shipments.map(shipment=><article className="business-shipment-row" key={shipment.id}><div><strong>{shipment.carrier||"Carrier pending"}{shipment.service?` · ${shipment.service}`:""}</strong><small>{shipment.trackingIdentifier||"Tracking pending"} · {label(shipment.status)}</small></div>{["DRAFT","LABEL_CREATED","PACKED","READY_TO_SHIP"].includes(shipment.status)?<button disabled={busy===shipment.id} onClick={()=>void ship(shipment)}>{busy===shipment.id?"Updating…":"Mark shipped"}</button>:null}</article>)}</div></div></details>
      <div className="business-card-actions business-order-actions">{nextStatus[order.status]?<button className="primary" disabled={busy===order.id} onClick={()=>void advance(order)}>{busy===order.id?"Updating…":`Mark ${label(nextStatus[order.status]??"")}`}</button>:null}{!["SHIPPED","OUT_FOR_DELIVERY","DELIVERED","CANCELLED","CANCELLATION_REQUESTED"].includes(order.status)?<button disabled={busy===`cancel-${order.id}`} onClick={()=>void cancelRequest(order)}>Request cancellation</button>:null}</div>
      {order.cancellationRequests.some(r=>r.status==="REQUESTED")?<div className="business-warning-strip">Cancellation request pending Operations review.</div>:null}
      {order.returns.length?<details className="business-return-stack"><summary>Returns ({order.returns.length})</summary>{order.returns.map(r=><div className="business-return-row" key={r.id}><div><strong>{label(r.status)}</strong><small>{r.reason} · requested {money(r.requestedRefundMinor??0,order.currency)}</small></div>{["REQUESTED","UNDER_REVIEW"].includes(r.status)?<div className="business-inline-actions"><button disabled={busy===r.id} onClick={()=>void reviewReturn(r,"APPROVE")}>Approve</button><button disabled={busy===r.id} onClick={()=>void reviewReturn(r,"REJECT")}>Reject</button></div>:null}<div className="business-inline-actions">{["APPROVED","RETURN_LABEL_CREATED"].includes(r.status)?<button disabled={busy===`return-${r.id}`} onClick={()=>void transitionReturn(r,"IN_TRANSIT")}>In transit</button>:null}{r.status==="IN_TRANSIT"?<button disabled={busy===`return-${r.id}`} onClick={()=>void transitionReturn(r,"RECEIVED")}>Received</button>:null}{r.status==="RECEIVED"?<button disabled={busy===`return-${r.id}`} onClick={()=>void transitionReturn(r,"INSPECTING")}>Inspect</button>:null}</div>{["RECEIVED","INSPECTING"].includes(r.status)?<form className="business-inspection-form" onSubmit={e=>void inspectReturn(e,r)}><strong>Inspection</strong>{r.items.map(item=>{const source=order.items.find(oi=>oi.id===item.orderItemId);return <div className="business-inspection-item" key={item.id}><span>{source?.productTitle||item.orderItemId}</span><input name={`qty:${item.id}`} type="number" min={0} max={item.quantity} defaultValue={item.quantity}/><select name={`outcome:${item.id}`} defaultValue="ACCEPTED"><option value="ACCEPTED">Accepted</option><option value="DAMAGED">Damaged</option><option value="NOT_AS_DESCRIBED">Not as described</option><option value="REJECTED">Reject item</option></select><input name={`refund:${item.id}`} type="number" min="0" step="0.01" defaultValue={source?String(((source.lineTotalMinor/source.quantity)*item.quantity)/100):"0"}/><label><input name={`restock:${item.id}`} type="checkbox"/> Restock</label></div>})}<label>Approved refund total (NGN)<input name="approvedRefundNgn" type="number" min="0" step="0.01" defaultValue={String((r.approvedRefundMinor??r.requestedRefundMinor??0)/100)}/></label><button className="business-secondary-button" disabled={busy===`inspect-${r.id}`}>{busy===`inspect-${r.id}`?"Saving inspection…":"Complete inspection"}</button></form>:null}</div>)}</details>:null}
    </article>)}</div>}</section>
  </main></div>
}
