"use client";
import { useCallback, useEffect, useMemo, useState, type FormEvent } from "react";
import { api, errorText, Member, ProfileSetup, SessionGate, Shell, uploadMedia, useSocialSession } from "@bazaara/social-ui";

type Person={id:string;displayName:string|null;handle?:string;socialProfile?:{handle:string}|null};
type Topic={id:string;slug:string;name:string;description:string;_count:{threads:number}};
type Thread={id:string;title:string;body:string;createdAt:string;author:Person;topic:{id:string;name:string;slug:string};_count:{replies:number};voteScore:number;myVote:number};
type Reply={id:string;body:string;createdAt:string;author:Person};
type Post={id:string;body:string;audience:string;createdAt:string;author:Person;_count:{likes:number;comments:number};liked:boolean;media?:{url:string;contentType:string;byteSize:number}|null};

type View="community"|"feed"|"people";

export default function BicordHome(){
 const session=useSocialSession();
 const [view,setView]=useState<View>("community");
 const [topics,setTopics]=useState<Topic[]>([]);const [topicId,setTopicId]=useState("");const [threads,setThreads]=useState<Thread[]>([]);const [activeThread,setActiveThread]=useState<Thread|null>(null);const [replies,setReplies]=useState<Reply[]>([]);
 const [posts,setPosts]=useState<Post[]>([]);const [postBody,setPostBody]=useState("");const [mediaFile,setMediaFile]=useState<File|null>(null);
 const [query,setQuery]=useState("");const [people,setPeople]=useState<Person[]>([]);
 const [threadTitle,setThreadTitle]=useState("");const [threadBody,setThreadBody]=useState("");const [reply,setReply]=useState("");
 const [showThreadComposer,setShowThreadComposer]=useState(false);const [showTopicComposer,setShowTopicComposer]=useState(false);const [topicName,setTopicName]=useState("");const [topicDescription,setTopicDescription]=useState("");
 const [busy,setBusy]=useState(false);const [error,setError]=useState("");

 const currentTopic=useMemo(()=>topics.find(t=>t.id===topicId)??null,[topics,topicId]);
 const loadTopics=useCallback(async()=>{try{const data=await api.get<{topics:Topic[]}>("/v1/bazforum/topics",{maxRetries:0});setTopics(data.topics);}catch(e){setError(errorText(e));}},[]);
 const loadThreads=useCallback(async(id?:string)=>{try{const data=await api.get<{threads:Thread[]}>("/v1/bazforum/threads",{query:{topicId:id},maxRetries:0});setThreads(data.threads);}catch(e){setError(errorText(e));}},[]);
 const loadFeed=useCallback(async()=>{try{const data=await api.get<{posts:Post[]}>("/v1/bazcircle/feed",{query:{limit:30},maxRetries:0});setPosts(data.posts);}catch(e){setError(errorText(e));}},[]);
 useEffect(()=>{if(!session.user?.profile)return;void loadTopics();void loadThreads();void loadFeed();},[session.user?.profile,loadTopics,loadThreads,loadFeed]);
 useEffect(()=>{if(!session.user?.profile||query.trim().length<2){setPeople([]);return;}const timer=window.setTimeout(async()=>{try{const data=await api.get<{users:Person[]}>("/v1/social/users",{query:{q:query},maxRetries:0});setPeople(data.users);}catch(e){setError(errorText(e));}},260);return()=>window.clearTimeout(timer);},[query,session.user?.profile]);
 async function selectTopic(id:string){setTopicId(id);setActiveThread(null);await loadThreads(id||undefined);}
 async function openThread(thread:Thread){try{const data=await api.get<{thread:Thread;replies:Reply[]}>(`/v1/bazforum/threads/${encodeURIComponent(thread.id)}`,{maxRetries:0});setActiveThread(data.thread);setReplies(data.replies);}catch(e){setError(errorText(e));}}
 async function createTopic(e:FormEvent){e.preventDefault();const name=topicName.trim();if(!name)return;setBusy(true);try{const slug=name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,50);const data=await api.post<{topic:Topic}>("/v1/bazforum/topics",{slug,name,description:topicDescription.trim()});setTopicName("");setTopicDescription("");setShowTopicComposer(false);await loadTopics();await selectTopic(data.topic.id);}catch(err){setError(errorText(err));}finally{setBusy(false);}}
 async function createThread(e:FormEvent){e.preventDefault();if(!topicId){setError("Choose a community before creating a discussion.");return;}setBusy(true);try{const data=await api.post<{thread:Thread}>("/v1/bazforum/threads",{topicId,title:threadTitle.trim(),body:threadBody.trim()});setThreadTitle("");setThreadBody("");setShowThreadComposer(false);await loadThreads(topicId);await openThread(data.thread);}catch(err){setError(errorText(err));}finally{setBusy(false);}}
 async function addReply(e:FormEvent){e.preventDefault();if(!activeThread||!reply.trim())return;setBusy(true);try{const data=await api.post<{reply:Reply}>(`/v1/bazforum/threads/${encodeURIComponent(activeThread.id)}/replies`,{body:reply.trim()});setReplies(old=>[...old,data.reply]);setReply("");}catch(err){setError(errorText(err));}finally{setBusy(false);}}
 async function vote(thread:Thread,value:1|-1){try{const data=thread.myVote===value?await api.delete<{myVote:number;voteScore:number}>(`/v1/bazforum/threads/${encodeURIComponent(thread.id)}/vote`):await api.put<{myVote:number;voteScore:number}>(`/v1/bazforum/threads/${encodeURIComponent(thread.id)}/vote`,{value});setThreads(old=>old.map(x=>x.id===thread.id?{...x,...data}:x));setActiveThread(old=>old?.id===thread.id?{...old,...data}:old);}catch(err){setError(errorText(err));}}
 async function publishPost(e:FormEvent){e.preventDefault();if((!postBody.trim()&&!mediaFile)||busy)return;setBusy(true);try{let mediaAssetId:string|undefined;if(mediaFile){if(mediaFile.size>100*1024*1024)throw new Error("Post media is limited to 100 MB.");mediaAssetId=(await uploadMedia(mediaFile,"PUBLIC")).id;}await api.post("/v1/bazcircle/posts",{body:postBody.trim(),audience:"PUBLIC",mediaAssetId});setPostBody("");setMediaFile(null);await loadFeed();}catch(err){setError(errorText(err));}finally{setBusy(false);}}
 async function likePost(post:Post){try{if(post.liked)await api.delete(`/v1/bazcircle/posts/${encodeURIComponent(post.id)}/like`);else await api.put(`/v1/bazcircle/posts/${encodeURIComponent(post.id)}/like`,{});setPosts(old=>old.map(item=>item.id===post.id?{...item,liked:!item.liked,_count:{...item._count,likes:Math.max(0,item._count.likes+(item.liked?-1:1))}}:item));}catch(err){setError(errorText(err));}}
 async function follow(person:Person){try{await api.post(`/v1/social/follows/${encodeURIComponent(person.id)}`,{});setPeople(old=>old.filter(item=>item.id!==person.id));}catch(err){setError(errorText(err));}}

 return <Shell slug="bazcircle" section="Communities"><SessionGate {...session} productName="Bicord">{session.user?.profile?<div className="bicord-app">
  <aside className="bicord-rail" aria-label="Bicord communities"><div className="bicord-brandBlock"><span className="bicord-orb">Bi</span><strong>Bicord</strong><small>communities</small></div><button className={!topicId?"active":""} onClick={()=>void selectTopic("")} title="All communities">⌂</button>{topics.map(topic=><button key={topic.id} className={topicId===topic.id?"active":""} onClick={()=>void selectTopic(topic.id)} title={topic.name}>{topic.name.slice(0,2).toUpperCase()}</button>)}<button className="bicord-add" onClick={()=>setShowTopicComposer(true)} title="Create community">＋</button></aside>
  <aside className="bicord-sidebar"><div className="bicord-communityHead"><span className="e2-kicker">{currentTopic?"COMMUNITY":"BICORD"}</span><h2>{currentTopic?.name??"Your communities"}</h2><p>{currentTopic?.description||"Join discussions, publish updates and meet people around shared interests."}</p></div><nav className="bicord-nav"><button className={view==="community"?"active":""} onClick={()=>setView("community")}># Discussions <span>{threads.length}</span></button><button className={view==="feed"?"active":""} onClick={()=>setView("feed")}>◫ Social feed <span>{posts.length}</span></button><button className={view==="people"?"active":""} onClick={()=>setView("people")}>◎ Discover people</button></nav><div className="bicord-sideActions">{view==="community"?<button className="e2-button" onClick={()=>setShowThreadComposer(true)} disabled={!topicId}>New discussion</button>:null}{view==="feed"?<button className="e2-button" onClick={()=>document.getElementById("bicord-post")?.focus()}>New post</button>:null}<small>Bicord is independent from BChat. Community conversations stay inside Bicord.</small></div></aside>
  <main className="bicord-main">{error?<div className="e2-notice" role="alert">{error}<button className="e2-textButton" onClick={()=>setError("")}>Dismiss</button></div>:null}
   {view==="community"?(activeThread?<article className="bicord-thread e2-card e2-cardPad"><button className="e2-textButton" onClick={()=>setActiveThread(null)}>← Back to discussions</button><span className="e2-chip">{activeThread.topic.name}</span><h1>{activeThread.title}</h1><div className="e2-row"><Member name={activeThread.author.displayName} handle={activeThread.author.socialProfile?.handle}/><div><strong>{activeThread.author.displayName||activeThread.author.socialProfile?.handle||"Member"}</strong><small>{new Date(activeThread.createdAt).toLocaleString()}</small></div></div><p className="bicord-threadBody">{activeThread.body}</p><div className="bicord-votes"><button className={activeThread.myVote===1?"active":""} onClick={()=>void vote(activeThread,1)}>▲</button><strong>{activeThread.voteScore}</strong><button className={activeThread.myVote===-1?"active":""} onClick={()=>void vote(activeThread,-1)}>▼</button></div><h3>{replies.length} replies</h3><div className="bicord-replies">{replies.map(item=><div key={item.id} className="bicord-reply"><Member size="small" name={item.author.displayName} handle={item.author.socialProfile?.handle}/><div><strong>{item.author.displayName||item.author.socialProfile?.handle||"Member"}</strong><small>{new Date(item.createdAt).toLocaleString()}</small><p>{item.body}</p></div></div>)}</div><form className="bicord-replyForm" onSubmit={addReply}><textarea value={reply} onChange={e=>setReply(e.target.value)} maxLength={5000} rows={3} placeholder="Reply to the discussion…"/><button className="e2-button" disabled={busy||!reply.trim()}>Reply</button></form></article>:<section><div className="bicord-mainHead"><div><span className="e2-kicker">TEXT ROOMS</span><h1>{currentTopic?currentTopic.name:"Community discovery"}</h1><p>{currentTopic?"Discussions in this community.":"Choose a community from the rail or create a new one."}</p></div>{topicId?<button className="e2-button" onClick={()=>setShowThreadComposer(true)}>New discussion +</button>:null}</div><div className="bicord-threadList">{threads.map(thread=><button key={thread.id} className="bicord-threadCard e2-card" onClick={()=>void openThread(thread)}><div><span className="e2-chip">#{thread.topic.name}</span><h3>{thread.title}</h3><p>{thread.body}</p><small>{thread.author.displayName||thread.author.socialProfile?.handle||"Member"} · {new Date(thread.createdAt).toLocaleDateString()}</small></div><div className="bicord-threadStats"><strong>{thread.voteScore}</strong><span>score</span><strong>{thread._count.replies}</strong><span>replies</span></div></button>)}{!threads.length?<div className="e2-card e2-empty"><strong>No discussions yet.</strong><p>{topicId?"Start the first conversation in this community.":"Select a community to view its discussions."}</p></div>:null}</div></section>):null}
   {view==="feed"?<section className="bicord-feed"><form className="bicord-composer e2-card e2-cardPad" onSubmit={publishPost}><div className="e2-row"><Member name={session.user.displayName} handle={session.user.profile?.handle}/><div><strong>{session.user.displayName||session.user.profile?.handle}</strong><small>@{session.user.profile?.handle}</small></div></div><textarea id="bicord-post" value={postBody} onChange={e=>setPostBody(e.target.value)} maxLength={2000} rows={4} placeholder="Share an update with Bicord…"/><div className="e2-rowBetween"><label className="e2-textButton">＋ Media<input type="file" accept="image/*,video/*" onChange={e=>setMediaFile(e.target.files?.[0]??null)} style={{display:"none"}}/></label>{mediaFile?<span className="e2-subtle">{mediaFile.name}</span>:null}<button className="e2-button" disabled={busy||(!postBody.trim()&&!mediaFile)}>Post</button></div></form><div className="bicord-posts">{posts.map(post=><article key={post.id} className="e2-card e2-cardPad bicord-post"><div className="e2-row"><Member name={post.author.displayName} handle={post.author.socialProfile?.handle}/><div><strong>{post.author.displayName||post.author.socialProfile?.handle||"Member"}</strong><small>@{post.author.socialProfile?.handle||"member"} · {new Date(post.createdAt).toLocaleString()}</small></div></div><p>{post.body}</p>{post.media?(post.media.contentType.startsWith("video/")?<video src={post.media.url} controls playsInline/>:<img src={post.media.url} alt="Community post media"/>):null}<div className="bicord-postActions"><button className={post.liked?"active":""} onClick={()=>void likePost(post)}>♡ {post._count.likes}</button><span>💬 {post._count.comments}</span></div></article>)}{!posts.length?<div className="e2-card e2-empty">No community posts yet.</div>:null}</div></section>:null}
   {view==="people"?<section className="bicord-people"><div className="bicord-mainHead"><div><span className="e2-kicker">DISCOVER</span><h1>Find your people.</h1><p>Search discoverable Bicord members by name or handle.</p></div></div><input className="e2-input bicord-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search people…"/><div className="bicord-peopleGrid">{people.map(person=><article key={person.id} className="e2-card e2-cardPad"><Member name={person.displayName} handle={person.handle}/><div><strong>{person.displayName||person.handle}</strong><small>@{person.handle}</small></div><button className="e2-button sm" onClick={()=>void follow(person)}>Follow</button></article>)}</div></section>:null}
  </main>
  {showThreadComposer?<div className="bicord-modal" role="dialog" aria-modal="true"><form className="e2-card e2-cardPad" onSubmit={createThread}><div className="e2-rowBetween"><h2>New discussion</h2><button type="button" className="e2-textButton" onClick={()=>setShowThreadComposer(false)}>Close</button></div><label>Community<select value={topicId} onChange={e=>setTopicId(e.target.value)} required><option value="">Choose community</option>{topics.map(topic=><option key={topic.id} value={topic.id}>{topic.name}</option>)}</select></label><label>Title<input value={threadTitle} onChange={e=>setThreadTitle(e.target.value)} minLength={5} maxLength={150} required/></label><label>Message<textarea value={threadBody} onChange={e=>setThreadBody(e.target.value)} minLength={10} maxLength={10000} rows={6} required/></label><button className="e2-button" disabled={busy}>Create discussion</button></form></div>:null}
  {showTopicComposer?<div className="bicord-modal" role="dialog" aria-modal="true"><form className="e2-card e2-cardPad" onSubmit={createTopic}><div className="e2-rowBetween"><h2>Create a community</h2><button type="button" className="e2-textButton" onClick={()=>setShowTopicComposer(false)}>Close</button></div><label>Name<input value={topicName} onChange={e=>setTopicName(e.target.value)} minLength={3} maxLength={90} required/></label><label>Description<textarea value={topicDescription} onChange={e=>setTopicDescription(e.target.value)} maxLength={300} rows={4}/></label><button className="e2-button" disabled={busy}>Create community</button></form></div>:null}
 </div>:session.user?<ProfileSetup user={session.user} onComplete={session.refresh} productName="Bicord" headline="Create your community identity."/>:null}</SessionGate></Shell>;
}
