export type ProductGroup = 'Internet' | 'Communication' | 'Productivity' | 'Storage & Security' | 'Creative & Intelligence' | 'Collaboration' | 'Platform & Infrastructure';
export type ProductStatus = 'available' | 'planned';
export type Product = { id:string; name:string; description:string; category:ProductGroup; icon:string; status:ProductStatus; href?:string; color:string; };
export const categories: ProductGroup[] = ['Internet','Communication','Productivity','Storage & Security','Creative & Intelligence','Collaboration','Platform & Infrastructure'];
export const products: Product[] = [
  {id:'search',name:'Search',description:'Privacy-first web discovery.',category:'Internet',icon:'⌕',status:'available',href:'http://localhost:3020',color:'aqua'},
  {id:'bmap',name:'BMap',description:'Maps, places and local discovery.',category:'Internet',icon:'◇',status:'available',href:'http://localhost:3038',color:'aqua'},
  {id:'translate',name:'Translate',description:'Language tools and translation history.',category:'Internet',icon:'文',status:'available',href:'http://localhost:3039',color:'aqua'},
  {id:'news',name:'News',description:'Source-aware news discovery.',category:'Internet',icon:'▤',status:'available',href:'http://localhost:3040',color:'aqua'},
  {id:'bazlens',name:'BazLens',description:'Visual search and image understanding.',category:'Internet',icon:'◉',status:'available',href:'http://localhost:3041',color:'aqua'},
  {id:'bmail',name:'Bmail',description:'Connected BazID email workspace.',category:'Communication',icon:'✉',status:'available',href:'http://localhost:3036',color:'violet'},
  {id:'bazmeet',name:'BazMeet',description:'Meetings, rooms and scheduling.',category:'Communication',icon:'▣',status:'available',href:'http://localhost:3037',color:'violet'},
  {id:'bazchat',name:'BChat',description:'Talk privately. Stay in control.',category:'Communication',icon:'✉',status:'available',href:'http://localhost:3013/phase2',color:'violet'},
  {id:'bazclips',name:'ZimZam',description:'Discover and publish short-form video.',category:'Creative & Intelligence',icon:'▶',status:'available',href:'http://localhost:3014/phase2',color:'ember'},
  {id:'baztune',name:'BTune',description:'Your playlists, audio, and listening space.',category:'Creative & Intelligence',icon:'♫',status:'available',href:'http://localhost:3015/phase2',color:'ember'},
  {id:'bazcircle',name:'Bicord',description:'Communities, discussions, and live spaces.',category:'Communication',icon:'◈',status:'available',href:'http://localhost:3017/phase2',color:'violet'},
  {id:'bazcut',name:'BazCut',description:'Edit and prepare your original videos.',category:'Creative & Intelligence',icon:'✂',status:'available',href:'http://localhost:3018/phase2',color:'ember'},
  {id:'bazsend',name:'BSend',description:'Share files and manage transfers.',category:'Storage & Security',icon:'⇢',status:'available',href:'http://localhost:3019/phase2',color:'blue'},
  {id:'biflix',name:'Ɓiflix',description:'Cinematic discovery and local playback demo.',category:'Creative & Intelligence',icon:'▷',status:'available',href:'http://localhost:3055/phase2',color:'ember'},
  {id:'calendar',name:'Calendar',description:'Shared schedules and availability.',category:'Communication',icon:'▦',status:'available',href:'http://localhost:3028',color:'violet'},
  {id:'contacts',name:'Contacts',description:'Personal and team directory.',category:'Communication',icon:'◎',status:'available',href:'http://localhost:3029',color:'violet'},
  {id:'docs',name:'Docs',description:'Connected documents.',category:'Productivity',icon:'≡',status:'available',href:'http://localhost:3023',color:'green'},
  {id:'sheets',name:'Sheets',description:'Analyze and share structured data.',category:'Productivity',icon:'▥',status:'available',href:'http://localhost:3024',color:'green'},
  {id:'slides',name:'Slides',description:'Presentation creation.',category:'Productivity',icon:'▧',status:'available',href:'http://localhost:3025',color:'green'},
  {id:'forms',name:'Forms',description:'Surveys and structured responses.',category:'Productivity',icon:'☷',status:'available',href:'http://localhost:3026',color:'green'},
  {id:'notes',name:'Notes',description:'Fast notes and ideas.',category:'Productivity',icon:'✎',status:'available',href:'http://localhost:3027',color:'green'},
  {id:'tasks',name:'Tasks',description:'Personal and team task management.',category:'Productivity',icon:'✓',status:'available',href:'http://localhost:3045',color:'green'},
  {id:'learn',name:'Learn',description:'Courses and classroom workflows.',category:'Productivity',icon:'⌂',status:'available',href:'http://localhost:3048',color:'green'},
  {id:'bcloud-drive',name:'BCloud Drive',description:'Secure file storage powered by the Box storage layer.',category:'Storage & Security',icon:'□',status:'available',href:'http://localhost:3022',color:'blue'},
  {id:'vault',name:'Vault',description:'Confidential files and recovery controls.',category:'Storage & Security',icon:'✳',status:'available',href:'http://localhost:3031',color:'blue'},
  {id:'photos',name:'Photos',description:'Private media library.',category:'Storage & Security',icon:'▧',status:'available',href:'http://localhost:3030',color:'blue'},
  {id:'bazshield',name:'BazShield',description:'Application verification and protection.',category:'Storage & Security',icon:'⬡',status:'available',href:'http://localhost:3054',color:'blue'},
  {id:'bazgames',name:'BazGames',description:'Games, achievements and leaderboards.',category:'Creative & Intelligence',icon:'✦',status:'available',href:'http://localhost:3050',color:'ember'},
  {id:'studio',name:'Studio',description:'Creative production workspace.',category:'Creative & Intelligence',icon:'✦',status:'planned',color:'ember'},
  {id:'ai',name:'Bazaara AI',description:'Permission-aware intelligence.',category:'Creative & Intelligence',icon:'✳',status:'planned',color:'ember'},
  {id:'workspace',name:'Workspace',description:'One destination for BAZAARA tools.',category:'Collaboration',icon:'▤',status:'available',href:'/',color:'orchid'},
  {id:'spaces',name:'Spaces',description:'Shared team spaces.',category:'Collaboration',icon:'▦',status:'available',href:'http://localhost:3032',color:'orchid'},
  {id:'boards',name:'Boards',description:'Visual task organization.',category:'Collaboration',icon:'☷',status:'available',href:'http://localhost:3033',color:'orchid'},
  {id:'projects',name:'Projects',description:'Project planning and coordination.',category:'Collaboration',icon:'◈',status:'available',href:'http://localhost:3034',color:'orchid'},
  {id:'flow',name:'Flow',description:'Reviewed workflow automation.',category:'Collaboration',icon:'⟡',status:'available',href:'http://localhost:3035',color:'orchid'},
  {id:'groups',name:'Groups',description:'Group membership and communication.',category:'Collaboration',icon:'◎',status:'available',href:'http://localhost:3046',color:'orchid'},
  {id:'sites',name:'Sites',description:'Create and publish websites.',category:'Platform & Infrastructure',icon:'◉',status:'available',href:'http://localhost:3042',color:'gold'},
  {id:'bcloud',name:'BCloud',description:'Developer cloud infrastructure.',category:'Platform & Infrastructure',icon:'◈',status:'available',href:'http://localhost:3043',color:'gold'},
  {id:'admin',name:'Admin',description:'Organization and policy administration.',category:'Platform & Infrastructure',icon:'⚙',status:'available',href:'http://localhost:3044',color:'gold'},
  {id:'marketplace',name:'Marketplace',description:'Workspace integrations and extensions.',category:'Platform & Infrastructure',icon:'▦',status:'available',href:'http://localhost:3047',color:'gold'},
  {id:'bazstore',name:'BazStore',description:'Official BAZAARA app marketplace.',category:'Platform & Infrastructure',icon:'⬢',status:'available',href:'http://localhost:3049',color:'gold'},
  {id:'one',name:'Bazaara One',description:'Unified subscription and account benefits.',category:'Platform & Infrastructure',icon:'◉',status:'available',href:'http://localhost:3051',color:'gold'},
  {id:'analytics',name:'Analytics',description:'Product and business analytics.',category:'Platform & Infrastructure',icon:'▥',status:'available',href:'http://localhost:3052',color:'gold'},
  {id:'bazservices',name:'BazServices',description:'Shared platform capabilities.',category:'Platform & Infrastructure',icon:'⌘',status:'available',href:'http://localhost:3053',color:'gold'},
  {id:'wallet',name:'Bazaara Pay / Wallet',description:'Payments and wallet infrastructure.',category:'Platform & Infrastructure',icon:'◫',status:'available',href:'http://localhost:3010',color:'gold'},
  {id:'business',name:'Business',description:'Business operations and management.',category:'Platform & Infrastructure',icon:'▣',status:'available',href:'http://localhost:3001',color:'gold'},
  {id:'code',name:'Code',description:'Software projects and developer tooling.',category:'Platform & Infrastructure',icon:'⌘',status:'planned',color:'gold'},
];
export const activeProducts=products.filter(p=>p.status==='available');
