"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { readSaved, SavedButton } from "./SavedButton";
import { titles } from "../lib/catalog";
type Screen="home"|"explore"|"saved"|"downloads";
export default function BiflixHome(){
 const [screen,setScreen]=useState<Screen>("home"),[query,setQuery]=useState(""),[saved,setSaved]=useState<string[]>([]),[profile,setProfile]=useState("Guest"),[profiles,setProfiles]=useState(["Guest"]),[editingProfile,setEditingProfile]=useState(false);
 useEffect(()=>{function refresh(){setSaved(readSaved())}refresh();window.addEventListener("biflix-saved-changed",refresh);const stored=localStorage.getItem("biflix-demo-profile-v1");if(stored)setProfile(stored);const ps=localStorage.getItem("biflix-demo-profiles-v1");if(ps){try{const arr=JSON.parse(ps) as unknown;if(Array.isArray(arr))setProfiles(arr.filter((p):p is string=>typeof p==="string"))}catch{}}window.addEventListener("biflix-profile-changed",refresh);return()=>{window.removeEventListener("biflix-saved-changed",refresh);window.removeEventListener("biflix-profile-changed",refresh)}},[]);
 const filtered=useMemo(()=>titles.filter(t=>(screen!=="saved"||saved.includes(t.slug))&&(!query||`${t.name} ${t.genres.join(" ")}`.toLowerCase().includes(query.toLowerCase()))),[screen,saved,query]);
 const hero=titles[0];if(!hero)return null;
 const nav:Screen[]=["home","explore","saved","downloads"];
 return <div className="bf"><a className="bf-skip" href="#bf-content">Skip to content</a><header className="bf-header"><Link href="/" className="bf-brand" aria-label="Ɓiflix home"><span>Ɓ</span>iflix<small>BAZAARA</small></Link><nav aria-label="Ɓiflix primary navigation" className="bf-nav">{nav.map(n=><button key={n} className={screen===n?"active":""} aria-current={screen===n?"page":undefined} onClick={()=>{setScreen(n);setQuery("")}}>{n.charAt(0).toUpperCase()+n.slice(1)}</button>)}</nav><button className="bf-profile" onClick={()=>setEditingProfile(!editingProfile)} aria-expanded={editingProfile} aria-label="Choose demo profile"><span>◈</span>{profile}</button></header>{editingProfile&&<div className="bf-profileMenu"><h2>Demo profiles</h2><p>No BazID profile data is used in this prototype.</p>{profiles.map(p=><button key={p} onClick={()=>{setProfile(p);localStorage.setItem("biflix-demo-profile-v1",p);window.dispatchEvent(new Event("biflix-profile-changed"));setEditingProfile(false)}}>{p}</button>)}{profiles.length<3&&<button onClick={()=>{const name=prompt("New demo profile name (max 20 characters)")?.trim().slice(0,20);if(name&&!profiles.includes(name)){setProfiles([...profiles,name]);localStorage.setItem("biflix-demo-profiles-v1",JSON.stringify([...profiles,name]));setProfile(name);localStorage.setItem("biflix-demo-profile-v1",name);window.dispatchEvent(new Event("biflix-profile-changed"));setEditingProfile(false)}}}>+ Add demo profile</button>}</div>}
 <main id="bf-content">{screen==="home"?<><section className="bf-hero" style={{backgroundImage:`linear-gradient(90deg,#060a16 5%,#080b1b77 60%,#080b1b11),url('${hero.artwork}')`}}><div className="bf-heroCopy"><div className="bf-eyebrow">THE CINEMATIC CONSTELLATION · PROTOTYPE</div><h1>Stories that stay<br/>with you.</h1><p>Watchlist, discovery and a distraction-free local media player. A preview of the Ɓiflix experience.</p><div className="bf-actions"><Link href={`/title/${hero.slug}`} className="bf-primary">Explore {hero.name} →</Link><SavedButton slug={hero.slug}/></div></div></section><Content title="Curated constellation" items={titles.slice(0,4)}/><Content title="Explore new worlds" items={titles.slice(2)}/></>:screen==="downloads"?<div className="bf-blank"><span>⌁</span><h1>Downloads, designed for control.</h1><p>Licensed offline media requires rights clearance, entitlement, DRM and native secure storage. This preview does not fake downloadable commercial content.</p><Link className="bf-primary" href={`/watch/${hero.slug}`}>Try local playback →</Link></div>:<><div className="bf-search"><div className="bf-eyebrow">{screen==="saved"?"YOUR SPACE":"DISCOVER BY INTENTION"}</div><h1>{screen==="saved"?"Saved for later":"What do you feel like watching?"}</h1><label htmlFor="bf-search">Filter by title or genre</label><input id="bf-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search fictional demo entries…"/></div><Content title={screen==="saved"?`${filtered.length} saved`:`${filtered.length} discoveries`} items={filtered}/></>}</main><footer className="bf-footer"><strong>Ɓiflix</strong><span>Original BAZAARA design · Demo catalog only · No licensed streaming or DRM in this build</span></footer><div className="bf-mobileNav">{nav.map(n=><button key={n} aria-current={screen===n?"page":undefined} onClick={()=>setScreen(n)}>{n}</button>)}</div></div>
}
function Content({title,items}:{title:string;items:typeof titles}){return <section className="bf-shelf"><h2>{title}</h2>{items.length?<div className="bf-cards">{items.map(t=><article className="bf-tile" key={t.slug}><Link href={`/title/${t.slug}`} aria-label={`Details for ${t.name}`}><div className="bf-tileArt" style={{backgroundImage:`url('${t.artwork}')`}}/><div className="bf-tileMeta"><strong>{t.name}</strong><small>{t.kind} · {t.year} · {t.genres[0]}</small></div></Link></article>)}</div>:<p className="bf-muted">Nothing in this collection yet.</p>}</section>}
