import { StyleSheet } from "react-native";

export const groceryPalette = {
  background: "#0B0C0B",
  surface: "#111311",
  surface2: "#171A17",
  surface3: "#1D211D",
  line: "rgba(255,255,255,.085)",
  lineStrong: "rgba(255,255,255,.14)",
  text: "#F5F6F4",
  muted: "#A0A49F",
  muted2: "#777D77",
  primary: "#2F8F62",
  primary2: "#2F8F62",
  lime: "#3FA46F",
  orange: "#C88A3A",
  danger: "#E97984",
  success: "#65B98A",
  white: "#FFFFFF",
} as const;

export const groceryTone = {
  primary: groceryPalette.primary,
  secondary: groceryPalette.success,
};

export const groceryStyles = StyleSheet.create({
  top: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 14,
  },
  brand: {
    color: groceryPalette.text,
    fontSize: 20,
    fontWeight: "900",
    letterSpacing: -0.7,
  },
  brandAccent: { color: groceryPalette.success },
  h1: {
    color: groceryPalette.text,
    fontSize: 29,
    lineHeight: 32,
    fontWeight: "900",
    letterSpacing: -1.1,
  },
  h2: {
    color: groceryPalette.text,
    fontSize: 19,
    lineHeight: 23,
    fontWeight: "900",
    letterSpacing: -0.45,
  },
  p: {
    color: groceryPalette.muted,
    fontSize: 12.5,
    lineHeight: 18.5,
  },
  small: {
    color: groceryPalette.muted2,
    fontSize: 9.5,
    lineHeight: 14,
  },
  name: {
    color: groceryPalette.text,
    fontSize: 14.5,
    lineHeight: 18,
    fontWeight: "800",
  },
  meta: {
    color: groceryPalette.muted,
    fontSize: 10.5,
    lineHeight: 15,
  },
  price: {
    color: groceryPalette.text,
    fontSize: 15,
    fontWeight: "900",
  },
  status: {
    color: groceryPalette.success,
    fontSize: 9.5,
    fontWeight: "900",
    letterSpacing: 0.4,
  },
  card: {
    borderWidth: 1,
    borderColor: groceryPalette.line,
    borderRadius: 15,
    backgroundColor: groceryPalette.surface,
    padding: 13,
    gap: 6,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    gap: 9,
  },
  wrap: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  button: {
    minHeight: 44,
    borderRadius: 11,
    backgroundColor: groceryPalette.primary,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 15,
  },
  buttonText: {
    color: "#FFFFFF",
    fontSize: 11.5,
    fontWeight: "900",
  },
  secondary: {
    minHeight: 42,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: groceryPalette.line,
    backgroundColor: groceryPalette.surface2,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 13,
  },
  secondaryText: {
    color: "#D5D8D5",
    fontSize: 10.5,
    fontWeight: "800",
  },
  pill: {
    minHeight: 34,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: groceryPalette.line,
    backgroundColor: groceryPalette.surface,
    paddingHorizontal: 11,
    paddingVertical: 7,
    justifyContent: "center",
  },
  pillActive: {
    borderColor: "rgba(47,143,98,.36)",
    backgroundColor: "rgba(47,143,98,.12)",
  },
  pillText: {
    color: groceryPalette.muted,
    fontSize: 9.5,
    fontWeight: "800",
  },
  pillTextActive: { color: "#DDE9E1" },
  input: {
    minHeight: 44,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: groceryPalette.line,
    backgroundColor: "#0F110F",
    color: groceryPalette.text,
    paddingHorizontal: 12,
  },
  search: {
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 0,
    backgroundColor: groceryPalette.surface2,
    color: groceryPalette.text,
    paddingHorizontal: 14,
    fontSize: 13.5,
  },
  label: {
    color: "#B6BAB6",
    fontSize: 10,
    fontWeight: "800",
  },
  error: {
    color: "#F3A1AA",
    lineHeight: 18,
    fontSize: 11,
  },
  success: {
    color: groceryPalette.success,
    lineHeight: 18,
    fontSize: 10.5,
    fontWeight: "700",
  },
  divider: {
    height: 1,
    backgroundColor: groceryPalette.line,
    marginVertical: 8,
  },
  image: {
    width: "100%",
    height: 150,
    backgroundColor: groceryPalette.surface2,
    borderRadius: 13,
  },
  product: {
    width: "48.5%",
    borderWidth: 1,
    borderColor: groceryPalette.line,
    borderRadius: 15,
    backgroundColor: groceryPalette.surface,
    overflow: "hidden",
    marginBottom: 8,
  },
  productBody: {
    padding: 9,
    gap: 4,
  },
  thumb: {
    width: "100%",
    aspectRatio: 1.08,
    backgroundColor: groceryPalette.surface2,
  },
  section: { marginTop: 20 },
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 10,
  },
});
