"use client";
import {useEffect,useMemo,useState} from "react";
type Item={id:string,title:string,content:string,createdAt:string,updatedAt:string};
export default function ProductApp(){
 const [items,setItems]=useState<Item[]>([]),[query,setQuery]=useState(""),[busy,setBusy]=useState(true),[error,setError]=useState(""),[open,setOpen]=useState(false),[editing,setEditing]=useState<Item|null>(null),[title,setTitle]=useState(""),[content,setContent]=useState("");
 const load=async()=>{setBusy(true);setError("");try{const r=await fetch("/api/items",{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.message||"Unable to load");setItems(j.items||[])}catch(e:any){setError(e.message||"Unable to load") }finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const shown=useMemo(()=>items.filter(x=>(x.title+" "+x.content).toLowerCase().includes(query.toLowerCase())),[items,query]);
 function start(item?:Item){setEditing(item||null);setTitle(item?.title||"");setContent(item?.content||"");setOpen(true)}
 async function save(){if(!title.trim())return;setError("");const method=editing?"PUT":"POST";const r=await fetch("/api/items",{method,headers:{"content-type":"application/json"},body:JSON.stringify({id:editing?.id,title:title.trim(),content})});const j=await r.json();if(!r.ok){setError(j.message||"Save failed");return}setOpen(false);await load()}
 async function remove(id:string){if(!confirm("Delete this item?"))return;const r=await fetch(`/api/items?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(!r.ok){const j=await r.json();setError(j.message||"Delete failed");return}await load()}
 return <div className="shell"><header className="top"><div className="mark">B</div><div><div className="brand">BAZAARA Projects</div><small>Connected workspace</small></div></header><div className="layout"><aside className="side"><button className="active">Projects</button><button>Recent</button><button>Shared with me</button><button>Starred</button><button>Trash</button></aside><main className="main"><div className="hero"><div><h1>Projects</h1><p>Track project work, context and ownership.</p></div><button className="btn" onClick={()=>start()}>+ Create project</button></div>{error&&<div className="status">{error}</div>}<div className="toolbar"><input className="search" placeholder="Search projects..." value={query} onChange={e=>setQuery(e.target.value)}/></div>{busy?<div className="empty">Loading…</div>:shown.length===0?<div className="empty">No projects yet. Create your first one.</div>:<div className="grid">{shown.map(i=><article className="card" key={i.id}><h3>{i.title}</h3><p>{i.content.slice(0,220)||"No details yet."}</p><div className="meta">Updated {new Date(i.updatedAt).toLocaleString()}</div><div className="actions"><button onClick={()=>start(i)}>Edit</button><button className="danger" onClick={()=>remove(i.id)}>Delete</button></div></article>)}</div>}</main></div>{open&&<div className="modal" onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><div className="panel"><h2>{editing?"Edit":"Create"} project</h2><input autoFocus placeholder="Title" value={title} onChange={e=>setTitle(e.target.value)}/><textarea placeholder="Details" value={content} onChange={e=>setContent(e.target.value)}/><div className="row"><button className="btn secondary" onClick={()=>setOpen(false)}>Cancel</button><button className="btn" onClick={save}>Save</button></div></div></div>}</div>}
