"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { api, errorText } from "@bazaara/social-ui";
import { Access, Frame, State, useReady } from "./Frame";
type Plan={startMs:number;endMs:number;brightness:number;contrast:number;aspectRatio?:"ORIGINAL"|"9:16"|"16:9"|"1:1";playbackRate?:number;muted?:boolean;captions:Array<{startMs:number;endMs:number;text:string}>};
type Project={id:string;title:string;editPlan:Plan;status:string;updatedAt:string;source?:{url:string}|null};
export default function BazCutNext(){
 const session=useReady();const player=useRef<HTMLVideoElement>(null);const [projects,setProjects]=useState<Project[]>([]),[selected,setSelected]=useState(""),[title,setTitle]=useState(""),[plan,setPlan]=useState<Plan|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[status,setStatus]=useState("");const [mode,setMode]=useState<"build"|"grade"|"sound">("build");
 const load=useCallback(async()=>{try{const r=await api.get<{projects:Project[]}>("/v1/bazcut/projects",{maxRetries:0});setProjects(r.projects)}catch(e){setError(errorText(e))}},[]);
 useEffect(()=>{if(session.user?.profile)void load()},[session.user?.profile,load]);
 const current=projects.find(p=>p.id===selected);
 useEffect(()=>{const video=player.current;if(video)video.playbackRate=plan?.playbackRate??1;},[selected,plan?.playbackRate]);
 function choose(p:Project){setSelected(p.id);setTitle(p.title);setPlan({...p.editPlan, captions:p.editPlan.captions??[]});setStatus("")}
 async function save(){if(!selected||!plan||busy)return;setBusy(true);try{await api.patch(`/v1/bazcut/projects/${encodeURIComponent(selected)}`,{title:title.trim()||"Untitled project",editPlan:plan});setStatus("Edit plan saved.");await load()}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <Frame app="BazCut" initial="CREATOR STUDIO" mark="✂" accent="#4a7fff" nav={[{id:"build",label:"Build",active:mode==="build",onClick:()=>setMode("build")},{id:"grade",label:"Grade",active:mode==="grade",onClick:()=>setMode("grade")},{id:"sound",label:"Sound",active:mode==="sound",onClick:()=>setMode("sound")},{id:"projects",label:"Project library",onClick:()=>window.location.assign("/")}]}><Access session={session} app="BazCut"/>{session.user?.profile&&<><div className="nx-cutTop"><div><div className="nx-eyebrow">NONDESTRUCTIVE EDIT PLAN</div><h1>Build something unforgettable.</h1><p className="nx-muted">Preview and persist existing project adjustments. Multi-track rendering is a separate engineering milestone.</p></div><div className="nx-row"><a href="/" className="nx-secondary">Import media ↗</a><button className="nx-primary" onClick={()=>void save()} disabled={!current||!plan||busy}>Save changes</button></div></div>{error&&<div className="nx-alert" role="alert">{error}</div>}{status&&<div role="status" className="nx-tag">{status}</div>}
 <div className="nx-cutEditor"><aside className="nx-card nx-cutBin"><h2>Project media</h2><button className="nx-secondary" onClick={()=>void load()}>Refresh</button><div className="nx-list nx-section">{projects.map(p=><button key={p.id} className={`nx-item ${selected===p.id?"nx-on":""}`} onClick={()=>choose(p)}><span className="nx-thumb">▶</span><span><strong>{p.title}</strong><small>{new Date(p.updatedAt).toLocaleDateString()}</small></span></button>)}{!projects.length&&<State>Start by creating a project in the current BazCut app.</State>}</div></aside><section className="nx-cutMonitor"><div className="nx-cutScreen">{current?.source?.url?<video key={current.id} ref={player} controls playsInline src={current.source.url} style={{filter:`brightness(${plan?.brightness??100}%) contrast(${plan?.contrast??100}%)`}} muted={plan?.muted}/>:<div className="nx-cutEmpty"><span>▱</span><strong>PREVIEW MONITOR</strong><p>Select a project with media to inspect it here.</p></div>}</div><div className="nx-cutTimeline nx-card"><div className="nx-row"><h3>Timeline</h3><span className="nx-tag">Preview · edit plan</span></div><div className="nx-cutRuler">{[0,5,10,15,20,25,30].map(n=><span key={n}>{n}s</span>)}</div><div className="nx-cutTrack" aria-label="Video track">{current?<div style={{left:`${Math.min(96,(plan?.startMs??0)/300)}%`,width:`${Math.min(100,Math.max(7,((plan?.endMs??0)-(plan?.startMs??0))/300))}%`}}><strong>{current.title}</strong></div>:null}</div><div className="nx-cutTrack nx-cutAudio" aria-label="Audio track"><span>{current?"Source audio · project plan":"No audio imported"}</span></div><p className="nx-muted">A visual overview of the saved plan. Drag editing, tracks and export worker are not active in this preview.</p></div></section>
 <aside className="nx-card nx-cutInspector"><h2>{mode==="build"?"Build inspector":mode==="grade"?"Color studio":"Audio controls"}</h2>{!plan?<State>Choose a project to adjust its properties.</State>:<><label className="nx-cutField">Project title<input className="nx-input" value={title} onChange={e=>setTitle(e.target.value)}/></label>{mode==="build"?<><label className="nx-cutField">Aspect ratio<select className="nx-input" value={plan.aspectRatio??"ORIGINAL"} onChange={e=>setPlan({...plan,aspectRatio:e.target.value as Plan["aspectRatio"]})}>{["ORIGINAL","9:16","16:9","1:1"].map(x=><option key={x} value={x}>{x}</option>)}</select></label><label className="nx-cutField">Start (ms)<input className="nx-input" type="number" min="0" max={plan.endMs} value={plan.startMs} onChange={e=>setPlan({...plan,startMs:Number(e.target.value)})}/></label><label className="nx-cutField">End (ms)<input className="nx-input" type="number" min={plan.startMs} value={plan.endMs} onChange={e=>setPlan({...plan,endMs:Number(e.target.value)})}/></label><label className="nx-cutField">Playback speed<select className="nx-input" value={plan.playbackRate??1} onChange={e=>setPlan({...plan,playbackRate:Number(e.target.value)})}>{[0.5,0.75,1,1.25,1.5,2].map(n=><option value={n} key={n}>{n}×</option>)}</select></label></>:mode==="grade"?<>{(["brightness","contrast"] as const).map(k=><label key={k} className="nx-cutField">{k} · {plan[k]}%<input type="range" min="30" max="170" value={plan[k]} onChange={e=>setPlan({...plan,[k]:Number(e.target.value)})}/></label>)}</>:<label className="nx-cutField">Mute source audio<input type="checkbox" checked={plan.muted??false} onChange={e=>setPlan({...plan,muted:e.target.checked})}/></label>}<button className="nx-primary" disabled={busy||plan.endMs<=plan.startMs} onClick={()=>void save()}>Save plan</button></>}</aside></div></>}</Frame>
}
