"use client";
import {useCallback,useEffect,useState,type FormEvent} from "react";
import {api,errorText,uploadMedia} from "@bazaara/social-ui";
import {Dock,Failure,Notice} from "./Dock";
type Person={id:string;displayName:string|null;socialProfile?:{handle:string}|null};
type Transfer={id:string;fileName:string;byteSize:number;status:string;createdAt:string;expiresAt:string;downloadCount:number;maxDownloads:number|null;sender:Person;recipient:Person};
export default function Tools(){return <Dock app="BSend">{()=> <Panel/>}</Dock>}
function Panel(){
 const [files,setFiles]=useState<File[]>([]),[query,setQuery]=useState(""),[people,setPeople]=useState<Person[]>([]),[recipient,setRecipient]=useState<Person|null>(null),[expires,setExpires]=useState(86400),[limit,setLimit]=useState(1),[note,setNote]=useState(""),[inbox,setInbox]=useState<Transfer[]>([]),[outbox,setOutbox]=useState<Transfer[]>([]),[tab,setTab]=useState<"send"|"activity">("send"),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const x=await api.get<{inbox:Transfer[];outbox:Transfer[]}>("/v1/bazsend/transfers",{maxRetries:0});setInbox(x.inbox);setOutbox(x.outbox)}catch(e){setError(errorText(e))}},[]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{if(recipient||query.trim().length<2){setPeople([]);return}const i=setTimeout(()=>void api.get<{users:Person[]}>("/v1/social/users",{query:{q:query.trim()},maxRetries:0}).then(x=>setPeople(x.users)).catch(e=>setError(errorText(e))),350);return()=>clearTimeout(i)},[query,recipient]);
 function choose(next:FileList|null){if(!next)return;const all=Array.from(next);if(all.length>4){setError("Choose at most four files per batch.");return}if(all.some(f=>f.size===0||f.size>250*1024*1024)){setError("Each file must be non-empty and at most 250 MB.");return}setFiles(all);setError("")}
 async function send(e:FormEvent){e.preventDefault();if(!recipient||!files.length||busy)return;setBusy(true);setError("");let done=0;try{for(const f of files){setNotice(`Uploading file ${done+1} of ${files.length}: ${f.name}`);const asset=await uploadMedia(f,"PRIVATE");await api.post("/v1/bazsend/transfers",{recipientUserId:recipient.id,assetId:asset.id,fileName:f.name,note:note.trim(),maxDownloads:limit,expiresInSeconds:expires});done++}setFiles([]);setNote("");setNotice(`${done} recipient-restricted transfer(s) created. This is internet/cloud transfer, not nearby P2P.`);setTab("activity");await load()}catch(e){setError(`${errorText(e)}${done?` ${done} of ${files.length} files were sent before the error.`:""}`);setNotice("");await load()}finally{setBusy(false)}}
 async function accept(t:Transfer){try{await api.post(`/v1/bazsend/transfers/${encodeURIComponent(t.id)}/accept`,{});setNotice("Transfer accepted.");await load()}catch(e){setError(errorText(e))}}
 async function download(t:Transfer){try{const x=await api.get<{download:{url:string}}>(`/v1/bazsend/transfers/${encodeURIComponent(t.id)}/download`,{maxRetries:0});window.open(x.download.url,"_blank","noopener,noreferrer");await load()}catch(e){setError(errorText(e))}}
 async function revoke(t:Transfer){if(!confirm(`Revoke ${t.fileName}?`))return;try{await api.post(`/v1/bazsend/transfers/${encodeURIComponent(t.id)}/revoke`,{});setNotice("Transfer revoked.");await load()}catch(e){setError(errorText(e))}}
 const active=(s:string)=>s==="PENDING"||s==="ACCEPTED";
 return <><span className="tag">REAL PRIVATE CLOUD TRANSFERS</span><h2>Batch transfer control</h2><p>Send up to four files to one verified recipient with expiry and download limits. Accept, download and revoke individual transfers. Native Bluetooth/LAN discovery and resumable encrypted P2P are not part of this web release.</p><div className="actions"><button className={tab==="send"?"primary":""} onClick={()=>setTab("send")}>Send</button><button className={tab==="activity"?"primary":""} onClick={()=>setTab("activity")}>Activity</button><button onClick={()=>void load()}>Refresh</button></div><Failure message={error} clear={()=>setError("")}/><Notice message={notice}/>
 {tab==="send"?<form className="card" onSubmit={e=>void send(e)}><h3>Private batch</h3><label>Choose 1–4 files<input type="file" multiple disabled={busy} onChange={e=>choose(e.target.files)}/></label>{files.map(f=><p className="textbox" key={`${f.name}-${f.size}`}>{f.name} · {(f.size/1048576).toFixed(1)} MB</p>)}<label>Recipient handle or display name<input value={query} onChange={e=>{setQuery(e.target.value);setRecipient(null)}} disabled={busy} placeholder="Find a discoverable member"/></label>{recipient?<p>Recipient selected: <strong>{recipient.displayName??"Member"}</strong> <button type="button" onClick={()=>{setRecipient(null);setQuery("")}}>Change</button></p>:<div className="list">{people.map(p=><button className="item" type="button" key={p.id} onClick={()=>{setRecipient(p);setQuery(p.displayName??p.socialProfile?.handle??"");setPeople([])}}>{p.displayName??"Member"} · @{p.socialProfile?.handle??"member"}</button>)}</div>}<label>Note<textarea maxLength={500} rows={3} value={note} onChange={e=>setNote(e.target.value)}/></label><div className="grid2"><label>Expires in<select value={expires} onChange={e=>setExpires(Number(e.target.value))}><option value={3600}>1 hour</option><option value={86400}>24 hours</option><option value={604800}>7 days</option></select></label><label>Download limit<select value={limit} onChange={e=>setLimit(Number(e.target.value))}>{[1,2,5,10,25].map(n=><option key={n} value={n}>{n}</option>)}</select></label></div><button className="primary" disabled={!recipient||!files.length||busy}>{busy?"Sending…":"Send private batch"}</button></form>:<div className="grid2">{([{title:"Received",rows:inbox,received:true},{title:"Sent",rows:outbox,received:false}] as const).map(group=><section className="card" key={group.title}><h3>{group.title}</h3><div className="list">{group.rows.map(t=><div className="card" key={t.id}><strong className="textbox">{t.fileName}</strong><p>{(t.byteSize/1048576).toFixed(1)} MB · {t.status}<br/>Expires {new Date(t.expiresAt).toLocaleString()}</p><span className="chip">{t.downloadCount}/{t.maxDownloads??"∞"} downloads</span>{active(t.status)&&<div className="actions">{group.received?<>{t.status==="PENDING"&&<button onClick={()=>void accept(t)}>Accept</button>}<button onClick={()=>void download(t)}>Download</button></>:<button onClick={()=>void revoke(t)}>Revoke</button>}</div>}</div>)}{!group.rows.length&&<p>Nothing here yet.</p>}</div></section>)}</div>}
 </>
}
