'use client';
import {useCallback,useEffect,useMemo,useRef,useState,type FormEvent} from 'react';
import {Dialog,Field,ToolRow,download,useCollection} from '../../../packages/flagship-ui/src/core';
import StandaloneFrame from './StandaloneFrame';

type Article={id:string;title:string;description:string;url:string;source:string;publishedAt:string;category:string;image?:string};
type Reading={id:string;collection:string;note:string;readAt:string};
const validReading=(v:unknown):v is Reading=>{const r=v as Reading;return !!r&&typeof r.id==='string'&&validUrl(r.id)&&['collection','note','readAt'].every(k=>typeof (r as unknown as Record<string,unknown>)[k]==='string');};
function safeArticle(v:unknown):v is Article{const a=v as Article;return !!a&&typeof a.url==='string'&&validUrl(a.url)&&['id','title','description','source','publishedAt','category'].every(k=>typeof (a as unknown as Record<string,unknown>)[k]==='string')&&(a.image===undefined||typeof a.image==='string'&&validUrl(a.image));}
type Section='For you'|'Headlines'|'Local'|'Nigeria'|'Following'|'Newsstand'|'Saved'|'Business'|'Technology'|'World'|'Africa';
type Topic='Politics'|'World'|'Business'|'Technology'|'Science'|'Health'|'Sports'|'Energy'|'Entertainment'|'Public health'|'Education'|'Climate';
const TOPICS:Topic[]=['Politics','World','Business','Technology','Science','Health','Sports','Energy','Entertainment','Public health','Education','Climate'];
const PUBS=[
 {name:'BBC News',url:'https://www.bbc.com/news',tag:'BBC',group:'Headlines'},
 {name:'Punch Newspapers',url:'https://punchng.com',tag:'P',group:'Headlines'},
 {name:'TheCable',url:'https://www.thecable.ng',tag:'TC',group:'Headlines'},
 {name:'Vanguard',url:'https://www.vanguardngr.com',tag:'V',group:'Headlines'},
 {name:'Premium Times',url:'https://www.premiumtimesng.com',tag:'PT',group:'Headlines'},
 {name:'Channels Television',url:'https://www.channelstv.com',tag:'CH',group:'Headlines'},
 {name:'Legit.ng',url:'https://www.legit.ng',tag:'L',group:'Business'},
 {name:'TVC News',url:'https://www.tvcnews.tv',tag:'TVC',group:'Business'},
 {name:'Daily Post Nigeria',url:'https://dailypost.ng',tag:'DP',group:'Business'},
];
const KEY='bazaara-news-personal-v8';
const STOP=new Set(['the','a','an','and','or','to','of','in','on','for','with','from','at','as','is','are','was','were','be','by','after','before','over','under','new','latest']);
function load(){try{const raw=JSON.parse(localStorage.getItem(KEY)||'{}') as {saved?:Article[];topics?:Topic[];publishers?:string[];region?:string;hiddenSources?:string[];downrankTerms?:string[]};return{saved:Array.isArray(raw.saved)?raw.saved.filter(safeArticle).slice(0,100):[],topics:Array.isArray(raw.topics)?raw.topics.filter(t=>TOPICS.includes(t)).slice(0,12):[],publishers:Array.isArray(raw.publishers)?raw.publishers.filter(s=>PUBS.some(p=>p.name===s)):[],region:typeof raw.region==='string'?raw.region.slice(0,60):'Nigeria',hiddenSources:Array.isArray(raw.hiddenSources)?raw.hiddenSources.filter(x=>typeof x==='string').slice(0,30):[],downrankTerms:Array.isArray(raw.downrankTerms)?raw.downrankTerms.filter(x=>typeof x==='string').slice(0,40):[]};}catch{return{saved:[] as Article[],topics:[] as Topic[],publishers:[] as string[],region:'Nigeria',hiddenSources:[] as string[],downrankTerms:[] as string[]};}}
function validUrl(url:string){try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password;}catch{return false;}}
function share(item:Article){if(navigator.share){void navigator.share({title:item.title,url:item.url}).catch(()=>{});}else if(navigator.clipboard){void navigator.clipboard.writeText(item.url);}}
function tokens(value:string){return [...new Set(value.toLowerCase().replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(word=>word.length>3&&!STOP.has(word)))];}
function related(seed:Article,items:Article[]){const seedTokens=new Set(tokens(`${seed.title} ${seed.description}`));return items.filter(item=>item.url!==seed.url).map(item=>({item,score:tokens(`${item.title} ${item.description}`).filter(token=>seedTokens.has(token)).length})).filter(row=>row.score>0).sort((a,b)=>b.score-a.score).slice(0,8).map(row=>row.item);}

export default function NewsExperience(){
 const reading=useCollection<Reading>('news-reading-v2',validReading);const [reader,setReader]=useState<Reading|null>(null),[readFilter,setReadFilter]=useState('all'),[collection,setCollection]=useState(''),[age,setAge]=useState('any');const request=useRef<AbortController|null>(null);
 const [section,setSection]=useState<Section>('For you'),[articles,setArticles]=useState<Article[]>([]),[saved,setSaved]=useState<Article[]>([]),[topics,setTopics]=useState<Topic[]>([]),[publishers,setPublishers]=useState<string[]>([]),[region,setRegion]=useState('Nigeria'),[searchMode,setSearchMode]=useState(false),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[updated,setUpdated]=useState(''),[loaded,setLoaded]=useState(false),[interestOpen,setInterestOpen]=useState(false),[hiddenSources,setHiddenSources]=useState<string[]>([]),[downrankTerms,setDownrankTerms]=useState<string[]>([]),[coverage,setCoverage]=useState<Article|null>(null),[tune,setTune]=useState<Article|null>(null);
 useEffect(()=>{const p=load();setSaved(p.saved);setTopics(p.topics);setPublishers(p.publishers);setRegion(p.region);setHiddenSources(p.hiddenSources);setDownrankTerms(p.downrankTerms);setLoaded(true);const params=new URLSearchParams(window.location.search);const q=(params.get('q')||'').trim();if(q.length>0&&q.length<=180){setQuery(q);setSearchMode(true);}const sectionParam=params.get('section');if(sectionParam&&['For you','Headlines','Local','Nigeria','Following','Newsstand','Saved','Business','Technology','World','Africa'].includes(sectionParam))setSection(sectionParam as Section);},[]);
 useEffect(()=>{if(!loaded)return;try{localStorage.setItem(KEY,JSON.stringify({saved,topics,publishers,region,hiddenSources,downrankTerms}));}catch{}},[saved,topics,publishers,region,hiddenSources,downrankTerms,loaded]);
 const category=useMemo(()=>({'For you':'top','Headlines':'top','Following':'top','Local':'local','Nigeria':'nigeria','Newsstand':'top','Saved':'top','Business':'business','Technology':'technology','World':'world','Africa':'africa'} as Record<Section,string>)[section],[section]);
 const reload=useCallback(async(cat:string)=>{request.current?.abort();const controller=new AbortController();request.current=controller;setLoading(true);setError('');try{const resp=await fetch(`/api/headlines?category=${encodeURIComponent(cat)}`,{cache:'no-store',credentials:'same-origin',signal:controller.signal});const body=await resp.json() as {articles?:Article[];message?:string;retrievedAt?:string};if(!resp.ok)throw Error(body.message||'News is temporarily unavailable.');if(controller.signal.aborted)return;const seen=new Set<string>();setArticles(Array.isArray(body.articles)?body.articles.filter(safeArticle).filter(a=>{if(seen.has(a.url))return false;seen.add(a.url);return true;}):[]);setUpdated(body.retrievedAt||'');}catch(e){if(!controller.signal.aborted){setError(e instanceof Error?e.message:'Could not load publisher feeds.');setArticles([]);}}finally{if(request.current===controller&&!controller.signal.aborted)setLoading(false);}},[]);
 useEffect(()=>{request.current?.abort();if(section!=='Saved'&&section!=='Newsstand')void reload(category);else setLoading(false);return()=>{request.current?.abort();window.speechSynthesis?.cancel();};},[section,category,reload]);
 const metadata=(a:Article)=>reading.items.find(r=>r.id===a.url)||{id:a.url,collection:'Reading list',note:'',readAt:''};
 const markRead=(a:Article)=>reading.put({...metadata(a),readAt:new Date().toISOString()});
 const visible=useMemo(()=>{let all=section==='Saved'?saved:articles;all=all.filter(a=>!hiddenSources.includes(a.source));const relevance=(a:Article)=>{const body=`${a.title} ${a.description} ${a.category}`.toLowerCase();const positive=(topics.some(t=>body.includes(t.toLowerCase()))?2:0)+(publishers.some(p=>a.source.toLowerCase().includes(p.toLowerCase().split(' ')[0]))?3:0);const negative=downrankTerms.some(term=>body.includes(term))?-4:0;return positive+negative;};if(section==='Following')all=all.filter(a=>(topics.length>0||publishers.length>0)&&relevance(a)>0);if(section==='For you'&&(topics.length>0||publishers.length>0||downrankTerms.length>0))all=[...all].sort((a,b)=>relevance(b)-relevance(a));if(section==='Local'&&region!=='Nigeria')all=all.filter(a=>`${a.title} ${a.description}`.toLowerCase().includes(region.toLowerCase()));if(query.trim())all=all.filter(a=>`${a.title} ${a.description} ${a.source}`.toLowerCase().includes(query.trim().toLowerCase()));all=all.filter(a=>{const m=reading.items.find(r=>r.id===a.url);return (!collection||(m?.collection||'Reading list')===collection)&&(readFilter==='all'||readFilter==='read'&&!!m?.readAt||readFilter==='unread'&&!m?.readAt)&&(age==='any'||Number.isFinite(Date.parse(a.publishedAt))&&Date.parse(a.publishedAt)>=Date.now()-(age==='day'?86400000:604800000));});return all;},[articles,section,saved,topics,publishers,region,query,hiddenSources,downrankTerms,reading.items,collection,readFilter,age]);
 const coverageItems=useMemo(()=>coverage?related(coverage,articles):[],[coverage,articles]);
 const starred=(a:Article)=>saved.some(x=>x.url===a.url);
 const save=(a:Article)=>setSaved(current=>current.some(x=>x.url===a.url)?current.filter(x=>x.url!==a.url):[a,...current].slice(0,100));
 const topicsToggle=(t:Topic)=>setTopics(curr=>curr.includes(t)?curr.filter(x=>x!==t):[...curr,t]);
 const pubToggle=(p:string)=>setPublishers(curr=>curr.includes(p)?curr.filter(x=>x!==p):[...curr,p]);
 const goto=(s:string)=>{setSection(s as Section);setQuery('');setSearchMode(false);};
 function fewerLike(a:Article){const key=tokens(`${a.title} ${a.description}`)[0];if(!key)return;setDownrankTerms(current=>current.includes(key)?current:[...current,key].slice(-40));setTune(null);}
 function hideSource(source:string){setHiddenSources(current=>current.includes(source)?current:[...current,source].slice(-30));setTune(null);}
 function listenBriefing(){if(!('speechSynthesis' in window)){setError('Audio briefing is unavailable in this browser.');return;}const copy=visible.slice(0,6).map((item,index)=>`${index+1}. ${item.title}. ${item.source}.`).join(' ');if(!copy){setError('No stories are loaded for a briefing.');return;}window.speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(copy.slice(0,6000));utterance.rate=.96;window.speechSynthesis.speak(utterance);}
 const lead=visible[0], secondary=visible.slice(1,7), moreStories=visible.slice(7);
 const translateLink=(story:Article)=>{
   let base='';
   try{const configured=JSON.parse(process.env.NEXT_PUBLIC_BAZAARA_APP_URLS||'{}') as Record<string,unknown>;if(typeof configured.translate==='string'&&/^https:\/\//.test(configured.translate))base=configured.translate;}catch{}
   if(!base&&typeof window!=='undefined'&&['localhost','127.0.0.1'].includes(window.location.hostname))base=`${window.location.protocol}//${window.location.hostname}:3039/`;
   if(!base)return '#';
   const url=new URL(base);url.searchParams.set('text',story.title.slice(0,240));return url.href;
 };
 const tabs=['For you','Headlines','Local','Nigeria','Following','Newsstand','Saved','Business','Technology','World','Africa'];
 return <StandaloneFrame product="News" tagline="" tabs={tabs} active={section} onTab={goto} actions={<button type="button" className="ig5-top-icon" aria-label="Search headlines" aria-expanded={searchMode} onClick={()=>setSearchMode(value=>!value)}>⌕</button>}>
  {searchMode&&<form className="bz83-news-search" role="search" onSubmit={(e:FormEvent)=>e.preventDefault()}><span>⌕</span><input aria-label="Search news" autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search topics, locations and sources"/><button type="button" onClick={()=>{setSearchMode(false);setQuery('');}}>×</button></form>}
  <ToolRow><select aria-label="Reading status" value={readFilter} onChange={e=>setReadFilter(e.target.value)}><option value="all">All stories</option><option value="unread">Unread</option><option value="read">Read</option></select><select aria-label="Story age" value={age} onChange={e=>setAge(e.target.value)}><option value="any">Any date</option><option value="day">Past day</option><option value="week">Past week</option></select>{section==='Saved'&&<><select aria-label="Reading collection" value={collection} onChange={e=>setCollection(e.target.value)}><option value="">All reading lists</option>{[...new Set(['Reading list',...reading.items.map(r=>r.collection)])].map(c=><option key={c}>{c}</option>)}</select><button onClick={()=>download('bazaara-reading-list.json',JSON.stringify({version:1,stories:saved,reading:reading.items},null,2))}>Export reading list</button></>}<button disabled={loading||section==='Saved'||section==='Newsstand'} onClick={()=>void reload(category)}>Refresh feed</button><span>{visible.length} stories</span></ToolRow>
  {error&&<div className="bz8-error" role="alert">{error}</div>}

  {coverage&&<div className="bz83-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setCoverage(null);}}><section className="bz83-sheet" role="dialog" aria-modal="true" aria-label="Full coverage"><header><div><small>FULL COVERAGE</small><h2>{coverage.title}</h2></div><button onClick={()=>setCoverage(null)} aria-label="Close">×</button></header><article className="bz83-coverage-lead"><span>{coverage.source}</span><p>{coverage.description||'Open the publisher for the full story.'}</p><a href={coverage.url} target="_blank" rel="noopener noreferrer">Read original ↗</a></article><div className="bz83-inline-actions"><button onClick={()=>markRead(coverage)}>Mark read</button><button onClick={()=>setReader(metadata(coverage))}>Reading notes</button></div><h3>More perspectives</h3>{coverageItems.length?<div className="bz83-coverage-list">{coverageItems.map(item=><a href={item.url} key={item.url} target="_blank" rel="noopener noreferrer"><strong>{item.title}</strong><span>{item.source}</span></a>)}</div>:<p className="bz83-muted">No sufficiently related article exists in the currently loaded feed.</p>}</section></div>}

  {tune&&<div className="bz83-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setTune(null);}}><section className="bz83-sheet bz83-tune" role="dialog" aria-modal="true"><header><div><small>TUNE YOUR FEED</small><h2>{tune.source}</h2></div><button onClick={()=>setTune(null)} aria-label="Close">×</button></header><button onClick={()=>save(tune)}>{starred(tune)?'Remove from saved':'Save story'}</button><button onClick={()=>{markRead(tune);setTune(null);}}>Mark read</button><button onClick={()=>{setReader(metadata(tune));setTune(null);}}>Notes & collection</button><button onClick={()=>fewerLike(tune)}>Fewer stories like this</button><button onClick={()=>hideSource(tune.source)}>Hide stories from {tune.source}</button><button onClick={()=>share(tune)}>Share story</button></section></div>}

  {interestOpen&&<div className="bz83-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setInterestOpen(false);}}><section className="bz83-sheet bz83-interests" role="dialog" aria-modal="true"><header><div><small>PERSONALIZE</small><h2>Your news</h2></div><button onClick={()=>setInterestOpen(false)} aria-label="Close">×</button></header><h3>Topics</h3><div className="bz83-chip-grid">{TOPICS.map(topic=><button key={topic} aria-pressed={topics.includes(topic)} onClick={()=>topicsToggle(topic)}>{topics.includes(topic)?'✓ ':''}{topic}</button>)}</div><h3>Preferred sources</h3><div className="bz83-source-grid">{PUBS.map(pub=><button key={pub.name} aria-pressed={publishers.includes(pub.name)} onClick={()=>pubToggle(pub.name)}><b>{pub.tag}</b><span>{pub.name}</span>{publishers.includes(pub.name)&&<i>✓</i>}</button>)}</div>{!!hiddenSources.length&&<><h3>Hidden sources</h3><div className="bz83-chip-grid">{hiddenSources.map(source=><button key={source} onClick={()=>setHiddenSources(hiddenSources.filter(s=>s!==source))}>Show {source}</button>)}</div></>}{!!downrankTerms.length&&<button onClick={()=>setDownrankTerms([])}>Reset reduced-topic preferences</button>}<label className="bz83-region">Local region<input value={region} onChange={e=>setRegion(e.target.value.slice(0,60))}/></label></section></div>}

  {section==='Newsstand'?<div className="bz83-news-page"><div className="bz83-news-section-title"><div><small>NEWSSTAND</small><h1>Sources worth following</h1></div><button onClick={()=>setInterestOpen(true)}>Manage sources</button></div><div className="bz83-newsstand-grid">{PUBS.map(pub=><article key={pub.name}><span>{pub.tag}</span><div><strong>{pub.name}</strong><small>{pub.group}</small></div><button onClick={()=>pubToggle(pub.name)}>{publishers.includes(pub.name)?'Following':'Follow'}</button><a href={pub.url} target="_blank" rel="noopener noreferrer" aria-label={`Open ${pub.name}`}>↗</a></article>)}</div></div>:
  <div className="bz83-news-page">
    <section className="bz83-news-utility"><button className="bz83-listen" onClick={listenBriefing}><span>▶</span><div><strong>Listen to your briefing</strong><small>Top headlines, read aloud on this device</small></div></button><button className="bz83-personalize" onClick={()=>setInterestOpen(true)}><span>✦</span><div><strong>Personalize</strong><small>{topics.length+publishers.length?`${topics.length+publishers.length} preferences`:'Topics & preferred sources'}</small></div></button></section>

    <div className="bz83-news-section-title"><div><small>{section==='For you'?'YOUR BRIEFING':section.toUpperCase()}</small><h1>{section==='For you'?'Top stories':section==='Following'?'Following':section==='Saved'?'Saved stories':section}</h1></div>{updated&&<span>Updated {new Date(updated).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span>}</div>

    {loading?<div className="bz83-news-loading"><span/><span/><span/></div>:!lead?<div className="bz83-empty"><strong>No stories here yet</strong><p>{section==='Following'?'Follow topics or publishers to build this feed.':'Try another section or refresh the publisher feed.'}</p></div>:<>
      <section className="bz83-news-lead">
        <a className="bz83-lead-image" href={lead.url} target="_blank" rel="noopener noreferrer">{lead.image?<img src={lead.image} alt="" loading="eager" referrerPolicy="no-referrer"/>:<div className="bz83-image-fallback">{lead.source.slice(0,2).toUpperCase()}</div>}</a>
        <div className="bz83-lead-copy"><div className="bz83-source-line"><span>{lead.source}</span><button onClick={()=>setTune(lead)} aria-label="Story options">⋮</button></div><a href={lead.url} target="_blank" rel="noopener noreferrer"><h2>{lead.title}</h2></a><p>{lead.description}</p><div className="bz83-story-meta"><span>{lead.publishedAt?new Date(lead.publishedAt).toLocaleString():''}</span><div>{translateLink(lead)!=='#'&&<a href={translateLink(lead)} target="_blank" rel="noopener noreferrer" aria-label="Translate headline">Translate ↗</a>}<button onClick={()=>setCoverage(lead)}>▤ See more</button><button onClick={()=>save(lead)} aria-label={starred(lead)?'Unsave story':'Save story'}>{starred(lead)?'★':'☆'}</button></div></div></div>
      </section>
      <section className="bz83-news-list">{secondary.map(item=><article key={item.url}><div className="bz83-story-copy"><div className="bz83-source-line"><span>{item.source}</span><button onClick={()=>setTune(item)} aria-label="Story options">⋮</button></div><a href={item.url} target="_blank" rel="noopener noreferrer"><h3>{item.title}</h3></a><p>{item.description}</p><div className="bz83-story-meta"><span>{item.publishedAt?new Date(item.publishedAt).toLocaleString():''}</span><div>{translateLink(item)!=='#'&&<a href={translateLink(item)} target="_blank" rel="noopener noreferrer" aria-label="Translate headline">Translate ↗</a>}<button onClick={()=>setCoverage(item)}>▤ See more</button><button onClick={()=>save(item)}>{starred(item)?'★':'☆'}</button></div></div></div>{item.image&&<a href={item.url} className="bz83-story-thumb" target="_blank" rel="noopener noreferrer"><img src={item.image} alt="" loading="lazy" referrerPolicy="no-referrer"/></a>}</article>)}</section>
      {moreStories.length>0&&<section className="bz83-more-news"><h2>More stories</h2>{moreStories.map(item=><article key={item.url}><div><small>{item.source}</small><a href={item.url} target="_blank" rel="noopener noreferrer"><strong>{item.title}</strong></a></div><button onClick={()=>save(item)}>{starred(item)?'★':'☆'}</button></article>)}</section>}
    </>}
  </div>}
 {reader&&<Dialog title="Reading notes" close={()=>setReader(null)}><Field label="Collection"><input autoFocus maxLength={100} value={reader.collection} onChange={e=>setReader({...reader,collection:e.target.value})}/></Field><Field label="Your notes"><textarea maxLength={15000} value={reader.note} onChange={e=>setReader({...reader,note:e.target.value})}/></Field><label><input type="checkbox" checked={!!reader.readAt} onChange={e=>setReader({...reader,readAt:e.target.checked?new Date().toISOString():''})}/> Mark as read</label><button onClick={()=>{if(reading.put({...reader,collection:reader.collection.trim()||'Reading list'})){const story=articles.find(a=>a.url===reader.id);if(story&&!saved.some(a=>a.url===reader.id))setSaved([story,...saved].slice(0,100));setReader(null);}}}>Save reading notes</button>{reading.error&&<p role="alert">{reading.error}</p>}</Dialog>}
 </StandaloneFrame>;
}
