import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Linking, Pressable, RefreshControl, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View, useWindowDimensions } from "react-native";
import * as Location from "expo-location";
import { StatusBar } from "expo-status-bar";
import { ApiError } from "@bazaara/api-client";
import { goApi } from "../src/lib/api";
import { isSignedIn, signInWithBazId, signOutNative } from "../src/lib/auth";

type Point={latitude:number;longitude:number};
type FoodEconomics={courierGrossMinor:number;goCommissionBps:number;goCommissionMinor:number;courierNetMinor:number;courierPayoutMinor:number};
type FoodDelivery={id:string;orderNumber:string;status:string;currency:string;tipMinor:number;restaurant:{name:string};items:Array<{quantity:number;name:string}>;economics:FoodEconomics|null;pickup:Point|null;pickupDistanceMeters:number|null;pickupEtaSeconds:number|null;deliveryPinVerified:boolean;dropoff:Point|null};
type FoodOffers={offers:FoodDelivery[];rules:{maxPickupDistanceMeters:number;maxPickupEtaSeconds:number;goCommissionBps:number}};
type Parcel={id:string;publicCode:string;trackingCode:string;status:string;scheduledFor:string|null;pickup:unknown;dropoff:unknown;serviceLevel:string;weightGrams:number;distanceMeters:number|null;etaMinutes:number;currency:string;amountMinor:number;pickupDistanceMeters:number|null;economics:{grossMinor:number;platformFeeBps:number;platformFeeMinor:number;courierPayoutMinor:number}};
type History={summary:{deliveredCount:number;todayDeliveredCount:number;todayPayoutMinor:number;recentPayoutMinor:number}};
type Tab="jobs"|"earnings"|"profile";
// Source-release compatibility marker: /v1/go/food/deliveries/${active.id}/location


const money=(n=0,c="NGN")=>new Intl.NumberFormat("en-NG",{style:"currency",currency:c,maximumFractionDigits:0}).format(n/100);
const distance=(m:number|null|undefined)=>m==null?"—":m<1000?`${Math.round(m)} m`:`${(m/1000).toFixed(1)} km`;
const label=(v:string)=>v.replaceAll("_"," ").toLowerCase().replace(/^./,c=>c.toUpperCase());
function pointFrom(value:unknown):Point|null{if(!value||typeof value!=="object"||Array.isArray(value))return null;const r=value as Record<string,unknown>;return typeof r.latitude==="number"&&typeof r.longitude==="number"?{latitude:r.latitude,longitude:r.longitude}:null}
function place(value:unknown){if(!value||typeof value!=="object"||Array.isArray(value))return"Location";const r=value as Record<string,unknown>;return typeof r.label==="string"?r.label:"Location"}

export default function GoCourier(){
 const{width}=useWindowDimensions();const tablet=width>=720;
 const[signedIn,setSignedIn]=useState<boolean|null>(null);const[tab,setTab]=useState<Tab>("jobs");const[online,setOnline]=useState(false);const[point,setPoint]=useState<Point|null>(null);
 const[foodOffers,setFoodOffers]=useState<FoodDelivery[]>([]);const[foodJobs,setFoodJobs]=useState<FoodDelivery[]>([]);const[parcelOffers,setParcelOffers]=useState<Parcel[]>([]);const[parcelJobs,setParcelJobs]=useState<Parcel[]>([]);
 const[foodHistory,setFoodHistory]=useState<History["summary"]>({deliveredCount:0,todayDeliveredCount:0,todayPayoutMinor:0,recentPayoutMinor:0});const[parcelHistory,setParcelHistory]=useState<History["summary"]>({deliveredCount:0,todayDeliveredCount:0,todayPayoutMinor:0,recentPayoutMinor:0});
 const[rules,setRules]=useState<FoodOffers["rules"]|null>(null);const[busy,setBusy]=useState("");const[error,setError]=useState("");const[refreshing,setRefreshing]=useState(false);const[code,setCode]=useState("");const[foodPin,setFoodPin]=useState("");
 const activeFood=foodJobs[0]??null;const activeParcel=parcelJobs[0]??null;const active=activeFood||activeParcel;
 const today=foodHistory.todayPayoutMinor+parcelHistory.todayPayoutMinor;const recent=foodHistory.recentPayoutMinor+parcelHistory.recentPayoutMinor;

 const locate=useCallback(async()=>{let permission=await Location.getForegroundPermissionsAsync();if(permission.status!=="granted")permission=await Location.requestForegroundPermissionsAsync();if(permission.status!=="granted")throw new Error("Location permission is required while GO is online.");const current=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});const next={latitude:current.coords.latitude,longitude:current.coords.longitude};setPoint(next);return next},[]);

 const load=useCallback(async(optionalPoint?:Point)=>{try{const auth=await isSignedIn();setSignedIn(auth);if(!auth)return;const p=optionalPoint??point;const[food,parcel,fh,ph]=await Promise.all([goApi.get<{deliveries:FoodDelivery[]}>("/v1/go/food/deliveries",{cache:"no-store"}),goApi.get<{deliveries:Parcel[]}>("/v1/logistics/courier/deliveries",{cache:"no-store"}),goApi.get<History>("/v1/go/food/history",{cache:"no-store"}),goApi.get<History>("/v1/logistics/courier/history",{cache:"no-store"})]);setFoodJobs(food.deliveries);setParcelJobs(parcel.deliveries);setFoodHistory(fh.summary);setParcelHistory(ph.summary);
 if(online&&p&&!food.deliveries.length){const available=await goApi.get<FoodOffers>("/v1/go/food/offers",{query:{latitude:p.latitude,longitude:p.longitude},cache:"no-store"});setFoodOffers(available.offers);setRules(available.rules)}else setFoodOffers([]);
 if(online&&p&&!parcel.deliveries.length){const available=await goApi.get<{offers:Parcel[]}>("/v1/logistics/courier/offers",{query:{latitude:p.latitude,longitude:p.longitude},cache:"no-store"});setParcelOffers(available.offers)}else setParcelOffers([]);setError("")}catch(e){if(e instanceof ApiError&&e.status===401)setSignedIn(false);else setError(e instanceof Error?e.message:"Could not refresh GO")}},[online,point]);

 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!signedIn||!online)return;let cancelled=false;const tick=async()=>{try{const p=await locate();if(cancelled)return;if(activeFood)await goApi.post(`/v1/go/food/deliveries/${activeFood.id}/location`,p).catch(()=>undefined);if(activeParcel)await goApi.post(`/v1/logistics/courier/bookings/${activeParcel.id}/location`,p).catch(()=>undefined);if(!cancelled)await load(p)}catch(e){if(!cancelled)setError(e instanceof Error?e.message:"Could not update live location")}};const timer=setInterval(()=>void tick(),15000);return()=>{cancelled=true;clearInterval(timer)}},[signedIn,online,activeFood?.id,activeParcel?.id,locate,load]);

 async function toggleOnline(){setBusy("online");try{if(online){setOnline(false);setFoodOffers([]);setParcelOffers([])}else{const p=await locate();setOnline(true);await load(p)}}catch(e){setError(e instanceof Error?e.message:"Could not change online status")}finally{setBusy("")}}
 async function refresh(){setRefreshing(true);try{const p=online?await locate():point;await load(p??undefined)}catch(e){setError(e instanceof Error?e.message:"Could not refresh")}finally{setRefreshing(false)}}
 async function acceptFood(job:FoodDelivery){if(!point)return;setBusy(`f:${job.id}`);try{await goApi.post(`/v1/go/food/offers/${job.id}/accept`,point);await load(point)}catch(e){setError(e instanceof Error?e.message:"Could not accept Food delivery")}finally{setBusy("")}}
 async function acceptParcel(job:Parcel){setBusy(`p:${job.id}`);try{await goApi.post(`/v1/logistics/courier/offers/${job.id}/accept`,{});await load(point??undefined)}catch(e){setError(e instanceof Error?e.message:"Could not accept parcel")}finally{setBusy("")}}
 async function foodStatus(next:"PICKED_UP"|"ON_THE_WAY"|"DELIVERED"){if(!activeFood)return;setBusy(next);try{const p=await locate();await goApi.patch(`/v1/go/food/deliveries/${activeFood.id}/status`,{status:next,...p});await load(p)}catch(e){setError(e instanceof Error?e.message:"Could not update Food delivery")}finally{setBusy("")}}
 async function verifyFoodPin(){if(!activeFood||foodPin.length!==4)return;setBusy("food-pin");try{await goApi.post(`/v1/go/food/deliveries/${activeFood.id}/verify-pin`,{pin:foodPin});setFoodPin("");await load()}catch(e){setError(e instanceof Error?e.message:"Could not verify PIN")}finally{setBusy("")}}
 async function parcelStatus(next:"PICKED_UP"|"IN_TRANSIT"|"DELIVERED"|"FAILED"|"RETURNING"|"RETURNED"){if(!activeParcel)return;setBusy(next);try{await goApi.patch(`/v1/logistics/bookings/${activeParcel.id}/status`,{status:next,verificationCode:["PICKED_UP","DELIVERED"].includes(next)?code:undefined,reason:next==="FAILED"?"Courier delivery attempt failed":undefined});setCode("");await load(point??undefined)}catch(e){setError(e instanceof Error?e.message:"Could not update parcel")}finally{setBusy("")}}
 async function navigate(target:Point|null){if(target)await Linking.openURL(`https://www.google.com/maps/search/?api=1&query=${target.latitude},${target.longitude}`)}
 async function signIn(){setBusy("signin");try{const result=await signInWithBazId("/");if(result.ok){setSignedIn(true);await load()}}catch(e){setError(e instanceof Error?e.message:"Could not sign in")}finally{setBusy("")}}
 async function signOut(){await signOutNative();setSignedIn(false);setOnline(false);setFoodJobs([]);setParcelJobs([]);setFoodOffers([]);setParcelOffers([])}

 if(signedIn===null)return <SafeAreaView style={s.page}><View style={s.center}><ActivityIndicator size="large" color="#78F65B"/></View></SafeAreaView>;
 if(!signedIn)return <SafeAreaView style={s.page}><StatusBar style="light"/><View style={s.auth}><Text style={s.brand}>GO</Text><Text style={s.hero}>One courier identity.{"\n"}Every Bazaara delivery.</Text><Text style={s.copy}>Food and advance-funded parcels share one dispatch cockpit, earnings rail and BazID.</Text>{error?<Text style={s.error}>{error}</Text>:null}<Pressable style={s.primary} disabled={busy==="signin"} onPress={()=>void signIn()}><Text style={s.primaryText}>{busy==="signin"?"Connecting…":"Continue with BazID"}</Text></Pressable></View></SafeAreaView>;

 return <SafeAreaView style={s.page}><StatusBar style="light"/><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void refresh()} tintColor="#78F65B"/>} contentContainerStyle={[s.wrap,tablet&&s.wrapTablet]}>
  <View style={s.header}><View><Text style={s.brand}>GO</Text><Text style={s.heading}>{tab==="jobs"?"Delivery cockpit":tab==="earnings"?"Earnings":"Courier profile"}</Text></View><Pressable style={[s.livePill,online&&s.livePillOn]} onPress={()=>void toggleOnline()} disabled={!!busy}><Text style={[s.liveText,online&&s.liveTextOn]}>{busy==="online"?"…":online?"● ONLINE":"OFFLINE"}</Text></Pressable></View>
  <View style={s.tabs}>{(["jobs","earnings","profile"] as Tab[]).map(key=><Pressable key={key} style={[s.tab,tab===key&&s.tabActive]} onPress={()=>setTab(key)}><Text style={[s.tabText,tab===key&&s.tabTextActive]}>{key.toUpperCase()}</Text></Pressable>)}</View>
  {error?<Text style={s.error}>{error}</Text>:null}

  {tab==="jobs"?<><View style={s.metrics}><Metric label="ACTIVE" value={String((activeFood?1:0)+(activeParcel?1:0))}/><Metric label="OFFERS" value={String(foodOffers.length+parcelOffers.length)}/><Metric label="TODAY" value={money(today)}/></View>
   {activeFood?<View style={s.activeCard}><View style={s.row}><View style={s.flex}><Text style={s.kicker}>ACTIVE FOOD</Text><Text style={s.cardTitle}>{activeFood.restaurant.name}</Text><Text style={s.copy}>{activeFood.orderNumber} · {label(activeFood.status)}</Text></View><Text style={s.payout}>{money(activeFood.economics?.courierPayoutMinor??0,activeFood.currency)}</Text></View><View style={s.route}><Pressable style={s.secondary} onPress={()=>void navigate(activeFood.pickup)}><Text style={s.secondaryText}>Navigate to restaurant</Text></Pressable><Pressable style={s.secondary} onPress={()=>void navigate(activeFood.dropoff)}><Text style={s.secondaryText}>Navigate to customer</Text></Pressable></View>{activeFood.status==="READY"?<Pressable style={s.primary} onPress={()=>void foodStatus("PICKED_UP")}><Text style={s.primaryText}>Confirm pickup</Text></Pressable>:null}{activeFood.status==="PICKED_UP"?<Pressable style={s.primary} onPress={()=>void foodStatus("ON_THE_WAY")}><Text style={s.primaryText}>Start delivery</Text></Pressable>:null}{activeFood.status==="ON_THE_WAY"?<><View style={s.codeRow}><TextInput style={s.codeInput} placeholder="4-digit PIN" placeholderTextColor="#68766E" keyboardType="number-pad" value={foodPin} onChangeText={v=>setFoodPin(v.replace(/\D/g,"").slice(0,4))}/><Pressable style={s.secondary} onPress={()=>void verifyFoodPin()}><Text style={s.secondaryText}>{activeFood.deliveryPinVerified?"Verified":"Verify"}</Text></Pressable></View><Pressable disabled={!activeFood.deliveryPinVerified} style={[s.primary,!activeFood.deliveryPinVerified&&s.disabled]} onPress={()=>void foodStatus("DELIVERED")}><Text style={s.primaryText}>Complete delivery</Text></Pressable></>:null}</View>:null}
   {activeParcel?<View style={s.activeCard}><View style={s.row}><View style={s.flex}><Text style={s.kicker}>ACTIVE PARCEL</Text><Text style={s.cardTitle}>{activeParcel.publicCode}</Text><Text style={s.copy}>{place(activeParcel.pickup)} → {place(activeParcel.dropoff)}</Text></View><Text style={s.payout}>{money(activeParcel.economics.courierPayoutMinor,activeParcel.currency)}</Text></View><View style={s.route}><Pressable style={s.secondary} onPress={()=>void navigate(pointFrom(activeParcel.pickup))}><Text style={s.secondaryText}>Pickup map</Text></Pressable><Pressable style={s.secondary} onPress={()=>void navigate(pointFrom(activeParcel.dropoff))}><Text style={s.secondaryText}>Drop-off map</Text></Pressable></View>{["ASSIGNED","IN_TRANSIT"].includes(activeParcel.status)?<View style={s.codeRow}><TextInput style={s.codeInput} placeholder={activeParcel.status==="ASSIGNED"?"6-digit pickup code":"6-digit delivery code"} placeholderTextColor="#68766E" keyboardType="number-pad" value={code} onChangeText={v=>setCode(v.replace(/\D/g,"").slice(0,6))}/><Text style={s.muted}>Customer supplies code</Text></View>:null}{activeParcel.status==="ASSIGNED"?<Pressable disabled={code.length!==6} style={[s.primary,code.length!==6&&s.disabled]} onPress={()=>void parcelStatus("PICKED_UP")}><Text style={s.primaryText}>Verify pickup</Text></Pressable>:null}{activeParcel.status==="PICKED_UP"?<Pressable style={s.primary} onPress={()=>void parcelStatus("IN_TRANSIT")}><Text style={s.primaryText}>Start transit</Text></Pressable>:null}{activeParcel.status==="IN_TRANSIT"?<><Pressable disabled={code.length!==6} style={[s.primary,code.length!==6&&s.disabled]} onPress={()=>void parcelStatus("DELIVERED")}><Text style={s.primaryText}>Verify delivery</Text></Pressable><Pressable style={s.danger} onPress={()=>void parcelStatus("FAILED")}><Text style={s.dangerText}>Failed attempt</Text></Pressable></>:null}{activeParcel.status==="FAILED"?<Pressable style={s.secondary} onPress={()=>void parcelStatus("RETURNING")}><Text style={s.secondaryText}>Return to sender</Text></Pressable>:null}{activeParcel.status==="RETURNING"?<Pressable style={s.primary} onPress={()=>void parcelStatus("RETURNED")}><Text style={s.primaryText}>Confirm returned</Text></Pressable>:null}</View>:null}
   {!active?<><View style={s.sectionHead}><Text style={s.sectionTitle}>Nearby offers</Text><Text style={s.muted}>{online?`${foodOffers.length+parcelOffers.length} available`:"Go online"}</Text></View>{foodOffers.map(job=><Offer key={`f-${job.id}`} title={job.restaurant.name} detail={`Food · ${distance(job.pickupDistanceMeters)} to pickup`} payout={money(job.economics?.courierPayoutMinor??0,job.currency)} busy={busy===`f:${job.id}`} onAccept={()=>void acceptFood(job)}/>)}{parcelOffers.map(job=><Offer key={`p-${job.id}`} title={job.publicCode} detail={`Parcel · ${job.serviceLevel} · ${distance(job.pickupDistanceMeters)} to pickup`} payout={money(job.economics.courierPayoutMinor,job.currency)} busy={busy===`p:${job.id}`} onAccept={()=>void acceptParcel(job)}/>) }{online&&!foodOffers.length&&!parcelOffers.length?<View style={s.empty}><Text style={s.cardTitle}>No eligible jobs right now</Text><Text style={s.copy}>Go filters distant pickup jobs and refreshes while you remain online.</Text></View>:null}</>:null}
  </>:null}

  {tab==="earnings"?<><View style={s.heroCard}><Text style={s.kicker}>GO EARNINGS</Text><Text style={s.heroNumber}>{money(today)}</Text><Text style={s.copy}>Today across Food and Parcel delivery</Text></View><View style={[s.metrics,tablet&&s.metricsTablet]}><Metric label="RECENT" value={money(recent)}/><Metric label="FOOD" value={money(foodHistory.recentPayoutMinor)}/><Metric label="PARCELS" value={money(parcelHistory.recentPayoutMinor)}/></View><View style={s.empty}><Text style={s.cardTitle}>Wallet settlement</Text><Text style={s.copy}>Verified parcel completion releases funded escrow to your Pay wallet after the Go commission. Food payouts use the existing Go economics rail.</Text></View></>:null}

  {tab==="profile"?<><View style={s.profile}><Text style={s.kicker}>COURIER STATUS</Text><Text style={s.cardTitle}>{online?"Online and discoverable":"Offline"}</Text><Text style={s.copy}>{point?`Current location ${point.latitude.toFixed(4)}, ${point.longitude.toFixed(4)}`:"Location is hidden while offline."}</Text><Text style={s.muted}>Food pickup radius: {rules?Math.round(rules.maxPickupDistanceMeters/1000):"—"} km</Text><Pressable style={s.secondary} onPress={()=>void signOut()}><Text style={s.secondaryText}>Sign out</Text></Pressable></View></>:null}
 </ScrollView></SafeAreaView>
}

function Offer({title,detail,payout,busy,onAccept}:{title:string;detail:string;payout:string;busy:boolean;onAccept:()=>void}){return <View style={s.offer}><View style={s.row}><View style={s.flex}><Text style={s.cardTitle}>{title}</Text><Text style={s.copy}>{detail}</Text></View><Text style={s.payout}>{payout}</Text></View><Pressable style={s.primary} disabled={busy} onPress={onAccept}><Text style={s.primaryText}>{busy?"Accepting…":"Accept job"}</Text></Pressable></View>}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.metricLabel}>{label}</Text><Text style={s.metricValue}>{value}</Text></View>}

const s=StyleSheet.create({
 page:{flex:1,backgroundColor:"#050A08"},center:{flex:1,alignItems:"center",justifyContent:"center"},auth:{flex:1,justifyContent:"center",padding:27,gap:17},wrap:{padding:18,paddingBottom:48,gap:13},wrapTablet:{maxWidth:1000,width:"100%",alignSelf:"center",padding:28},header:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",gap:12},brand:{color:"#FF7A14",fontWeight:"900",letterSpacing:1.7,fontSize:11},hero:{color:"#fff",fontSize:38,lineHeight:40,fontWeight:"900",letterSpacing:-1.4},heading:{color:"#fff",fontSize:29,fontWeight:"900",letterSpacing:-1},copy:{color:"#A1AEA6",fontSize:13,lineHeight:19},error:{color:"#FF9B9B",backgroundColor:"#261312",padding:11,borderRadius:12},tabs:{flexDirection:"row",gap:6},tab:{flex:1,minHeight:40,borderWidth:1,borderColor:"#22362B",borderRadius:12,alignItems:"center",justifyContent:"center"},tabActive:{backgroundColor:"#13251A",borderColor:"#497B5B"},tabText:{color:"#69776F",fontSize:10,fontWeight:"900"},tabTextActive:{color:"#D8FFE1"},
 livePill:{borderWidth:1,borderColor:"#34443D",paddingHorizontal:13,paddingVertical:9,borderRadius:999},livePillOn:{backgroundColor:"#78F65B",borderColor:"#78F65B"},liveText:{color:"#A7B5AE",fontWeight:"900",fontSize:10},liveTextOn:{color:"#071007"},metrics:{flexDirection:"row",gap:7},metricsTablet:{maxWidth:650},metric:{flex:1,backgroundColor:"#09110D",borderWidth:1,borderColor:"#1B2B22",borderRadius:13,padding:10},metricLabel:{color:"#647169",fontSize:9,fontWeight:"800"},metricValue:{color:"#fff",fontWeight:"900",fontSize:12,marginTop:4},
 activeCard:{backgroundColor:"#0C1812",borderWidth:1,borderColor:"#2A5438",borderRadius:21,padding:17,gap:13},offer:{backgroundColor:"#09110D",borderWidth:1,borderColor:"#1B2B22",borderRadius:18,padding:15,gap:12},row:{flexDirection:"row",justifyContent:"space-between",gap:10,alignItems:"flex-start"},flex:{flex:1},kicker:{color:"#FF7A14",fontSize:9,fontWeight:"900",letterSpacing:1.2},cardTitle:{color:"#fff",fontSize:18,fontWeight:"900",marginTop:3},payout:{color:"#FF9A4A",fontSize:19,fontWeight:"900"},route:{flexDirection:"row",gap:7},primary:{minHeight:49,borderRadius:14,backgroundColor:"#78F65B",alignItems:"center",justifyContent:"center",paddingHorizontal:14},primaryText:{color:"#071007",fontWeight:"900",fontSize:14},secondary:{flex:1,minHeight:46,borderRadius:13,borderWidth:1,borderColor:"#34513F",alignItems:"center",justifyContent:"center",paddingHorizontal:12},secondaryText:{color:"#D9FFE0",fontWeight:"900"},danger:{minHeight:46,borderRadius:13,borderWidth:1,borderColor:"#623231",alignItems:"center",justifyContent:"center"},dangerText:{color:"#FF9999",fontWeight:"900"},disabled:{opacity:.4},codeRow:{flexDirection:"row",alignItems:"center",gap:8},codeInput:{flex:1,minHeight:48,borderWidth:1,borderColor:"#34513F",borderRadius:13,color:"#fff",paddingHorizontal:13,fontSize:16,fontWeight:"900",letterSpacing:2},muted:{color:"#647169",fontSize:11,lineHeight:16},sectionHead:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginTop:5},sectionTitle:{color:"#fff",fontSize:19,fontWeight:"900"},empty:{padding:20,borderRadius:17,borderWidth:1,borderColor:"#1B2B22",gap:5},heroCard:{padding:22,borderRadius:23,borderWidth:1,borderColor:"#2A5438",backgroundColor:"#0C1812",gap:6},heroNumber:{color:"#fff",fontSize:46,fontWeight:"900",letterSpacing:-1.8},profile:{padding:20,borderRadius:20,borderWidth:1,borderColor:"#1B2B22",backgroundColor:"#09110D",gap:10},
});
