"use client";
import {useCallback,useEffect,useMemo,useState,type FormEvent} from "react";
import {API_BASE,api,errorText,uploadMedia} from "@bazaara/social-ui";
import {Dock,Failure,Notice,saveBlob,type PhaseSession} from "./Dock";
type Person={id:string;displayName:string|null;socialProfile?:{handle:string}|null};
type Chat={id:string;participants:Person[];unread:number;latestMessage:{body:string|null}|null};
type ReplyPreview={id:string;senderUserId:string;body:string|null;deletedAt:string|null;attachmentName:string|null};
type Msg={id:string;senderUserId:string;body:string|null;createdAt:string;deletedAt:string|null;replyToMessageId?:string|null;replyTo?:ReplyPreview|null;attachment?:{name:string;url:string}|null};
export default function Tools(){return <Dock app="BChat">{session=><Panel session={session}/>}</Dock>}
function Panel({session}:{session:PhaseSession}){
 const [conversations,setConversations]=useState<Chat[]>([]),[selected,setSelected]=useState(""),[messages,setMessages]=useState<Msg[]>([]);
 const [filter,setFilter]=useState(""),[draft,setDraft]=useState(""),[file,setFile]=useState<File|null>(null),[replying,setReplying]=useState<Msg|null>(null),[error,setError]=useState(""),[info,setInfo]=useState(""),[busy,setBusy]=useState(false),[live,setLive]=useState(false);
 const loadList=useCallback(async()=>{try{const data=await api.get<{conversations:Chat[]}>("/v1/bazchat/conversations",{maxRetries:0});setConversations(data.conversations)}catch(e){setError(errorText(e))}},[]);
 const loadMessages=useCallback(async(id:string)=>{if(!id)return;try{const data=await api.get<{messages:Msg[]}>(`/v1/bazchat/conversations/${encodeURIComponent(id)}/messages`,{query:{limit:50},maxRetries:0});setMessages(data.messages);await api.post(`/v1/bazchat/conversations/${encodeURIComponent(id)}/read`,{}).catch(()=>undefined)}catch(e){setError(errorText(e))}},[]);
 useEffect(()=>{void loadList();const i=window.setInterval(()=>void loadList(),15000);return()=>window.clearInterval(i)},[loadList]);
 useEffect(()=>{setMessages([]);setFilter("");setReplying(null);if(!selected)return;void loadMessages(selected);const i=window.setInterval(()=>void loadMessages(selected),12000);return()=>window.clearInterval(i)},[selected,loadMessages]);
 useEffect(()=>{let es:EventSource|null=null;try{es=new EventSource(`${API_BASE}/v1/bazchat/events`,{withCredentials:true});es.onopen=()=>setLive(true);es.onerror=()=>setLive(false);es.addEventListener("changed",event=>{try{const payload=JSON.parse((event as MessageEvent).data) as {conversationId?:string};void loadList();if(payload.conversationId&&payload.conversationId===selected)void loadMessages(selected);}catch{}});}catch{setLive(false)}return()=>{es?.close();setLive(false)}},[selected,loadList,loadMessages]);
 const active=conversations.find(c=>c.id===selected);const name=active?.participants.find(p=>p.id!==session.user?.id)?.displayName??"Conversation";
 const visible=useMemo(()=>messages.filter(m=>(m.body??m.attachment?.name??"").toLocaleLowerCase().includes(filter.toLocaleLowerCase())),[messages,filter]);
 async function send(e:FormEvent){e.preventDefault();if(!selected||(!draft.trim()&&!file)||busy)return;setBusy(true);setError("");try{let assetId:string|undefined;let attachmentName:string|undefined;if(file){if(file.size>25*1024*1024)throw new Error("Attachments must be at most 25 MB.");const uploaded=await uploadMedia(file,"PRIVATE");assetId=uploaded.id;attachmentName=file.name;}await api.post(`/v1/bazchat/conversations/${encodeURIComponent(selected)}/messages`,{body:draft.trim(),clientNonce:crypto.randomUUID(),...(assetId?{assetId,attachmentName}:{}),...(replying?{replyToMessageId:replying.id}:{})});setDraft("");setFile(null);setReplying(null);await Promise.all([loadMessages(selected),loadList()]);setInfo("Message sent.")}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function remove(m:Msg){if(!selected||!confirm("Delete this message for everyone in this conversation?"))return;setBusy(true);try{await api.delete(`/v1/bazchat/conversations/${encodeURIComponent(selected)}/messages/${encodeURIComponent(m.id)}`);await loadMessages(selected);setInfo("Message deleted.")}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 function exportHistory(){if(!selected)return;const text=`BChat — ${name}\nExport: ${new Date().toISOString()}\nOnly the latest ${messages.length} retrieved messages are included.\n\n`+messages.map(m=>`${new Date(m.createdAt).toLocaleString()} | ${m.senderUserId===session.user?.id?"You":name}: ${m.deletedAt?"[deleted]":m.body??m.attachment?.name??"[attachment]"}${m.replyTo?` [reply to ${m.replyTo.id.slice(0,8)}]`:""}`).join("\n");saveBlob(`bchat-conversation-${selected.slice(0,8)}.txt`,text)}
 return <><span className="tag">WORKING / EXISTING API</span><h2>Conversation operations</h2><p>Realtime refresh, recent-message search, replies, sending, deletion, calls and local export. This release does not claim end-to-end encrypted messaging.</p><div className="actions"><span className="chip">{live?"Live updates connected":"Polling fallback active"}</span>{selected&&<a className="p2-linkbutton" href="/calls">Open calls</a>}</div><Failure message={error} clear={()=>setError("")}/><Notice message={info}/>
 <div className="grid2"><div className="card"><div className="row"><h3>Inbox</h3><button type="button" onClick={()=>void loadList()}>Refresh</button></div><div className="list">{conversations.map(c=>{const peer=c.participants.find(p=>p.id!==session.user?.id);return <button className={`item ${selected===c.id?"primary":""}`} type="button" key={c.id} onClick={()=>setSelected(c.id)} aria-pressed={selected===c.id}>{peer?.displayName??"Member"} {c.unread>0&&<span className="chip">{c.unread} new</span>}</button>})}{!conversations.length&&<p>Start a conversation from BChat's main inbox.</p>}</div></div><div className="card"><h3>{active?name:"Open a conversation"}</h3>{active?<><label>Find in loaded messages<input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Filter recent messages"/></label><div className="actions"><button onClick={exportHistory} type="button">Export loaded messages</button><a className="p2-linkbutton" href="/calls">Voice / video call</a></div></>:<p>Select a conversation to inspect it.</p>}</div></div>
 {active&&<><div className="list" aria-live="polite">{visible.map(m=><article className="card" key={m.id}>{m.replyTo&&<div className="p2-replypreview"><strong>Replying to {m.replyTo.senderUserId===session.user?.id?"you":name}</strong><span>{m.replyTo.deletedAt?"Message removed":m.replyTo.body??m.replyTo.attachmentName??"Attachment"}</span></div>}<div className="row"><strong>{m.senderUserId===session.user?.id?"You":name}</strong><small>{new Date(m.createdAt).toLocaleString()}</small></div><div className="textbox">{m.deletedAt?"Message removed":m.body??"Attachment"}</div>{m.attachment&&<a className="p2-linkbutton" href={m.attachment.url} target="_blank" rel="noreferrer">{m.attachment.name}</a>}<div className="actions">{!m.deletedAt&&<button type="button" onClick={()=>setReplying(m)}>Reply</button>}{m.senderUserId===session.user?.id&&!m.deletedAt&&<button type="button" disabled={busy} onClick={()=>void remove(m)}>Delete my message</button>}</div></article>)}{!visible.length&&<p>{filter?"No matching message in the loaded 50.":"No messages yet."}</p>}</div><form onSubmit={e=>void send(e)}>{replying&&<div className="p2-replybar"><span>Replying to {replying.senderUserId===session.user?.id?"yourself":name}: {(replying.body??"Attachment").slice(0,120)}</span><button type="button" onClick={()=>setReplying(null)}>Cancel reply</button></div>}<label>Message<textarea rows={3} maxLength={4000} value={draft} onChange={e=>setDraft(e.target.value)}/></label><label className="p2-filepick">Attachment up to 25 MB<input type="file" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>{file&&<div className="p2-attachmentbar"><span>{file.name} · {Math.ceil(file.size/1024)} KB</span><button type="button" onClick={()=>setFile(null)}>Remove</button></div>}<button className="primary" disabled={busy||(!draft.trim()&&!file)}>Send message</button></form></>}
 </>
}
