'use client';
import {useCallback,useEffect,useRef,useState} from 'react';

import {Dialog,Notice,ToolRow,csv,download,errorText} from '../../../packages/flagship-ui/src/core';
type Folder={id:string,name:string,parentId:string|null,createdAt:string};
type StoredFile={id:string,name:string,size:number,folderId:string|null,createdAt:string};
type Listing={folders:Folder[],files:StoredFile[],usage:number,quota:number,maxUpload:number};
const initial:Listing={folders:[],files:[],usage:0,quota:104857600,maxUpload:10485760};
const size=(n:number)=>n>=1048576?`${(n/1048576).toFixed(1)} MB`:n>=1024?`${(n/1024).toFixed(1)} KB`:`${n} B`;
async function responseData(res:Response){try{return await res.json();}catch{return {message:'Unexpected server response.'}}}
export default function BoxApp(){
 const [data,setData]=useState<Listing>(initial),[loading,setLoading]=useState(true),[authorized,setAuthorized]=useState(true),[message,setMessage]=useState(''),[folder,setFolder]=useState<string|null>(null),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[showNew,setShowNew]=useState(false),[folderName,setFolderName]=useState('');
 const [sort,setSort]=useState('name'),[kind,setKind]=useState('all'),[selected,setSelected]=useState<string[]>([]),[progress,setProgress]=useState(''),[preview,setPreview]=useState<{name:string;kind:string;url?:string;text?:string}|null>(null);
 const controller=useRef<AbortController|null>(null),working=useRef(false),previewController=useRef<AbortController|null>(null);
 const uploadRef=useRef<HTMLInputElement>(null), mounted=useRef(true);
 const refresh=useCallback(async()=>{
  try{const r=await fetch('/api/box',{cache:'no-store'});const json=await responseData(r);if(!mounted.current)return;
   if(r.status===401){setAuthorized(false);setMessage('Sign in to your existing BazID account to use Box.');return;}
   if(!r.ok)throw new Error(json.message||'Unable to load Box.');
   setAuthorized(true);setData(json);setMessage('');
  }catch(e){if(mounted.current)setMessage(e instanceof Error?e.message:'Unable to connect to Box.');}
  finally{if(mounted.current)setLoading(false);}
 },[]);
 useEffect(()=>{mounted.current=true;void refresh();return()=>{mounted.current=false;controller.current?.abort();previewController.current?.abort();}},[refresh]);
 const mutate=async(path:string,init:RequestInit)=>{
  setBusy(true);setMessage('');try{const r=await fetch(path,init),json=await responseData(r);if(!r.ok)throw new Error(json.message||'Request failed.');await refresh();return true;}
  catch(e){setMessage(e instanceof Error?e.message:'Request failed.');return false;}
  finally{setBusy(false);}
 };
 const makeFolder=async()=>{const name=folderName.trim();if(!name)return;const created=await mutate('/api/box',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,parentId:folder})});if(created){setFolderName('');setShowNew(false);}};
 const upload=async(list:FileList|File[]|null)=>{const files=Array.from(list||[]);if(!files.length||working.current||!authorized)return;if(files.length>50){setMessage('Upload up to 50 files per batch.');return;}if(files.some(f=>f.size>data.maxUpload)){setMessage('Every file must be under '+size(data.maxUpload)+'.');return;}if(files.reduce((n,f)=>n+f.size,0)>data.quota-data.usage){setMessage('This batch exceeds your available storage.');return;}working.current=true;setBusy(true);setMessage('');controller.current=new AbortController();const destination=folder;let completed=0;try{for(const file of files){setProgress('Uploading '+(completed+1)+' of '+files.length+': '+file.name);const body=new FormData();body.set('file',file);if(destination)body.set('folderId',destination);const response=await fetch('/api/box/upload',{method:'POST',body,signal:controller.current.signal}),result=await responseData(response);if(!response.ok)throw Error(result.message||'Upload failed.');completed++;}await refresh();setMessage(completed+' files uploaded.');}catch(e){await refresh();setMessage((e instanceof DOMException&&e.name==='AbortError'?'Upload cancelled.':errorText(e))+' '+completed+' files completed; remaining files were not uploaded.');}finally{controller.current=null;working.current=false;setBusy(false);setProgress('');if(uploadRef.current)uploadRef.current.value='';}};
 const fileKind=(name:string)=>/\.(png|jpe?g|webp|gif)$/i.test(name)?'image':/\.(mp3|m4a|wav|ogg|opus)$/i.test(name)?'audio':/\.(mp4|webm|mov)$/i.test(name)?'video':/\.(txt|md|csv|json|log)$/i.test(name)?'text':'other';
 useEffect(()=>()=>{if(preview?.url)URL.revokeObjectURL(preview.url);},[preview?.url]);
 const showPreview=async(file:StoredFile)=>{previewController.current?.abort();const request=new AbortController();previewController.current=request;const kind=fileKind(file.name);if(kind==='other'){setMessage('Download this file to view it in its associated application.');return;}if(kind==='text'&&file.size>1048576){setMessage('Text preview supports files up to 1 MB.');return;}setPreview({name:file.name,kind:'loading'});try{const response=await fetch('/api/box/file/'+file.id,{signal:request.signal});if(!response.ok)throw Error('Unable to load file preview.');const blob=await response.blob();if(request.signal.aborted)return;if(kind==='text')setPreview({name:file.name,kind,text:await blob.text()});else setPreview({name:file.name,kind,url:URL.createObjectURL(blob)});}catch(e){if(!request.signal.aborted)setMessage(errorText(e));setPreview(null);}};
 const deleteSelected=async()=>{const files=data.files.filter(f=>selected.includes(f.id));if(!files.length||working.current||!confirm('Permanently delete '+files.length+' selected files?'))return;working.current=true;setBusy(true);let completed=0,failure='';try{for(const file of files){const response=await fetch('/api/box/file/'+file.id,{method:'DELETE'}),body=await responseData(response);if(!response.ok)throw Error(body.message||'Delete failed.');completed++;}setSelected([]);}catch(e){failure=errorText(e)+' '+completed+' files deleted.';}finally{working.current=false;setBusy(false);await refresh();if(failure)setMessage(failure);else setMessage(completed+' files deleted.');}};

 const removeFile=async(file:StoredFile)=>{if(!window.confirm(`Delete “${file.name}” permanently?`))return;await mutate(`/api/box/file/${file.id}`,{method:'DELETE'});};
 const removeFolder=async(item:Folder)=>{if(!window.confirm(`Delete empty folder “${item.name}”?`))return;await mutate(`/api/box/folder/${item.id}`,{method:'DELETE'});};
 const trail:Folder[]=[];let active=folder;for(let i=0;i<10&&active;i++){const item=data.folders.find(f=>f.id===active);if(!item)break;trail.unshift(item);active=item.parentId;}
 const matching=(name:string)=>name.toLowerCase().includes(query.trim().toLowerCase());
 const folders=data.folders.filter(f=>f.parentId===folder&&matching(f.name)).sort((a,b)=>a.name.localeCompare(b.name));const files=data.files.filter(f=>f.folderId===folder&&matching(f.name)&&(kind==='all'||fileKind(f.name)===kind)).sort((a,b)=>sort==='size'?b.size-a.size:sort==='newest'?b.createdAt.localeCompare(a.createdAt):a.name.localeCompare(b.name,undefined,{numeric:true}));
 return <div className="layout">
   <aside className="sidebar" aria-label="Main navigation">
    <a className="brand" href="http://localhost:3021" aria-label="BAZAARA Workspace"><span className="brand-mark">◇</span><span>BAZAARA <b>Box</b><small>ECOSYSTEM 03</small></span></a>
    <div className="navigation"><a href="http://localhost:3021">◈ <span>Workspace</span></a><a className="active" href="http://localhost:3022">▣ <span>My Box</span></a><a href="http://localhost:3020">⌕ <span>Search</span></a></div>
    <div className="side-bottom"><span className="minor">STORAGE USED</span><div className="storage"><div style={{width:`${Math.min(100,data.usage/data.quota*100)}%`}}/></div><b>{size(data.usage)} <span>of {size(data.quota)}</span></b><p>Private local development storage. No public sharing yet.</p></div>
   </aside>
   <main>
    <header className="topbar"><div className="mini-logo">BAZAARA <b>Box</b></div><div className="top-right"><span className="local-tag">DEVELOPMENT ALPHA</span><a href="http://localhost:3004/account">My account ↗</a></div></header>
    <div className="content"><nav className="mobile-nav" aria-label="Mobile applications"><a href="http://localhost:3021">Workspace</a><a aria-current="page" href="http://localhost:3022">My Box</a><a href="http://localhost:3020">Search</a></nav><div className="heading"><div><span className="eyebrow">YOUR DIGITAL SPACE</span><h1>Everything in its place.</h1><p>Keep your important files organized in one private workspace.</p></div><div className="actions"><button type="button" className="secondary" onClick={()=>setShowNew(true)} disabled={busy||!authorized}>＋ New folder</button><button className="primary" type="button" onClick={()=>uploadRef.current?.click()} disabled={busy||!authorized}>↑ Upload files</button><input ref={uploadRef} type="file" multiple className="visually-hidden" onChange={e=>void upload(e.target.files)} aria-label="Upload file"/></div></div>
    {showNew&&<Dialog title="Create a folder" close={()=>setShowNew(false)}><form onSubmit={e=>{e.preventDefault();void makeFolder();}}><label htmlFor="folder-name">Folder name</label><input id="folder-name" autoFocus autoComplete="off" maxLength={128} required value={folderName} onChange={e=>setFolderName(e.target.value)}/><div className="bf-actions"><button type="button" onClick={()=>{setShowNew(false);setFolderName('');}}>Cancel</button><button className="primary" disabled={busy||!folderName.trim()}>Create folder</button></div><Notice error>{message}</Notice></form></Dialog>}
    {preview&&<Dialog title={preview.name} close={()=>{previewController.current?.abort();setPreview(null);}}>{preview.kind==='loading'?<p>Loading preview…</p>:preview.kind==='image'?<img src={preview.url} alt={preview.name} style={{maxWidth:'100%',maxHeight:'70vh',objectFit:'contain'}}/>:preview.kind==='audio'?<audio src={preview.url} controls/>:preview.kind==='video'?<video src={preview.url} controls style={{maxWidth:'100%',maxHeight:'65vh'}}/>:<pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{preview.text}</pre>}</Dialog>}

    <section className="summary" aria-label="Storage summary"><div className="summary-icon">◈</div><div><strong>Your private development storage</strong><p>Access through BazID. Files are private to your signed-in account.</p></div><span className="summary-right">{data.files.length} files · {data.folders.length} folders</span></section>
    {message&&<div className="alert" role="alert">{message} {!authorized&&<a href="http://localhost:3004">Open BazID ↗</a>}<button aria-label="Retry loading" type="button" onClick={()=>void refresh()}>Retry</button></div>}
    <div className="browser" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void upload(Array.from(e.dataTransfer.files));}}><div className="browser-header"><nav aria-label="Folder path" className="breadcrumb"><button type="button" onClick={()=>setFolder(null)}>My Box</button>{trail.map(f=><span key={f.id}> / <button type="button" onClick={()=>setFolder(f.id)}>{f.name}</button></span>)}</nav><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search this folder" aria-label="Search this folder"/></label></div>
    <div className="bf-root" style={{minHeight:0,padding:12}}><ToolRow><select aria-label="Sort files" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name</option><option value="size">Largest first</option><option value="newest">Newest first</option></select><select aria-label="File type" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All files</option>{['image','audio','video','text','other'].map(k=><option key={k}>{k}</option>)}</select><button disabled={busy} onClick={()=>setSelected(files.map(f=>f.id))}>Select visible</button><button onClick={()=>setSelected([])}>Clear selection</button><button disabled={busy||!selected.length} onClick={()=>void deleteSelected()}>Delete selected ({selected.length})</button><button onClick={()=>download('box-file-list.csv',csv([['Name','Bytes','Added','Folder'],...files.map(f=>[f.name,f.size,f.createdAt,trail.map(x=>x.name).join('/')])]),'text/csv')}>Export listing CSV</button>{progress&&<><span role="status">{progress}</span><button onClick={()=>controller.current?.abort()}>Cancel remaining uploads</button></>}<small>Drop files into this folder to upload.</small></ToolRow></div>
    <div className="column-heading"><span>NAME</span><span>SIZE</span><span>ADDED</span><span>ACTIONS</span></div>
    {loading?<div className="empty">Loading your files…</div>:!authorized?<div className="empty">Sign in with BazID to access your private files.</div>:(!folders.length&&!files.length)?<div className="empty"><div className="empty-illustration">▣</div><h2>{query?'No matching files':'Your space is ready'}</h2><p>{query?'Try a different search term.':'Upload your first file or create a folder to get organized.'}</p></div>:<div role="list" className="entries">{folders.map(f=><div className="entry" role="listitem" key={f.id}><button className="file-name" type="button" onClick={()=>{setFolder(f.id);setQuery('')}}><span className="entry-icon folder">▣</span><span>{f.name}</span></button><span>—</span><span>{new Date(f.createdAt).toLocaleDateString()}</span><button aria-label={`Delete folder ${f.name}`} className="delete" type="button" disabled={busy} onClick={()=>void removeFolder(f)}>Delete</button></div>)}{files.map(f=><div className="entry" role="listitem" key={f.id}><div className="file-name"><input type="checkbox" aria-label={'Select '+f.name} checked={selected.includes(f.id)} onChange={e=>setSelected(e.target.checked?[...selected,f.id]:selected.filter(id=>id!==f.id))}/><a href={`/api/box/file/${f.id}`} download={f.name}><span className="entry-icon">▤</span><span>{f.name}</span></a></div><span>{size(f.size)}</span><span>{new Date(f.createdAt).toLocaleDateString()}</span><div className="actions"><button onClick={()=>void showPreview(f)}>Preview</button><button aria-label={`Delete file ${f.name}`} className="delete" type="button" disabled={busy} onClick={()=>void removeFile(f)}>Delete</button></div></div>)}</div>}
    </div><p className="disclaimer">Box development · Maximum {size(data.maxUpload)} per file · {size(data.quota)} per account. Scanning, external sharing, version history and recovery are not enabled. Do not store sensitive information during development.</p>
    </div>
   </main>
 </div>;
}
