"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { createApiClient } from "@bazaara/api-client";
import type { SportsCompetitionContract, SportsFixtureContract } from "@bazaara/contracts";

const API=process.env.NEXT_PUBLIC_API_BASE_URL??"http://localhost:4000";
const api=createApiClient({baseUrl:API,credentials:"include"});
type Fixture=SportsFixtureContract&{competition:SportsCompetitionContract};
export default function SportHome(){const [sport,setSport]=useState("All");const [fixtures,setFixtures]=useState<Fixture[]>([]);const [competitions,setCompetitions]=useState<SportsCompetitionContract[]>([]);const [error,setError]=useState("");
  const load=useCallback(async()=>{try{const [f,c]=await Promise.all([api.get<{fixtures:Fixture[]}>("/v1/sport/fixtures"),api.get<{competitions:SportsCompetitionContract[]}>("/v1/sport/competitions")]);setFixtures(f.fixtures);setCompetitions(c.competitions);setError("")}catch(e){setError(e instanceof Error?e.message:"Could not load sports data")}},[]);useEffect(()=>{void load()},[load]);
  const sports=useMemo(()=>["All",...Array.from(new Set(competitions.map(c=>c.sport))).sort()],[competitions]);const shown=useMemo(()=>sport==="All"?fixtures:fixtures.filter(f=>f.competition.sport===sport),[fixtures,sport]);const live=fixtures.filter(f=>f.status.toUpperCase()==="LIVE").length;
  return <div className="shell"><header className="topbar"><a className="brand" href="/">BAZA<span>SPORT</span></a><nav className="topnav"><a href="#fixtures">Fixtures</a><a href="#policy">Policy</a></nav></header><main><section className="hero"><div className="heroCopy"><div className="eyebrow">Bazasport</div><h1>Live sport.<br/>Pure signal.</h1><p className="lede">Provider-backed competition and fixture APIs for schedules and live-state ingestion. No fabricated matches are inserted by the client.</p><div className="actions"><a className="button" href="#fixtures">Fixtures</a><a className="ghost" href="#policy">Product policy</a></div></div><aside className="heroPanel"><div className="metric"><small>Live now</small><strong>{live} events</strong></div><div className="metric"><small>Competitions</small><strong>{competitions.length}</strong></div><div className="metric"><small>Real-money betting</small><strong>Disabled</strong></div></aside></section>
  {error?<div className="notice" role="alert">{error}</div>:null}
  <section className="panel" id="fixtures"><div className="sectionHead"><div><div className="eyebrow">Score center</div><h2>Fixtures & live scores</h2></div><div className="actions">{sports.map(x=><button key={x} className={`button ${sport===x?"":"secondary"}`} onClick={()=>setSport(x)}>{x}</button>)}</div></div><div className="list">{shown.map(f=><div className="row" key={f.id}><div><span className="status">{f.status} · {f.competition.name}</span><h3 style={{marginTop:8}}>{f.homeName} <span className="soft">vs</span> {f.awayName}</h3></div><div style={{textAlign:"right"}}><strong className="amount" style={{fontSize:24}}>{f.homeScore!==null&&f.awayScore!==null?`${f.homeScore}–${f.awayScore}`:new Date(f.startsAt).toLocaleString()}</strong>{f.clock?<div className="meta">{f.clock}</div>:null}</div></div>)}{!shown.length?<div className="soft">No fixtures have been ingested for this filter.</div>:null}</div></section>
  <section className="panel" id="policy"><div className="eyebrow">Regulatory boundary</div><h2>Sports content first. Real-money wagering remains off.</h2><p className="lede">Betting endpoints are server-disabled. Activation requires licensing, age verification, KYC, geolocation, responsible-gambling controls and compliant financial segregation.</p></section><footer className="bottom"><span>Bazasport · neon green</span><span>Real-money wagering disabled</span></footer></main></div>}
