import { useCallback, useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { router } from "expo-router";
import { Button, Card, Screen, SectionTitle, colors } from "@bazaara/mobile-ui";
import { publicApi } from "@/lib/api";
import { notificationHref, registerPushNotifications } from "@/lib/notifications";

type NotificationItem = {
  id: string; category: string; title: string; body: string; resourceType: string | null; resourceId: string | null;
  mandatory: boolean; readAt: string | null; createdAt: string;
};
type Preference = { id: string; category: string; channel: "PUSH"|"EMAIL"|"SMS"|"IN_APP"; enabled: boolean };

export default function NotificationsPage() {
  const [items,setItems]=useState<NotificationItem[]>([]); const [preferences,setPreferences]=useState<Preference[]>([]);
  const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(""); const [error,setError]=useState(""); const [pushMessage,setPushMessage]=useState("");
  const load=useCallback(async()=>{setLoading(true);setError("");try{const [list,prefs]=await Promise.all([publicApi.get<{notifications:NotificationItem[]}>("/v1/notifications?limit=80"),publicApi.get<{preferences:Preference[]}>("/v1/notifications/preferences")]);setItems(list.notifications);setPreferences(prefs.preferences);}catch(cause){setError(cause instanceof Error?cause.message:"Could not load notifications");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function open(item:NotificationItem){if(!item.readAt){await publicApi.patch(`/v1/notifications/${encodeURIComponent(item.id)}/read`,{}).catch(()=>undefined);setItems(v=>v.map(n=>n.id===item.id?{...n,readAt:new Date().toISOString()}:n));}router.push(notificationHref({resourceType:item.resourceType,resourceId:item.resourceId}));}
  async function enablePush(){setBusy("push");setError("");try{const result=await registerPushNotifications();setPushMessage(result.registered?"Push notifications enabled for this device.":result.reason==="permission-denied"?"Push permission was not granted.":"Push registration is unavailable in this build.");}catch(cause){setError(cause instanceof Error?cause.message:"Could not enable push notifications");}finally{setBusy("");}}
  async function toggle(category:string,channel:"PUSH"|"EMAIL"|"SMS",enabled:boolean){const key=`${category}:${channel}`;setBusy(key);try{const body=await publicApi.put<{preference:Preference}>(`/v1/notifications/preferences/${encodeURIComponent(category)}/${channel}`,{enabled});setPreferences(v=>[...v.filter(p=>!(p.category===category&&p.channel===channel)),body.preference]);}catch(cause){setError(cause instanceof Error?cause.message:"Could not save preference");}finally{setBusy("");}}
  const pref=(category:string,channel:"PUSH"|"EMAIL"|"SMS")=>preferences.find(p=>p.category===category&&p.channel===channel)?.enabled??true;
  return <Screen tabBarSafe={false}><SectionTitle eyebrow="Updates" title="Notifications"/>{error?<Text style={styles.error}>{error}</Text>:null}<Card style={styles.push}><Text style={styles.title}>Device notifications</Text><Text style={styles.muted}>Order, payment, refund and security updates can be delivered to this device.</Text><Button compact label="Enable push" loading={busy==="push"} onPress={()=>void enablePush()}/>{pushMessage?<Text style={styles.success}>{pushMessage}</Text>:null}</Card><Text style={styles.group}>Preferences</Text><Card style={styles.preferences}>{["ORDER","PAYMENT","REFUND","SUPPORT"].map(category=><View key={category} style={styles.prefRow}><Text style={styles.prefTitle}>{category.toLowerCase().replace(/^./,c=>c.toUpperCase())}</Text>{(["PUSH","EMAIL"] as const).map(channel=><Pressable key={channel} disabled={busy===`${category}:${channel}`} onPress={()=>void toggle(category,channel,!pref(category,channel))} style={[styles.chip,pref(category,channel)&&styles.chipActive]}><Text style={[styles.chipText,pref(category,channel)&&styles.chipTextActive]}>{channel}</Text></Pressable>)}</View>)}</Card><Text style={styles.group}>Inbox</Text>{loading?<Text style={styles.muted}>Loading notifications…</Text>:items.length===0?<Card><Text style={styles.title}>No notifications yet</Text><Text style={styles.muted}>Order and payment updates will appear here.</Text></Card>:<View style={styles.list}>{items.map(item=><Pressable key={item.id} onPress={()=>void open(item)}><Card style={[styles.item,!item.readAt&&styles.unread]}><View style={styles.itemHead}><Text style={styles.category}>{item.category}</Text><Text style={styles.date}>{new Date(item.createdAt).toLocaleDateString()}</Text></View><Text style={styles.itemTitle}>{item.title}</Text><Text style={styles.muted}>{item.body}</Text></Card></Pressable>)}</View>}</Screen>;
}
const styles=StyleSheet.create({error:{color:"#FCA5A5",fontSize:11,marginBottom:8},success:{color:colors.green,fontSize:10},push:{gap:8},title:{color:colors.text,fontSize:15,fontWeight:"900"},muted:{color:colors.muted,fontSize:11,lineHeight:17},group:{color:colors.muted2,fontSize:9,fontWeight:"900",letterSpacing:1,textTransform:"uppercase",marginTop:16,marginBottom:7},preferences:{padding:0,overflow:"hidden"},prefRow:{minHeight:54,paddingHorizontal:12,flexDirection:"row",alignItems:"center",gap:8,borderBottomWidth:1,borderBottomColor:colors.border},prefTitle:{color:colors.text,fontWeight:"800",fontSize:11,flex:1},chip:{borderWidth:1,borderColor:colors.borderStrong,borderRadius:999,paddingHorizontal:10,paddingVertical:6},chipActive:{borderColor:colors.indigoBright,backgroundColor:"rgba(91,77,255,.13)"},chipText:{color:colors.muted,fontSize:9,fontWeight:"800"},chipTextActive:{color:colors.indigoBright},list:{gap:8},item:{gap:5},unread:{borderColor:colors.indigoBright},itemHead:{flexDirection:"row",justifyContent:"space-between"},category:{color:colors.orange,fontSize:8,fontWeight:"900",letterSpacing:.8},date:{color:colors.muted2,fontSize:8},itemTitle:{color:colors.text,fontSize:13,fontWeight:"900"}});
