import { useCallback, useEffect, useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { useLocalSearchParams } from "expo-router";
import { Button, Card, Field, Screen, SectionTitle, colors } from "@bazaara/mobile-ui";
import { publicApi } from "@/lib/api";

type Message={id:string;kind:string;body:string;createdAt:string;author?:{displayName:string|null}|null};
type Case={id:string;category:string;subject:string;description:string;status:string;priority:string;lastActivityAt:string;messages:Message[]};
const categories=["ORDER","DELIVERY","PAYMENT","RETURN","PRODUCT","ACCOUNT","OTHER"] as const;
export default function SupportPage(){
 const params=useLocalSearchParams<{case?:string|string[]}>(); const requested=Array.isArray(params.case)?params.case[0]:params.case;
 const[cases,setCases]=useState<Case[]>([]);const[selected,setSelected]=useState<string|undefined>(requested);const[subject,setSubject]=useState("");const[description,setDescription]=useState("");const[category,setCategory]=useState<(typeof categories)[number]>("ORDER");const[reply,setReply]=useState("");const[busy,setBusy]=useState("");const[error,setError]=useState("");
 const current=useMemo(()=>cases.find(item=>item.id===selected),[cases,selected]);
 const load=useCallback(async()=>{try{const body=await publicApi.get<{cases:Case[]}>("/v1/support/cases");setCases(body.cases);if(requested&&body.cases.some(item=>item.id===requested))setSelected(requested);}catch(cause){setError(cause instanceof Error?cause.message:"Could not load support cases");}},[requested]);
 useEffect(()=>{void load();},[load]);
 async function create(){if(!subject.trim()||!description.trim())return;setBusy("create");setError("");try{const body=await publicApi.post<{case:Case}>("/v1/support/cases",{category,subject:subject.trim(),description:description.trim()});setCases(v=>[body.case,...v]);setSelected(body.case.id);setSubject("");setDescription("");}catch(cause){setError(cause instanceof Error?cause.message:"Could not create support case");}finally{setBusy("");}}
 async function send(){if(!current||!reply.trim())return;setBusy("reply");try{const body=await publicApi.post<{case:Case}>(`/v1/support/cases/${encodeURIComponent(current.id)}/messages`,{body:reply.trim()});setCases(v=>v.map(item=>item.id===body.case.id?body.case:item));setReply("");}catch(cause){setError(cause instanceof Error?cause.message:"Could not send message");}finally{setBusy("");}}
 async function escalate(){if(!current)return;setBusy("escalate");try{const body=await publicApi.post<{case:Case}>(`/v1/support/cases/${encodeURIComponent(current.id)}/escalate`,{reason:"Customer requested additional review in Shopping"});setCases(v=>v.map(item=>item.id===body.case.id?body.case:item));}catch(cause){setError(cause instanceof Error?cause.message:"Could not escalate case");}finally{setBusy("");}}
 return <Screen tabBarSafe={false}><SectionTitle eyebrow="Shopping assistance" title="Help & support"/>{error?<Text style={styles.error}>{error}</Text>:null}{current?<><Pressable onPress={()=>setSelected(undefined)}><Text style={styles.back}>‹ All cases</Text></Pressable><Card style={styles.caseCard}><View style={styles.caseHead}><Text style={styles.caseTitle}>{current.subject}</Text><Text style={styles.status}>{current.status.replaceAll("_"," ")}</Text></View><Text style={styles.muted}>{current.category} · {current.priority}</Text>{current.messages.map(message=><View key={message.id} style={[styles.message,message.kind==="CUSTOMER"&&styles.customer]}><Text style={styles.messageKind}>{message.kind}</Text><Text style={styles.messageBody}>{message.body}</Text><Text style={styles.time}>{new Date(message.createdAt).toLocaleString()}</Text></View>)}{current.status!=="CLOSED"?<><Field label="Reply" value={reply} onChangeText={setReply}/><Button label="Send reply" loading={busy==="reply"} onPress={()=>void send()}/><Button kind="secondary" label="Escalate" loading={busy==="escalate"} onPress={()=>void escalate()}/></>:null}</Card></>:<><Card style={styles.create}><Text style={styles.caseTitle}>Start a support case</Text><View style={styles.categoryRow}>{categories.map(item=><Pressable key={item} onPress={()=>setCategory(item)} style={[styles.categoryChip,item===category&&styles.categoryActive]}><Text style={[styles.categoryText,item===category&&styles.categoryTextActive]}>{item}</Text></Pressable>)}</View><Field label="Subject" value={subject} onChangeText={setSubject}/><Field label="Describe what happened" value={description} onChangeText={setDescription} multiline/><Button label="Create support case" loading={busy==="create"} onPress={()=>void create()}/></Card><Text style={styles.group}>Your cases</Text>{cases.length===0?<Text style={styles.muted}>No support cases yet.</Text>:<View style={styles.list}>{cases.map(item=><Pressable key={item.id} onPress={()=>setSelected(item.id)}><Card style={styles.row}><View style={{flex:1}}><Text style={styles.caseTitle}>{item.subject}</Text><Text style={styles.muted}>{item.category} · {item.status.replaceAll("_"," ")}</Text></View><Text style={styles.chev}>›</Text></Card></Pressable>)}</View>}</>}</Screen>;
}
const styles=StyleSheet.create({error:{color:"#FCA5A5",fontSize:11,marginBottom:8},back:{color:colors.indigoBright,fontWeight:"800",marginBottom:8},muted:{color:colors.muted,fontSize:10,lineHeight:15},create:{gap:9},caseCard:{gap:9},caseHead:{flexDirection:"row",gap:8,alignItems:"flex-start"},caseTitle:{color:colors.text,fontSize:13,fontWeight:"900",flex:1},status:{color:colors.orange,fontSize:8,fontWeight:"900"},categoryRow:{flexDirection:"row",flexWrap:"wrap",gap:6},categoryChip:{borderWidth:1,borderColor:colors.borderStrong,borderRadius:999,paddingHorizontal:8,paddingVertical:5},categoryActive:{borderColor:colors.indigoBright,backgroundColor:"rgba(91,77,255,.12)"},categoryText:{color:colors.muted,fontSize:8,fontWeight:"800"},categoryTextActive:{color:colors.indigoBright},message:{borderRadius:10,backgroundColor:colors.card,padding:10,gap:4},customer:{borderColor:colors.indigoBright,borderWidth:1},messageKind:{color:colors.muted2,fontSize:8,fontWeight:"900"},messageBody:{color:colors.text,fontSize:11,lineHeight:16},time:{color:colors.muted2,fontSize:8},group:{color:colors.muted2,fontSize:9,fontWeight:"900",textTransform:"uppercase",letterSpacing:1,marginTop:16,marginBottom:7},list:{gap:7},row:{flexDirection:"row",alignItems:"center",gap:8},chev:{color:colors.muted2,fontSize:24}});
