"use client";
import {useCallback,useEffect,useState,type ChangeEvent,type FormEvent} from "react";
import {api,errorText,uploadMedia} from "@bazaara/social-ui";
import {Dock,Failure,Notice} from "./Dock";
type Clip={id:string;caption:string;creator:{displayName:string|null};_count:{comments:number};media:{url:string}};
type Comment={id:string;body:string;author:{displayName:string|null};createdAt:string};
export default function Tools(){return <Dock app="ZimZam">{()=> <Panel/>}</Dock>}
function Panel(){
 const [clips,setClips]=useState<Clip[]>([]),[selected,setSelected]=useState(""),[comments,setComments]=useState<Comment[]>([]),[body,setBody]=useState(""),[caption,setCaption]=useState(""),[file,setFile]=useState<File|null>(null),[visibility,setVisibility]=useState<"PUBLIC"|"PRIVATE">("PUBLIC"),[error,setError]=useState(""),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[view,setView]=useState<"publish"|"comments">("comments");
 const load=useCallback(async()=>{try{const data=await api.get<{clips:Clip[]}>("/v1/bazclips/feed",{query:{limit:24},maxRetries:0});setClips(data.clips)}catch(e){setError(errorText(e))}},[]);
 const loadComments=useCallback(async(id:string)=>{if(!id)return;try{const data=await api.get<{comments:Comment[]}>(`/v1/bazclips/clips/${encodeURIComponent(id)}/comments`,{maxRetries:0});setComments(data.comments)}catch(e){setError(errorText(e))}},[]);
 useEffect(()=>{void load()},[load]);useEffect(()=>{setComments([]);if(selected)void loadComments(selected)},[selected,loadComments]);
 function choose(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0]??null;if(f&&!f.type.startsWith("video/")){setError("Select a video file.");setFile(null);return}if(f&&f.size>250*1024*1024){setError("The current API accepts up to 250 MB per video.");setFile(null);return}setError("");setFile(f)}
 async function publish(e:FormEvent){e.preventDefault();if(!file||busy)return;setBusy(true);setError("");setNotice("Uploading selected video. Keep this page open.");try{const asset=await uploadMedia(file,visibility);await api.post("/v1/bazclips/clips",{assetId:asset.id,caption:caption.trim(),visibility});setFile(null);setCaption("");setNotice("Video published. Private videos are visible to you only.");await load();setView("comments")}catch(e){setError(errorText(e));setNotice("")}finally{setBusy(false)}}
 async function comment(e:FormEvent){e.preventDefault();if(!selected||!body.trim()||busy)return;setBusy(true);try{await api.post(`/v1/bazclips/clips/${encodeURIComponent(selected)}/comments`,{body:body.trim()});setBody("");await loadComments(selected);setNotice("Comment posted.")}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 return <><span className="tag">REAL MEDIA + COMMENTS API</span><h2>Creator operations</h2><p>Upload and publish a video using your existing media service. Read and post clip comments without leaving ZimZam. This is not an AI-ranked global feed or live streaming service.</p><div className="actions"><button className={view==="comments"?"primary":""} onClick={()=>setView("comments")}>Comments</button><button className={view==="publish"?"primary":""} onClick={()=>setView("publish")}>Publish video</button></div><Failure message={error} clear={()=>setError("")}/><Notice message={notice}/>
 {view==="publish"?<form onSubmit={e=>void publish(e)} className="card"><h3>New short-form video</h3><label>Video file (up to 250 MB)<input type="file" accept="video/*" onChange={choose} disabled={busy}/></label>{file&&<span className="chip">{file.name} · {(file.size/1048576).toFixed(1)} MB</span>}<label>Caption<textarea maxLength={2200} rows={4} value={caption} onChange={e=>setCaption(e.target.value)}/></label><label>Visibility<select value={visibility} onChange={e=>setVisibility(e.target.value as "PUBLIC"|"PRIVATE")}><option value="PUBLIC">Public</option><option value="PRIVATE">Private / only me</option></select></label><button className="primary" disabled={!file||busy}>{busy?"Uploading…":"Upload and publish"}</button></form>:<><div className="card"><div className="row"><h3>Published clips</h3><button type="button" onClick={()=>void load()}>Refresh</button></div><label>Select a video<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose a clip</option>{clips.map(c=><option key={c.id} value={c.id}>{(c.creator.displayName??"Creator")+" · "+(c.caption||"Untitled").slice(0,65)}</option>)}</select></label></div>{selected&&<><div className="card"><h3>{clips.find(c=>c.id===selected)?.caption||"Selected clip"}</h3><video className="media" controls preload="metadata" playsInline src={clips.find(c=>c.id===selected)?.media.url}/></div><div className="list">{comments.map(c=><div className="card" key={c.id}><div className="row"><strong>{c.author.displayName??"Member"}</strong><small>{new Date(c.createdAt).toLocaleString()}</small></div><div className="textbox">{c.body}</div></div>)}{!comments.length&&<p>No comments yet.</p>}</div><form onSubmit={e=>void comment(e)}><label>Write a comment<textarea value={body} rows={3} maxLength={1000} onChange={e=>setBody(e.target.value)} /></label><button className="primary" disabled={busy||!body.trim()}>Post comment</button></form></>}{!clips.length&&<p>Your accessible feed is empty. Publish the first video.</p>}</>}
 </>
}
