'use client';
import { useEffect, useMemo, useRef, useState } from 'react';

type Moment={id:string;title:string;subtitle:string;month:number;day:number;category:'Discovery'|'Culture'|'Learning'|'Nature';region:string;story:string;prompt:string;symbol:string};
// Editorial exemplars: do not imply the selected event is today's news or auto-generated.
const MOMENTS:Moment[]=[
 {id:'space',title:'The wonder of discovery',subtitle:'An original space-inspired visual story',month:10,day:4,category:'Discovery',region:'Global',story:'From the night sky to spacecraft, curiosity connects the world. World Space Week runs October 4–10 each year.',prompt:'What makes the night sky worth exploring?',symbol:'✦'},
 {id:'literacy',title:'Stories change everything',subtitle:'Celebrating the power of reading',month:9,day:8,category:'Learning',region:'Global',story:'International Literacy Day is observed September 8. Every language and every story creates new possibilities.',prompt:'Search the history of writing',symbol:'⌘'},
 {id:'ocean',title:'A world beneath the surface',subtitle:'Explore our extraordinary blue planet',month:6,day:8,category:'Nature',region:'Global',story:'World Oceans Day takes place June 8. Oceans shape our climate, sustain ecosystems and inspire exploration.',prompt:'Explore marine biodiversity',symbol:'≈'},
 {id:'culture',title:'Many cultures. One horizon.',subtitle:'A celebration of creative expression',month:5,day:21,category:'Culture',region:'Global',story:'The World Day for Cultural Diversity for Dialogue and Development is observed May 21.',prompt:'Explore world cultures and traditions',symbol:'✳'},
 {id:'teachers',title:'Where every future begins',subtitle:'Celebrating people who teach and inspire',month:10,day:5,category:'Learning',region:'Global',story:'World Teachers’ Day is observed October 5. This original artwork celebrates learning everywhere.',prompt:'History of education',symbol:'✎'},
 {id:'earth',title:'Designed to protect tomorrow',subtitle:'Creative exploration of our planet',month:4,day:22,category:'Nature',region:'Global',story:'Earth Day is observed April 22. This original BAZAARA illustration encourages learning about our environment.',prompt:'Earth science',symbol:'◌'},
];
export function SearchMoments({onSearch}:{onSearch:(query:string)=>void}){
 const today=new Date();const [open,setOpen]=useState(false);const [filter,setFilter]=useState('All');const [term,setTerm]=useState('');const [selected,setSelected]=useState<Moment|null>(null);const dialogRef=useRef<HTMLElement>(null);
 useEffect(()=>{if(!selected)return;const previous=document.activeElement instanceof HTMLElement?document.activeElement:null;dialogRef.current?.querySelector<HTMLButtonElement>('button')?.focus();const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape'){setSelected(null);return;}if(e.key==='Tab'&&dialogRef.current){const els=Array.from(dialogRef.current.querySelectorAll<HTMLElement>('button,a[href]'));if(!els.length)return;if(e.shiftKey&&document.activeElement===els[0]){e.preventDefault();els[els.length-1]?.focus();}else if(!e.shiftKey&&document.activeElement===els[els.length-1]){e.preventDefault();els[0]?.focus();}}};document.addEventListener('keydown',onKey,true);return()=>{document.removeEventListener('keydown',onKey,true);previous?.focus();};},[selected]);
 const sorted=useMemo(()=>[...MOMENTS].sort((a,b)=>{const da=(a.month-today.getMonth()-1+12)%12;const db=(b.month-today.getMonth()-1+12)%12;return da-db||a.day-b.day;}),[today.getMonth()]);
 const featured=sorted[0];
  if (!featured) return <section className="bz86-moments" aria-label="BAZAARA Moments original editorial collection"><p>Moments are currently unavailable.</p></section>;
 const visible=MOMENTS.filter(m=>(filter==='All'||m.category===filter)&&`${m.title} ${m.subtitle} ${m.category} ${m.region}`.toLowerCase().includes(term.toLowerCase()));
 return <section className="bz86-moments" aria-label="BAZAARA Moments original editorial collection">
  <div className="bz86-moment-hero">
   <div className="bz86-moment-art" aria-hidden="true"><span className="bz86-moment-orbit one"/><span className="bz86-moment-orbit two"/><span className="bz86-moment-glyph">{featured.symbol}</span><span className="bz86-moment-star">✧</span></div>
   <div className="bz86-moment-copy"><div className="bz86-eyebrow">BAZAARA MOMENTS <span>·</span> ORIGINAL ARTWORK</div><h2>{featured.title}</h2><p>{featured.subtitle}</p><div className="bz86-moment-buttons"><button type="button" onClick={()=>setSelected(featured)}>Discover the story</button><button type="button" className="bz86-subtle" onClick={()=>setOpen(value=>!value)} aria-expanded={open}>Moments archive ↗</button></div></div>
  </div>
  {open && <div className="bz86-moment-archive"><header><div><span className="bz86-eyebrow">ARCHIVE · CURATED EDITORIAL EXAMPLES</span><h3>Explore Moments</h3><p>Original sample artwork. Upcoming calendar dates are not a live events feed.</p></div><button type="button" onClick={()=>setOpen(false)} aria-label="Close Moments archive">×</button></header>
   <div className="bz86-moment-controls"><input aria-label="Find a moment" placeholder="Search the collection" value={term} onChange={e=>setTerm(e.target.value)}/><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Filter Moments category">{['All','Discovery','Culture','Learning','Nature'].map(c=><option key={c}>{c}</option>)}</select></div>
   <div className="bz86-moment-grid">{visible.map(m=><button type="button" key={m.id} onClick={()=>setSelected(m)} className={`bz86-moment-tile bz86-moment-${m.id}`}><span aria-hidden="true">{m.symbol}</span><small>{new Date(2026,m.month-1,m.day).toLocaleString('en-US',{month:'short',day:'numeric'})} · {m.category}</small><strong>{m.title}</strong><em>{m.region}</em></button>)}{visible.length===0&&<p className="bz86-empty">No Moments match your search.</p>}</div>
  </div>}
  {selected && <div className="bz86-moment-overlay" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null);}}><section className="bz86-moment-dialog" ref={dialogRef} role="dialog" aria-modal="true" aria-label="Moment story"><button type="button" aria-label="Close Moment story" onClick={()=>setSelected(null)} className="bz86-moment-close">×</button><span className="bz86-moment-story-glyph" aria-hidden="true">{selected.symbol}</span><small>BAZAARA MOMENTS · {selected.category.toUpperCase()}</small><h2>{selected.title}</h2><p>{selected.story}</p><button type="button" onClick={()=>{setSelected(null);onSearch(selected.prompt);}}>Explore this topic ↗</button></section></div>}
 </section>;
}
