"use client";
import { useCallback, useEffect, useMemo, useRef, useState, type ChangeEvent, type FormEvent } from "react";
import { api, errorText, Member, ProfileSetup, SessionGate, Shell, TitleBlock, uploadMedia, useSocialSession } from "@bazaara/social-ui";

type Creator = { id:string; displayName:string|null; socialProfile?:{handle:string}|null };
type Clip = { id:string; caption:string; visibility:string; createdAt:string; creator:Creator; creatorId:string; liked:boolean; viewCount:number; _count:{likes:number;comments:number}; media:{id:string;contentType:string;byteSize:number;url:string} };
type Comment={id:string;body:string;createdAt:string;authorId:string;author:Creator};

export default function ZimZamHome(){
  const session=useSocialSession();
  const [clips,setClips]=useState<Clip[]>([]),[feedMode,setFeedMode]=useState<"FOR_YOU"|"LATEST">("FOR_YOU"),[file,setFile]=useState<File|null>(null),[caption,setCaption]=useState(""),[visibility,setVisibility]=useState<"PUBLIC"|"PRIVATE">("PUBLIC"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[progress,setProgress]=useState("");
  const [commentOpen,setCommentOpen]=useState(""),[comments,setComments]=useState<Record<string,Comment[]>>({}),[commentDraft,setCommentDraft]=useState(""); const viewed=useRef(new Set<string>());
  const preview=useMemo(()=>file?URL.createObjectURL(file):"",[file]);
  const displayClips=useMemo(()=>feedMode==="LATEST"?[...clips].sort((a,b)=>Date.parse(b.createdAt)-Date.parse(a.createdAt)):clips,[clips,feedMode]);
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
  const load=useCallback(async()=>{try{const data=await api.get<{clips:Clip[]}>("/v1/bazclips/feed",{query:{limit:24},maxRetries:0});setClips(data.clips);}catch(e){setError(errorText(e));}},[]);
  useEffect(()=>{if(session.user?.profile)void load();},[session.user?.profile,load]);
  function choose(e:ChangeEvent<HTMLInputElement>){const next=e.target.files?.[0]??null;if(next&&next.size>250*1024*1024){setError("Choose a video smaller than 250 MB.");return;}setFile(next);setError("");}
  async function publish(e:FormEvent){e.preventDefault();if(!file||busy)return;setBusy(true);setError("");try{setProgress("Uploading video…");const asset=await uploadMedia(file,visibility);setProgress("Publishing clip…");await api.post("/v1/bazclips/clips",{assetId:asset.id,caption:caption.trim(),visibility});setFile(null);setCaption("");setProgress("");await load();}catch(err){setError(errorText(err));setProgress("");}finally{setBusy(false);}}
  async function like(clip:Clip){try{if(clip.liked)await api.delete(`/v1/bazclips/clips/${encodeURIComponent(clip.id)}/like`);else await api.put(`/v1/bazclips/clips/${encodeURIComponent(clip.id)}/like`,{});setClips(old=>old.map(x=>x.id===clip.id?{...x,liked:!x.liked,_count:{...x._count,likes:Math.max(0,x._count.likes+(x.liked?-1:1))}}:x));}catch(err){setError(errorText(err));}}
  async function remove(clip:Clip){if(!confirm("Remove this clip from ZimZam?"))return;try{await api.delete(`/v1/bazclips/clips/${encodeURIComponent(clip.id)}`);setClips(old=>old.filter(x=>x.id!==clip.id));}catch(err){setError(errorText(err));}}
  async function markView(clip:Clip){if(viewed.current.has(clip.id))return;viewed.current.add(clip.id);try{const data=await api.post<{viewCount:number}>(`/v1/bazclips/clips/${encodeURIComponent(clip.id)}/view`,{});setClips(old=>old.map(x=>x.id===clip.id?{...x,viewCount:data.viewCount}:x));}catch{viewed.current.delete(clip.id);}}
  async function toggleComments(clip:Clip){if(commentOpen===clip.id){setCommentOpen("");return;}setCommentOpen(clip.id);setCommentDraft("");if(comments[clip.id])return;try{const data=await api.get<{comments:Comment[]}>(`/v1/bazclips/clips/${encodeURIComponent(clip.id)}/comments`,{maxRetries:0});setComments(old=>({...old,[clip.id]:data.comments}));}catch(err){setError(errorText(err));}}
  async function addComment(clip:Clip,e:FormEvent){e.preventDefault();const body=commentDraft.trim();if(!body||busy)return;setBusy(true);try{const data=await api.post<{comment:Comment}>(`/v1/bazclips/clips/${encodeURIComponent(clip.id)}/comments`,{body});setComments(old=>({...old,[clip.id]:[...(old[clip.id]??[]),data.comment]}));setClips(old=>old.map(x=>x.id===clip.id?{...x,_count:{...x._count,comments:x._count.comments+1}}:x));setCommentDraft("");}catch(err){setError(errorText(err));}finally{setBusy(false);}}
  async function deleteComment(clip:Clip,comment:Comment){try{await api.delete(`/v1/bazclips/clips/${encodeURIComponent(clip.id)}/comments/${encodeURIComponent(comment.id)}`);setComments(old=>({...old,[clip.id]:(old[clip.id]??[]).filter(x=>x.id!==comment.id)}));setClips(old=>old.map(x=>x.id===clip.id?{...x,_count:{...x._count,comments:Math.max(0,x._count.comments-1)}}:x));}catch(err){setError(errorText(err));}}
  return <Shell slug="bazclips" section="Creator feed"><SessionGate {...session} productName="ZimZam">{session.user?.profile?<>
    <TitleBlock eyebrow="ZIMZAM / CREATE & DISCOVER" title="Make every second count." description="Publish short-form video through your BazID account, then discover clips from the BAZAARA community." action={<span className="e2-chip">LIVE MEDIA PIPELINE</span>}/>
    {error?<div className="e2-notice" role="alert">{error}<button className="e2-textButton" style={{marginLeft:12}} onClick={()=>setError("")}>Dismiss</button></div>:null}
    <div className="clips-layout"><section className="e2-card e2-cardPad clips-create"><div className="e2-rowBetween"><div><span className="e2-kicker">CREATOR STUDIO</span><h2>Publish a clip</h2></div><span className="e2-chip">≤ 250 MB</span></div><form onSubmit={publish} className="e2-form">{preview?<video className="clips-preview" src={preview} controls playsInline/>:<label className="clips-drop"><strong>Choose a video</strong><span>MP4, WebM, MOV or another browser-supported video.</span><input type="file" accept="video/*" onChange={choose}/></label>}<div className="e2-rowBetween">{file?<span className="e2-subtle">{file.name} · {(file.size/1024/1024).toFixed(1)} MB</span>:<span className="e2-subtle">Nothing selected</span>}{file?<label className="e2-textButton">Change<input type="file" accept="video/*" onChange={choose} style={{display:"none"}}/></label>:null}</div><label>Caption <span>{caption.length}/2200</span><textarea value={caption} maxLength={2200} onChange={e=>setCaption(e.target.value)} placeholder="Tell the story behind your clip…"/></label><label>Audience<select value={visibility} onChange={e=>setVisibility(e.target.value as "PUBLIC"|"PRIVATE")}><option value="PUBLIC">Public</option><option value="PRIVATE">Only me</option></select></label><button className="e2-button" disabled={!file||busy}>{busy?(progress||"Working…"):"Publish clip ↗"}</button></form></section>
    <section><div className="e2-rowBetween clips-feedHead"><div><span className="e2-kicker">DISCOVERY</span><h2>Fresh clips</h2></div><div className="clips-tabs" role="tablist" aria-label="Clip feed"><button className={feedMode==="FOR_YOU"?"active":""} onClick={()=>setFeedMode("FOR_YOU")}>For you</button><button className={feedMode==="LATEST"?"active":""} onClick={()=>setFeedMode("LATEST")}>Latest</button><button className="refresh" onClick={()=>void load()} aria-label="Refresh clips">↻</button></div></div><div className="clips-grid">{displayClips.map(clip=><article key={clip.id} className="e2-card clips-card"><video src={clip.media.url} controls playsInline preload="metadata" onPlay={()=>void markView(clip)}/><div className="clips-meta"><div className="e2-row"><Member size="small" name={clip.creator.displayName} handle={clip.creator.socialProfile?.handle}/><div><strong>{clip.creator.displayName||clip.creator.socialProfile?.handle||"Creator"}</strong><small>@{clip.creator.socialProfile?.handle||"member"}</small></div></div>{clip.caption?<p>{clip.caption}</p>:null}<div className="clips-stats"><span>▶ {clip.viewCount} views</span><button className={`circle-like ${clip.liked?"liked":""}`} onClick={()=>void like(clip)}>♡ {clip._count.likes}</button><button className="e2-textButton" onClick={()=>void toggleComments(clip)}>💬 {clip._count.comments}</button><span>{new Date(clip.createdAt).toLocaleDateString()}</span>{clip.creatorId===session.user?.id?<button className="e2-textButton" onClick={()=>void remove(clip)}>Remove</button>:null}</div>{commentOpen===clip.id?<div className="clips-comments"><div>{(comments[clip.id]??[]).map(comment=><div className="clips-comment" key={comment.id}><Member size="small" name={comment.author.displayName} handle={comment.author.socialProfile?.handle}/><div><strong>{comment.author.displayName||comment.author.socialProfile?.handle||"Member"}</strong><p>{comment.body}</p></div>{comment.authorId===session.user?.id?<button className="e2-textButton" onClick={()=>void deleteComment(clip,comment)}>Delete</button>:null}</div>)}{comments[clip.id]?.length===0?<p className="e2-subtle">No comments yet.</p>:null}</div><form onSubmit={e=>void addComment(clip,e)}><input value={commentDraft} onChange={e=>setCommentDraft(e.target.value)} maxLength={1000} placeholder="Add a comment…"/><button className="e2-button sm" disabled={busy||!commentDraft.trim()}>Post</button></form></div>:null}</div></article>)}{!clips.length?<div className="e2-card e2-empty"><strong>No clips yet.</strong><p>Publish the first clip or come back when creators have shared something new.</p></div>:null}</div></section></div>
  </>:session.user?<ProfileSetup user={session.user} onComplete={session.refresh} productName="ZimZam"/>:null}</SessionGate></Shell>;
}
