import { useCallback, useEffect, useState } from "react";
import { Pressable, Text, TextInput, View } from "react-native";
import { router, useLocalSearchParams } from "expo-router";
import { EmptyState, Screen } from "@bazaara/mobile-ui";
import { ApiError, foodApi } from "@/lib/api";
import { signInWithBazId } from "@/lib/auth";
import { foodStyles as s } from "@/ui/theme";

type Preview={shareToken:string;spendingLimitMinor:number|null;expiresAt:string;restaurant:{slug:string;name:string};memberCount:number};
export default function GroupJoin(){const{token}=useLocalSearchParams<{token:string}>();const[data,setData]=useState<Preview|null>(null);const[name,setName]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);const load=useCallback(async()=>{if(!token)return;try{const body=await foodApi.get<{group:Preview}>(`/v1/food/group-orders/${encodeURIComponent(token)}`,{cache:"no-store"});setData(body.group);setError("")}catch(e){setError(e instanceof Error?e.message:"This group order is unavailable")}},[token]);useEffect(()=>{void load()},[load]);async function join(){if(!token||!name.trim())return;setBusy(true);try{await foodApi.post(`/v1/food/group-orders/join/${encodeURIComponent(token)}`,{displayName:name.trim()});if(data)router.replace(`/restaurant/${data.restaurant.slug}`)}catch(e){if(e instanceof ApiError&&e.status===401){const r=await signInWithBazId(`/group/${token}`);if(r.ok)await join();else setError("Sign-in was cancelled.")}else setError(e instanceof Error?e.message:"Could not join group order")}finally{setBusy(false)}}if(!data)return <Screen tabBarSafe={false}><EmptyState title="Group order" message={error||"Loading invitation…"}/></Screen>;return <Screen tabBarSafe={false}><Text style={s.status}>GROUP ORDER</Text><Text style={s.h1}>{data.restaurant.name}</Text><Text style={s.p}>Join this shared restaurant order. Each person keeps a separate basket until the host places the combined order.</Text><View style={[s.card,{marginTop:16}]}><Text style={s.h2}>{data.memberCount} participant{data.memberCount===1?"":"s"}</Text>{data.spendingLimitMinor!=null?<Text style={s.p}>Host spending cap: ₦{Math.round(data.spendingLimitMinor/100).toLocaleString()}</Text>:null}<Text style={s.small}>Invitation expires {new Date(data.expiresAt).toLocaleString("en-NG")}</Text><Text style={[s.label,{marginTop:14}]}>Your display name</Text><TextInput style={s.input} value={name} onChangeText={setName} maxLength={80}/>{error?<Text style={[s.error,{marginTop:8}]}>{error}</Text>:null}<Pressable style={[s.button,{marginTop:12},!name.trim()&&{opacity:.5}]} disabled={!name.trim()||busy} onPress={()=>void join()}><Text style={s.buttonText}>{busy?"Joining…":"Join group order"}</Text></Pressable></View></Screen>}
