"use client";
import { useState } from "react";

type Ride = { id:string; status:string; rideClass:string; totalMinor:number; currency:string; createdAt:string };
type Props = { signedOut:boolean; payUrl:string; activeRideId:string|null; rides:Ride[]; onSignIn:()=>void; onSupport:(rideId?:string)=>void; onRefresh:()=>void };
const rows:{[k:string]:Array<[string,string,string,string]>}={
 account:[["profile","â—Ž","Profile","Personal details and identity"],["payment","â—«","Payment","Wallet, cards and transactions"],["safety","â—ˆ","Safety","Pickup code and trusted contacts"],["places","âŒ–","Saved places","Home, work and favourite places"],["settings","âš™","Settings","Communication, privacy and security"],["plus","âœ¦","Drive Plus","Benefits and ride perks"],["promos","â—‡","Promotions","Promo codes, offers and savings"],["family","âŒ‚","Family Profile","Manage and pay for family rides"],["work","â–£","Work Profile","Expense business rides"],["earn","â–¤","Earn with BAZAARA","Become a driver or courier"],["support","?","Help & support","Articles, cases and trip support"]],
 settings:[["communication","â—–","Communication","Notifications and preferences"],["calendar","â–¡","Calendar","Smart ride suggestions"],["language","A","Language","English"],["privacy","â—Ž","Privacy","Manage data and permissions"],["security","â–£","Sign in and security","Passkeys and verification"],["legal","Â§","Legal","Terms, privacy and accessibility"]],
 communication:[["noop","â€¢","Promotions & Tips",""],["noop","â€¢","BAZAARA products",""],["noop","â€¢","Travelling",""],["noop","â€¢","Partner offers",""],["noop","â€¢","Suggestions",""]],
 legal:[["noop","â—Ž","Accessibility Commitment",""],["noop","Â§","Terms and Conditions",""],["noop","â–¤","Acknowledgements",""],["noop","â–¤","Privacy Notice",""]],
 safety:[["noop","âœ£","Pick-up code","Disabled"],["noop","â˜Ž","Trusted contacts","None added"]],
 places:[["noop","âŒ‚","Add home address",""],["noop","â–£","Add work address",""],["noop","ï¼‹","Add a place",""]]
};
const titles:{[k:string]:string}={account:"Account",settings:"Settings",communication:"Communication preferences",legal:"Legal",safety:"Safety",places:"Saved places",profile:"Profile",payment:"Payment",support:"Support",security:"Sign in and security",plus:"Drive Plus",family:"Family Profile",work:"Work Profile",earn:"Earn with BAZAARA",promos:"Promotions",privacy:"Privacy",calendar:"Calendar",language:"Language"};
export default function DriveAccountHub({signedOut,payUrl,activeRideId,rides,onSignIn,onSupport,onRefresh}:Props){
 const [screen,setScreen]=useState('account'); const [twoStep,setTwoStep]=useState(false); const [pickupCode,setPickupCode]=useState(false);
 const go=(id:string)=>{ if(id==='payment'){location.href=`${payUrl}?section=drive${activeRideId?`&rideId=${encodeURIComponent(activeRideId)}`:''}`;return;} if(id==='support'){setScreen('support');return;} if(id==='noop')return; setScreen(id);};
 const back=()=>setScreen(screen==='account'?'account':(['communication','legal','security','privacy','calendar','language'].includes(screen)?'settings':'account'));
 const list=rows[screen];
 return <main className="dv14-page dv14-account dv15-account">{screen!=='account'?<button className="dv15-back" onClick={back}>â†</button>:null}<h1>{titles[screen]||'Account'}</h1>
 {screen==='account'?<><div className="dv14-profile"><span className="dv14-profile-icon">â—Ž</span><div><strong>{signedOut?'Your BAZAARA account':'Your account'}</strong><small>{signedOut?'Sign in to book and manage rides':'Drive profile, payments and safety'}</small></div><button onClick={signedOut?onSignIn:onRefresh}>{signedOut?'Sign in':'â†»'}</button></div></>:null}
 {list?<div className="dv14-account-list dv15-list">{list.map(([id,icon,label,sub],i)=><button type="button" key={label+i} onClick={()=>go(id)}>{icon}<span>{label}{sub?<small>{sub}</small>:null}</span><b>â€º</b></button>)}</div>:null}
 {screen==='profile'?<div className="dv15-cards"><div className="dv15-photo">â—Ž<button>âœŽ</button></div><p className="dv15-center">Drivers can only see your photo during pickup</p><div className="dv15-field"><small>Name</small><strong>BAZAARA rider</strong><b>â€º</b></div><div className="dv15-field"><small>Phone number</small><strong>Managed by BazID</strong><b>â€º</b></div><div className="dv15-field"><small>Email</small><strong>Managed by BazID</strong><b>â€º</b></div><div className="dv15-field"><small>Identity</small><strong>Verify with BazID</strong><button onClick={onSignIn}>Verify</button></div></div>:null}
 {screen==='security'?<div className="dv15-cards"><section><h2>Passkeys</h2><button className="dv15-link">Set up your passkeys</button><p>Use a device passkey for a faster, phishing-resistant sign-in when supported by BazID.</p></section><section><h2>Two-step verification</h2><div className="dv15-field"><strong>Two-step verification</strong><button onClick={()=>setTwoStep(!twoStep)}>{twoStep?'Turn off':'Turn on'}</button></div><p>Add an additional verification step to your account.</p></section><section><h2>Other login options</h2><p>Linked login providers are managed by BazID.</p></section></div>:null}
 {screen==='safety'?<div className="dv15-cards"><div className="dv15-field"><span>âœ£</span><div><strong>Pick-up code</strong><small>{pickupCode?'Enabled':'Disabled'}</small></div><button onClick={()=>setPickupCode(!pickupCode)}>{pickupCode?'Disable':'Enable'}</button></div><div className="dv15-field"><span>â˜Ž</span><div><strong>Trusted contacts</strong><small>Choose people for trip sharing</small></div><b>â€º</b></div><a className="dv15-emergency" href="tel:112">Emergency Â· 112</a></div>:null}
 {screen==='payment'?null:null}
 {screen==='support'?<div className="dv15-support-home"><h2>What can we help with?</h2>{rides.length?<><h3>Recent trips</h3>{rides.slice(0,2).map(r=><button key={r.id} onClick={()=>onSupport(r.id)}><span>â–°</span><div><strong>{r.rideClass.replaceAll('_',' ')} ride</strong><small>{new Date(r.createdAt).toLocaleString('en-NG')} Â· {r.status.replaceAll('_',' ')}</small></div><b>â€º</b></button>)}</>:null}<h3>Something else</h3><button onClick={()=>onSupport()}><span>â˜</span><strong>Contact a support agent</strong><b>â€º</b></button><button onClick={()=>setScreen('help')}><span>â–¤</span><strong>Browse help articles</strong><b>â€º</b></button><button onClick={()=>setScreen('cases')}><span>â—Œ</span><strong>Cases</strong><b>â€º</b></button></div>:null}
 {screen==='help'?<div className="dv15-help">{['About BAZAARA Drive','App and features','Account and data','Payments and pricing','Using Drive','Safety and accessibility'].map(x=><button key={x}>{x}<b>â€º</b></button>)}</div>:null}
 {screen==='cases'?<div className="dv15-empty"><div className="dv15-bubble">â€¢â€¢â€¢</div><h2>No open cases</h2><p>Support cases you create will appear here.</p></div>:null}
 {screen==='plus'?<div className="dv15-perks"><div className="dv15-hero"><strong>BAZAARA Drive+</strong><p>Optional ride membership</p></div>{['Ride rewards','Priority matching when available','Flexible cancellation benefits','Pause or cancel membership'].map(x=><div key={x}>âœ“ <strong>{x}</strong></div>)}<button className="dv14-primary">View membership options</button></div>:null}
 {screen==='family'?<div className="dv15-feature"><div className="dv15-art">â™Ÿ â™Ÿ</div><h2>Keep your family connected</h2><p>Share ride visibility, manage family payment preferences and review family ride activity from one profile.</p><button className="dv14-primary">Create family profile</button></div>:null}
 {screen==='work'?<div className="dv15-feature"><div className="dv15-art">â–£ â–°</div><h2>Expense your work rides with ease</h2><p>Separate business rides, receipts and payment methods from personal travel.</p><button className="dv14-primary">Set up work profile</button></div>:null}
 {screen==='earn'?<div className="dv15-help"><p>Earn on your own schedule with BAZAARA.</p><button>Become a BAZAARA driver<b>â€º</b></button><button>Become a BAZAARA courier<b>â€º</b></button></div>:null}
 {['privacy','calendar','language','promos'].includes(screen)?<div className="dv15-empty"><h2>{titles[screen]}</h2><p>This preference is connected to your BAZAARA account and will use the platform service when available.</p></div>:null}
 </main>
}
