var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/search-data/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__19w432d._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1m3joqg._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j26pto._.js")
R.c("server/chunks/ssr/apps_search-web_app_layout_tsx_06jnkfc._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/apps_search-web__next-internal_server_app_search-data_page_actions_0-1o-ts.js")
R.m(17185)
module.exports=R.m(17185).exports
