'use client';
import {useEffect,useMemo,useRef,useState,type ChangeEvent,type DragEvent} from 'react';
import StandaloneFrame from './StandaloneFrame';
import InternetWorkspace from './InternetWorkspace';

type Vision={labels:string[];text:string;matches:{title:string;url:string}[]};
type Barcode={rawValue:string;format:string};
type Mode='Search'|'Text'|'Translate'|'Shopping'|'QR';

function localApp(slug:string,port:number){if(typeof window==='undefined')return '#';try{const urls=JSON.parse(process.env.NEXT_PUBLIC_BAZAARA_APP_URLS||'{}') as Record<string,string>;if(typeof urls[slug]==='string'&&/^https:\/\//.test(urls[slug]))return urls[slug];}catch{}const host=window.location.hostname;return ['localhost','127.0.0.1','::1'].includes(host)?`${window.location.protocol}//${host.includes(':')?`[${host}]`:host}:${port}/`:'#';}

export default function BazLensExperience(){
 const [tab,setTab]=useState('Explore'),[mode,setMode]=useState<Mode>('Search'),[file,setFile]=useState<File|null>(null),[preview,setPreview]=useState(''),[remoteUrl,setRemoteUrl]=useState(''),[dimensions,setDimensions]=useState<{width:number;height:number}|null>(null),[colors,setColors]=useState<string[]>([]),[crop,setCrop]=useState(100),[notes,setNotes]=useState(''),[label,setLabel]=useState(''),[loading,setLoading]=useState(false),[connected,setConnected]=useState(false),[result,setResult]=useState<Vision|null>(null),[codes,setCodes]=useState<Barcode[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[camera,setCamera]=useState(false),[links,setLinks]=useState<Record<string,string>>({}),[followUp,setFollowUp]=useState('');
 const chooser=useRef<HTMLInputElement>(null),picture=useRef<HTMLImageElement>(null),video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null);
 useEffect(()=>{void fetch('/api/analyze',{cache:'no-store'}).then(r=>r.json()).then((d:{configured?:boolean})=>setConnected(d.configured===true)).catch(()=>setConnected(false));setLinks({translate:localApp('translate',3039),search:localApp('search',3020),shopping:localApp('shopping',3003),map:localApp('bmap',3038),news:localApp('news',3040)});return()=>{stream.current?.getTracks().forEach(t=>t.stop());};},[]);
 useEffect(()=>{if(!camera||!video.current||!stream.current)return;video.current.srcObject=stream.current;void video.current.play().catch(()=>setNotice('Tap the preview to start your camera.'));},[camera]);
 useEffect(()=>{if(!file){setPreview('');setDimensions(null);setColors([]);return;}const url=URL.createObjectURL(file);setPreview(url);setResult(null);setCodes([]);const img=new Image();img.onload=()=>{setDimensions({width:img.naturalWidth,height:img.naturalHeight});const canvas=document.createElement('canvas');canvas.width=52;canvas.height=52;const ctx=canvas.getContext('2d',{willReadFrequently:true});if(ctx){ctx.drawImage(img,0,0,52,52);const data=ctx.getImageData(0,0,52,52).data;const bucket=new Map<string,number>();for(let i=0;i<data.length;i+=16){if(data[i+3]<125)continue;const r=Math.round(data[i]/32)*32,g=Math.round(data[i+1]/32)*32,b=Math.round(data[i+2]/32)*32;const color='#'+[r,g,b].map(v=>Math.min(255,v).toString(16).padStart(2,'0')).join('');bucket.set(color,(bucket.get(color)||0)+1);}setColors([...bucket.entries()].sort((a,b)=>b[1]-a[1]).slice(0,6).map(([c])=>c));}};img.onerror=()=>setError('Image could not be decoded.');img.src=url;return()=>{URL.revokeObjectURL(url);img.onload=null;};},[file]);
 function pick(candidate:File|undefined){if(!candidate)return;setError('');setNotice('');if(!['image/png','image/jpeg','image/webp','image/gif'].includes(candidate.type)){setError('Select a PNG, JPEG, WebP or GIF image.');return;}if(candidate.size>8*1024*1024){setError('Choose an image smaller than 8 MB.');return;}setFile(candidate);setLabel(candidate.name.replace(/\.[^.]+$/,'').slice(0,90));setCrop(100);setTab('Explore');stopCamera();}
 function dropped(e:DragEvent<HTMLDivElement>){e.preventDefault();pick(e.dataTransfer.files?.[0]);}
 async function importRemote(){const raw=remoteUrl.trim();if(!raw)return;setError('');setNotice('');try{const parsed=new URL(raw);if(parsed.protocol!=='https:')throw Error('Use an HTTPS image URL.');const response=await fetch(parsed.href,{mode:'cors',credentials:'omit',referrerPolicy:'no-referrer'});if(!response.ok)throw Error('The image host did not allow this request.');const blob=await response.blob();if(!blob.type.startsWith('image/'))throw Error('That URL did not return an image.');if(blob.size>8*1024*1024)throw Error('The image is larger than 8 MB.');pick(new File([blob],`linked-image.${blob.type.split('/')[1]||'jpg'}`,{type:blob.type}));setNotice('Image imported from the provided link.');}catch(e){setError(e instanceof Error?e.message:'Could not import that image link.');}}
 function stopCamera(){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setCamera(false);}
 async function openCamera(){if(!navigator.mediaDevices?.getUserMedia){setError('Camera access is unavailable. Use HTTPS or localhost.');return;}setError('');try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});setCamera(true);}catch{setError('Camera permission was denied or the device has no available camera.');}}
 function snap(){if(!video.current||!stream.current)return;const el=video.current;const canvas=document.createElement('canvas');canvas.width=el.videoWidth||960;canvas.height=el.videoHeight||720;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.drawImage(el,0,0,canvas.width,canvas.height);canvas.toBlob(blob=>{if(blob)pick(new File([blob],`bazaara-capture-${Date.now()}.jpg`,{type:'image/jpeg'}));else setError('Could not capture the camera image.');},'image/jpeg',.9);}
 async function analyze(kind:'objects'|'text'|'similar'){if(!file){setError('Select or capture an image first.');return;}if(!connected){setError('Visual recognition requires a connected vision service.');return;}setLoading(true);setError('');try{const form=new FormData();form.append('image',file);form.append('mode',kind);const r=await fetch('/api/analyze',{method:'POST',body:form,credentials:'same-origin'});const data=await r.json() as Vision&{message?:string};if(!r.ok)throw Error(data.message||'Image analysis unavailable.');setResult({labels:Array.isArray(data.labels)?data.labels.filter(x=>typeof x==='string').slice(0,25):[],text:typeof data.text==='string'?data.text:'',matches:Array.isArray(data.matches)?data.matches.filter(x=>typeof x.title==='string'&&/^https:\/\//.test(x.url)).slice(0,8):[]});setTab('Results');}catch(e){setError(e instanceof Error?e.message:'Image analysis failed.');}finally{setLoading(false);}}
 async function barcode(){if(!file||!picture.current){setError('Choose an image before scanning for a QR code.');return;}type Detect={detect:(element:HTMLImageElement)=>Promise<Barcode[]>};const w=window as typeof window&{BarcodeDetector?:new(config:{formats?:string[]})=>Detect};if(!w.BarcodeDetector){setError('Barcode detection is unavailable in this browser.');return;}try{const detector=new w.BarcodeDetector({formats:['qr_code','ean_13','ean_8','code_128']});setCodes((await detector.detect(picture.current)).slice(0,20));setTab('Results');}catch{setError('No readable code was found.');}}
 function run(){if(mode==='QR')void barcode();else if(mode==='Text'||mode==='Translate')void analyze('text');else if(mode==='Shopping')void analyze('objects');else void analyze('similar');}
 function downloadCrop(){if(!picture.current||!dimensions)return;const canvas=document.createElement('canvas');const fraction=crop/100;const w=Math.max(1,Math.floor(dimensions.width*fraction)),h=Math.max(1,Math.floor(dimensions.height*fraction));canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');if(!ctx){setError('Canvas is unavailable.');return;}ctx.drawImage(picture.current,(dimensions.width-w)/2,(dimensions.height-h)/2,w,h,0,0,w,h);canvas.toBlob(blob=>{if(!blob){setError('Could not export the crop.');return;}const href=URL.createObjectURL(blob);const a=document.createElement('a');a.href=href;a.download=`bazaara-crop-${Date.now()}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(href),2000);},'image/png');}
 async function save(){if(!file)return;setLoading(true);try{const payload='BZ_INTERNET_1|'+JSON.stringify({v:2,notes:notes.slice(0,700),filename:file.name,mime:file.type,bytes:file.size,width:dimensions?.width,height:dimensions?.height,labels:result?.labels.slice(0,12)||[]});const r=await fetch('/api/items',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json'},body:JSON.stringify({title:label.slice(0,120)||file.name,body:payload})});if(!r.ok)throw Error('Could not save scan.');setNotice('Saved notes and image metadata. Your image remains on this device.');}catch(e){setError(e instanceof Error?e.message:'Save failed.');}finally{setLoading(false);}}
 function speakText(value:string){if(!value||!('speechSynthesis'in window)){setNotice('Read aloud is unavailable.');return;}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(value.slice(0,4000));window.speechSynthesis.speak(u);}
 const searchQuery=useMemo(()=>[...(result?.labels||[]),followUp].filter(Boolean).join(' ').trim().slice(0,180),[result,followUp]);
 const tabs=['Explore','Results','About image','Saved scans'];
 return <StandaloneFrame product="BazLens" tagline="" tabs={tabs} active={tab} onTab={next=>{setTab(next);if(next==='Saved scans')stopCamera();}}>
  {error&&<div role="alert" className="gl5-error bz8-error">{error}</div>}
  {notice&&<div role="status" className="gl5-notice bz8-notice">{notice}<button onClick={()=>setNotice('')} aria-label="Dismiss">×</button></div>}

  {tab==='Saved scans'?<div className="bz83-feature-page"><div className="bz83-feature-intro"><small>LIBRARY</small><h1>Saved visual searches</h1><p>Your saved scan notes and metadata.</p></div><InternetWorkspace kind="bazlens"/></div>:
  tab==='About image'?<div className="bz83-feature-page"><div className="bz83-feature-intro"><small>ABOUT IMAGE</small><h1>Image details</h1><p>Inspect local file metadata and dominant colors. Web provenance and authenticity signals require a connected provenance service.</p></div>{file?<div className="bz83-about-image"><div>{preview&&<img src={preview} alt="Selected source"/>}</div><aside><dl><div><dt>File</dt><dd>{file.name}</dd></div><div><dt>Type</dt><dd>{file.type||'Unknown'}</dd></div><div><dt>Size</dt><dd>{Math.round(file.size/1024)} KB</dd></div><div><dt>Dimensions</dt><dd>{dimensions?`${dimensions.width} × ${dimensions.height}`:'Unknown'}</dd></div></dl><h3>Dominant colors</h3><div className="gl5-palette">{colors.map(color=><button key={color} aria-label={`Copy ${color}`} title={color} style={{background:color}} onClick={()=>void navigator.clipboard?.writeText(color).then(()=>setNotice(`Copied ${color}`))}/>)}</div><button className="bz83-primary" onClick={()=>setTab('Explore')}>Back to visual search</button></aside></div>:<div className="bz83-empty"><strong>No image selected</strong><button onClick={()=>{setTab('Explore');chooser.current?.click();}}>Choose an image</button></div>}</div>:
  <div className="bz83-lens-page">
    <div className="bz83-lens-heading"><div><small>BAZAARA VISUAL SEARCH</small><h1>Search what you see</h1></div><button className="bz83-lens-gallery-top" onClick={()=>chooser.current?.click()}>▣ Upload</button></div>

    <section className={`bz83-lens-stage ${preview||camera?'has-media':''}`} onDragOver={e=>e.preventDefault()} onDrop={dropped}>
      <input ref={chooser} type="file" accept="image/png,image/jpeg,image/webp,image/gif" hidden onChange={(e:ChangeEvent<HTMLInputElement>)=>pick(e.target.files?.[0])}/>
      {camera?<video ref={video} playsInline autoPlay muted aria-label="Live camera preview" onClick={()=>void video.current?.play()}/>:preview?<img ref={picture} src={preview} alt="Selected image"/>:<div className="bz83-lens-empty"><div className="bz83-lens-mark">◫</div><h2>Drag an image here</h2><p>or <button onClick={()=>chooser.current?.click()}>upload a file</button></p><div className="bz83-lens-divider"><span/>OR<span/></div><div className="bz83-lens-url"><input type="url" value={remoteUrl} onChange={e=>setRemoteUrl(e.target.value)} placeholder="Paste image link" aria-label="Image URL"/><button type="button" disabled={!remoteUrl.trim()} onClick={()=>void importRemote()}>Search</button></div></div>}
      {(preview||camera)&&<div className="bz83-lens-reticle" aria-hidden="true"><i/><i/><i/><i/></div>}
      {preview&&<div className="bz83-lens-crop-label">Selection {crop}%</div>}
    </section>

    <div className="bz83-lens-mode-dock" role="tablist" aria-label="Visual search modes">{(['Search','Text','Translate','Shopping','QR'] as Mode[]).map(item=><button role="tab" aria-selected={item===mode} key={item} onClick={()=>setMode(item)}><span>{item==='Search'?'⌕':item==='Text'?'T':item==='Translate'?'文':item==='Shopping'?'◇':'▦'}</span><small>{item}</small></button>)}</div>

    <div className="bz83-lens-camera-row"><button type="button" onClick={()=>chooser.current?.click()}><span>▣</span><small>Gallery</small></button><button className="bz83-lens-shutter" aria-label={camera?'Capture photo':preview?'Analyze image':'Open camera'} disabled={loading} onClick={()=>{if(camera)snap();else if(preview)run();else void openCamera();}}><span>{loading?'…':camera?'●':preview?'⌕':'◎'}</span></button><button type="button" onClick={()=>{if(camera)stopCamera();else void openCamera();}}><span>{camera?'×':'◉'}</span><small>{camera?'Close':'Camera'}</small></button></div>

    {preview&&<div className="bz83-lens-command"><button className="bz83-primary" disabled={loading||(!connected&&mode!=='QR')} onClick={run}>{loading?'Analyzing…':mode==='QR'?'Scan code':`Search with ${mode}`}</button><button onClick={()=>setTab('About image')}>About image</button><button onClick={()=>{setFile(null);setResult(null);setCodes([]);setFollowUp('');}}>Clear</button><small>{connected?'Vision service connected.':'Vision provider required for object, text and visual-match analysis.'}</small></div>}

    {tab==='Results'&&<section className="bz83-lens-results" aria-live="polite"><header><div><small>RESULTS</small><h2>{mode==='Text'||mode==='Translate'?'Recognized text':mode==='Shopping'?'Product clues':mode==='QR'?'Codes':'Visual matches'}</h2></div><button onClick={()=>setTab('Explore')}>New search</button></header>{result?<><div className="bz83-lens-tags">{result.labels.map(tag=><span key={tag}>{tag}</span>)}</div>{result.text&&<div className="bz83-lens-text-result"><h3>Text in image</h3><p>{result.text}</p><div><button onClick={()=>void navigator.clipboard?.writeText(result.text).then(()=>setNotice('Text copied.'))}>Copy</button><button onClick={()=>speakText(result.text)}>Read aloud</button><a href={`${links.search||'#'}?q=${encodeURIComponent(result.text.slice(0,160))}`}>Search text ↗</a><a href={links.translate&&links.translate!=='#'?`${links.translate}?text=${encodeURIComponent(result.text.slice(0,5000))}`:'#'} aria-disabled={!links.translate||links.translate==='#'}>Translate text ↗</a></div></div>}{result.matches.length>0&&<div className="bz83-lens-matches"><h3>Visual matches</h3>{result.matches.map(match=><a key={match.url} href={match.url} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer"><strong>{match.title}</strong><span>↗</span></a>)}</div>}{result.labels.length>0&&<div className="bz83-lens-followup"><label>Add to your search<input value={followUp} onChange={e=>setFollowUp(e.target.value)} placeholder="e.g. cheaper, nearby, similar style"/></label><a className="bz83-primary-link" href={`${links.search||'#'}?q=${encodeURIComponent(searchQuery)}`}>Search with image + text ↗</a>{links.map&&links.map!=='#'&&<a href={`${links.map}?q=${encodeURIComponent(searchQuery)}`}>Find on BMap ↗</a>}{links.news&&links.news!=='#'&&<a href={`${links.news}?q=${encodeURIComponent(searchQuery)}`}>Find related news ↗</a>}{mode==='Shopping'&&<a href={`${links.shopping||'#'}?q=${encodeURIComponent(searchQuery)}`}>Open BAZAARA Shopping ↗</a>}</div>}</>:<p>Choose an image and run a supported analysis.</p>}{codes.length>0&&<div className="bz83-code-results"><h3>Detected codes</h3>{codes.map((code,index)=><p key={`${code.rawValue}-${index}`}><strong>{code.format}</strong>{code.rawValue}</p>)}</div>}</section>}

    {preview&&<details className="bz83-lens-details"><summary>Edit image & save notes</summary><label>Center crop: {crop}%<input type="range" min="30" max="100" value={crop} onChange={e=>setCrop(Number(e.target.value))}/></label><button onClick={downloadCrop}>Download crop</button><div className="gl5-palette">{colors.map(color=><button key={color} aria-label={`Copy color ${color}`} title={color} style={{background:color}} onClick={()=>void navigator.clipboard?.writeText(color).then(()=>setNotice(`Copied ${color}`))}/>)}</div><label>Title<input value={label} maxLength={120} onChange={e=>setLabel(e.target.value)}/></label><label>Notes<textarea value={notes} maxLength={700} onChange={e=>setNotes(e.target.value)}/></label><button disabled={loading} onClick={()=>void save()}>Save scan notes</button><p>Images remain on this device; only notes and metadata are saved.</p></details>}
  </div>}
 </StandaloneFrame>;
}
